exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abatiá', name_order: 'Abatia', uf: 'PR' },
			{ name: 'Adrianópolis', name_order: 'Adrianopolis', uf: 'PR' },
			{ name: 'Agudos do Sul', name_order: 'Agudos do Sul', uf: 'PR' },
			{ name: 'Almirante Tamandaré', name_order: 'Almirante Tamandare', uf: 'PR' },
			{ name: 'Altamira do Paraná', name_order: 'Altamira do Parana', uf: 'PR' },
			{ name: 'Altônia', name_order: 'Altonia', uf: 'PR' },
			{ name: 'Alto Paraná', name_order: 'Alto Parana', uf: 'PR' },
			{ name: 'Alto Piquiri', name_order: 'Alto Piquiri', uf: 'PR' },
			{ name: 'Alvorada do Sul', name_order: 'Alvorada do Sul', uf: 'PR' },
			{ name: 'Amaporã', name_order: 'Amapora', uf: 'PR' },
			{ name: 'Ampére', name_order: 'Ampere', uf: 'PR' },
			{ name: 'Anahy', name_order: 'Anahy', uf: 'PR' },
			{ name: 'Andirá', name_order: 'Andira', uf: 'PR' },
			{ name: 'Ângulo', name_order: 'Angulo', uf: 'PR' },
			{ name: 'Antonina', name_order: 'Antonina', uf: 'PR' },
			{ name: 'Antônio Olinto', name_order: 'Antonio Olinto', uf: 'PR' },
			{ name: 'Apucarana', name_order: 'Apucarana', uf: 'PR' },
			{ name: 'Arapongas', name_order: 'Arapongas', uf: 'PR' },
			{ name: 'Arapoti', name_order: 'Arapoti', uf: 'PR' },
			{ name: 'Arapuã', name_order: 'Arapua', uf: 'PR' },
			{ name: 'Araruna', name_order: 'Araruna', uf: 'PR' },
			{ name: 'Araucária', name_order: 'Araucaria', uf: 'PR' },
			{ name: 'Ariranha do Ivaí', name_order: 'Ariranha do Ivai', uf: 'PR' },
			{ name: 'Assaí', name_order: 'Assai', uf: 'PR' },
			{ name: 'Assis Chateaubriand', name_order: 'Assis Chateaubriand', uf: 'PR' },
			{ name: 'Astorga', name_order: 'Astorga', uf: 'PR' },
			{ name: 'Atalaia', name_order: 'Atalaia', uf: 'PR' },
			{ name: 'Balsa Nova', name_order: 'Balsa Nova', uf: 'PR' },
			{ name: 'Bandeirantes', name_order: 'Bandeirantes', uf: 'PR' },
			{ name: 'Barbosa Ferraz', name_order: 'Barbosa Ferraz', uf: 'PR' },
			{ name: 'Barracão', name_order: 'Barracao', uf: 'PR' },
			{ name: 'Barra do Jacaré', name_order: 'Barra do Jacare', uf: 'PR' },
			{ name: 'Bela Vista da Caroba', name_order: 'Bela Vista da Caroba', uf: 'PR' },
			{ name: 'Bela Vista do Paraíso', name_order: 'Bela Vista do Paraiso', uf: 'PR' },
			{ name: 'Bituruna', name_order: 'Bituruna', uf: 'PR' },
			{ name: 'Boa Esperança', name_order: 'Boa Esperanca', uf: 'PR' },
			{ name: 'Boa Esperança do Iguaçu', name_order: 'Boa Esperanca do Iguacu', uf: 'PR' },
			{ name: 'Boa Ventura de São Roque', name_order: 'Boa Ventura de Sao Roque', uf: 'PR' },
			{ name: 'Boa Vista da Aparecida', name_order: 'Boa Vista da Aparecida', uf: 'PR' },
			{ name: 'Bocaiúva do Sul', name_order: 'Bocaiuva do Sul', uf: 'PR' },
			{ name: 'Bom Jesus do Sul', name_order: 'Bom Jesus do Sul', uf: 'PR' },
			{ name: 'Bom Sucesso', name_order: 'Bom Sucesso', uf: 'PR' },
			{ name: 'Bom Sucesso do Sul', name_order: 'Bom Sucesso do Sul', uf: 'PR' },
			{ name: 'Borrazópolis', name_order: 'Borrazopolis', uf: 'PR' },
			{ name: 'Braganey', name_order: 'Braganey', uf: 'PR' },
			{ name: 'Brasilândia do Sul', name_order: 'Brasilandia do Sul', uf: 'PR' },
			{ name: 'Cafeara', name_order: 'Cafeara', uf: 'PR' },
			{ name: 'Cafelândia', name_order: 'Cafelandia', uf: 'PR' },
			{ name: 'Cafezal do Sul', name_order: 'Cafezal do Sul', uf: 'PR' },
			{ name: 'Califórnia', name_order: 'California', uf: 'PR' },
			{ name: 'Cambará', name_order: 'Cambara', uf: 'PR' },
			{ name: 'Cambé', name_order: 'Cambe', uf: 'PR' },
			{ name: 'Cambira', name_order: 'Cambira', uf: 'PR' },
			{ name: 'Campina da Lagoa', name_order: 'Campina da Lagoa', uf: 'PR' },
			{ name: 'Campina do Simão', name_order: 'Campina do Simao', uf: 'PR' },
			{ name: 'Campina Grande do Sul', name_order: 'Campina Grande do Sul', uf: 'PR' },
			{ name: 'Campo Bonito', name_order: 'Campo Bonito', uf: 'PR' },
			{ name: 'Campo do Tenente', name_order: 'Campo do Tenente', uf: 'PR' },
			{ name: 'Campo Largo', name_order: 'Campo Largo', uf: 'PR' },
			{ name: 'Campo Magro', name_order: 'Campo Magro', uf: 'PR' },
			{ name: 'Campo Mourão', name_order: 'Campo Mourao', uf: 'PR' },
			{ name: 'Cândido de Abreu', name_order: 'Candido de Abreu', uf: 'PR' },
			{ name: 'Candói', name_order: 'Candoi', uf: 'PR' },
			{ name: 'Cantagalo', name_order: 'Cantagalo', uf: 'PR' },
			{ name: 'Capanema', name_order: 'Capanema', uf: 'PR' },
			{ name: 'Capitão Leônidas Marques', name_order: 'Capitao Leonidas Marques', uf: 'PR' },
			{ name: 'Carambeí', name_order: 'Carambei', uf: 'PR' },
			{ name: 'Carlópolis', name_order: 'Carlopolis', uf: 'PR' },
			{ name: 'Cascavel', name_order: 'Cascavel', uf: 'PR' },
			{ name: 'Castro', name_order: 'Castro', uf: 'PR' },
			{ name: 'Catanduvas', name_order: 'Catanduvas', uf: 'PR' },
			{ name: 'Centenário do Sul', name_order: 'Centenario do Sul', uf: 'PR' },
			{ name: 'Cerro Azul', name_order: 'Cerro Azul', uf: 'PR' },
			{ name: 'Céu Azul', name_order: 'Ceu Azul', uf: 'PR' },
			{ name: 'Chopinzinho', name_order: 'Chopinzinho', uf: 'PR' },
			{ name: 'Cianorte', name_order: 'Cianorte', uf: 'PR' },
			{ name: 'Cidade Gaúcha', name_order: 'Cidade Gaucha', uf: 'PR' },
			{ name: 'Clevelândia', name_order: 'Clevelandia', uf: 'PR' },
			{ name: 'Colombo', name_order: 'Colombo', uf: 'PR' },
			{ name: 'Colorado', name_order: 'Colorado', uf: 'PR' },
			{ name: 'Congonhinhas', name_order: 'Congonhinhas', uf: 'PR' },
			{ name: 'Conselheiro Mairinck', name_order: 'Conselheiro Mairinck', uf: 'PR' },
			{ name: 'Contenda', name_order: 'Contenda', uf: 'PR' },
			{ name: 'Corbélia', name_order: 'Corbelia', uf: 'PR' },
			{ name: 'Cornélio Procópio', name_order: 'Cornelio Procopio', uf: 'PR' },
			{ name: 'Coronel Domingos Soares', name_order: 'Coronel Domingos Soares', uf: 'PR' },
			{ name: 'Coronel Vivida', name_order: 'Coronel Vivida', uf: 'PR' },
			{ name: 'Corumbataí do Sul', name_order: 'Corumbatai do Sul', uf: 'PR' },
			{ name: 'Cruzeiro do Iguaçu', name_order: 'Cruzeiro do Iguacu', uf: 'PR' },
			{ name: 'Cruzeiro do Oeste', name_order: 'Cruzeiro do Oeste', uf: 'PR' },
			{ name: 'Cruzeiro do Sul', name_order: 'Cruzeiro do Sul', uf: 'PR' },
			{ name: 'Cruz Machado', name_order: 'Cruz Machado', uf: 'PR' },
			{ name: 'Cruzmaltina', name_order: 'Cruzmaltina', uf: 'PR' },
			{ name: 'Curitiba', name_order: 'Curitiba', uf: 'PR' },
			{ name: 'Curiúva', name_order: 'Curiuva', uf: 'PR' },
			{ name: 'Diamante do Norte', name_order: 'Diamante do Norte', uf: 'PR' },
			{ name: 'Diamante do Sul', name_order: 'Diamante do Sul', uf: 'PR' },
			{ name: 'Diamante D´oeste', name_order: 'Diamante Doeste', uf: 'PR' },
			{ name: 'Dois Vizinhos', name_order: 'Dois Vizinhos', uf: 'PR' },
			{ name: 'Douradina', name_order: 'Douradina', uf: 'PR' },
			{ name: 'Doutor Camargo', name_order: 'Doutor Camargo', uf: 'PR' },
			{ name: 'Enéas Marques', name_order: 'Eneas Marques', uf: 'PR' },
			{ name: 'Engenheiro Beltrão', name_order: 'Engenheiro Beltrao', uf: 'PR' },
			{ name: 'Esperança Nova', name_order: 'Esperanca Nova', uf: 'PR' },
			{ name: 'Entre Rios do Oeste', name_order: 'Entre Rios do Oeste', uf: 'PR' },
			{ name: 'Espigão Alto do Iguaçu', name_order: 'Espigao Alto do Iguacu', uf: 'PR' },
			{ name: 'Farol', name_order: 'Farol', uf: 'PR' },
			{ name: 'Faxinal', name_order: 'Faxinal', uf: 'PR' },
			{ name: 'Fazenda Rio Grande', name_order: 'Fazenda Rio Grande', uf: 'PR' },
			{ name: 'Fênix', name_order: 'Fenix', uf: 'PR' },
			{ name: 'Fernandes Pinheiro', name_order: 'Fernandes Pinheiro', uf: 'PR' },
			{ name: 'Figueira', name_order: 'Figueira', uf: 'PR' },
			{ name: 'Floraí', name_order: 'Florai', uf: 'PR' },
			{ name: 'Flor da Serra do Sul', name_order: 'Flor da Serra do Sul', uf: 'PR' },
			{ name: 'Floresta', name_order: 'Floresta', uf: 'PR' },
			{ name: 'Florestópolis', name_order: 'Florestopolis', uf: 'PR' },
			{ name: 'Flórida', name_order: 'Florida', uf: 'PR' },
			{ name: 'Formosa do Oeste', name_order: 'Formosa do Oeste', uf: 'PR' },
			{ name: 'Foz do Iguaçu', name_order: 'Foz do Iguacu', uf: 'PR' },
			{ name: 'Francisco Alves', name_order: 'Francisco Alves', uf: 'PR' },
			{ name: 'Francisco Beltrão', name_order: 'Francisco Beltrao', uf: 'PR' },
			{ name: 'Foz do Jordão', name_order: 'Foz do Jordao', uf: 'PR' },
			{ name: 'General Carneiro', name_order: 'General Carneiro', uf: 'PR' },
			{ name: 'Godoy Moreira', name_order: 'Godoy Moreira', uf: 'PR' },
			{ name: 'Goioerê', name_order: 'Goioere', uf: 'PR' },
			{ name: 'Goioxim', name_order: 'Goioxim', uf: 'PR' },
			{ name: 'Grandes Rios', name_order: 'Grandes Rios', uf: 'PR' },
			{ name: 'Guaíra', name_order: 'Guaira', uf: 'PR' },
			{ name: 'Guairaçá', name_order: 'Guairaca', uf: 'PR' },
			{ name: 'Guamiranga', name_order: 'Guamiranga', uf: 'PR' },
			{ name: 'Guapirama', name_order: 'Guapirama', uf: 'PR' },
			{ name: 'Guaporema', name_order: 'Guaporema', uf: 'PR' },
			{ name: 'Guaraci', name_order: 'Guaraci', uf: 'PR' },
			{ name: 'Guaraniaçu', name_order: 'Guaraniacu', uf: 'PR' },
			{ name: 'Guarapuava', name_order: 'Guarapuava', uf: 'PR' },
			{ name: 'Guaraqueçaba', name_order: 'Guaraquecaba', uf: 'PR' },
			{ name: 'Guaratuba', name_order: 'Guaratuba', uf: 'PR' },
			{ name: 'Honório Serpa', name_order: 'Honorio Serpa', uf: 'PR' },
			{ name: 'Ibaiti', name_order: 'Ibaiti', uf: 'PR' },
			{ name: 'Ibema', name_order: 'Ibema', uf: 'PR' },
			{ name: 'Ibiporã', name_order: 'Ibipora', uf: 'PR' },
			{ name: 'Icaraíma', name_order: 'Icaraima', uf: 'PR' },
			{ name: 'Iguaraçu', name_order: 'Iguaracu', uf: 'PR' },
			{ name: 'Iguatu', name_order: 'Iguatu', uf: 'PR' },
			{ name: 'Imbaú', name_order: 'Imbau', uf: 'PR' },
			{ name: 'Imbituva', name_order: 'Imbituva', uf: 'PR' },
			{ name: 'Inácio Martins', name_order: 'Inacio Martins', uf: 'PR' },
			{ name: 'Inajá', name_order: 'Inaja', uf: 'PR' },
			{ name: 'Indianópolis', name_order: 'Indianopolis', uf: 'PR' },
			{ name: 'Ipiranga', name_order: 'Ipiranga', uf: 'PR' },
			{ name: 'Iporã', name_order: 'Ipora', uf: 'PR' },
			{ name: 'Iracema do Oeste', name_order: 'Iracema do Oeste', uf: 'PR' },
			{ name: 'Irati', name_order: 'Irati', uf: 'PR' },
			{ name: 'Iretama', name_order: 'Iretama', uf: 'PR' },
			{ name: 'Itaguajé', name_order: 'Itaguaje', uf: 'PR' },
			{ name: 'Itaipulândia', name_order: 'Itaipulandia', uf: 'PR' },
			{ name: 'Itambaracá', name_order: 'Itambaraca', uf: 'PR' },
			{ name: 'Itambé', name_order: 'Itambe', uf: 'PR' },
			{ name: 'Itapejara D´oeste', name_order: 'Itapejara Doeste', uf: 'PR' },
			{ name: 'Itaperuçu', name_order: 'Itaperucu', uf: 'PR' },
			{ name: 'Itaúna do Sul', name_order: 'Itauna do Sul', uf: 'PR' },
			{ name: 'Ivaí', name_order: 'Ivai', uf: 'PR' },
			{ name: 'Ivaiporã', name_order: 'Ivaipora', uf: 'PR' },
			{ name: 'Ivaté', name_order: 'Ivate', uf: 'PR' },
			{ name: 'Ivatuba', name_order: 'Ivatuba', uf: 'PR' },
			{ name: 'Jaboti', name_order: 'Jaboti', uf: 'PR' },
			{ name: 'Jacarezinho', name_order: 'Jacarezinho', uf: 'PR' },
			{ name: 'Jaguapitã', name_order: 'Jaguapita', uf: 'PR' },
			{ name: 'Jaguariaíva', name_order: 'Jaguariaiva', uf: 'PR' },
			{ name: 'Jandaia do Sul', name_order: 'Jandaia do Sul', uf: 'PR' },
			{ name: 'Janiópolis', name_order: 'Janiopolis', uf: 'PR' },
			{ name: 'Japira', name_order: 'Japira', uf: 'PR' },
			{ name: 'Japurá', name_order: 'Japura', uf: 'PR' },
			{ name: 'Jardim Alegre', name_order: 'Jardim Alegre', uf: 'PR' },
			{ name: 'Jardim Olinda', name_order: 'Jardim Olinda', uf: 'PR' },
			{ name: 'Jataizinho', name_order: 'Jataizinho', uf: 'PR' },
			{ name: 'Jesuítas', name_order: 'Jesuitas', uf: 'PR' },
			{ name: 'Joaquim Távora', name_order: 'Joaquim Tavora', uf: 'PR' },
			{ name: 'Jundiaí do Sul', name_order: 'Jundiai do Sul', uf: 'PR' },
			{ name: 'Juranda', name_order: 'Juranda', uf: 'PR' },
			{ name: 'Jussara', name_order: 'Jussara', uf: 'PR' },
			{ name: 'Kaloré', name_order: 'Kalore', uf: 'PR' },
			{ name: 'Lapa', name_order: 'Lapa', uf: 'PR' },
			{ name: 'Laranjal', name_order: 'Laranjal', uf: 'PR' },
			{ name: 'Laranjeiras do Sul', name_order: 'Laranjeiras do Sul', uf: 'PR' },
			{ name: 'Leópolis', name_order: 'Leopolis', uf: 'PR' },
			{ name: 'Lidianópolis', name_order: 'Lidianopolis', uf: 'PR' },
			{ name: 'Lindoeste', name_order: 'Lindoeste', uf: 'PR' },
			{ name: 'Loanda', name_order: 'Loanda', uf: 'PR' },
			{ name: 'Lobato', name_order: 'Lobato', uf: 'PR' },
			{ name: 'Londrina', name_order: 'Londrina', uf: 'PR' },
			{ name: 'Luiziana', name_order: 'Luiziana', uf: 'PR' },
			{ name: 'Lunardelli', name_order: 'Lunardelli', uf: 'PR' },
			{ name: 'Lupionópolis', name_order: 'Lupionopolis', uf: 'PR' },
			{ name: 'Mallet', name_order: 'Mallet', uf: 'PR' },
			{ name: 'Mamborê', name_order: 'Mambore', uf: 'PR' },
			{ name: 'Mandaguaçu', name_order: 'Mandaguacu', uf: 'PR' },
			{ name: 'Mandaguari', name_order: 'Mandaguari', uf: 'PR' },
			{ name: 'Mandirituba', name_order: 'Mandirituba', uf: 'PR' },
			{ name: 'Manfrinópolis', name_order: 'Manfrinopolis', uf: 'PR' },
			{ name: 'Mangueirinha', name_order: 'Mangueirinha', uf: 'PR' },
			{ name: 'Manoel Ribas', name_order: 'Manoel Ribas', uf: 'PR' },
			{ name: 'Marechal Cândido Rondon', name_order: 'Marechal Candido Rondon', uf: 'PR' },
			{ name: 'Maria Helena', name_order: 'Maria Helena', uf: 'PR' },
			{ name: 'Marialva', name_order: 'Marialva', uf: 'PR' },
			{ name: 'Marilândia do Sul', name_order: 'Marilandia do Sul', uf: 'PR' },
			{ name: 'Marilena', name_order: 'Marilena', uf: 'PR' },
			{ name: 'Mariluz', name_order: 'Mariluz', uf: 'PR' },
			{ name: 'Maringá', name_order: 'Maringa', uf: 'PR' },
			{ name: 'Mariópolis', name_order: 'Mariopolis', uf: 'PR' },
			{ name: 'Maripá', name_order: 'Maripa', uf: 'PR' },
			{ name: 'Marmeleiro', name_order: 'Marmeleiro', uf: 'PR' },
			{ name: 'Marquinho', name_order: 'Marquinho', uf: 'PR' },
			{ name: 'Marumbi', name_order: 'Marumbi', uf: 'PR' },
			{ name: 'Matelândia', name_order: 'Matelandia', uf: 'PR' },
			{ name: 'Matinhos', name_order: 'Matinhos', uf: 'PR' },
			{ name: 'Mato Rico', name_order: 'Mato Rico', uf: 'PR' },
			{ name: 'Mauá da Serra', name_order: 'Maua da Serra', uf: 'PR' },
			{ name: 'Medianeira', name_order: 'Medianeira', uf: 'PR' },
			{ name: 'Mercedes', name_order: 'Mercedes', uf: 'PR' },
			{ name: 'Mirador', name_order: 'Mirador', uf: 'PR' },
			{ name: 'Miraselva', name_order: 'Miraselva', uf: 'PR' },
			{ name: 'Missal', name_order: 'Missal', uf: 'PR' },
			{ name: 'Moreira Sales', name_order: 'Moreira Sales', uf: 'PR' },
			{ name: 'Morretes', name_order: 'Morretes', uf: 'PR' },
			{ name: 'Munhoz de Melo', name_order: 'Munhoz de Melo', uf: 'PR' },
			{ name: 'Nossa Senhora Das Graças', name_order: 'Nossa Senhora Das Gracas', uf: 'PR' },
			{ name: 'Nova Aliança do Ivaí', name_order: 'Nova Alianca do Ivai', uf: 'PR' },
			{ name: 'Nova América da Colina', name_order: 'Nova America da Colina', uf: 'PR' },
			{ name: 'Nova Aurora', name_order: 'Nova Aurora', uf: 'PR' },
			{ name: 'Nova Cantu', name_order: 'Nova Cantu', uf: 'PR' },
			{ name: 'Nova Esperança', name_order: 'Nova Esperanca', uf: 'PR' },
			{ name: 'Nova Esperança do Sudoeste', name_order: 'Nova Esperanca do Sudoeste', uf: 'PR' },
			{ name: 'Nova Fátima', name_order: 'Nova Fatima', uf: 'PR' },
			{ name: 'Nova Laranjeiras', name_order: 'Nova Laranjeiras', uf: 'PR' },
			{ name: 'Nova Londrina', name_order: 'Nova Londrina', uf: 'PR' },
			{ name: 'Nova Olímpia', name_order: 'Nova Olimpia', uf: 'PR' },
			{ name: 'Nova Santa Bárbara', name_order: 'Nova Santa Barbara', uf: 'PR' },
			{ name: 'Nova Santa Rosa', name_order: 'Nova Santa Rosa', uf: 'PR' },
			{ name: 'Nova Prata do Iguaçu', name_order: 'Nova Prata do Iguacu', uf: 'PR' },
			{ name: 'Nova Tebas', name_order: 'Nova Tebas', uf: 'PR' },
			{ name: 'Novo Itacolomi', name_order: 'Novo Itacolomi', uf: 'PR' },
			{ name: 'Ortigueira', name_order: 'Ortigueira', uf: 'PR' },
			{ name: 'Ourizona', name_order: 'Ourizona', uf: 'PR' },
			{ name: 'Ouro Verde do Oeste', name_order: 'Ouro Verde do Oeste', uf: 'PR' },
			{ name: 'Paiçandu', name_order: 'Paicandu', uf: 'PR' },
			{ name: 'Palmas', name_order: 'Palmas', uf: 'PR' },
			{ name: 'Palmeira', name_order: 'Palmeira', uf: 'PR' },
			{ name: 'Palmital', name_order: 'Palmital', uf: 'PR' },
			{ name: 'Palotina', name_order: 'Palotina', uf: 'PR' },
			{ name: 'Paraíso do Norte', name_order: 'Paraiso do Norte', uf: 'PR' },
			{ name: 'Paranacity', name_order: 'Paranacity', uf: 'PR' },
			{ name: 'Paranaguá', name_order: 'Paranagua', uf: 'PR' },
			{ name: 'Paranapoema', name_order: 'Paranapoema', uf: 'PR' },
			{ name: 'Paranavaí', name_order: 'Paranavai', uf: 'PR' },
			{ name: 'Pato Bragado', name_order: 'Pato Bragado', uf: 'PR' },
			{ name: 'Pato Branco', name_order: 'Pato Branco', uf: 'PR' },
			{ name: 'Paula Freitas', name_order: 'Paula Freitas', uf: 'PR' },
			{ name: 'Paulo Frontin', name_order: 'Paulo Frontin', uf: 'PR' },
			{ name: 'Peabiru', name_order: 'Peabiru', uf: 'PR' },
			{ name: 'Perobal', name_order: 'Perobal', uf: 'PR' },
			{ name: 'Pérola', name_order: 'Perola', uf: 'PR' },
			{ name: 'Pérola D´oeste', name_order: 'Perola Doeste', uf: 'PR' },
			{ name: 'Piên', name_order: 'Pien', uf: 'PR' },
			{ name: 'Pinhais', name_order: 'Pinhais', uf: 'PR' },
			{ name: 'Pinhalão', name_order: 'Pinhalao', uf: 'PR' },
			{ name: 'Pinhal de São Bento', name_order: 'Pinhal de Sao Bento', uf: 'PR' },
			{ name: 'Pinhão', name_order: 'Pinhao', uf: 'PR' },
			{ name: 'Piraí do Sul', name_order: 'Pirai do Sul', uf: 'PR' },
			{ name: 'Piraquara', name_order: 'Piraquara', uf: 'PR' },
			{ name: 'Pitanga', name_order: 'Pitanga', uf: 'PR' },
			{ name: 'Pitangueiras', name_order: 'Pitangueiras', uf: 'PR' },
			{ name: 'Planaltina do Paraná', name_order: 'Planaltina do Parana', uf: 'PR' },
			{ name: 'Planalto', name_order: 'Planalto', uf: 'PR' },
			{ name: 'Ponta Grossa', name_order: 'Ponta Grossa', uf: 'PR' },
			{ name: 'Pontal do Paraná', name_order: 'Pontal do Parana', uf: 'PR' },
			{ name: 'Porecatu', name_order: 'Porecatu', uf: 'PR' },
			{ name: 'Porto Amazonas', name_order: 'Porto Amazonas', uf: 'PR' },
			{ name: 'Porto Barreiro', name_order: 'Porto Barreiro', uf: 'PR' },
			{ name: 'Porto Rico', name_order: 'Porto Rico', uf: 'PR' },
			{ name: 'Porto Vitória', name_order: 'Porto Vitoria', uf: 'PR' },
			{ name: 'Prado Ferreira', name_order: 'Prado Ferreira', uf: 'PR' },
			{ name: 'Pranchita', name_order: 'Pranchita', uf: 'PR' },
			{ name: 'Presidente Castelo Branco', name_order: 'Presidente Castelo Branco', uf: 'PR' },
			{ name: 'Primeiro de Maio', name_order: 'Primeiro de Maio', uf: 'PR' },
			{ name: 'Prudentópolis', name_order: 'Prudentopolis', uf: 'PR' },
			{ name: 'Quarto Centenário', name_order: 'Quarto Centenario', uf: 'PR' },
	]);
};
