exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Acari', name_order: 'Acari', uf: 'RN' },
			{ name: 'Açu', name_order: 'Acu', uf: 'RN' },
			{ name: 'Afonso Bezerra', name_order: 'Afonso Bezerra', uf: 'RN' },
			{ name: 'Água Nova', name_order: 'Agua Nova', uf: 'RN' },
			{ name: 'Alexandria', name_order: 'Alexandria', uf: 'RN' },
			{ name: 'Almino Afonso', name_order: 'Almino Afonso', uf: 'RN' },
			{ name: 'Alto do Rodrigues', name_order: 'Alto do Rodrigues', uf: 'RN' },
			{ name: 'Angicos', name_order: 'Angicos', uf: 'RN' },
			{ name: 'Antônio Martins', name_order: 'Antonio Martins', uf: 'RN' },
			{ name: 'Apodi', name_order: 'Apodi', uf: 'RN' },
			{ name: 'Areia Branca', name_order: 'Areia Branca', uf: 'RN' },
			{ name: 'Arês', name_order: 'Ares', uf: 'RN' },
			{ name: 'Augusto Severo', name_order: 'Augusto Severo', uf: 'RN' },
			{ name: 'Baía Formosa', name_order: 'Baia Formosa', uf: 'RN' },
			{ name: 'Baraúna', name_order: 'Barauna', uf: 'RN' },
			{ name: 'Barcelona', name_order: 'Barcelona', uf: 'RN' },
			{ name: 'Bento Fernandes', name_order: 'Bento Fernandes', uf: 'RN' },
			{ name: 'Bodó', name_order: 'Bodo', uf: 'RN' },
			{ name: 'Bom Jesus', name_order: 'Bom Jesus', uf: 'RN' },
			{ name: 'Brejinho', name_order: 'Brejinho', uf: 'RN' },
			{ name: 'Caiçara do Norte', name_order: 'Caicara do Norte', uf: 'RN' },
			{ name: 'Caiçara do Rio do Vento', name_order: 'Caicara do Rio do Vento', uf: 'RN' },
			{ name: 'Caicó', name_order: 'Caico', uf: 'RN' },
			{ name: 'Campo Redondo', name_order: 'Campo Redondo', uf: 'RN' },
			{ name: 'Canguaretama', name_order: 'Canguaretama', uf: 'RN' },
			{ name: 'Caraúbas', name_order: 'Caraubas', uf: 'RN' },
			{ name: 'Carnaúba Dos Dantas', name_order: 'Carnauba Dos Dantas', uf: 'RN' },
			{ name: 'Carnaubais', name_order: 'Carnaubais', uf: 'RN' },
			{ name: 'Ceará-mirim', name_order: 'Cearamirim', uf: 'RN' },
			{ name: 'Cerro Corá', name_order: 'Cerro Cora', uf: 'RN' },
			{ name: 'Coronel Ezequiel', name_order: 'Coronel Ezequiel', uf: 'RN' },
			{ name: 'Coronel João Pessoa', name_order: 'Coronel Joao Pessoa', uf: 'RN' },
			{ name: 'Cruzeta', name_order: 'Cruzeta', uf: 'RN' },
			{ name: 'Currais Novos', name_order: 'Currais Novos', uf: 'RN' },
			{ name: 'Doutor Severiano', name_order: 'Doutor Severiano', uf: 'RN' },
			{ name: 'Parnamirim', name_order: 'Parnamirim', uf: 'RN' },
			{ name: 'Encanto', name_order: 'Encanto', uf: 'RN' },
			{ name: 'Equador', name_order: 'Equador', uf: 'RN' },
			{ name: 'Espírito Santo', name_order: 'Espirito Santo', uf: 'RN' },
			{ name: 'Extremoz', name_order: 'Extremoz', uf: 'RN' },
			{ name: 'Felipe Guerra', name_order: 'Felipe Guerra', uf: 'RN' },
			{ name: 'Fernando Pedroza', name_order: 'Fernando Pedroza', uf: 'RN' },
			{ name: 'Florânia', name_order: 'Florania', uf: 'RN' },
			{ name: 'Francisco Dantas', name_order: 'Francisco Dantas', uf: 'RN' },
			{ name: 'Frutuoso Gomes', name_order: 'Frutuoso Gomes', uf: 'RN' },
			{ name: 'Galinhos', name_order: 'Galinhos', uf: 'RN' },
			{ name: 'Goianinha', name_order: 'Goianinha', uf: 'RN' },
			{ name: 'Governador Dix-sept Rosado', name_order: 'Governador Dixsept Rosado', uf: 'RN' },
			{ name: 'Grossos', name_order: 'Grossos', uf: 'RN' },
			{ name: 'Guamaré', name_order: 'Guamare', uf: 'RN' },
			{ name: 'Ielmo Marinho', name_order: 'Ielmo Marinho', uf: 'RN' },
			{ name: 'Ipanguaçu', name_order: 'Ipanguacu', uf: 'RN' },
			{ name: 'Ipueira', name_order: 'Ipueira', uf: 'RN' },
			{ name: 'Itajá', name_order: 'Itaja', uf: 'RN' },
			{ name: 'Itaú', name_order: 'Itau', uf: 'RN' },
			{ name: 'Jaçanã', name_order: 'Jacana', uf: 'RN' },
			{ name: 'Jandaíra', name_order: 'Jandaira', uf: 'RN' },
			{ name: 'Janduís', name_order: 'Janduis', uf: 'RN' },
			{ name: 'Januário Cicco', name_order: 'Januario Cicco', uf: 'RN' },
			{ name: 'Japi', name_order: 'Japi', uf: 'RN' },
			{ name: 'Jardim de Angicos', name_order: 'Jardim de Angicos', uf: 'RN' },
			{ name: 'Jardim de Piranhas', name_order: 'Jardim de Piranhas', uf: 'RN' },
			{ name: 'Jardim do Seridó', name_order: 'Jardim do Serido', uf: 'RN' },
			{ name: 'João Câmara', name_order: 'Joao Camara', uf: 'RN' },
			{ name: 'João Dias', name_order: 'Joao Dias', uf: 'RN' },
			{ name: 'José da Penha', name_order: 'Jose da Penha', uf: 'RN' },
			{ name: 'Jucurutu', name_order: 'Jucurutu', uf: 'RN' },
			{ name: 'Jundiá', name_order: 'Jundia', uf: 'RN' },
			{ name: 'Lagoa D´anta', name_order: 'Lagoa Danta', uf: 'RN' },
			{ name: 'Lagoa de Pedras', name_order: 'Lagoa de Pedras', uf: 'RN' },
			{ name: 'Lagoa de Velhos', name_order: 'Lagoa de Velhos', uf: 'RN' },
			{ name: 'Lagoa Nova', name_order: 'Lagoa Nova', uf: 'RN' },
			{ name: 'Lagoa Salgada', name_order: 'Lagoa Salgada', uf: 'RN' },
			{ name: 'Lajes', name_order: 'Lajes', uf: 'RN' },
			{ name: 'Lajes Pintadas', name_order: 'Lajes Pintadas', uf: 'RN' },
			{ name: 'Lucrécia', name_order: 'Lucrecia', uf: 'RN' },
			{ name: 'Luís Gomes', name_order: 'Luis Gomes', uf: 'RN' },
			{ name: 'Macaíba', name_order: 'Macaiba', uf: 'RN' },
			{ name: 'Macau', name_order: 'Macau', uf: 'RN' },
			{ name: 'Major Sales', name_order: 'Major Sales', uf: 'RN' },
			{ name: 'Marcelino Vieira', name_order: 'Marcelino Vieira', uf: 'RN' },
			{ name: 'Martins', name_order: 'Martins', uf: 'RN' },
			{ name: 'Maxaranguape', name_order: 'Maxaranguape', uf: 'RN' },
			{ name: 'Messias Targino', name_order: 'Messias Targino', uf: 'RN' },
			{ name: 'Montanhas', name_order: 'Montanhas', uf: 'RN' },
			{ name: 'Monte Alegre', name_order: 'Monte Alegre', uf: 'RN' },
			{ name: 'Monte Das Gameleiras', name_order: 'Monte Das Gameleiras', uf: 'RN' },
			{ name: 'Mossoró', name_order: 'Mossoro', uf: 'RN' },
			{ name: 'Natal', name_order: 'Natal', uf: 'RN' },
			{ name: 'Nísia Floresta', name_order: 'Nisia Floresta', uf: 'RN' },
			{ name: 'Nova Cruz', name_order: 'Nova Cruz', uf: 'RN' },
			{ name: 'Olho-d´água do Borges', name_order: 'Olhodagua do Borges', uf: 'RN' },
			{ name: 'Ouro Branco', name_order: 'Ouro Branco', uf: 'RN' },
			{ name: 'Paraná', name_order: 'Parana', uf: 'RN' },
			{ name: 'Paraú', name_order: 'Parau', uf: 'RN' },
			{ name: 'Parazinho', name_order: 'Parazinho', uf: 'RN' },
			{ name: 'Parelhas', name_order: 'Parelhas', uf: 'RN' },
			{ name: 'Rio do Fogo', name_order: 'Rio do Fogo', uf: 'RN' },
			{ name: 'Passa e Fica', name_order: 'Passa e Fica', uf: 'RN' },
			{ name: 'Passagem', name_order: 'Passagem', uf: 'RN' },
			{ name: 'Patu', name_order: 'Patu', uf: 'RN' },
			{ name: 'Santa Maria', name_order: 'Santa Maria', uf: 'RN' },
			{ name: 'Pau Dos Ferros', name_order: 'Pau Dos Ferros', uf: 'RN' },
			{ name: 'Pedra Grande', name_order: 'Pedra Grande', uf: 'RN' },
			{ name: 'Pedra Preta', name_order: 'Pedra Preta', uf: 'RN' },
			{ name: 'Pedro Avelino', name_order: 'Pedro Avelino', uf: 'RN' },
			{ name: 'Pedro Velho', name_order: 'Pedro Velho', uf: 'RN' },
			{ name: 'Pendências', name_order: 'Pendencias', uf: 'RN' },
			{ name: 'Pilões', name_order: 'Piloes', uf: 'RN' },
			{ name: 'Poço Branco', name_order: 'Poco Branco', uf: 'RN' },
			{ name: 'Portalegre', name_order: 'Portalegre', uf: 'RN' },
			{ name: 'Porto do Mangue', name_order: 'Porto do Mangue', uf: 'RN' },
			{ name: 'Presidente Juscelino', name_order: 'Presidente Juscelino', uf: 'RN' },
			{ name: 'Pureza', name_order: 'Pureza', uf: 'RN' },
			{ name: 'Rafael Fernandes', name_order: 'Rafael Fernandes', uf: 'RN' },
			{ name: 'Rafael Godeiro', name_order: 'Rafael Godeiro', uf: 'RN' },
			{ name: 'Riacho da Cruz', name_order: 'Riacho da Cruz', uf: 'RN' },
			{ name: 'Riacho de Santana', name_order: 'Riacho de Santana', uf: 'RN' },
			{ name: 'Riachuelo', name_order: 'Riachuelo', uf: 'RN' },
			{ name: 'Rodolfo Fernandes', name_order: 'Rodolfo Fernandes', uf: 'RN' },
			{ name: 'Tibau', name_order: 'Tibau', uf: 'RN' },
			{ name: 'Ruy Barbosa', name_order: 'Ruy Barbosa', uf: 'RN' },
			{ name: 'Santa Cruz', name_order: 'Santa Cruz', uf: 'RN' },
			{ name: 'Santana do Matos', name_order: 'Santana do Matos', uf: 'RN' },
	]);
};
