exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Água Branca', name_order: 'Agua Branca', uf: 'PB' },
			{ name: 'Aguiar', name_order: 'Aguiar', uf: 'PB' },
			{ name: 'Alagoa Grande', name_order: 'Alagoa Grande', uf: 'PB' },
			{ name: 'Alagoa Nova', name_order: 'Alagoa Nova', uf: 'PB' },
			{ name: 'Alagoinha', name_order: 'Alagoinha', uf: 'PB' },
			{ name: 'Alcantil', name_order: 'Alcantil', uf: 'PB' },
			{ name: 'Algodão de Jandaíra', name_order: 'Algodao de Jandaira', uf: 'PB' },
			{ name: 'Alhandra', name_order: 'Alhandra', uf: 'PB' },
			{ name: 'São João do Rio do Peixe', name_order: 'Sao Joao do Rio do Peixe', uf: 'PB' },
			{ name: 'Amparo', name_order: 'Amparo', uf: 'PB' },
			{ name: 'Aparecida', name_order: 'Aparecida', uf: 'PB' },
			{ name: 'Araçagi', name_order: 'Aracagi', uf: 'PB' },
			{ name: 'Arara', name_order: 'Arara', uf: 'PB' },
			{ name: 'Araruna', name_order: 'Araruna', uf: 'PB' },
			{ name: 'Areia', name_order: 'Areia', uf: 'PB' },
			{ name: 'Areia de Baraúnas', name_order: 'Areia de Baraunas', uf: 'PB' },
			{ name: 'Areial', name_order: 'Areial', uf: 'PB' },
			{ name: 'Aroeiras', name_order: 'Aroeiras', uf: 'PB' },
			{ name: 'Assunção', name_order: 'Assuncao', uf: 'PB' },
			{ name: 'Baía da Traição', name_order: 'Baia da Traicao', uf: 'PB' },
			{ name: 'Bananeiras', name_order: 'Bananeiras', uf: 'PB' },
			{ name: 'Baraúna', name_order: 'Barauna', uf: 'PB' },
			{ name: 'Barra de Santana', name_order: 'Barra de Santana', uf: 'PB' },
			{ name: 'Barra de Santa Rosa', name_order: 'Barra de Santa Rosa', uf: 'PB' },
			{ name: 'Barra de São Miguel', name_order: 'Barra de Sao Miguel', uf: 'PB' },
			{ name: 'Bayeux', name_order: 'Bayeux', uf: 'PB' },
			{ name: 'Belém', name_order: 'Belem', uf: 'PB' },
			{ name: 'Belém do Brejo do Cruz', name_order: 'Belem do Brejo do Cruz', uf: 'PB' },
			{ name: 'Bernardino Batista', name_order: 'Bernardino Batista', uf: 'PB' },
			{ name: 'Boa Ventura', name_order: 'Boa Ventura', uf: 'PB' },
			{ name: 'Boa Vista', name_order: 'Boa Vista', uf: 'PB' },
			{ name: 'Bom Jesus', name_order: 'Bom Jesus', uf: 'PB' },
			{ name: 'Bom Sucesso', name_order: 'Bom Sucesso', uf: 'PB' },
			{ name: 'Bonito de Santa fé', name_order: 'Bonito de Santa fe', uf: 'PB' },
			{ name: 'Boqueirão', name_order: 'Boqueirao', uf: 'PB' },
			{ name: 'Igaracy', name_order: 'Igaracy', uf: 'PB' },
			{ name: 'Borborema', name_order: 'Borborema', uf: 'PB' },
			{ name: 'Brejo do Cruz', name_order: 'Brejo do Cruz', uf: 'PB' },
			{ name: 'Brejo Dos Santos', name_order: 'Brejo Dos Santos', uf: 'PB' },
			{ name: 'Caaporã', name_order: 'Caapora', uf: 'PB' },
			{ name: 'Cabaceiras', name_order: 'Cabaceiras', uf: 'PB' },
			{ name: 'Cabedelo', name_order: 'Cabedelo', uf: 'PB' },
			{ name: 'Cachoeira Dos Índios', name_order: 'Cachoeira Dos Indios', uf: 'PB' },
			{ name: 'Cacimba de Areia', name_order: 'Cacimba de Areia', uf: 'PB' },
			{ name: 'Cacimba de Dentro', name_order: 'Cacimba de Dentro', uf: 'PB' },
			{ name: 'Cacimbas', name_order: 'Cacimbas', uf: 'PB' },
			{ name: 'Caiçara', name_order: 'Caicara', uf: 'PB' },
			{ name: 'Cajazeiras', name_order: 'Cajazeiras', uf: 'PB' },
			{ name: 'Cajazeirinhas', name_order: 'Cajazeirinhas', uf: 'PB' },
			{ name: 'Caldas Brandão', name_order: 'Caldas Brandao', uf: 'PB' },
			{ name: 'Camalaú', name_order: 'Camalau', uf: 'PB' },
			{ name: 'Campina Grande', name_order: 'Campina Grande', uf: 'PB' },
			{ name: 'Capim', name_order: 'Capim', uf: 'PB' },
			{ name: 'Caraúbas', name_order: 'Caraubas', uf: 'PB' },
			{ name: 'Carrapateira', name_order: 'Carrapateira', uf: 'PB' },
			{ name: 'Casserengue', name_order: 'Casserengue', uf: 'PB' },
			{ name: 'Catingueira', name_order: 'Catingueira', uf: 'PB' },
			{ name: 'Catolé do Rocha', name_order: 'Catole do Rocha', uf: 'PB' },
			{ name: 'Caturité', name_order: 'Caturite', uf: 'PB' },
			{ name: 'Conceição', name_order: 'Conceicao', uf: 'PB' },
			{ name: 'Condado', name_order: 'Condado', uf: 'PB' },
			{ name: 'Conde', name_order: 'Conde', uf: 'PB' },
			{ name: 'Congo', name_order: 'Congo', uf: 'PB' },
			{ name: 'Coremas', name_order: 'Coremas', uf: 'PB' },
			{ name: 'Coxixola', name_order: 'Coxixola', uf: 'PB' },
			{ name: 'Cruz do Espírito Santo', name_order: 'Cruz do Espirito Santo', uf: 'PB' },
			{ name: 'Cubati', name_order: 'Cubati', uf: 'PB' },
			{ name: 'Cuité', name_order: 'Cuite', uf: 'PB' },
			{ name: 'Cuitegi', name_order: 'Cuitegi', uf: 'PB' },
			{ name: 'Cuité de Mamanguape', name_order: 'Cuite de Mamanguape', uf: 'PB' },
			{ name: 'Curral de Cima', name_order: 'Curral de Cima', uf: 'PB' },
			{ name: 'Curral Velho', name_order: 'Curral Velho', uf: 'PB' },
			{ name: 'Damião', name_order: 'Damiao', uf: 'PB' },
			{ name: 'Desterro', name_order: 'Desterro', uf: 'PB' },
			{ name: 'Vista Serrana', name_order: 'Vista Serrana', uf: 'PB' },
			{ name: 'Diamante', name_order: 'Diamante', uf: 'PB' },
			{ name: 'Dona Inês', name_order: 'Dona Ines', uf: 'PB' },
			{ name: 'Duas Estradas', name_order: 'Duas Estradas', uf: 'PB' },
			{ name: 'Emas', name_order: 'Emas', uf: 'PB' },
			{ name: 'Esperança', name_order: 'Esperanca', uf: 'PB' },
			{ name: 'Fagundes', name_order: 'Fagundes', uf: 'PB' },
			{ name: 'Frei Martinho', name_order: 'Frei Martinho', uf: 'PB' },
			{ name: 'Gado Bravo', name_order: 'Gado Bravo', uf: 'PB' },
			{ name: 'Guarabira', name_order: 'Guarabira', uf: 'PB' },
			{ name: 'Gurinhém', name_order: 'Gurinhem', uf: 'PB' },
			{ name: 'Gurjão', name_order: 'Gurjao', uf: 'PB' },
			{ name: 'Ibiara', name_order: 'Ibiara', uf: 'PB' },
			{ name: 'Imaculada', name_order: 'Imaculada', uf: 'PB' },
			{ name: 'Ingá', name_order: 'Inga', uf: 'PB' },
			{ name: 'Itabaiana', name_order: 'Itabaiana', uf: 'PB' },
			{ name: 'Itaporanga', name_order: 'Itaporanga', uf: 'PB' },
			{ name: 'Itapororoca', name_order: 'Itapororoca', uf: 'PB' },
			{ name: 'Itatuba', name_order: 'Itatuba', uf: 'PB' },
			{ name: 'Jacaraú', name_order: 'Jacarau', uf: 'PB' },
			{ name: 'Jericó', name_order: 'Jerico', uf: 'PB' },
			{ name: 'João Pessoa', name_order: 'Joao Pessoa', uf: 'PB' },
			{ name: 'Juarez Távora', name_order: 'Juarez Tavora', uf: 'PB' },
			{ name: 'Juazeirinho', name_order: 'Juazeirinho', uf: 'PB' },
			{ name: 'Junco do Seridó', name_order: 'Junco do Serido', uf: 'PB' },
			{ name: 'Juripiranga', name_order: 'Juripiranga', uf: 'PB' },
			{ name: 'Juru', name_order: 'Juru', uf: 'PB' },
			{ name: 'Lagoa', name_order: 'Lagoa', uf: 'PB' },
			{ name: 'Lagoa de Dentro', name_order: 'Lagoa de Dentro', uf: 'PB' },
			{ name: 'Lagoa Seca', name_order: 'Lagoa Seca', uf: 'PB' },
			{ name: 'Lastro', name_order: 'Lastro', uf: 'PB' },
			{ name: 'Livramento', name_order: 'Livramento', uf: 'PB' },
			{ name: 'Logradouro', name_order: 'Logradouro', uf: 'PB' },
			{ name: 'Lucena', name_order: 'Lucena', uf: 'PB' },
			{ name: 'Mãe D´água', name_order: 'Mae Dagua', uf: 'PB' },
			{ name: 'Malta', name_order: 'Malta', uf: 'PB' },
			{ name: 'Mamanguape', name_order: 'Mamanguape', uf: 'PB' },
			{ name: 'Manaíra', name_order: 'Manaira', uf: 'PB' },
			{ name: 'Marcação', name_order: 'Marcacao', uf: 'PB' },
			{ name: 'Mari', name_order: 'Mari', uf: 'PB' },
			{ name: 'Marizópolis', name_order: 'Marizopolis', uf: 'PB' },
			{ name: 'Massaranduba', name_order: 'Massaranduba', uf: 'PB' },
			{ name: 'Mataraca', name_order: 'Mataraca', uf: 'PB' },
			{ name: 'Matinhas', name_order: 'Matinhas', uf: 'PB' },
			{ name: 'Mato Grosso', name_order: 'Mato Grosso', uf: 'PB' },
			{ name: 'Maturéia', name_order: 'Matureia', uf: 'PB' },
			{ name: 'Mogeiro', name_order: 'Mogeiro', uf: 'PB' },
			{ name: 'Montadas', name_order: 'Montadas', uf: 'PB' },
			{ name: 'Monte Horebe', name_order: 'Monte Horebe', uf: 'PB' },
			{ name: 'Monteiro', name_order: 'Monteiro', uf: 'PB' },
			{ name: 'Mulungu', name_order: 'Mulungu', uf: 'PB' },
			{ name: 'Natuba', name_order: 'Natuba', uf: 'PB' },
			{ name: 'Nazarezinho', name_order: 'Nazarezinho', uf: 'PB' },
			{ name: 'Nova Floresta', name_order: 'Nova Floresta', uf: 'PB' },
			{ name: 'Nova Olinda', name_order: 'Nova Olinda', uf: 'PB' },
			{ name: 'Nova Palmeira', name_order: 'Nova Palmeira', uf: 'PB' },
			{ name: 'Olho D´água', name_order: 'Olho Dagua', uf: 'PB' },
			{ name: 'Olivedos', name_order: 'Olivedos', uf: 'PB' },
			{ name: 'Ouro Velho', name_order: 'Ouro Velho', uf: 'PB' },
			{ name: 'Parari', name_order: 'Parari', uf: 'PB' },
			{ name: 'Passagem', name_order: 'Passagem', uf: 'PB' },
			{ name: 'Patos', name_order: 'Patos', uf: 'PB' },
			{ name: 'Paulista', name_order: 'Paulista', uf: 'PB' },
			{ name: 'Pedra Branca', name_order: 'Pedra Branca', uf: 'PB' },
			{ name: 'Pedra Lavrada', name_order: 'Pedra Lavrada', uf: 'PB' },
			{ name: 'Pedras de Fogo', name_order: 'Pedras de Fogo', uf: 'PB' },
			{ name: 'Piancó', name_order: 'Pianco', uf: 'PB' },
			{ name: 'Picuí', name_order: 'Picui', uf: 'PB' },
			{ name: 'Pilar', name_order: 'Pilar', uf: 'PB' },
			{ name: 'Pilões', name_order: 'Piloes', uf: 'PB' },
			{ name: 'Pilõezinhos', name_order: 'Piloezinhos', uf: 'PB' },
			{ name: 'Pirpirituba', name_order: 'Pirpirituba', uf: 'PB' },
			{ name: 'Pitimbu', name_order: 'Pitimbu', uf: 'PB' },
			{ name: 'Pocinhos', name_order: 'Pocinhos', uf: 'PB' },
			{ name: 'Poço Dantas', name_order: 'Poco Dantas', uf: 'PB' },
			{ name: 'Poço de José de Moura', name_order: 'Poco de Jose de Moura', uf: 'PB' },
			{ name: 'Pombal', name_order: 'Pombal', uf: 'PB' },
			{ name: 'Prata', name_order: 'Prata', uf: 'PB' },
			{ name: 'Princesa Isabel', name_order: 'Princesa Isabel', uf: 'PB' },
			{ name: 'Puxinanã', name_order: 'Puxinana', uf: 'PB' },
			{ name: 'Queimadas', name_order: 'Queimadas', uf: 'PB' },
			{ name: 'Quixabá', name_order: 'Quixaba', uf: 'PB' },
			{ name: 'Remígio', name_order: 'Remigio', uf: 'PB' },
			{ name: 'Pedro Régis', name_order: 'Pedro Regis', uf: 'PB' },
			{ name: 'Riachão', name_order: 'Riachao', uf: 'PB' },
			{ name: 'Riachão do Bacamarte', name_order: 'Riachao do Bacamarte', uf: 'PB' },
			{ name: 'Riachão do Poço', name_order: 'Riachao do Poco', uf: 'PB' },
			{ name: 'Riacho de Santo Antônio', name_order: 'Riacho de Santo Antonio', uf: 'PB' },
			{ name: 'Riacho Dos Cavalos', name_order: 'Riacho Dos Cavalos', uf: 'PB' },
			{ name: 'Rio Tinto', name_order: 'Rio Tinto', uf: 'PB' },
			{ name: 'Salgadinho', name_order: 'Salgadinho', uf: 'PB' },
			{ name: 'Salgado de São Félix', name_order: 'Salgado de Sao Felix', uf: 'PB' },
			{ name: 'Santa Cecília', name_order: 'Santa Cecilia', uf: 'PB' },
			{ name: 'Santa Cruz', name_order: 'Santa Cruz', uf: 'PB' },
			{ name: 'Santa Helena', name_order: 'Santa Helena', uf: 'PB' },
			{ name: 'Santa Inês', name_order: 'Santa Ines', uf: 'PB' },
			{ name: 'Santa Luzia', name_order: 'Santa Luzia', uf: 'PB' },
			{ name: 'Santana de Mangueira', name_order: 'Santana de Mangueira', uf: 'PB' },
			{ name: 'Santana Dos Garrotes', name_order: 'Santana Dos Garrotes', uf: 'PB' },
			{ name: 'Santarém', name_order: 'Santarem', uf: 'PB' },
			{ name: 'Santa Rita', name_order: 'Santa Rita', uf: 'PB' },
			{ name: 'Santa Teresinha', name_order: 'Santa Teresinha', uf: 'PB' },
			{ name: 'Santo André', name_order: 'Santo Andre', uf: 'PB' },
			{ name: 'São Bento', name_order: 'Sao Bento', uf: 'PB' },
			{ name: 'São Bentinho', name_order: 'Sao Bentinho', uf: 'PB' },
			{ name: 'São Domingos do Cariri', name_order: 'Sao Domingos do Cariri', uf: 'PB' },
			{ name: 'São Domingos de Pombal', name_order: 'Sao Domingos de Pombal', uf: 'PB' },
			{ name: 'São Francisco', name_order: 'Sao Francisco', uf: 'PB' },
			{ name: 'São João do Cariri', name_order: 'Sao Joao do Cariri', uf: 'PB' },
			{ name: 'São João do Tigre', name_order: 'Sao Joao do Tigre', uf: 'PB' },
			{ name: 'São José da Lagoa Tapada', name_order: 'Sao Jose da Lagoa Tapada', uf: 'PB' },
			{ name: 'São José de Caiana', name_order: 'Sao Jose de Caiana', uf: 'PB' },
			{ name: 'São José de Espinharas', name_order: 'Sao Jose de Espinharas', uf: 'PB' },
			{ name: 'São José Dos Ramos', name_order: 'Sao Jose Dos Ramos', uf: 'PB' },
			{ name: 'São José de Piranhas', name_order: 'Sao Jose de Piranhas', uf: 'PB' },
			{ name: 'São José de Princesa', name_order: 'Sao Jose de Princesa', uf: 'PB' },
			{ name: 'São José do Bonfim', name_order: 'Sao Jose do Bonfim', uf: 'PB' },
			{ name: 'São José do Brejo do Cruz', name_order: 'Sao Jose do Brejo do Cruz', uf: 'PB' },
			{ name: 'São José do Sabugi', name_order: 'Sao Jose do Sabugi', uf: 'PB' },
			{ name: 'São José Dos Cordeiros', name_order: 'Sao Jose Dos Cordeiros', uf: 'PB' },
			{ name: 'São Mamede', name_order: 'Sao Mamede', uf: 'PB' },
			{ name: 'São Miguel de Taipu', name_order: 'Sao Miguel de Taipu', uf: 'PB' },
			{ name: 'São Sebastião de Lagoa de Roça', name_order: 'Sao Sebastiao de Lagoa de Roca', uf: 'PB' },
			{ name: 'São Sebastião do Umbuzeiro', name_order: 'Sao Sebastiao do Umbuzeiro', uf: 'PB' },
			{ name: 'Sapé', name_order: 'Sape', uf: 'PB' },
			{ name: 'Seridó', name_order: 'Serido', uf: 'PB' },
			{ name: 'Serra Branca', name_order: 'Serra Branca', uf: 'PB' },
			{ name: 'Serra da Raiz', name_order: 'Serra da Raiz', uf: 'PB' },
			{ name: 'Serra Grande', name_order: 'Serra Grande', uf: 'PB' },
			{ name: 'Serra Redonda', name_order: 'Serra Redonda', uf: 'PB' },
			{ name: 'Serraria', name_order: 'Serraria', uf: 'PB' },
			{ name: 'Sertãozinho', name_order: 'Sertaozinho', uf: 'PB' },
			{ name: 'Sobrado', name_order: 'Sobrado', uf: 'PB' },
			{ name: 'Solânea', name_order: 'Solanea', uf: 'PB' },
			{ name: 'Soledade', name_order: 'Soledade', uf: 'PB' },
			{ name: 'Sossêgo', name_order: 'Sossego', uf: 'PB' },
			{ name: 'Sousa', name_order: 'Sousa', uf: 'PB' },
			{ name: 'Sumé', name_order: 'Sume', uf: 'PB' },
			{ name: 'Campo de Santana', name_order: 'Campo de Santana', uf: 'PB' },
			{ name: 'Taperoá', name_order: 'Taperoa', uf: 'PB' },
			{ name: 'Tavares', name_order: 'Tavares', uf: 'PB' },
			{ name: 'Teixeira', name_order: 'Teixeira', uf: 'PB' },
			{ name: 'Tenório', name_order: 'Tenorio', uf: 'PB' },
			{ name: 'Triunfo', name_order: 'Triunfo', uf: 'PB' },
			{ name: 'Uiraúna', name_order: 'Uirauna', uf: 'PB' },
			{ name: 'Umbuzeiro', name_order: 'Umbuzeiro', uf: 'PB' },
			{ name: 'Várzea', name_order: 'Varzea', uf: 'PB' },
			{ name: 'Vieirópolis', name_order: 'Vieiropolis', uf: 'PB' },
			{ name: 'Zabelê', name_order: 'Zabele', uf: 'PB' },
	]);
};
