exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abaetetuba', name_order: 'Abaetetuba', uf: 'PA' },
			{ name: 'Abel Figueiredo', name_order: 'Abel Figueiredo', uf: 'PA' },
			{ name: 'Acará', name_order: 'Acara', uf: 'PA' },
			{ name: 'Afuá', name_order: 'Afua', uf: 'PA' },
			{ name: 'Água Azul do Norte', name_order: 'Agua Azul do Norte', uf: 'PA' },
			{ name: 'Alenquer', name_order: 'Alenquer', uf: 'PA' },
			{ name: 'Almeirim', name_order: 'Almeirim', uf: 'PA' },
			{ name: 'Altamira', name_order: 'Altamira', uf: 'PA' },
			{ name: 'Anajás', name_order: 'Anajas', uf: 'PA' },
			{ name: 'Ananindeua', name_order: 'Ananindeua', uf: 'PA' },
			{ name: 'Anapu', name_order: 'Anapu', uf: 'PA' },
			{ name: 'Augusto Corrêa', name_order: 'Augusto Correa', uf: 'PA' },
			{ name: 'Aurora do Pará', name_order: 'Aurora do Para', uf: 'PA' },
			{ name: 'Aveiro', name_order: 'Aveiro', uf: 'PA' },
			{ name: 'Bagre', name_order: 'Bagre', uf: 'PA' },
			{ name: 'Baião', name_order: 'Baiao', uf: 'PA' },
			{ name: 'Bannach', name_order: 'Bannach', uf: 'PA' },
			{ name: 'Barcarena', name_order: 'Barcarena', uf: 'PA' },
			{ name: 'Belém', name_order: 'Belem', uf: 'PA' },
			{ name: 'Belterra', name_order: 'Belterra', uf: 'PA' },
			{ name: 'Benevides', name_order: 'Benevides', uf: 'PA' },
			{ name: 'Bom Jesus do Tocantins', name_order: 'Bom Jesus do Tocantins', uf: 'PA' },
			{ name: 'Bonito', name_order: 'Bonito', uf: 'PA' },
			{ name: 'Bragança', name_order: 'Braganca', uf: 'PA' },
			{ name: 'Brasil Novo', name_order: 'Brasil Novo', uf: 'PA' },
			{ name: 'Brejo Grande do Araguaia', name_order: 'Brejo Grande do Araguaia', uf: 'PA' },
			{ name: 'Breu Branco', name_order: 'Breu Branco', uf: 'PA' },
			{ name: 'Breves', name_order: 'Breves', uf: 'PA' },
			{ name: 'Bujaru', name_order: 'Bujaru', uf: 'PA' },
			{ name: 'Cachoeira do Piriá', name_order: 'Cachoeira do Piria', uf: 'PA' },
			{ name: 'Cachoeira do Arari', name_order: 'Cachoeira do Arari', uf: 'PA' },
			{ name: 'Cametá', name_order: 'Cameta', uf: 'PA' },
			{ name: 'Canaã Dos Carajás', name_order: 'Canaa Dos Carajas', uf: 'PA' },
			{ name: 'Capanema', name_order: 'Capanema', uf: 'PA' },
			{ name: 'Capitão Poço', name_order: 'Capitao Poco', uf: 'PA' },
			{ name: 'Castanhal', name_order: 'Castanhal', uf: 'PA' },
			{ name: 'Chaves', name_order: 'Chaves', uf: 'PA' },
			{ name: 'Colares', name_order: 'Colares', uf: 'PA' },
			{ name: 'Conceição do Araguaia', name_order: 'Conceicao do Araguaia', uf: 'PA' },
			{ name: 'Concórdia do Pará', name_order: 'Concordia do Para', uf: 'PA' },
			{ name: 'Cumaru do Norte', name_order: 'Cumaru do Norte', uf: 'PA' },
			{ name: 'Curionópolis', name_order: 'Curionopolis', uf: 'PA' },
			{ name: 'Curralinho', name_order: 'Curralinho', uf: 'PA' },
			{ name: 'Curuá', name_order: 'Curua', uf: 'PA' },
			{ name: 'Curuçá', name_order: 'Curuca', uf: 'PA' },
			{ name: 'Dom Eliseu', name_order: 'Dom Eliseu', uf: 'PA' },
			{ name: 'Eldorado Dos Carajás', name_order: 'Eldorado Dos Carajas', uf: 'PA' },
			{ name: 'Faro', name_order: 'Faro', uf: 'PA' },
			{ name: 'Floresta do Araguaia', name_order: 'Floresta do Araguaia', uf: 'PA' },
			{ name: 'Garrafão do Norte', name_order: 'Garrafao do Norte', uf: 'PA' },
			{ name: 'Goianésia do Pará', name_order: 'Goianesia do Para', uf: 'PA' },
			{ name: 'Gurupá', name_order: 'Gurupa', uf: 'PA' },
			{ name: 'Igarapé-açu', name_order: 'Igarapeacu', uf: 'PA' },
			{ name: 'Igarapé-miri', name_order: 'Igarapemiri', uf: 'PA' },
			{ name: 'Inhangapi', name_order: 'Inhangapi', uf: 'PA' },
			{ name: 'Ipixuna do Pará', name_order: 'Ipixuna do Para', uf: 'PA' },
			{ name: 'Irituia', name_order: 'Irituia', uf: 'PA' },
			{ name: 'Itaituba', name_order: 'Itaituba', uf: 'PA' },
			{ name: 'Itupiranga', name_order: 'Itupiranga', uf: 'PA' },
			{ name: 'Jacareacanga', name_order: 'Jacareacanga', uf: 'PA' },
			{ name: 'Jacundá', name_order: 'Jacunda', uf: 'PA' },
			{ name: 'Juruti', name_order: 'Juruti', uf: 'PA' },
			{ name: 'Limoeiro do Ajuru', name_order: 'Limoeiro do Ajuru', uf: 'PA' },
			{ name: 'Mãe do Rio', name_order: 'Mae do Rio', uf: 'PA' },
			{ name: 'Magalhães Barata', name_order: 'Magalhaes Barata', uf: 'PA' },
			{ name: 'Marabá', name_order: 'Maraba', uf: 'PA' },
			{ name: 'Maracanã', name_order: 'Maracana', uf: 'PA' },
			{ name: 'Marapanim', name_order: 'Marapanim', uf: 'PA' },
			{ name: 'Marituba', name_order: 'Marituba', uf: 'PA' },
			{ name: 'Medicilândia', name_order: 'Medicilandia', uf: 'PA' },
			{ name: 'Melgaço', name_order: 'Melgaco', uf: 'PA' },
			{ name: 'Mocajuba', name_order: 'Mocajuba', uf: 'PA' },
			{ name: 'Moju', name_order: 'Moju', uf: 'PA' },
			{ name: 'Mojuí dos Campos', name_order: 'Mojui dos Campos', uf: 'PA' },
			{ name: 'Monte Alegre', name_order: 'Monte Alegre', uf: 'PA' },
			{ name: 'Muaná', name_order: 'Muana', uf: 'PA' },
			{ name: 'Nova Esperança do Piriá', name_order: 'Nova Esperanca do Piria', uf: 'PA' },
			{ name: 'Nova Ipixuna', name_order: 'Nova Ipixuna', uf: 'PA' },
			{ name: 'Nova Timboteua', name_order: 'Nova Timboteua', uf: 'PA' },
			{ name: 'Novo Progresso', name_order: 'Novo Progresso', uf: 'PA' },
			{ name: 'Novo Repartimento', name_order: 'Novo Repartimento', uf: 'PA' },
			{ name: 'Óbidos', name_order: 'Obidos', uf: 'PA' },
			{ name: 'Oeiras do Pará', name_order: 'Oeiras do Para', uf: 'PA' },
			{ name: 'Oriximiná', name_order: 'Oriximina', uf: 'PA' },
			{ name: 'Ourém', name_order: 'Ourem', uf: 'PA' },
			{ name: 'Ourilândia do Norte', name_order: 'Ourilandia do Norte', uf: 'PA' },
			{ name: 'Pacajá', name_order: 'Pacaja', uf: 'PA' },
			{ name: 'Palestina do Pará', name_order: 'Palestina do Para', uf: 'PA' },
			{ name: 'Paragominas', name_order: 'Paragominas', uf: 'PA' },
			{ name: 'Parauapebas', name_order: 'Parauapebas', uf: 'PA' },
			{ name: 'Pau D´arco', name_order: 'Pau Darco', uf: 'PA' },
			{ name: 'Peixe-boi', name_order: 'Peixeboi', uf: 'PA' },
			{ name: 'Piçarra', name_order: 'Picarra', uf: 'PA' },
			{ name: 'Placas', name_order: 'Placas', uf: 'PA' },
			{ name: 'Ponta de Pedras', name_order: 'Ponta de Pedras', uf: 'PA' },
			{ name: 'Portel', name_order: 'Portel', uf: 'PA' },
			{ name: 'Porto de Moz', name_order: 'Porto de Moz', uf: 'PA' },
			{ name: 'Prainha', name_order: 'Prainha', uf: 'PA' },
			{ name: 'Primavera', name_order: 'Primavera', uf: 'PA' },
			{ name: 'Quatipuru', name_order: 'Quatipuru', uf: 'PA' },
			{ name: 'Redenção', name_order: 'Redencao', uf: 'PA' },
			{ name: 'Rio Maria', name_order: 'Rio Maria', uf: 'PA' },
			{ name: 'Rondon do Pará', name_order: 'Rondon do Para', uf: 'PA' },
			{ name: 'Rurópolis', name_order: 'Ruropolis', uf: 'PA' },
			{ name: 'Salinópolis', name_order: 'Salinopolis', uf: 'PA' },
			{ name: 'Salvaterra', name_order: 'Salvaterra', uf: 'PA' },
			{ name: 'Santa Bárbara do Pará', name_order: 'Santa Barbara do Para', uf: 'PA' },
			{ name: 'Santa Cruz do Arari', name_order: 'Santa Cruz do Arari', uf: 'PA' },
			{ name: 'Santa Isabel do Pará', name_order: 'Santa Isabel do Para', uf: 'PA' },
			{ name: 'Santa Luzia do Pará', name_order: 'Santa Luzia do Para', uf: 'PA' },
			{ name: 'Santa Maria Das Barreiras', name_order: 'Santa Maria Das Barreiras', uf: 'PA' },
			{ name: 'Santa Maria do Pará', name_order: 'Santa Maria do Para', uf: 'PA' },
			{ name: 'Santana do Araguaia', name_order: 'Santana do Araguaia', uf: 'PA' },
			{ name: 'Santarém', name_order: 'Santarem', uf: 'PA' },
			{ name: 'Santarém Novo', name_order: 'Santarem Novo', uf: 'PA' },
			{ name: 'Santo Antônio do Tauá', name_order: 'Santo Antonio do Taua', uf: 'PA' },
			{ name: 'São Caetano de Odivelas', name_order: 'Sao Caetano de Odivelas', uf: 'PA' },
			{ name: 'São Domingos do Araguaia', name_order: 'Sao Domingos do Araguaia', uf: 'PA' },
			{ name: 'São Domingos do Capim', name_order: 'Sao Domingos do Capim', uf: 'PA' },
			{ name: 'São Félix do Xingu', name_order: 'Sao Felix do Xingu', uf: 'PA' },
			{ name: 'São Francisco do Pará', name_order: 'Sao Francisco do Para', uf: 'PA' },
			{ name: 'São Geraldo do Araguaia', name_order: 'Sao Geraldo do Araguaia', uf: 'PA' },
			{ name: 'São João da Ponta', name_order: 'Sao Joao da Ponta', uf: 'PA' },
			{ name: 'São João de Pirabas', name_order: 'Sao Joao de Pirabas', uf: 'PA' },
			{ name: 'São João do Araguaia', name_order: 'Sao Joao do Araguaia', uf: 'PA' },
			{ name: 'São Miguel do Guamá', name_order: 'Sao Miguel do Guama', uf: 'PA' },
			{ name: 'São Sebastião da Boa Vista', name_order: 'Sao Sebastiao da Boa Vista', uf: 'PA' },
			{ name: 'Sapucaia', name_order: 'Sapucaia', uf: 'PA' },
			{ name: 'Senador José Porfírio', name_order: 'Senador Jose Porfirio', uf: 'PA' },
			{ name: 'Soure', name_order: 'Soure', uf: 'PA' },
			{ name: 'Tailândia', name_order: 'Tailandia', uf: 'PA' },
			{ name: 'Terra Alta', name_order: 'Terra Alta', uf: 'PA' },
			{ name: 'Terra Santa', name_order: 'Terra Santa', uf: 'PA' },
			{ name: 'Tomé-açu', name_order: 'Tomeacu', uf: 'PA' },
			{ name: 'Tracuateua', name_order: 'Tracuateua', uf: 'PA' },
			{ name: 'Trairão', name_order: 'Trairao', uf: 'PA' },
			{ name: 'Tucumã', name_order: 'Tucuma', uf: 'PA' },
			{ name: 'Tucuruí', name_order: 'Tucurui', uf: 'PA' },
			{ name: 'Ulianópolis', name_order: 'Ulianopolis', uf: 'PA' },
			{ name: 'Uruará', name_order: 'Uruara', uf: 'PA' },
			{ name: 'Vigia', name_order: 'Vigia', uf: 'PA' },
			{ name: 'Viseu', name_order: 'Viseu', uf: 'PA' },
			{ name: 'Vitória do Xingu', name_order: 'Vitoria do Xingu', uf: 'PA' },
			{ name: 'Xinguara', name_order: 'Xinguara', uf: 'PA' },
	]);
};
