exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Manhumirim', name_order: 'Manhumirim', uf: 'MG' },
			{ name: 'Mantena', name_order: 'Mantena', uf: 'MG' },
			{ name: 'Maravilhas', name_order: 'Maravilhas', uf: 'MG' },
			{ name: 'Mar de Espanha', name_order: 'Mar de Espanha', uf: 'MG' },
			{ name: 'Maria da fé', name_order: 'Maria da fe', uf: 'MG' },
			{ name: 'Mariana', name_order: 'Mariana', uf: 'MG' },
			{ name: 'Marilac', name_order: 'Marilac', uf: 'MG' },
			{ name: 'Mário Campos', name_order: 'Mario Campos', uf: 'MG' },
			{ name: 'Maripá de Minas', name_order: 'Maripa de Minas', uf: 'MG' },
			{ name: 'Marliéria', name_order: 'Marlieria', uf: 'MG' },
			{ name: 'Marmelópolis', name_order: 'Marmelopolis', uf: 'MG' },
			{ name: 'Martinho Campos', name_order: 'Martinho Campos', uf: 'MG' },
			{ name: 'Martins Soares', name_order: 'Martins Soares', uf: 'MG' },
			{ name: 'Mata Verde', name_order: 'Mata Verde', uf: 'MG' },
			{ name: 'Materlândia', name_order: 'Materlandia', uf: 'MG' },
			{ name: 'Mateus Leme', name_order: 'Mateus Leme', uf: 'MG' },
			{ name: 'Matias Barbosa', name_order: 'Matias Barbosa', uf: 'MG' },
			{ name: 'Matias Cardoso', name_order: 'Matias Cardoso', uf: 'MG' },
			{ name: 'Matipó', name_order: 'Matipo', uf: 'MG' },
			{ name: 'Mato Verde', name_order: 'Mato Verde', uf: 'MG' },
			{ name: 'Matozinhos', name_order: 'Matozinhos', uf: 'MG' },
			{ name: 'Matutina', name_order: 'Matutina', uf: 'MG' },
			{ name: 'Medeiros', name_order: 'Medeiros', uf: 'MG' },
			{ name: 'Medina', name_order: 'Medina', uf: 'MG' },
			{ name: 'Mendes Pimentel', name_order: 'Mendes Pimentel', uf: 'MG' },
			{ name: 'Mercês', name_order: 'Merces', uf: 'MG' },
			{ name: 'Mesquita', name_order: 'Mesquita', uf: 'MG' },
			{ name: 'Minas Novas', name_order: 'Minas Novas', uf: 'MG' },
			{ name: 'Minduri', name_order: 'Minduri', uf: 'MG' },
			{ name: 'Mirabela', name_order: 'Mirabela', uf: 'MG' },
			{ name: 'Miradouro', name_order: 'Miradouro', uf: 'MG' },
			{ name: 'Miraí', name_order: 'Mirai', uf: 'MG' },
			{ name: 'Miravânia', name_order: 'Miravania', uf: 'MG' },
			{ name: 'Moeda', name_order: 'Moeda', uf: 'MG' },
			{ name: 'Moema', name_order: 'Moema', uf: 'MG' },
			{ name: 'Monjolos', name_order: 'Monjolos', uf: 'MG' },
			{ name: 'Monsenhor Paulo', name_order: 'Monsenhor Paulo', uf: 'MG' },
			{ name: 'Montalvânia', name_order: 'Montalvania', uf: 'MG' },
			{ name: 'Monte Alegre de Minas', name_order: 'Monte Alegre de Minas', uf: 'MG' },
			{ name: 'Monte Azul', name_order: 'Monte Azul', uf: 'MG' },
			{ name: 'Monte Belo', name_order: 'Monte Belo', uf: 'MG' },
			{ name: 'Monte Carmelo', name_order: 'Monte Carmelo', uf: 'MG' },
			{ name: 'Monte Formoso', name_order: 'Monte Formoso', uf: 'MG' },
			{ name: 'Monte Santo de Minas', name_order: 'Monte Santo de Minas', uf: 'MG' },
			{ name: 'Montes Claros', name_order: 'Montes Claros', uf: 'MG' },
			{ name: 'Monte Sião', name_order: 'Monte Siao', uf: 'MG' },
			{ name: 'Montezuma', name_order: 'Montezuma', uf: 'MG' },
			{ name: 'Morada Nova de Minas', name_order: 'Morada Nova de Minas', uf: 'MG' },
			{ name: 'Morro da Garça', name_order: 'Morro da Garca', uf: 'MG' },
			{ name: 'Morro do Pilar', name_order: 'Morro do Pilar', uf: 'MG' },
			{ name: 'Munhoz', name_order: 'Munhoz', uf: 'MG' },
			{ name: 'Muriaé', name_order: 'Muriae', uf: 'MG' },
			{ name: 'Mutum', name_order: 'Mutum', uf: 'MG' },
			{ name: 'Muzambinho', name_order: 'Muzambinho', uf: 'MG' },
			{ name: 'Nacip Raydan', name_order: 'Nacip Raydan', uf: 'MG' },
			{ name: 'Nanuque', name_order: 'Nanuque', uf: 'MG' },
			{ name: 'Naque', name_order: 'Naque', uf: 'MG' },
			{ name: 'Natalândia', name_order: 'Natalandia', uf: 'MG' },
			{ name: 'Natércia', name_order: 'Natercia', uf: 'MG' },
			{ name: 'Nazareno', name_order: 'Nazareno', uf: 'MG' },
			{ name: 'Nepomuceno', name_order: 'Nepomuceno', uf: 'MG' },
			{ name: 'Ninheira', name_order: 'Ninheira', uf: 'MG' },
			{ name: 'Nova Belém', name_order: 'Nova Belem', uf: 'MG' },
			{ name: 'Nova Era', name_order: 'Nova Era', uf: 'MG' },
			{ name: 'Nova Lima', name_order: 'Nova Lima', uf: 'MG' },
			{ name: 'Nova Módica', name_order: 'Nova Modica', uf: 'MG' },
			{ name: 'Nova Ponte', name_order: 'Nova Ponte', uf: 'MG' },
			{ name: 'Nova Porteirinha', name_order: 'Nova Porteirinha', uf: 'MG' },
			{ name: 'Nova Resende', name_order: 'Nova Resende', uf: 'MG' },
			{ name: 'Nova Serrana', name_order: 'Nova Serrana', uf: 'MG' },
			{ name: 'Novo Cruzeiro', name_order: 'Novo Cruzeiro', uf: 'MG' },
			{ name: 'Novo Oriente de Minas', name_order: 'Novo Oriente de Minas', uf: 'MG' },
			{ name: 'Novorizonte', name_order: 'Novorizonte', uf: 'MG' },
			{ name: 'Olaria', name_order: 'Olaria', uf: 'MG' },
			{ name: 'Olhos-d´água', name_order: 'Olhosdagua', uf: 'MG' },
			{ name: 'Olímpio Noronha', name_order: 'Olimpio Noronha', uf: 'MG' },
			{ name: 'Oliveira', name_order: 'Oliveira', uf: 'MG' },
			{ name: 'Oliveira Fortes', name_order: 'Oliveira Fortes', uf: 'MG' },
			{ name: 'Onça de Pitangui', name_order: 'Onca de Pitangui', uf: 'MG' },
			{ name: 'Oratórios', name_order: 'Oratorios', uf: 'MG' },
			{ name: 'Orizânia', name_order: 'Orizania', uf: 'MG' },
			{ name: 'Ouro Branco', name_order: 'Ouro Branco', uf: 'MG' },
			{ name: 'Ouro Fino', name_order: 'Ouro Fino', uf: 'MG' },
			{ name: 'Ouro Preto', name_order: 'Ouro Preto', uf: 'MG' },
			{ name: 'Ouro Verde de Minas', name_order: 'Ouro Verde de Minas', uf: 'MG' },
			{ name: 'Padre Carvalho', name_order: 'Padre Carvalho', uf: 'MG' },
			{ name: 'Padre Paraíso', name_order: 'Padre Paraiso', uf: 'MG' },
			{ name: 'Paineiras', name_order: 'Paineiras', uf: 'MG' },
			{ name: 'Pains', name_order: 'Pains', uf: 'MG' },
			{ name: 'Pai Pedro', name_order: 'Pai Pedro', uf: 'MG' },
			{ name: 'Paiva', name_order: 'Paiva', uf: 'MG' },
			{ name: 'Palma', name_order: 'Palma', uf: 'MG' },
			{ name: 'Palmópolis', name_order: 'Palmopolis', uf: 'MG' },
			{ name: 'Papagaios', name_order: 'Papagaios', uf: 'MG' },
			{ name: 'Paracatu', name_order: 'Paracatu', uf: 'MG' },
			{ name: 'Pará de Minas', name_order: 'Para de Minas', uf: 'MG' },
			{ name: 'Paraguaçu', name_order: 'Paraguacu', uf: 'MG' },
			{ name: 'Paraisópolis', name_order: 'Paraisopolis', uf: 'MG' },
			{ name: 'Paraopeba', name_order: 'Paraopeba', uf: 'MG' },
			{ name: 'Passabém', name_order: 'Passabem', uf: 'MG' },
			{ name: 'Passa Quatro', name_order: 'Passa Quatro', uf: 'MG' },
			{ name: 'Passa Tempo', name_order: 'Passa Tempo', uf: 'MG' },
			{ name: 'Passa-vinte', name_order: 'Passavinte', uf: 'MG' },
			{ name: 'Passos', name_order: 'Passos', uf: 'MG' },
			{ name: 'Patis', name_order: 'Patis', uf: 'MG' },
			{ name: 'Patos de Minas', name_order: 'Patos de Minas', uf: 'MG' },
			{ name: 'Patrocínio', name_order: 'Patrocinio', uf: 'MG' },
			{ name: 'Patrocínio do Muriaé', name_order: 'Patrocinio do Muriae', uf: 'MG' },
			{ name: 'Paula Cândido', name_order: 'Paula Candido', uf: 'MG' },
			{ name: 'Paulistas', name_order: 'Paulistas', uf: 'MG' },
			{ name: 'Pavão', name_order: 'Pavao', uf: 'MG' },
			{ name: 'Peçanha', name_order: 'Pecanha', uf: 'MG' },
			{ name: 'Pedra Azul', name_order: 'Pedra Azul', uf: 'MG' },
			{ name: 'Pedra Bonita', name_order: 'Pedra Bonita', uf: 'MG' },
			{ name: 'Pedra do Anta', name_order: 'Pedra do Anta', uf: 'MG' },
			{ name: 'Pedra do Indaiá', name_order: 'Pedra do Indaia', uf: 'MG' },
			{ name: 'Pedra Dourada', name_order: 'Pedra Dourada', uf: 'MG' },
			{ name: 'Pedralva', name_order: 'Pedralva', uf: 'MG' },
			{ name: 'Pedras de Maria da Cruz', name_order: 'Pedras de Maria da Cruz', uf: 'MG' },
			{ name: 'Pedrinópolis', name_order: 'Pedrinopolis', uf: 'MG' },
			{ name: 'Pedro Leopoldo', name_order: 'Pedro Leopoldo', uf: 'MG' },
			{ name: 'Pedro Teixeira', name_order: 'Pedro Teixeira', uf: 'MG' },
			{ name: 'Pequeri', name_order: 'Pequeri', uf: 'MG' },
			{ name: 'Pequi', name_order: 'Pequi', uf: 'MG' },
			{ name: 'Perdigão', name_order: 'Perdigao', uf: 'MG' },
			{ name: 'Perdizes', name_order: 'Perdizes', uf: 'MG' },
			{ name: 'Perdões', name_order: 'Perdoes', uf: 'MG' },
			{ name: 'Periquito', name_order: 'Periquito', uf: 'MG' },
			{ name: 'Pescador', name_order: 'Pescador', uf: 'MG' },
			{ name: 'Piau', name_order: 'Piau', uf: 'MG' },
			{ name: 'Piedade de Caratinga', name_order: 'Piedade de Caratinga', uf: 'MG' },
			{ name: 'Piedade de Ponte Nova', name_order: 'Piedade de Ponte Nova', uf: 'MG' },
			{ name: 'Piedade do Rio Grande', name_order: 'Piedade do Rio Grande', uf: 'MG' },
			{ name: 'Piedade Dos Gerais', name_order: 'Piedade Dos Gerais', uf: 'MG' },
			{ name: 'Pimenta', name_order: 'Pimenta', uf: 'MG' },
			{ name: 'Pingo-d´água', name_order: 'Pingodagua', uf: 'MG' },
			{ name: 'Pintópolis', name_order: 'Pintopolis', uf: 'MG' },
			{ name: 'Piracema', name_order: 'Piracema', uf: 'MG' },
			{ name: 'Pirajuba', name_order: 'Pirajuba', uf: 'MG' },
			{ name: 'Piranga', name_order: 'Piranga', uf: 'MG' },
			{ name: 'Piranguçu', name_order: 'Pirangucu', uf: 'MG' },
			{ name: 'Piranguinho', name_order: 'Piranguinho', uf: 'MG' },
			{ name: 'Pirapetinga', name_order: 'Pirapetinga', uf: 'MG' },
			{ name: 'Pirapora', name_order: 'Pirapora', uf: 'MG' },
			{ name: 'Piraúba', name_order: 'Pirauba', uf: 'MG' },
			{ name: 'Pitangui', name_order: 'Pitangui', uf: 'MG' },
			{ name: 'Piumhi', name_order: 'Piumhi', uf: 'MG' },
			{ name: 'Planura', name_order: 'Planura', uf: 'MG' },
			{ name: 'Poço Fundo', name_order: 'Poco Fundo', uf: 'MG' },
			{ name: 'Poços de Caldas', name_order: 'Pocos de Caldas', uf: 'MG' },
			{ name: 'Pocrane', name_order: 'Pocrane', uf: 'MG' },
			{ name: 'Pompéu', name_order: 'Pompeu', uf: 'MG' },
			{ name: 'Ponte Nova', name_order: 'Ponte Nova', uf: 'MG' },
			{ name: 'Ponto Chique', name_order: 'Ponto Chique', uf: 'MG' },
			{ name: 'Ponto Dos Volantes', name_order: 'Ponto Dos Volantes', uf: 'MG' },
			{ name: 'Porteirinha', name_order: 'Porteirinha', uf: 'MG' },
			{ name: 'Porto Firme', name_order: 'Porto Firme', uf: 'MG' },
			{ name: 'Poté', name_order: 'Pote', uf: 'MG' },
			{ name: 'Pouso Alegre', name_order: 'Pouso Alegre', uf: 'MG' },
			{ name: 'Pouso Alto', name_order: 'Pouso Alto', uf: 'MG' },
			{ name: 'Prados', name_order: 'Prados', uf: 'MG' },
			{ name: 'Prata', name_order: 'Prata', uf: 'MG' },
			{ name: 'Pratápolis', name_order: 'Pratapolis', uf: 'MG' },
			{ name: 'Pratinha', name_order: 'Pratinha', uf: 'MG' },
			{ name: 'Presidente Bernardes', name_order: 'Presidente Bernardes', uf: 'MG' },
			{ name: 'Presidente Juscelino', name_order: 'Presidente Juscelino', uf: 'MG' },
			{ name: 'Presidente Kubitschek', name_order: 'Presidente Kubitschek', uf: 'MG' },
			{ name: 'Presidente Olegário', name_order: 'Presidente Olegario', uf: 'MG' },
			{ name: 'Alto Jequitibá', name_order: 'Alto Jequitiba', uf: 'MG' },
			{ name: 'Prudente de Morais', name_order: 'Prudente de Morais', uf: 'MG' },
			{ name: 'Quartel Geral', name_order: 'Quartel Geral', uf: 'MG' },
			{ name: 'Queluzito', name_order: 'Queluzito', uf: 'MG' },
			{ name: 'Raposos', name_order: 'Raposos', uf: 'MG' },
			{ name: 'Raul Soares', name_order: 'Raul Soares', uf: 'MG' },
			{ name: 'Recreio', name_order: 'Recreio', uf: 'MG' },
			{ name: 'Reduto', name_order: 'Reduto', uf: 'MG' },
			{ name: 'Resende Costa', name_order: 'Resende Costa', uf: 'MG' },
			{ name: 'Resplendor', name_order: 'Resplendor', uf: 'MG' },
			{ name: 'Ressaquinha', name_order: 'Ressaquinha', uf: 'MG' },
			{ name: 'Riachinho', name_order: 'Riachinho', uf: 'MG' },
			{ name: 'Riacho Dos Machados', name_order: 'Riacho Dos Machados', uf: 'MG' },
			{ name: 'Ribeirão Das Neves', name_order: 'Ribeirao Das Neves', uf: 'MG' },
			{ name: 'Ribeirão Vermelho', name_order: 'Ribeirao Vermelho', uf: 'MG' },
			{ name: 'Rio Acima', name_order: 'Rio Acima', uf: 'MG' },
			{ name: 'Rio Casca', name_order: 'Rio Casca', uf: 'MG' },
			{ name: 'Rio Doce', name_order: 'Rio Doce', uf: 'MG' },
			{ name: 'Rio do Prado', name_order: 'Rio do Prado', uf: 'MG' },
			{ name: 'Rio Espera', name_order: 'Rio Espera', uf: 'MG' },
			{ name: 'Rio Manso', name_order: 'Rio Manso', uf: 'MG' },
			{ name: 'Rio Novo', name_order: 'Rio Novo', uf: 'MG' },
			{ name: 'Rio Paranaíba', name_order: 'Rio Paranaiba', uf: 'MG' },
			{ name: 'Rio Pardo de Minas', name_order: 'Rio Pardo de Minas', uf: 'MG' },
			{ name: 'Rio Piracicaba', name_order: 'Rio Piracicaba', uf: 'MG' },
			{ name: 'Rio Pomba', name_order: 'Rio Pomba', uf: 'MG' },
			{ name: 'Rio Preto', name_order: 'Rio Preto', uf: 'MG' },
			{ name: 'Rio Vermelho', name_order: 'Rio Vermelho', uf: 'MG' },
			{ name: 'Ritápolis', name_order: 'Ritapolis', uf: 'MG' },
			{ name: 'Rochedo de Minas', name_order: 'Rochedo de Minas', uf: 'MG' },
			{ name: 'Rodeiro', name_order: 'Rodeiro', uf: 'MG' },
			{ name: 'Romaria', name_order: 'Romaria', uf: 'MG' },
			{ name: 'Rosário da Limeira', name_order: 'Rosario da Limeira', uf: 'MG' },
			{ name: 'Rubelita', name_order: 'Rubelita', uf: 'MG' },
			{ name: 'Rubim', name_order: 'Rubim', uf: 'MG' },
			{ name: 'Sabará', name_order: 'Sabara', uf: 'MG' },
			{ name: 'Sabinópolis', name_order: 'Sabinopolis', uf: 'MG' },
			{ name: 'Sacramento', name_order: 'Sacramento', uf: 'MG' },
			{ name: 'Salinas', name_order: 'Salinas', uf: 'MG' },
			{ name: 'Salto da Divisa', name_order: 'Salto da Divisa', uf: 'MG' },
			{ name: 'Santa Bárbara', name_order: 'Santa Barbara', uf: 'MG' },
			{ name: 'Santa Bárbara do Leste', name_order: 'Santa Barbara do Leste', uf: 'MG' },
			{ name: 'Santa Bárbara do Monte Verde', name_order: 'Santa Barbara do Monte Verde', uf: 'MG' },
			{ name: 'Santa Bárbara do Tugúrio', name_order: 'Santa Barbara do Tugurio', uf: 'MG' },
			{ name: 'Santa Cruz de Minas', name_order: 'Santa Cruz de Minas', uf: 'MG' },
			{ name: 'Santa Cruz de Salinas', name_order: 'Santa Cruz de Salinas', uf: 'MG' },
			{ name: 'Santa Cruz do Escalvado', name_order: 'Santa Cruz do Escalvado', uf: 'MG' },
			{ name: 'Santa Efigênia de Minas', name_order: 'Santa Efigenia de Minas', uf: 'MG' },
			{ name: 'Santa fé de Minas', name_order: 'Santa fe de Minas', uf: 'MG' },
			{ name: 'Santa Helena de Minas', name_order: 'Santa Helena de Minas', uf: 'MG' },
			{ name: 'Santa Juliana', name_order: 'Santa Juliana', uf: 'MG' },
			{ name: 'Santa Luzia', name_order: 'Santa Luzia', uf: 'MG' },
			{ name: 'Santa Margarida', name_order: 'Santa Margarida', uf: 'MG' },
			{ name: 'Santa Maria de Itabira', name_order: 'Santa Maria de Itabira', uf: 'MG' },
			{ name: 'Santa Maria do Salto', name_order: 'Santa Maria do Salto', uf: 'MG' },
			{ name: 'Santa Maria do Suaçuí', name_order: 'Santa Maria do Suacui', uf: 'MG' },
			{ name: 'Santana da Vargem', name_order: 'Santana da Vargem', uf: 'MG' },
			{ name: 'Santana de Cataguases', name_order: 'Santana de Cataguases', uf: 'MG' },
			{ name: 'Santana de Pirapama', name_order: 'Santana de Pirapama', uf: 'MG' },
			{ name: 'Santana do Deserto', name_order: 'Santana do Deserto', uf: 'MG' },
			{ name: 'Santana do Garambéu', name_order: 'Santana do Garambeu', uf: 'MG' },
			{ name: 'Santana do Jacaré', name_order: 'Santana do Jacare', uf: 'MG' },
			{ name: 'Santana do Manhuaçu', name_order: 'Santana do Manhuacu', uf: 'MG' },
			{ name: 'Santana do Paraíso', name_order: 'Santana do Paraiso', uf: 'MG' },
			{ name: 'Santana do Riacho', name_order: 'Santana do Riacho', uf: 'MG' },
			{ name: 'Santana Dos Montes', name_order: 'Santana Dos Montes', uf: 'MG' },
			{ name: 'Santa Rita de Caldas', name_order: 'Santa Rita de Caldas', uf: 'MG' },
			{ name: 'Santa Rita de Jacutinga', name_order: 'Santa Rita de Jacutinga', uf: 'MG' },
			{ name: 'Santa Rita de Minas', name_order: 'Santa Rita de Minas', uf: 'MG' },
			{ name: 'Santa Rita de Ibitipoca', name_order: 'Santa Rita de Ibitipoca', uf: 'MG' },
			{ name: 'Santa Rita do Itueto', name_order: 'Santa Rita do Itueto', uf: 'MG' },
			{ name: 'Santa Rita do Sapucaí', name_order: 'Santa Rita do Sapucai', uf: 'MG' },
			{ name: 'Santa Rosa da Serra', name_order: 'Santa Rosa da Serra', uf: 'MG' },
			{ name: 'Santa Vitória', name_order: 'Santa Vitoria', uf: 'MG' },
			{ name: 'Santo Antônio do Amparo', name_order: 'Santo Antonio do Amparo', uf: 'MG' },
			{ name: 'Santo Antônio do Aventureiro', name_order: 'Santo Antonio do Aventureiro', uf: 'MG' },
			{ name: 'Santo Antônio do Grama', name_order: 'Santo Antonio do Grama', uf: 'MG' },
			{ name: 'Santo Antônio do Itambé', name_order: 'Santo Antonio do Itambe', uf: 'MG' },
			{ name: 'Santo Antônio do Jacinto', name_order: 'Santo Antonio do Jacinto', uf: 'MG' },
			{ name: 'Santo Antônio do Monte', name_order: 'Santo Antonio do Monte', uf: 'MG' },
			{ name: 'Santo Antônio do Retiro', name_order: 'Santo Antonio do Retiro', uf: 'MG' },
			{ name: 'Santo Antônio do Rio Abaixo', name_order: 'Santo Antonio do Rio Abaixo', uf: 'MG' },
			{ name: 'Santo Hipólito', name_order: 'Santo Hipolito', uf: 'MG' },
			{ name: 'Santos Dumont', name_order: 'Santos Dumont', uf: 'MG' },
			{ name: 'São Bento Abade', name_order: 'Sao Bento Abade', uf: 'MG' },
			{ name: 'São Brás do Suaçuí', name_order: 'Sao Bras do Suacui', uf: 'MG' },
			{ name: 'São Domingos Das Dores', name_order: 'Sao Domingos Das Dores', uf: 'MG' },
			{ name: 'São Domingos do Prata', name_order: 'Sao Domingos do Prata', uf: 'MG' },
			{ name: 'São Félix de Minas', name_order: 'Sao Felix de Minas', uf: 'MG' },
			{ name: 'São Francisco', name_order: 'Sao Francisco', uf: 'MG' },
			{ name: 'São Francisco de Paula', name_order: 'Sao Francisco de Paula', uf: 'MG' },
			{ name: 'São Francisco de Sales', name_order: 'Sao Francisco de Sales', uf: 'MG' },
			{ name: 'São Francisco do Glória', name_order: 'Sao Francisco do Gloria', uf: 'MG' },
			{ name: 'São Geraldo', name_order: 'Sao Geraldo', uf: 'MG' },
			{ name: 'São Geraldo da Piedade', name_order: 'Sao Geraldo da Piedade', uf: 'MG' },
			{ name: 'São Geraldo do Baixio', name_order: 'Sao Geraldo do Baixio', uf: 'MG' },
			{ name: 'São Gonçalo do Abaeté', name_order: 'Sao Goncalo do Abaete', uf: 'MG' },
			{ name: 'São Gonçalo do Pará', name_order: 'Sao Goncalo do Para', uf: 'MG' },
			{ name: 'São Gonçalo do Rio Abaixo', name_order: 'Sao Goncalo do Rio Abaixo', uf: 'MG' },
			{ name: 'São Gonçalo do Sapucaí', name_order: 'Sao Goncalo do Sapucai', uf: 'MG' },
			{ name: 'São Gotardo', name_order: 'Sao Gotardo', uf: 'MG' },
			{ name: 'São João Batista do Glória', name_order: 'Sao Joao Batista do Gloria', uf: 'MG' },
			{ name: 'São João da Lagoa', name_order: 'Sao Joao da Lagoa', uf: 'MG' },
			{ name: 'São João da Mata', name_order: 'Sao Joao da Mata', uf: 'MG' },
			{ name: 'São João da Ponte', name_order: 'Sao Joao da Ponte', uf: 'MG' },
			{ name: 'São João Das Missões', name_order: 'Sao Joao Das Missoes', uf: 'MG' },
			{ name: 'São João Del Rei', name_order: 'Sao Joao Del Rei', uf: 'MG' },
			{ name: 'São João do Manhuaçu', name_order: 'Sao Joao do Manhuacu', uf: 'MG' },
			{ name: 'São João do Manteninha', name_order: 'Sao Joao do Manteninha', uf: 'MG' },
			{ name: 'São João do Oriente', name_order: 'Sao Joao do Oriente', uf: 'MG' },
			{ name: 'São João do Pacuí', name_order: 'Sao Joao do Pacui', uf: 'MG' },
			{ name: 'São João do Paraíso', name_order: 'Sao Joao do Paraiso', uf: 'MG' },
			{ name: 'São João Evangelista', name_order: 'Sao Joao Evangelista', uf: 'MG' },
			{ name: 'São João Nepomuceno', name_order: 'Sao Joao Nepomuceno', uf: 'MG' },
			{ name: 'São Joaquim de Bicas', name_order: 'Sao Joaquim de Bicas', uf: 'MG' },
			{ name: 'São José da Barra', name_order: 'Sao Jose da Barra', uf: 'MG' },
			{ name: 'São José da Lapa', name_order: 'Sao Jose da Lapa', uf: 'MG' },
			{ name: 'São José da Safira', name_order: 'Sao Jose da Safira', uf: 'MG' },
			{ name: 'São José da Varginha', name_order: 'Sao Jose da Varginha', uf: 'MG' },
			{ name: 'São José do Alegre', name_order: 'Sao Jose do Alegre', uf: 'MG' },
			{ name: 'São José do Divino', name_order: 'Sao Jose do Divino', uf: 'MG' },
			{ name: 'São José do Goiabal', name_order: 'Sao Jose do Goiabal', uf: 'MG' },
			{ name: 'São José do Jacuri', name_order: 'Sao Jose do Jacuri', uf: 'MG' },
			{ name: 'São José do Mantimento', name_order: 'Sao Jose do Mantimento', uf: 'MG' },
			{ name: 'São Lourenço', name_order: 'Sao Lourenco', uf: 'MG' },
			{ name: 'São Miguel do Anta', name_order: 'Sao Miguel do Anta', uf: 'MG' },
			{ name: 'São Pedro da União', name_order: 'Sao Pedro da Uniao', uf: 'MG' },
			{ name: 'São Pedro Dos Ferros', name_order: 'Sao Pedro Dos Ferros', uf: 'MG' },
			{ name: 'São Pedro do Suaçuí', name_order: 'Sao Pedro do Suacui', uf: 'MG' },
			{ name: 'São Romão', name_order: 'Sao Romao', uf: 'MG' },
			{ name: 'São Roque de Minas', name_order: 'Sao Roque de Minas', uf: 'MG' },
			{ name: 'São Sebastião da Bela Vista', name_order: 'Sao Sebastiao da Bela Vista', uf: 'MG' },
	]);
};
