exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abadia de Goiás', name_order: 'Abadia de Goias', uf: 'GO' },
			{ name: 'Abadiânia', name_order: 'Abadiania', uf: 'GO' },
			{ name: 'Acreúna', name_order: 'Acreuna', uf: 'GO' },
			{ name: 'Adelândia', name_order: 'Adelandia', uf: 'GO' },
			{ name: 'Água Fria de Goiás', name_order: 'Agua Fria de Goias', uf: 'GO' },
			{ name: 'Água Limpa', name_order: 'Agua Limpa', uf: 'GO' },
			{ name: 'Águas Lindas de Goiás', name_order: 'Aguas Lindas de Goias', uf: 'GO' },
			{ name: 'Alexânia', name_order: 'Alexania', uf: 'GO' },
			{ name: 'Aloândia', name_order: 'Aloandia', uf: 'GO' },
			{ name: 'Alto Horizonte', name_order: 'Alto Horizonte', uf: 'GO' },
			{ name: 'Alto Paraíso de Goiás', name_order: 'Alto Paraiso de Goias', uf: 'GO' },
			{ name: 'Alvorada do Norte', name_order: 'Alvorada do Norte', uf: 'GO' },
			{ name: 'Amaralina', name_order: 'Amaralina', uf: 'GO' },
			{ name: 'Americano do Brasil', name_order: 'Americano do Brasil', uf: 'GO' },
			{ name: 'Amorinópolis', name_order: 'Amorinopolis', uf: 'GO' },
			{ name: 'Anápolis', name_order: 'Anapolis', uf: 'GO' },
			{ name: 'Anhanguera', name_order: 'Anhanguera', uf: 'GO' },
			{ name: 'Anicuns', name_order: 'Anicuns', uf: 'GO' },
			{ name: 'Aparecida de Goiânia', name_order: 'Aparecida de Goiania', uf: 'GO' },
			{ name: 'Aparecida do Rio Doce', name_order: 'Aparecida do Rio Doce', uf: 'GO' },
			{ name: 'Aporé', name_order: 'Apore', uf: 'GO' },
			{ name: 'Araçu', name_order: 'Aracu', uf: 'GO' },
			{ name: 'Aragarças', name_order: 'Aragarcas', uf: 'GO' },
			{ name: 'Aragoiânia', name_order: 'Aragoiania', uf: 'GO' },
			{ name: 'Araguapaz', name_order: 'Araguapaz', uf: 'GO' },
			{ name: 'Arenópolis', name_order: 'Arenopolis', uf: 'GO' },
			{ name: 'Aruanã', name_order: 'Aruana', uf: 'GO' },
			{ name: 'Aurilândia', name_order: 'Aurilandia', uf: 'GO' },
			{ name: 'Avelinópolis', name_order: 'Avelinopolis', uf: 'GO' },
			{ name: 'Baliza', name_order: 'Baliza', uf: 'GO' },
			{ name: 'Barro Alto', name_order: 'Barro Alto', uf: 'GO' },
			{ name: 'Bela Vista de Goiás', name_order: 'Bela Vista de Goias', uf: 'GO' },
			{ name: 'Bom Jardim de Goiás', name_order: 'Bom Jardim de Goias', uf: 'GO' },
			{ name: 'Bom Jesus de Goiás', name_order: 'Bom Jesus de Goias', uf: 'GO' },
			{ name: 'Bonfinópolis', name_order: 'Bonfinopolis', uf: 'GO' },
			{ name: 'Bonópolis', name_order: 'Bonopolis', uf: 'GO' },
			{ name: 'Brazabrantes', name_order: 'Brazabrantes', uf: 'GO' },
			{ name: 'Britânia', name_order: 'Britania', uf: 'GO' },
			{ name: 'Buriti Alegre', name_order: 'Buriti Alegre', uf: 'GO' },
			{ name: 'Buriti de Goiás', name_order: 'Buriti de Goias', uf: 'GO' },
			{ name: 'Buritinópolis', name_order: 'Buritinopolis', uf: 'GO' },
			{ name: 'Cabeceiras', name_order: 'Cabeceiras', uf: 'GO' },
			{ name: 'Cachoeira Alta', name_order: 'Cachoeira Alta', uf: 'GO' },
			{ name: 'Cachoeira de Goiás', name_order: 'Cachoeira de Goias', uf: 'GO' },
			{ name: 'Cachoeira Dourada', name_order: 'Cachoeira Dourada', uf: 'GO' },
			{ name: 'Caçu', name_order: 'Cacu', uf: 'GO' },
			{ name: 'Caiapônia', name_order: 'Caiaponia', uf: 'GO' },
			{ name: 'Caldas Novas', name_order: 'Caldas Novas', uf: 'GO' },
			{ name: 'Caldazinha', name_order: 'Caldazinha', uf: 'GO' },
			{ name: 'Campestre de Goiás', name_order: 'Campestre de Goias', uf: 'GO' },
			{ name: 'Campinaçu', name_order: 'Campinacu', uf: 'GO' },
			{ name: 'Campinorte', name_order: 'Campinorte', uf: 'GO' },
			{ name: 'Campo Alegre de Goiás', name_order: 'Campo Alegre de Goias', uf: 'GO' },
			{ name: 'Campo Limpo de Goiás', name_order: 'Campo Limpo de Goias', uf: 'GO' },
			{ name: 'Campos Belos', name_order: 'Campos Belos', uf: 'GO' },
			{ name: 'Campos Verdes', name_order: 'Campos Verdes', uf: 'GO' },
			{ name: 'Carmo do Rio Verde', name_order: 'Carmo do Rio Verde', uf: 'GO' },
			{ name: 'Castelândia', name_order: 'Castelandia', uf: 'GO' },
			{ name: 'Catalão', name_order: 'Catalao', uf: 'GO' },
			{ name: 'Caturaí', name_order: 'Caturai', uf: 'GO' },
			{ name: 'Cavalcante', name_order: 'Cavalcante', uf: 'GO' },
			{ name: 'Ceres', name_order: 'Ceres', uf: 'GO' },
			{ name: 'Cezarina', name_order: 'Cezarina', uf: 'GO' },
			{ name: 'Chapadão do Céu', name_order: 'Chapadao do Ceu', uf: 'GO' },
			{ name: 'Cidade Ocidental', name_order: 'Cidade Ocidental', uf: 'GO' },
			{ name: 'Cocalzinho de Goiás', name_order: 'Cocalzinho de Goias', uf: 'GO' },
			{ name: 'Colinas do Sul', name_order: 'Colinas do Sul', uf: 'GO' },
			{ name: 'Córrego do Ouro', name_order: 'Corrego do Ouro', uf: 'GO' },
			{ name: 'Corumbá de Goiás', name_order: 'Corumba de Goias', uf: 'GO' },
			{ name: 'Corumbaíba', name_order: 'Corumbaiba', uf: 'GO' },
			{ name: 'Cristalina', name_order: 'Cristalina', uf: 'GO' },
			{ name: 'Cristianópolis', name_order: 'Cristianopolis', uf: 'GO' },
			{ name: 'Crixás', name_order: 'Crixas', uf: 'GO' },
			{ name: 'Cromínia', name_order: 'Crominia', uf: 'GO' },
			{ name: 'Cumari', name_order: 'Cumari', uf: 'GO' },
			{ name: 'Damianópolis', name_order: 'Damianopolis', uf: 'GO' },
	]);
};
