exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Adamantina', name_order: 'Adamantina', uf: 'SP' },
			{ name: 'Adolfo', name_order: 'Adolfo', uf: 'SP' },
			{ name: 'Aguaí', name_order: 'Aguai', uf: 'SP' },
			{ name: 'Águas da Prata', name_order: 'Aguas da Prata', uf: 'SP' },
			{ name: 'Águas de Lindóia', name_order: 'Aguas de Lindoia', uf: 'SP' },
			{ name: 'Águas de Santa Bárbara', name_order: 'Aguas de Santa Barbara', uf: 'SP' },
			{ name: 'Águas de São Pedro', name_order: 'Aguas de Sao Pedro', uf: 'SP' },
			{ name: 'Agudos', name_order: 'Agudos', uf: 'SP' },
			{ name: 'Alambari', name_order: 'Alambari', uf: 'SP' },
			{ name: 'Alfredo Marcondes', name_order: 'Alfredo Marcondes', uf: 'SP' },
			{ name: 'Altair', name_order: 'Altair', uf: 'SP' },
			{ name: 'Altinópolis', name_order: 'Altinopolis', uf: 'SP' },
			{ name: 'Alto Alegre', name_order: 'Alto Alegre', uf: 'SP' },
			{ name: 'Alumínio', name_order: 'Aluminio', uf: 'SP' },
			{ name: 'Álvares Florence', name_order: 'Alvares Florence', uf: 'SP' },
			{ name: 'Álvares Machado', name_order: 'Alvares Machado', uf: 'SP' },
			{ name: 'Álvaro de Carvalho', name_order: 'Alvaro de Carvalho', uf: 'SP' },
			{ name: 'Alvinlândia', name_order: 'Alvinlandia', uf: 'SP' },
			{ name: 'Americana', name_order: 'Americana', uf: 'SP' },
			{ name: 'Américo Brasiliense', name_order: 'Americo Brasiliense', uf: 'SP' },
			{ name: 'Américo de Campos', name_order: 'Americo de Campos', uf: 'SP' },
			{ name: 'Amparo', name_order: 'Amparo', uf: 'SP' },
			{ name: 'Analândia', name_order: 'Analandia', uf: 'SP' },
			{ name: 'Andradina', name_order: 'Andradina', uf: 'SP' },
			{ name: 'Angatuba', name_order: 'Angatuba', uf: 'SP' },
			{ name: 'Anhembi', name_order: 'Anhembi', uf: 'SP' },
			{ name: 'Anhumas', name_order: 'Anhumas', uf: 'SP' },
			{ name: 'Aparecida', name_order: 'Aparecida', uf: 'SP' },
			{ name: 'Aparecida D´oeste', name_order: 'Aparecida Doeste', uf: 'SP' },
			{ name: 'Apiaí', name_order: 'Apiai', uf: 'SP' },
			{ name: 'Araçariguama', name_order: 'Aracariguama', uf: 'SP' },
			{ name: 'Araçatuba', name_order: 'Aracatuba', uf: 'SP' },
	]);
};
