exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Amontada', name_order: 'Amontada', uf: 'CE' },
			{ name: 'Antonina do Norte', name_order: 'Antonina do Norte', uf: 'CE' },
			{ name: 'Apuiarés', name_order: 'Apuiares', uf: 'CE' },
			{ name: 'Aquiraz', name_order: 'Aquiraz', uf: 'CE' },
			{ name: 'Aracati', name_order: 'Aracati', uf: 'CE' },
			{ name: 'Aracoiaba', name_order: 'Aracoiaba', uf: 'CE' },
			{ name: 'Ararendá', name_order: 'Ararenda', uf: 'CE' },
			{ name: 'Araripe', name_order: 'Araripe', uf: 'CE' },
			{ name: 'Aratuba', name_order: 'Aratuba', uf: 'CE' },
			{ name: 'Arneiroz', name_order: 'Arneiroz', uf: 'CE' },
			{ name: 'Assaré', name_order: 'Assare', uf: 'CE' },
			{ name: 'Aurora', name_order: 'Aurora', uf: 'CE' },
			{ name: 'Baixio', name_order: 'Baixio', uf: 'CE' },
			{ name: 'Banabuiú', name_order: 'Banabuiu', uf: 'CE' },
			{ name: 'Barbalha', name_order: 'Barbalha', uf: 'CE' },
			{ name: 'Barreira', name_order: 'Barreira', uf: 'CE' },
			{ name: 'Barro', name_order: 'Barro', uf: 'CE' },
			{ name: 'Barroquinha', name_order: 'Barroquinha', uf: 'CE' },
			{ name: 'Baturité', name_order: 'Baturite', uf: 'CE' },
			{ name: 'Beberibe', name_order: 'Beberibe', uf: 'CE' },
			{ name: 'Bela Cruz', name_order: 'Bela Cruz', uf: 'CE' },
			{ name: 'Boa Viagem', name_order: 'Boa Viagem', uf: 'CE' },
			{ name: 'Brejo Santo', name_order: 'Brejo Santo', uf: 'CE' },
			{ name: 'Camocim', name_order: 'Camocim', uf: 'CE' },
			{ name: 'Campos Sales', name_order: 'Campos Sales', uf: 'CE' },
			{ name: 'Canindé', name_order: 'Caninde', uf: 'CE' },
			{ name: 'Capistrano', name_order: 'Capistrano', uf: 'CE' },
			{ name: 'Caridade', name_order: 'Caridade', uf: 'CE' },
			{ name: 'Cariré', name_order: 'Carire', uf: 'CE' },
			{ name: 'Caririaçu', name_order: 'Caririacu', uf: 'CE' },
			{ name: 'Cariús', name_order: 'Carius', uf: 'CE' },
			{ name: 'Carnaubal', name_order: 'Carnaubal', uf: 'CE' },
			{ name: 'Cascavel', name_order: 'Cascavel', uf: 'CE' },
			{ name: 'Catarina', name_order: 'Catarina', uf: 'CE' },
			{ name: 'Catunda', name_order: 'Catunda', uf: 'CE' },
			{ name: 'Caucaia', name_order: 'Caucaia', uf: 'CE' },
			{ name: 'Cedro', name_order: 'Cedro', uf: 'CE' },
			{ name: 'Chaval', name_order: 'Chaval', uf: 'CE' },
			{ name: 'Choró', name_order: 'Choro', uf: 'CE' },
			{ name: 'Chorozinho', name_order: 'Chorozinho', uf: 'CE' },
			{ name: 'Coreaú', name_order: 'Coreau', uf: 'CE' },
			{ name: 'Crateús', name_order: 'Crateus', uf: 'CE' },
			{ name: 'Crato', name_order: 'Crato', uf: 'CE' },
			{ name: 'Croatá', name_order: 'Croata', uf: 'CE' },
			{ name: 'Cruz', name_order: 'Cruz', uf: 'CE' },
			{ name: 'Deputado Irapuan Pinheiro', name_order: 'Deputado Irapuan Pinheiro', uf: 'CE' },
			{ name: 'Ererê', name_order: 'Erere', uf: 'CE' },
			{ name: 'Eusébio', name_order: 'Eusebio', uf: 'CE' },
			{ name: 'Farias Brito', name_order: 'Farias Brito', uf: 'CE' },
			{ name: 'Forquilha', name_order: 'Forquilha', uf: 'CE' },
			{ name: 'Fortaleza', name_order: 'Fortaleza', uf: 'CE' },
			{ name: 'Fortim', name_order: 'Fortim', uf: 'CE' },
			{ name: 'Frecheirinha', name_order: 'Frecheirinha', uf: 'CE' },
			{ name: 'General Sampaio', name_order: 'General Sampaio', uf: 'CE' },
			{ name: 'Graça', name_order: 'Graca', uf: 'CE' },
			{ name: 'Granja', name_order: 'Granja', uf: 'CE' },
			{ name: 'Granjeiro', name_order: 'Granjeiro', uf: 'CE' },
			{ name: 'Groaíras', name_order: 'Groairas', uf: 'CE' },
			{ name: 'Guaiúba', name_order: 'Guaiuba', uf: 'CE' },
			{ name: 'Guaraciaba do Norte', name_order: 'Guaraciaba do Norte', uf: 'CE' },
			{ name: 'Guaramiranga', name_order: 'Guaramiranga', uf: 'CE' },
			{ name: 'Hidrolândia', name_order: 'Hidrolandia', uf: 'CE' },
			{ name: 'Horizonte', name_order: 'Horizonte', uf: 'CE' },
			{ name: 'Ibaretama', name_order: 'Ibaretama', uf: 'CE' },
			{ name: 'Ibiapina', name_order: 'Ibiapina', uf: 'CE' },
			{ name: 'Ibicuitinga', name_order: 'Ibicuitinga', uf: 'CE' },
			{ name: 'Icapuí', name_order: 'Icapui', uf: 'CE' },
			{ name: 'Icó', name_order: 'Ico', uf: 'CE' },
			{ name: 'Iguatu', name_order: 'Iguatu', uf: 'CE' },
			{ name: 'Independência', name_order: 'Independencia', uf: 'CE' },
			{ name: 'Ipaporanga', name_order: 'Ipaporanga', uf: 'CE' },
			{ name: 'Ipaumirim', name_order: 'Ipaumirim', uf: 'CE' },
			{ name: 'Ipu', name_order: 'Ipu', uf: 'CE' },
			{ name: 'Ipueiras', name_order: 'Ipueiras', uf: 'CE' },
			{ name: 'Iracema', name_order: 'Iracema', uf: 'CE' },
			{ name: 'Irauçuba', name_order: 'Iraucuba', uf: 'CE' },
			{ name: 'Itaiçaba', name_order: 'Itaicaba', uf: 'CE' },
			{ name: 'Itaitinga', name_order: 'Itaitinga', uf: 'CE' },
			{ name: 'Itapagé', name_order: 'Itapage', uf: 'CE' },
			{ name: 'Itapipoca', name_order: 'Itapipoca', uf: 'CE' },
			{ name: 'Itapiúna', name_order: 'Itapiuna', uf: 'CE' },
			{ name: 'Itarema', name_order: 'Itarema', uf: 'CE' },
			{ name: 'Itatira', name_order: 'Itatira', uf: 'CE' },
			{ name: 'Jaguaretama', name_order: 'Jaguaretama', uf: 'CE' },
			{ name: 'Jaguaribara', name_order: 'Jaguaribara', uf: 'CE' },
			{ name: 'Jaguaribe', name_order: 'Jaguaribe', uf: 'CE' },
			{ name: 'Jaguaruana', name_order: 'Jaguaruana', uf: 'CE' },
			{ name: 'Jardim', name_order: 'Jardim', uf: 'CE' },
			{ name: 'Jati', name_order: 'Jati', uf: 'CE' },
			{ name: 'Jijoca de Jericoacoara', name_order: 'Jijoca de Jericoacoara', uf: 'CE' },
			{ name: 'Juazeiro do Norte', name_order: 'Juazeiro do Norte', uf: 'CE' },
			{ name: 'Jucás', name_order: 'Jucas', uf: 'CE' },
			{ name: 'Lavras da Mangabeira', name_order: 'Lavras da Mangabeira', uf: 'CE' },
			{ name: 'Limoeiro do Norte', name_order: 'Limoeiro do Norte', uf: 'CE' },
			{ name: 'Madalena', name_order: 'Madalena', uf: 'CE' },
			{ name: 'Maracanaú', name_order: 'Maracanau', uf: 'CE' },
			{ name: 'Maranguape', name_order: 'Maranguape', uf: 'CE' },
			{ name: 'Marco', name_order: 'Marco', uf: 'CE' },
			{ name: 'Martinópole', name_order: 'Martinopole', uf: 'CE' },
			{ name: 'Massapê', name_order: 'Massape', uf: 'CE' },
			{ name: 'Mauriti', name_order: 'Mauriti', uf: 'CE' },
			{ name: 'Meruoca', name_order: 'Meruoca', uf: 'CE' },
			{ name: 'Milagres', name_order: 'Milagres', uf: 'CE' },
			{ name: 'Milhã', name_order: 'Milha', uf: 'CE' },
			{ name: 'Miraíma', name_order: 'Miraima', uf: 'CE' },
			{ name: 'Missão Velha', name_order: 'Missao Velha', uf: 'CE' },
			{ name: 'Mombaça', name_order: 'Mombaca', uf: 'CE' },
			{ name: 'Monsenhor Tabosa', name_order: 'Monsenhor Tabosa', uf: 'CE' },
			{ name: 'Morada Nova', name_order: 'Morada Nova', uf: 'CE' },
			{ name: 'Moraújo', name_order: 'Moraujo', uf: 'CE' },
			{ name: 'Morrinhos', name_order: 'Morrinhos', uf: 'CE' },
			{ name: 'Mucambo', name_order: 'Mucambo', uf: 'CE' },
			{ name: 'Mulungu', name_order: 'Mulungu', uf: 'CE' },
			{ name: 'Nova Olinda', name_order: 'Nova Olinda', uf: 'CE' },
			{ name: 'Nova Russas', name_order: 'Nova Russas', uf: 'CE' },
			{ name: 'Novo Oriente', name_order: 'Novo Oriente', uf: 'CE' },
			{ name: 'Ocara', name_order: 'Ocara', uf: 'CE' },
			{ name: 'Orós', name_order: 'Oros', uf: 'CE' },
			{ name: 'Pacajus', name_order: 'Pacajus', uf: 'CE' },
			{ name: 'Pacatuba', name_order: 'Pacatuba', uf: 'CE' },
			{ name: 'Pacoti', name_order: 'Pacoti', uf: 'CE' },
			{ name: 'Pacujá', name_order: 'Pacuja', uf: 'CE' },
			{ name: 'Palhano', name_order: 'Palhano', uf: 'CE' },
			{ name: 'Palmácia', name_order: 'Palmacia', uf: 'CE' },
			{ name: 'Paracuru', name_order: 'Paracuru', uf: 'CE' },
			{ name: 'Paraipaba', name_order: 'Paraipaba', uf: 'CE' },
			{ name: 'Parambu', name_order: 'Parambu', uf: 'CE' },
			{ name: 'Paramoti', name_order: 'Paramoti', uf: 'CE' },
			{ name: 'Pedra Branca', name_order: 'Pedra Branca', uf: 'CE' },
			{ name: 'Penaforte', name_order: 'Penaforte', uf: 'CE' },
			{ name: 'Pentecoste', name_order: 'Pentecoste', uf: 'CE' },
			{ name: 'Pereiro', name_order: 'Pereiro', uf: 'CE' },
			{ name: 'Pindoretama', name_order: 'Pindoretama', uf: 'CE' },
			{ name: 'Piquet Carneiro', name_order: 'Piquet Carneiro', uf: 'CE' },
			{ name: 'Pires Ferreira', name_order: 'Pires Ferreira', uf: 'CE' },
			{ name: 'Poranga', name_order: 'Poranga', uf: 'CE' },
			{ name: 'Porteiras', name_order: 'Porteiras', uf: 'CE' },
			{ name: 'Potengi', name_order: 'Potengi', uf: 'CE' },
			{ name: 'Potiretama', name_order: 'Potiretama', uf: 'CE' },
			{ name: 'Quiterianópolis', name_order: 'Quiterianopolis', uf: 'CE' },
			{ name: 'Quixadá', name_order: 'Quixada', uf: 'CE' },
			{ name: 'Quixelô', name_order: 'Quixelo', uf: 'CE' },
			{ name: 'Quixeramobim', name_order: 'Quixeramobim', uf: 'CE' },
			{ name: 'Quixeré', name_order: 'Quixere', uf: 'CE' },
			{ name: 'Redenção', name_order: 'Redencao', uf: 'CE' },
			{ name: 'Reriutaba', name_order: 'Reriutaba', uf: 'CE' },
			{ name: 'Russas', name_order: 'Russas', uf: 'CE' },
			{ name: 'Saboeiro', name_order: 'Saboeiro', uf: 'CE' },
			{ name: 'Salitre', name_order: 'Salitre', uf: 'CE' },
			{ name: 'Santana do Acaraú', name_order: 'Santana do Acarau', uf: 'CE' },
			{ name: 'Santana do Cariri', name_order: 'Santana do Cariri', uf: 'CE' },
			{ name: 'Santa Quitéria', name_order: 'Santa Quiteria', uf: 'CE' },
			{ name: 'São Benedito', name_order: 'Sao Benedito', uf: 'CE' },
			{ name: 'São Gonçalo do Amarante', name_order: 'Sao Goncalo do Amarante', uf: 'CE' },
			{ name: 'São João do Jaguaribe', name_order: 'Sao Joao do Jaguaribe', uf: 'CE' },
			{ name: 'São Luís do Curu', name_order: 'Sao Luis do Curu', uf: 'CE' },
			{ name: 'Senador Pompeu', name_order: 'Senador Pompeu', uf: 'CE' },
			{ name: 'Senador sá', name_order: 'Senador sa', uf: 'CE' },
			{ name: 'Sobral', name_order: 'Sobral', uf: 'CE' },
			{ name: 'Solonópole', name_order: 'Solonopole', uf: 'CE' },
			{ name: 'Tabuleiro do Norte', name_order: 'Tabuleiro do Norte', uf: 'CE' },
			{ name: 'Tamboril', name_order: 'Tamboril', uf: 'CE' },
			{ name: 'Tarrafas', name_order: 'Tarrafas', uf: 'CE' },
			{ name: 'Tauá', name_order: 'Taua', uf: 'CE' },
			{ name: 'Tejuçuoca', name_order: 'Tejucuoca', uf: 'CE' },
			{ name: 'Tianguá', name_order: 'Tiangua', uf: 'CE' },
			{ name: 'Trairi', name_order: 'Trairi', uf: 'CE' },
			{ name: 'Tururu', name_order: 'Tururu', uf: 'CE' },
			{ name: 'Ubajara', name_order: 'Ubajara', uf: 'CE' },
			{ name: 'Umari', name_order: 'Umari', uf: 'CE' },
			{ name: 'Umirim', name_order: 'Umirim', uf: 'CE' },
			{ name: 'Uruburetama', name_order: 'Uruburetama', uf: 'CE' },
			{ name: 'Uruoca', name_order: 'Uruoca', uf: 'CE' },
			{ name: 'Varjota', name_order: 'Varjota', uf: 'CE' },
			{ name: 'Várzea Alegre', name_order: 'Varzea Alegre', uf: 'CE' },
			{ name: 'Viçosa do Ceará', name_order: 'Vicosa do Ceara', uf: 'CE' },
	]);
};
