exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Afonso Cláudio', name_order: 'Afonso Claudio', uf: 'ES' },
			{ name: 'Águia Branca', name_order: 'Aguia Branca', uf: 'ES' },
			{ name: 'Água Doce do Norte', name_order: 'Agua Doce do Norte', uf: 'ES' },
			{ name: 'Alegre', name_order: 'Alegre', uf: 'ES' },
			{ name: 'Alfredo Chaves', name_order: 'Alfredo Chaves', uf: 'ES' },
			{ name: 'Alto Rio Novo', name_order: 'Alto Rio Novo', uf: 'ES' },
			{ name: 'Anchieta', name_order: 'Anchieta', uf: 'ES' },
			{ name: 'Apiacá', name_order: 'Apiaca', uf: 'ES' },
			{ name: 'Aracruz', name_order: 'Aracruz', uf: 'ES' },
			{ name: 'Atilio Vivacqua', name_order: 'Atilio Vivacqua', uf: 'ES' },
			{ name: 'Baixo Guandu', name_order: 'Baixo Guandu', uf: 'ES' },
			{ name: 'Barra de São Francisco', name_order: 'Barra de Sao Francisco', uf: 'ES' },
			{ name: 'Boa Esperança', name_order: 'Boa Esperanca', uf: 'ES' },
			{ name: 'Bom Jesus do Norte', name_order: 'Bom Jesus do Norte', uf: 'ES' },
			{ name: 'Brejetuba', name_order: 'Brejetuba', uf: 'ES' },
			{ name: 'Cachoeiro de Itapemirim', name_order: 'Cachoeiro de Itapemirim', uf: 'ES' },
			{ name: 'Cariacica', name_order: 'Cariacica', uf: 'ES' },
			{ name: 'Castelo', name_order: 'Castelo', uf: 'ES' },
			{ name: 'Colatina', name_order: 'Colatina', uf: 'ES' },
			{ name: 'Conceição da Barra', name_order: 'Conceicao da Barra', uf: 'ES' },
			{ name: 'Conceição do Castelo', name_order: 'Conceicao do Castelo', uf: 'ES' },
			{ name: 'Divino de São Lourenço', name_order: 'Divino de Sao Lourenco', uf: 'ES' },
			{ name: 'Domingos Martins', name_order: 'Domingos Martins', uf: 'ES' },
			{ name: 'Dores do Rio Preto', name_order: 'Dores do Rio Preto', uf: 'ES' },
			{ name: 'Ecoporanga', name_order: 'Ecoporanga', uf: 'ES' },
			{ name: 'Fundão', name_order: 'Fundao', uf: 'ES' },
			{ name: 'Governador Lindenberg', name_order: 'Governador Lindenberg', uf: 'ES' },
			{ name: 'Guaçuí', name_order: 'Guacui', uf: 'ES' },
			{ name: 'Guarapari', name_order: 'Guarapari', uf: 'ES' },
			{ name: 'Ibatiba', name_order: 'Ibatiba', uf: 'ES' },
			{ name: 'Ibiraçu', name_order: 'Ibiracu', uf: 'ES' },
			{ name: 'Ibitirama', name_order: 'Ibitirama', uf: 'ES' },
			{ name: 'Iconha', name_order: 'Iconha', uf: 'ES' },
			{ name: 'Irupi', name_order: 'Irupi', uf: 'ES' },
			{ name: 'Itaguaçu', name_order: 'Itaguacu', uf: 'ES' },
			{ name: 'Itapemirim', name_order: 'Itapemirim', uf: 'ES' },
			{ name: 'Itarana', name_order: 'Itarana', uf: 'ES' },
			{ name: 'Iúna', name_order: 'Iuna', uf: 'ES' },
			{ name: 'Jaguaré', name_order: 'Jaguare', uf: 'ES' },
			{ name: 'Jerônimo Monteiro', name_order: 'Jeronimo Monteiro', uf: 'ES' },
			{ name: 'João Neiva', name_order: 'Joao Neiva', uf: 'ES' },
			{ name: 'Laranja da Terra', name_order: 'Laranja da Terra', uf: 'ES' },
			{ name: 'Linhares', name_order: 'Linhares', uf: 'ES' },
			{ name: 'Mantenópolis', name_order: 'Mantenopolis', uf: 'ES' },
			{ name: 'Marataízes', name_order: 'Marataizes', uf: 'ES' },
			{ name: 'Marechal Floriano', name_order: 'Marechal Floriano', uf: 'ES' },
			{ name: 'Marilândia', name_order: 'Marilandia', uf: 'ES' },
			{ name: 'Mimoso do Sul', name_order: 'Mimoso do Sul', uf: 'ES' },
			{ name: 'Montanha', name_order: 'Montanha', uf: 'ES' },
			{ name: 'Mucurici', name_order: 'Mucurici', uf: 'ES' },
			{ name: 'Muniz Freire', name_order: 'Muniz Freire', uf: 'ES' },
			{ name: 'Muqui', name_order: 'Muqui', uf: 'ES' },
			{ name: 'Nova Venécia', name_order: 'Nova Venecia', uf: 'ES' },
			{ name: 'Pancas', name_order: 'Pancas', uf: 'ES' },
			{ name: 'Pedro Canário', name_order: 'Pedro Canario', uf: 'ES' },
			{ name: 'Pinheiros', name_order: 'Pinheiros', uf: 'ES' },
			{ name: 'Piúma', name_order: 'Piuma', uf: 'ES' },
			{ name: 'Ponto Belo', name_order: 'Ponto Belo', uf: 'ES' },
			{ name: 'Presidente Kennedy', name_order: 'Presidente Kennedy', uf: 'ES' },
			{ name: 'Rio Bananal', name_order: 'Rio Bananal', uf: 'ES' },
			{ name: 'Rio Novo do Sul', name_order: 'Rio Novo do Sul', uf: 'ES' },
			{ name: 'Santa Leopoldina', name_order: 'Santa Leopoldina', uf: 'ES' },
			{ name: 'Santa Maria de Jetibá', name_order: 'Santa Maria de Jetiba', uf: 'ES' },
			{ name: 'Santa Teresa', name_order: 'Santa Teresa', uf: 'ES' },
			{ name: 'São Domingos do Norte', name_order: 'Sao Domingos do Norte', uf: 'ES' },
			{ name: 'São Gabriel da Palha', name_order: 'Sao Gabriel da Palha', uf: 'ES' },
			{ name: 'São José do Calçado', name_order: 'Sao Jose do Calcado', uf: 'ES' },
			{ name: 'São Mateus', name_order: 'Sao Mateus', uf: 'ES' },
			{ name: 'São Roque do Canaã', name_order: 'Sao Roque do Canaa', uf: 'ES' },
			{ name: 'Serra', name_order: 'Serra', uf: 'ES' },
			{ name: 'Sooretama', name_order: 'Sooretama', uf: 'ES' },
			{ name: 'Vargem Alta', name_order: 'Vargem Alta', uf: 'ES' },
			{ name: 'Venda Nova do Imigrante', name_order: 'Venda Nova do Imigrante', uf: 'ES' },
			{ name: 'Viana', name_order: 'Viana', uf: 'ES' },
			{ name: 'Vila Pavão', name_order: 'Vila Pavao', uf: 'ES' },
			{ name: 'Vila Valério', name_order: 'Vila Valerio', uf: 'ES' },
			{ name: 'Vila Velha', name_order: 'Vila Velha', uf: 'ES' },
			{ name: 'Vitória', name_order: 'Vitoria', uf: 'ES' },
	]);
};
