exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Amparo de São Francisco', name_order: 'Amparo de Sao Francisco', uf: 'SE' },
			{ name: 'Aquidabã', name_order: 'Aquidaba', uf: 'SE' },
			{ name: 'Aracaju', name_order: 'Aracaju', uf: 'SE' },
			{ name: 'Arauá', name_order: 'Araua', uf: 'SE' },
			{ name: 'Areia Branca', name_order: 'Areia Branca', uf: 'SE' },
			{ name: 'Barra Dos Coqueiros', name_order: 'Barra Dos Coqueiros', uf: 'SE' },
			{ name: 'Boquim', name_order: 'Boquim', uf: 'SE' },
			{ name: 'Brejo Grande', name_order: 'Brejo Grande', uf: 'SE' },
			{ name: 'Campo do Brito', name_order: 'Campo do Brito', uf: 'SE' },
			{ name: 'Canhoba', name_order: 'Canhoba', uf: 'SE' },
			{ name: 'Canindé de São Francisco', name_order: 'Caninde de Sao Francisco', uf: 'SE' },
			{ name: 'Capela', name_order: 'Capela', uf: 'SE' },
			{ name: 'Carira', name_order: 'Carira', uf: 'SE' },
			{ name: 'Carmópolis', name_order: 'Carmopolis', uf: 'SE' },
			{ name: 'Cedro de São João', name_order: 'Cedro de Sao Joao', uf: 'SE' },
			{ name: 'Cristinápolis', name_order: 'Cristinapolis', uf: 'SE' },
			{ name: 'Cumbe', name_order: 'Cumbe', uf: 'SE' },
			{ name: 'Divina Pastora', name_order: 'Divina Pastora', uf: 'SE' },
			{ name: 'Estância', name_order: 'Estancia', uf: 'SE' },
			{ name: 'Feira Nova', name_order: 'Feira Nova', uf: 'SE' },
			{ name: 'Frei Paulo', name_order: 'Frei Paulo', uf: 'SE' },
			{ name: 'Gararu', name_order: 'Gararu', uf: 'SE' },
			{ name: 'General Maynard', name_order: 'General Maynard', uf: 'SE' },
			{ name: 'Gracho Cardoso', name_order: 'Gracho Cardoso', uf: 'SE' },
			{ name: 'Ilha Das Flores', name_order: 'Ilha Das Flores', uf: 'SE' },
			{ name: 'Indiaroba', name_order: 'Indiaroba', uf: 'SE' },
			{ name: 'Itabaiana', name_order: 'Itabaiana', uf: 'SE' },
			{ name: 'Itabaianinha', name_order: 'Itabaianinha', uf: 'SE' },
			{ name: 'Itabi', name_order: 'Itabi', uf: 'SE' },
			{ name: 'Itaporanga D´ajuda', name_order: 'Itaporanga Dajuda', uf: 'SE' },
			{ name: 'Japaratuba', name_order: 'Japaratuba', uf: 'SE' },
			{ name: 'Japoatã', name_order: 'Japoata', uf: 'SE' },
			{ name: 'Lagarto', name_order: 'Lagarto', uf: 'SE' },
			{ name: 'Laranjeiras', name_order: 'Laranjeiras', uf: 'SE' },
			{ name: 'Macambira', name_order: 'Macambira', uf: 'SE' },
			{ name: 'Malhada Dos Bois', name_order: 'Malhada Dos Bois', uf: 'SE' },
			{ name: 'Malhador', name_order: 'Malhador', uf: 'SE' },
			{ name: 'Maruim', name_order: 'Maruim', uf: 'SE' },
			{ name: 'Moita Bonita', name_order: 'Moita Bonita', uf: 'SE' },
			{ name: 'Monte Alegre de Sergipe', name_order: 'Monte Alegre de Sergipe', uf: 'SE' },
			{ name: 'Muribeca', name_order: 'Muribeca', uf: 'SE' },
			{ name: 'Neópolis', name_order: 'Neopolis', uf: 'SE' },
			{ name: 'Nossa Senhora Aparecida', name_order: 'Nossa Senhora Aparecida', uf: 'SE' },
			{ name: 'Nossa Senhora da Glória', name_order: 'Nossa Senhora da Gloria', uf: 'SE' },
			{ name: 'Nossa Senhora Das Dores', name_order: 'Nossa Senhora Das Dores', uf: 'SE' },
			{ name: 'Nossa Senhora de Lourdes', name_order: 'Nossa Senhora de Lourdes', uf: 'SE' },
			{ name: 'Nossa Senhora do Socorro', name_order: 'Nossa Senhora do Socorro', uf: 'SE' },
	]);
};
