exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abadia Dos Dourados', name_order: 'Abadia Dos Dourados', uf: 'MG' },
			{ name: 'Abaeté', name_order: 'Abaete', uf: 'MG' },
			{ name: 'Abre Campo', name_order: 'Abre Campo', uf: 'MG' },
			{ name: 'Acaiaca', name_order: 'Acaiaca', uf: 'MG' },
			{ name: 'Açucena', name_order: 'Acucena', uf: 'MG' },
			{ name: 'Água Boa', name_order: 'Agua Boa', uf: 'MG' },
			{ name: 'Água Comprida', name_order: 'Agua Comprida', uf: 'MG' },
			{ name: 'Aguanil', name_order: 'Aguanil', uf: 'MG' },
			{ name: 'Águas Formosas', name_order: 'Aguas Formosas', uf: 'MG' },
			{ name: 'Águas Vermelhas', name_order: 'Aguas Vermelhas', uf: 'MG' },
			{ name: 'Aimorés', name_order: 'Aimores', uf: 'MG' },
			{ name: 'Aiuruoca', name_order: 'Aiuruoca', uf: 'MG' },
			{ name: 'Alagoa', name_order: 'Alagoa', uf: 'MG' },
			{ name: 'Albertina', name_order: 'Albertina', uf: 'MG' },
			{ name: 'Além Paraíba', name_order: 'Alem Paraiba', uf: 'MG' },
			{ name: 'Alfenas', name_order: 'Alfenas', uf: 'MG' },
			{ name: 'Alfredo Vasconcelos', name_order: 'Alfredo Vasconcelos', uf: 'MG' },
			{ name: 'Almenara', name_order: 'Almenara', uf: 'MG' },
			{ name: 'Alpercata', name_order: 'Alpercata', uf: 'MG' },
			{ name: 'Alpinópolis', name_order: 'Alpinopolis', uf: 'MG' },
			{ name: 'Alterosa', name_order: 'Alterosa', uf: 'MG' },
			{ name: 'Alto Caparaó', name_order: 'Alto Caparao', uf: 'MG' },
			{ name: 'Alto Rio Doce', name_order: 'Alto Rio Doce', uf: 'MG' },
			{ name: 'Alvarenga', name_order: 'Alvarenga', uf: 'MG' },
			{ name: 'Alvinópolis', name_order: 'Alvinopolis', uf: 'MG' },
			{ name: 'Alvorada de Minas', name_order: 'Alvorada de Minas', uf: 'MG' },
			{ name: 'Amparo do Serra', name_order: 'Amparo do Serra', uf: 'MG' },
			{ name: 'Andradas', name_order: 'Andradas', uf: 'MG' },
			{ name: 'Cachoeira de Pajeú', name_order: 'Cachoeira de Pajeu', uf: 'MG' },
			{ name: 'Andrelândia', name_order: 'Andrelandia', uf: 'MG' },
			{ name: 'Angelândia', name_order: 'Angelandia', uf: 'MG' },
			{ name: 'Antônio Carlos', name_order: 'Antonio Carlos', uf: 'MG' },
			{ name: 'Antônio Dias', name_order: 'Antonio Dias', uf: 'MG' },
			{ name: 'Antônio Prado de Minas', name_order: 'Antonio Prado de Minas', uf: 'MG' },
			{ name: 'Araçaí', name_order: 'Aracai', uf: 'MG' },
			{ name: 'Aracitaba', name_order: 'Aracitaba', uf: 'MG' },
			{ name: 'Araçuaí', name_order: 'Aracuai', uf: 'MG' },
			{ name: 'Araguari', name_order: 'Araguari', uf: 'MG' },
			{ name: 'Arantina', name_order: 'Arantina', uf: 'MG' },
			{ name: 'Araponga', name_order: 'Araponga', uf: 'MG' },
			{ name: 'Araporã', name_order: 'Arapora', uf: 'MG' },
			{ name: 'Arapuá', name_order: 'Arapua', uf: 'MG' },
			{ name: 'Araújos', name_order: 'Araujos', uf: 'MG' },
			{ name: 'Araxá', name_order: 'Araxa', uf: 'MG' },
			{ name: 'Arceburgo', name_order: 'Arceburgo', uf: 'MG' },
			{ name: 'Arcos', name_order: 'Arcos', uf: 'MG' },
			{ name: 'Areado', name_order: 'Areado', uf: 'MG' },
			{ name: 'Argirita', name_order: 'Argirita', uf: 'MG' },
			{ name: 'Aricanduva', name_order: 'Aricanduva', uf: 'MG' },
			{ name: 'Arinos', name_order: 'Arinos', uf: 'MG' },
			{ name: 'Astolfo Dutra', name_order: 'Astolfo Dutra', uf: 'MG' },
			{ name: 'Ataléia', name_order: 'Ataleia', uf: 'MG' },
			{ name: 'Augusto de Lima', name_order: 'Augusto de Lima', uf: 'MG' },
			{ name: 'Baependi', name_order: 'Baependi', uf: 'MG' },
			{ name: 'Baldim', name_order: 'Baldim', uf: 'MG' },
			{ name: 'Bambuí', name_order: 'Bambui', uf: 'MG' },
			{ name: 'Bandeira', name_order: 'Bandeira', uf: 'MG' },
			{ name: 'Bandeira do Sul', name_order: 'Bandeira do Sul', uf: 'MG' },
			{ name: 'Barão de Cocais', name_order: 'Barao de Cocais', uf: 'MG' },
			{ name: 'Barão de Monte Alto', name_order: 'Barao de Monte Alto', uf: 'MG' },
			{ name: 'Barbacena', name_order: 'Barbacena', uf: 'MG' },
			{ name: 'Barra Longa', name_order: 'Barra Longa', uf: 'MG' },
			{ name: 'Barroso', name_order: 'Barroso', uf: 'MG' },
			{ name: 'Bela Vista de Minas', name_order: 'Bela Vista de Minas', uf: 'MG' },
			{ name: 'Belmiro Braga', name_order: 'Belmiro Braga', uf: 'MG' },
			{ name: 'Belo Horizonte', name_order: 'Belo Horizonte', uf: 'MG' },
			{ name: 'Belo Oriente', name_order: 'Belo Oriente', uf: 'MG' },
			{ name: 'Belo Vale', name_order: 'Belo Vale', uf: 'MG' },
			{ name: 'Berilo', name_order: 'Berilo', uf: 'MG' },
			{ name: 'Bertópolis', name_order: 'Bertopolis', uf: 'MG' },
			{ name: 'Berizal', name_order: 'Berizal', uf: 'MG' },
			{ name: 'Betim', name_order: 'Betim', uf: 'MG' },
			{ name: 'Bias Fortes', name_order: 'Bias Fortes', uf: 'MG' },
			{ name: 'Bicas', name_order: 'Bicas', uf: 'MG' },
			{ name: 'Biquinhas', name_order: 'Biquinhas', uf: 'MG' },
			{ name: 'Boa Esperança', name_order: 'Boa Esperanca', uf: 'MG' },
			{ name: 'Bocaina de Minas', name_order: 'Bocaina de Minas', uf: 'MG' },
			{ name: 'Bocaiúva', name_order: 'Bocaiuva', uf: 'MG' },
			{ name: 'Bom Despacho', name_order: 'Bom Despacho', uf: 'MG' },
			{ name: 'Bom Jardim de Minas', name_order: 'Bom Jardim de Minas', uf: 'MG' },
			{ name: 'Bom Jesus da Penha', name_order: 'Bom Jesus da Penha', uf: 'MG' },
			{ name: 'Bom Jesus do Amparo', name_order: 'Bom Jesus do Amparo', uf: 'MG' },
			{ name: 'Bom Jesus do Galho', name_order: 'Bom Jesus do Galho', uf: 'MG' },
			{ name: 'Bom Repouso', name_order: 'Bom Repouso', uf: 'MG' },
			{ name: 'Bom Sucesso', name_order: 'Bom Sucesso', uf: 'MG' },
			{ name: 'Bonfim', name_order: 'Bonfim', uf: 'MG' },
			{ name: 'Bonfinópolis de Minas', name_order: 'Bonfinopolis de Minas', uf: 'MG' },
			{ name: 'Bonito de Minas', name_order: 'Bonito de Minas', uf: 'MG' },
			{ name: 'Borda da Mata', name_order: 'Borda da Mata', uf: 'MG' },
			{ name: 'Botelhos', name_order: 'Botelhos', uf: 'MG' },
			{ name: 'Botumirim', name_order: 'Botumirim', uf: 'MG' },
			{ name: 'Brasilândia de Minas', name_order: 'Brasilandia de Minas', uf: 'MG' },
			{ name: 'Brasília de Minas', name_order: 'Brasilia de Minas', uf: 'MG' },
			{ name: 'Brás Pires', name_order: 'Bras Pires', uf: 'MG' },
			{ name: 'Braúnas', name_order: 'Braunas', uf: 'MG' },
			{ name: 'Brasópolis', name_order: 'Brasopolis', uf: 'MG' },
			{ name: 'Brumadinho', name_order: 'Brumadinho', uf: 'MG' },
			{ name: 'Bueno Brandão', name_order: 'Bueno Brandao', uf: 'MG' },
			{ name: 'Buenópolis', name_order: 'Buenopolis', uf: 'MG' },
			{ name: 'Bugre', name_order: 'Bugre', uf: 'MG' },
			{ name: 'Buritis', name_order: 'Buritis', uf: 'MG' },
			{ name: 'Buritizeiro', name_order: 'Buritizeiro', uf: 'MG' },
			{ name: 'Cabeceira Grande', name_order: 'Cabeceira Grande', uf: 'MG' },
			{ name: 'Cabo Verde', name_order: 'Cabo Verde', uf: 'MG' },
			{ name: 'Cachoeira da Prata', name_order: 'Cachoeira da Prata', uf: 'MG' },
			{ name: 'Cachoeira de Minas', name_order: 'Cachoeira de Minas', uf: 'MG' },
			{ name: 'Cachoeira Dourada', name_order: 'Cachoeira Dourada', uf: 'MG' },
			{ name: 'Caetanópolis', name_order: 'Caetanopolis', uf: 'MG' },
			{ name: 'Caeté', name_order: 'Caete', uf: 'MG' },
			{ name: 'Caiana', name_order: 'Caiana', uf: 'MG' },
			{ name: 'Cajuri', name_order: 'Cajuri', uf: 'MG' },
			{ name: 'Caldas', name_order: 'Caldas', uf: 'MG' },
			{ name: 'Camacho', name_order: 'Camacho', uf: 'MG' },
			{ name: 'Camanducaia', name_order: 'Camanducaia', uf: 'MG' },
			{ name: 'Cambuí', name_order: 'Cambui', uf: 'MG' },
			{ name: 'Cambuquira', name_order: 'Cambuquira', uf: 'MG' },
			{ name: 'Campanário', name_order: 'Campanario', uf: 'MG' },
			{ name: 'Campanha', name_order: 'Campanha', uf: 'MG' },
			{ name: 'Campestre', name_order: 'Campestre', uf: 'MG' },
			{ name: 'Campina Verde', name_order: 'Campina Verde', uf: 'MG' },
			{ name: 'Campo Azul', name_order: 'Campo Azul', uf: 'MG' },
			{ name: 'Campo Belo', name_order: 'Campo Belo', uf: 'MG' },
			{ name: 'Campo do Meio', name_order: 'Campo do Meio', uf: 'MG' },
			{ name: 'Campo Florido', name_order: 'Campo Florido', uf: 'MG' },
			{ name: 'Campos Altos', name_order: 'Campos Altos', uf: 'MG' },
			{ name: 'Campos Gerais', name_order: 'Campos Gerais', uf: 'MG' },
			{ name: 'Canaã', name_order: 'Canaa', uf: 'MG' },
			{ name: 'Canápolis', name_order: 'Canapolis', uf: 'MG' },
			{ name: 'Cana Verde', name_order: 'Cana Verde', uf: 'MG' },
			{ name: 'Candeias', name_order: 'Candeias', uf: 'MG' },
			{ name: 'Cantagalo', name_order: 'Cantagalo', uf: 'MG' },
			{ name: 'Caparaó', name_order: 'Caparao', uf: 'MG' },
			{ name: 'Capela Nova', name_order: 'Capela Nova', uf: 'MG' },
			{ name: 'Capelinha', name_order: 'Capelinha', uf: 'MG' },
			{ name: 'Capetinga', name_order: 'Capetinga', uf: 'MG' },
			{ name: 'Capim Branco', name_order: 'Capim Branco', uf: 'MG' },
			{ name: 'Capinópolis', name_order: 'Capinopolis', uf: 'MG' },
			{ name: 'Capitão Andrade', name_order: 'Capitao Andrade', uf: 'MG' },
			{ name: 'Capitão Enéas', name_order: 'Capitao Eneas', uf: 'MG' },
			{ name: 'Capitólio', name_order: 'Capitolio', uf: 'MG' },
			{ name: 'Caputira', name_order: 'Caputira', uf: 'MG' },
			{ name: 'Caraí', name_order: 'Carai', uf: 'MG' },
			{ name: 'Caranaíba', name_order: 'Caranaiba', uf: 'MG' },
			{ name: 'Carandaí', name_order: 'Carandai', uf: 'MG' },
			{ name: 'Carangola', name_order: 'Carangola', uf: 'MG' },
			{ name: 'Caratinga', name_order: 'Caratinga', uf: 'MG' },
			{ name: 'Carbonita', name_order: 'Carbonita', uf: 'MG' },
			{ name: 'Careaçu', name_order: 'Careacu', uf: 'MG' },
			{ name: 'Carlos Chagas', name_order: 'Carlos Chagas', uf: 'MG' },
			{ name: 'Carmésia', name_order: 'Carmesia', uf: 'MG' },
			{ name: 'Carmo da Cachoeira', name_order: 'Carmo da Cachoeira', uf: 'MG' },
			{ name: 'Carmo da Mata', name_order: 'Carmo da Mata', uf: 'MG' },
			{ name: 'Carmo de Minas', name_order: 'Carmo de Minas', uf: 'MG' },
			{ name: 'Carmo do Cajuru', name_order: 'Carmo do Cajuru', uf: 'MG' },
			{ name: 'Carmo do Paranaíba', name_order: 'Carmo do Paranaiba', uf: 'MG' },
	]);
};
