exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Alvarães', name_order: 'Alvaraes', uf: 'AM' },
			{ name: 'Amaturá', name_order: 'Amatura', uf: 'AM' },
			{ name: 'Anamã', name_order: 'Anama', uf: 'AM' },
			{ name: 'Anori', name_order: 'Anori', uf: 'AM' },
			{ name: 'Apuí', name_order: 'Apui', uf: 'AM' },
			{ name: 'Atalaia do Norte', name_order: 'Atalaia do Norte', uf: 'AM' },
			{ name: 'Autazes', name_order: 'Autazes', uf: 'AM' },
			{ name: 'Barcelos', name_order: 'Barcelos', uf: 'AM' },
			{ name: 'Barreirinha', name_order: 'Barreirinha', uf: 'AM' },
			{ name: 'Benjamin Constant', name_order: 'Benjamin Constant', uf: 'AM' },
			{ name: 'Beruri', name_order: 'Beruri', uf: 'AM' },
			{ name: 'Boa Vista do Ramos', name_order: 'Boa Vista do Ramos', uf: 'AM' },
			{ name: 'Boca do Acre', name_order: 'Boca do Acre', uf: 'AM' },
			{ name: 'Borba', name_order: 'Borba', uf: 'AM' },
			{ name: 'Caapiranga', name_order: 'Caapiranga', uf: 'AM' },
			{ name: 'Canutama', name_order: 'Canutama', uf: 'AM' },
			{ name: 'Carauari', name_order: 'Carauari', uf: 'AM' },
			{ name: 'Careiro', name_order: 'Careiro', uf: 'AM' },
			{ name: 'Careiro da Várzea', name_order: 'Careiro da Varzea', uf: 'AM' },
			{ name: 'Coari', name_order: 'Coari', uf: 'AM' },
			{ name: 'Codajás', name_order: 'Codajas', uf: 'AM' },
			{ name: 'Eirunepé', name_order: 'Eirunepe', uf: 'AM' },
			{ name: 'Envira', name_order: 'Envira', uf: 'AM' },
			{ name: 'Fonte Boa', name_order: 'Fonte Boa', uf: 'AM' },
			{ name: 'Guajará', name_order: 'Guajara', uf: 'AM' },
			{ name: 'Humaitá', name_order: 'Humaita', uf: 'AM' },
			{ name: 'Ipixuna', name_order: 'Ipixuna', uf: 'AM' },
			{ name: 'Iranduba', name_order: 'Iranduba', uf: 'AM' },
			{ name: 'Itacoatiara', name_order: 'Itacoatiara', uf: 'AM' },
			{ name: 'Itamarati', name_order: 'Itamarati', uf: 'AM' },
			{ name: 'Itapiranga', name_order: 'Itapiranga', uf: 'AM' },
			{ name: 'Japurá', name_order: 'Japura', uf: 'AM' },
			{ name: 'Juruá', name_order: 'Jurua', uf: 'AM' },
			{ name: 'Jutaí', name_order: 'Jutai', uf: 'AM' },
			{ name: 'Lábrea', name_order: 'Labrea', uf: 'AM' },
			{ name: 'Manacapuru', name_order: 'Manacapuru', uf: 'AM' },
			{ name: 'Manaquiri', name_order: 'Manaquiri', uf: 'AM' },
			{ name: 'Manaus', name_order: 'Manaus', uf: 'AM' },
			{ name: 'Manicoré', name_order: 'Manicore', uf: 'AM' },
			{ name: 'Maraã', name_order: 'Maraa', uf: 'AM' },
			{ name: 'Maués', name_order: 'Maues', uf: 'AM' },
			{ name: 'Nhamundá', name_order: 'Nhamunda', uf: 'AM' },
			{ name: 'Nova Olinda do Norte', name_order: 'Nova Olinda do Norte', uf: 'AM' },
			{ name: 'Novo Airão', name_order: 'Novo Airao', uf: 'AM' },
			{ name: 'Novo Aripuanã', name_order: 'Novo Aripuana', uf: 'AM' },
			{ name: 'Parintins', name_order: 'Parintins', uf: 'AM' },
			{ name: 'Pauini', name_order: 'Pauini', uf: 'AM' },
			{ name: 'Presidente Figueiredo', name_order: 'Presidente Figueiredo', uf: 'AM' },
			{ name: 'Rio Preto da Eva', name_order: 'Rio Preto da Eva', uf: 'AM' },
			{ name: 'Santa Isabel do Rio Negro', name_order: 'Santa Isabel do Rio Negro', uf: 'AM' },
			{ name: 'Santo Antônio do Içá', name_order: 'Santo Antonio do Ica', uf: 'AM' },
			{ name: 'São Gabriel da Cachoeira', name_order: 'Sao Gabriel da Cachoeira', uf: 'AM' },
			{ name: 'São Paulo de Olivença', name_order: 'Sao Paulo de Olivenca', uf: 'AM' },
			{ name: 'São Sebastião do Uatumã', name_order: 'Sao Sebastiao do Uatuma', uf: 'AM' },
			{ name: 'Silves', name_order: 'Silves', uf: 'AM' },
			{ name: 'Tabatinga', name_order: 'Tabatinga', uf: 'AM' },
			{ name: 'Tapauá', name_order: 'Tapaua', uf: 'AM' },
			{ name: 'Tefé', name_order: 'Tefe', uf: 'AM' },
			{ name: 'Tonantins', name_order: 'Tonantins', uf: 'AM' },
			{ name: 'Uarini', name_order: 'Uarini', uf: 'AM' },
			{ name: 'Urucará', name_order: 'Urucara', uf: 'AM' },
			{ name: 'Urucurituba', name_order: 'Urucurituba', uf: 'AM' },
	]);
};
