exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Alta Floresta D´oeste', name_order: 'Alta Floresta Doeste', uf: 'RO' },
			{ name: 'Ariquemes', name_order: 'Ariquemes', uf: 'RO' },
			{ name: 'Cabixi', name_order: 'Cabixi', uf: 'RO' },
			{ name: 'Cacoal', name_order: 'Cacoal', uf: 'RO' },
			{ name: 'Cerejeiras', name_order: 'Cerejeiras', uf: 'RO' },
			{ name: 'Colorado do Oeste', name_order: 'Colorado do Oeste', uf: 'RO' },
			{ name: 'Corumbiara', name_order: 'Corumbiara', uf: 'RO' },
			{ name: 'Costa Marques', name_order: 'Costa Marques', uf: 'RO' },
			{ name: 'Espigão D´oeste', name_order: 'Espigao Doeste', uf: 'RO' },
			{ name: 'Guajará-mirim', name_order: 'Guajaramirim', uf: 'RO' },
			{ name: 'Jaru', name_order: 'Jaru', uf: 'RO' },
			{ name: 'Ji-paraná', name_order: 'Jiparana', uf: 'RO' },
			{ name: 'Machadinho D´oeste', name_order: 'Machadinho Doeste', uf: 'RO' },
			{ name: 'Nova Brasilândia D´oeste', name_order: 'Nova Brasilandia Doeste', uf: 'RO' },
			{ name: 'Ouro Preto do Oeste', name_order: 'Ouro Preto do Oeste', uf: 'RO' },
			{ name: 'Pimenta Bueno', name_order: 'Pimenta Bueno', uf: 'RO' },
			{ name: 'Porto Velho', name_order: 'Porto Velho', uf: 'RO' },
			{ name: 'Presidente Médici', name_order: 'Presidente Medici', uf: 'RO' },
			{ name: 'Rio Crespo', name_order: 'Rio Crespo', uf: 'RO' },
			{ name: 'Rolim de Moura', name_order: 'Rolim de Moura', uf: 'RO' },
			{ name: 'Santa Luzia D´oeste', name_order: 'Santa Luzia Doeste', uf: 'RO' },
			{ name: 'Vilhena', name_order: 'Vilhena', uf: 'RO' },
			{ name: 'São Miguel do Guaporé', name_order: 'Sao Miguel do Guapore', uf: 'RO' },
			{ name: 'Nova Mamoré', name_order: 'Nova Mamore', uf: 'RO' },
			{ name: 'Alvorada D´oeste', name_order: 'Alvorada Doeste', uf: 'RO' },
			{ name: 'Alto Alegre Dos Parecis', name_order: 'Alto Alegre Dos Parecis', uf: 'RO' },
			{ name: 'Alto Paraíso', name_order: 'Alto Paraiso', uf: 'RO' },
			{ name: 'Buritis', name_order: 'Buritis', uf: 'RO' },
			{ name: 'Novo Horizonte do Oeste', name_order: 'Novo Horizonte do Oeste', uf: 'RO' },
			{ name: 'Cacaulândia', name_order: 'Cacaulandia', uf: 'RO' },
			{ name: 'Campo Novo de Rondônia', name_order: 'Campo Novo de Rondonia', uf: 'RO' },
			{ name: 'Candeias do Jamari', name_order: 'Candeias do Jamari', uf: 'RO' },
			{ name: 'Castanheiras', name_order: 'Castanheiras', uf: 'RO' },
			{ name: 'Chupinguaia', name_order: 'Chupinguaia', uf: 'RO' },
			{ name: 'Cujubim', name_order: 'Cujubim', uf: 'RO' },
			{ name: 'Governador Jorge Teixeira', name_order: 'Governador Jorge Teixeira', uf: 'RO' },
			{ name: 'Itapuã do Oeste', name_order: 'Itapua do Oeste', uf: 'RO' },
			{ name: 'Ministro Andreazza', name_order: 'Ministro Andreazza', uf: 'RO' },
			{ name: 'Mirante da Serra', name_order: 'Mirante da Serra', uf: 'RO' },
			{ name: 'Monte Negro', name_order: 'Monte Negro', uf: 'RO' },
			{ name: 'Nova União', name_order: 'Nova Uniao', uf: 'RO' },
			{ name: 'Parecis', name_order: 'Parecis', uf: 'RO' },
			{ name: 'Pimenteiras do Oeste', name_order: 'Pimenteiras do Oeste', uf: 'RO' },
			{ name: 'Primavera de Rondônia', name_order: 'Primavera de Rondonia', uf: 'RO' },
			{ name: 'São Felipe D´oeste', name_order: 'Sao Felipe Doeste', uf: 'RO' },
			{ name: 'São Francisco do Guaporé', name_order: 'Sao Francisco do Guapore', uf: 'RO' },
			{ name: 'Seringueiras', name_order: 'Seringueiras', uf: 'RO' },
			{ name: 'Teixeirópolis', name_order: 'Teixeiropolis', uf: 'RO' },
			{ name: 'Theobroma', name_order: 'Theobroma', uf: 'RO' },
			{ name: 'Urupá', name_order: 'Urupa', uf: 'RO' },
			{ name: 'Vale do Anari', name_order: 'Vale do Anari', uf: 'RO' },
			{ name: 'Vale do Paraíso', name_order: 'Vale do Paraiso', uf: 'RO' },
	]);
};
