exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Damolândia', name_order: 'Damolandia', uf: 'GO' },
			{ name: 'Davinópolis', name_order: 'Davinopolis', uf: 'GO' },
			{ name: 'Diorama', name_order: 'Diorama', uf: 'GO' },
			{ name: 'Doverlândia', name_order: 'Doverlandia', uf: 'GO' },
			{ name: 'Edealina', name_order: 'Edealina', uf: 'GO' },
			{ name: 'Edéia', name_order: 'Edeia', uf: 'GO' },
			{ name: 'Estrela do Norte', name_order: 'Estrela do Norte', uf: 'GO' },
			{ name: 'Faina', name_order: 'Faina', uf: 'GO' },
			{ name: 'Fazenda Nova', name_order: 'Fazenda Nova', uf: 'GO' },
			{ name: 'Firminópolis', name_order: 'Firminopolis', uf: 'GO' },
			{ name: 'Flores de Goiás', name_order: 'Flores de Goias', uf: 'GO' },
			{ name: 'Formosa', name_order: 'Formosa', uf: 'GO' },
			{ name: 'Formoso', name_order: 'Formoso', uf: 'GO' },
			{ name: 'Gameleira de Goiás', name_order: 'Gameleira de Goias', uf: 'GO' },
			{ name: 'Divinópolis de Goiás', name_order: 'Divinopolis de Goias', uf: 'GO' },
			{ name: 'Goianápolis', name_order: 'Goianapolis', uf: 'GO' },
			{ name: 'Goiandira', name_order: 'Goiandira', uf: 'GO' },
			{ name: 'Goianésia', name_order: 'Goianesia', uf: 'GO' },
			{ name: 'Goiânia', name_order: 'Goiania', uf: 'GO' },
			{ name: 'Goianira', name_order: 'Goianira', uf: 'GO' },
			{ name: 'Goiás', name_order: 'Goias', uf: 'GO' },
			{ name: 'Goiatuba', name_order: 'Goiatuba', uf: 'GO' },
			{ name: 'Gouvelândia', name_order: 'Gouvelandia', uf: 'GO' },
			{ name: 'Guapó', name_order: 'Guapo', uf: 'GO' },
			{ name: 'Guaraíta', name_order: 'Guaraita', uf: 'GO' },
			{ name: 'Guarani de Goiás', name_order: 'Guarani de Goias', uf: 'GO' },
			{ name: 'Guarinos', name_order: 'Guarinos', uf: 'GO' },
			{ name: 'Heitoraí', name_order: 'Heitorai', uf: 'GO' },
			{ name: 'Hidrolândia', name_order: 'Hidrolandia', uf: 'GO' },
			{ name: 'Hidrolina', name_order: 'Hidrolina', uf: 'GO' },
			{ name: 'Iaciara', name_order: 'Iaciara', uf: 'GO' },
			{ name: 'Inaciolândia', name_order: 'Inaciolandia', uf: 'GO' },
			{ name: 'Indiara', name_order: 'Indiara', uf: 'GO' },
			{ name: 'Inhumas', name_order: 'Inhumas', uf: 'GO' },
			{ name: 'Ipameri', name_order: 'Ipameri', uf: 'GO' },
			{ name: 'Ipiranga de Goiás', name_order: 'Ipiranga de Goias', uf: 'GO' },
			{ name: 'Iporá', name_order: 'Ipora', uf: 'GO' },
			{ name: 'Israelândia', name_order: 'Israelandia', uf: 'GO' },
			{ name: 'Itaberaí', name_order: 'Itaberai', uf: 'GO' },
			{ name: 'Itaguari', name_order: 'Itaguari', uf: 'GO' },
			{ name: 'Itaguaru', name_order: 'Itaguaru', uf: 'GO' },
			{ name: 'Itajá', name_order: 'Itaja', uf: 'GO' },
			{ name: 'Itapaci', name_order: 'Itapaci', uf: 'GO' },
			{ name: 'Itapirapuã', name_order: 'Itapirapua', uf: 'GO' },
			{ name: 'Itapuranga', name_order: 'Itapuranga', uf: 'GO' },
			{ name: 'Itarumã', name_order: 'Itaruma', uf: 'GO' },
			{ name: 'Itauçu', name_order: 'Itaucu', uf: 'GO' },
			{ name: 'Itumbiara', name_order: 'Itumbiara', uf: 'GO' },
			{ name: 'Ivolândia', name_order: 'Ivolandia', uf: 'GO' },
			{ name: 'Jandaia', name_order: 'Jandaia', uf: 'GO' },
			{ name: 'Jaraguá', name_order: 'Jaragua', uf: 'GO' },
			{ name: 'Jataí', name_order: 'Jatai', uf: 'GO' },
			{ name: 'Jaupaci', name_order: 'Jaupaci', uf: 'GO' },
			{ name: 'Jesúpolis', name_order: 'Jesupolis', uf: 'GO' },
			{ name: 'Joviânia', name_order: 'Joviania', uf: 'GO' },
			{ name: 'Jussara', name_order: 'Jussara', uf: 'GO' },
			{ name: 'Lagoa Santa', name_order: 'Lagoa Santa', uf: 'GO' },
			{ name: 'Leopoldo de Bulhões', name_order: 'Leopoldo de Bulhoes', uf: 'GO' },
			{ name: 'Luziânia', name_order: 'Luziania', uf: 'GO' },
			{ name: 'Mairipotaba', name_order: 'Mairipotaba', uf: 'GO' },
			{ name: 'Mambaí', name_order: 'Mambai', uf: 'GO' },
			{ name: 'Mara Rosa', name_order: 'Mara Rosa', uf: 'GO' },
			{ name: 'Marzagão', name_order: 'Marzagao', uf: 'GO' },
			{ name: 'Matrinchã', name_order: 'Matrincha', uf: 'GO' },
			{ name: 'Maurilândia', name_order: 'Maurilandia', uf: 'GO' },
			{ name: 'Mimoso de Goiás', name_order: 'Mimoso de Goias', uf: 'GO' },
			{ name: 'Minaçu', name_order: 'Minacu', uf: 'GO' },
			{ name: 'Mineiros', name_order: 'Mineiros', uf: 'GO' },
			{ name: 'Moiporá', name_order: 'Moipora', uf: 'GO' },
			{ name: 'Monte Alegre de Goiás', name_order: 'Monte Alegre de Goias', uf: 'GO' },
			{ name: 'Montes Claros de Goiás', name_order: 'Montes Claros de Goias', uf: 'GO' },
			{ name: 'Montividiu', name_order: 'Montividiu', uf: 'GO' },
			{ name: 'Montividiu do Norte', name_order: 'Montividiu do Norte', uf: 'GO' },
			{ name: 'Morrinhos', name_order: 'Morrinhos', uf: 'GO' },
			{ name: 'Morro Agudo de Goiás', name_order: 'Morro Agudo de Goias', uf: 'GO' },
			{ name: 'Mossâmedes', name_order: 'Mossamedes', uf: 'GO' },
			{ name: 'Mozarlândia', name_order: 'Mozarlandia', uf: 'GO' },
			{ name: 'Mundo Novo', name_order: 'Mundo Novo', uf: 'GO' },
			{ name: 'Mutunópolis', name_order: 'Mutunopolis', uf: 'GO' },
			{ name: 'Nazário', name_order: 'Nazario', uf: 'GO' },
			{ name: 'Nerópolis', name_order: 'Neropolis', uf: 'GO' },
			{ name: 'Niquelândia', name_order: 'Niquelandia', uf: 'GO' },
			{ name: 'Nova América', name_order: 'Nova America', uf: 'GO' },
			{ name: 'Nova Aurora', name_order: 'Nova Aurora', uf: 'GO' },
			{ name: 'Nova Crixás', name_order: 'Nova Crixas', uf: 'GO' },
			{ name: 'Nova Glória', name_order: 'Nova Gloria', uf: 'GO' },
			{ name: 'Nova Iguaçu de Goiás', name_order: 'Nova Iguacu de Goias', uf: 'GO' },
			{ name: 'Nova Roma', name_order: 'Nova Roma', uf: 'GO' },
			{ name: 'Nova Veneza', name_order: 'Nova Veneza', uf: 'GO' },
			{ name: 'Novo Brasil', name_order: 'Novo Brasil', uf: 'GO' },
			{ name: 'Novo Gama', name_order: 'Novo Gama', uf: 'GO' },
			{ name: 'Novo Planalto', name_order: 'Novo Planalto', uf: 'GO' },
			{ name: 'Orizona', name_order: 'Orizona', uf: 'GO' },
			{ name: 'Ouro Verde de Goiás', name_order: 'Ouro Verde de Goias', uf: 'GO' },
			{ name: 'Ouvidor', name_order: 'Ouvidor', uf: 'GO' },
			{ name: 'Padre Bernardo', name_order: 'Padre Bernardo', uf: 'GO' },
			{ name: 'Palestina de Goiás', name_order: 'Palestina de Goias', uf: 'GO' },
			{ name: 'Palmeiras de Goiás', name_order: 'Palmeiras de Goias', uf: 'GO' },
			{ name: 'Palmelo', name_order: 'Palmelo', uf: 'GO' },
			{ name: 'Palminópolis', name_order: 'Palminopolis', uf: 'GO' },
			{ name: 'Panamá', name_order: 'Panama', uf: 'GO' },
			{ name: 'Paranaiguara', name_order: 'Paranaiguara', uf: 'GO' },
			{ name: 'Paraúna', name_order: 'Parauna', uf: 'GO' },
			{ name: 'Perolândia', name_order: 'Perolandia', uf: 'GO' },
			{ name: 'Petrolina de Goiás', name_order: 'Petrolina de Goias', uf: 'GO' },
			{ name: 'Pilar de Goiás', name_order: 'Pilar de Goias', uf: 'GO' },
			{ name: 'Piracanjuba', name_order: 'Piracanjuba', uf: 'GO' },
			{ name: 'Piranhas', name_order: 'Piranhas', uf: 'GO' },
			{ name: 'Pirenópolis', name_order: 'Pirenopolis', uf: 'GO' },
			{ name: 'Pires do Rio', name_order: 'Pires do Rio', uf: 'GO' },
			{ name: 'Planaltina', name_order: 'Planaltina', uf: 'GO' },
			{ name: 'Pontalina', name_order: 'Pontalina', uf: 'GO' },
			{ name: 'Porangatu', name_order: 'Porangatu', uf: 'GO' },
			{ name: 'Porteirão', name_order: 'Porteirao', uf: 'GO' },
			{ name: 'Portelândia', name_order: 'Portelandia', uf: 'GO' },
			{ name: 'Posse', name_order: 'Posse', uf: 'GO' },
			{ name: 'Professor Jamil', name_order: 'Professor Jamil', uf: 'GO' },
			{ name: 'Quirinópolis', name_order: 'Quirinopolis', uf: 'GO' },
			{ name: 'Rialma', name_order: 'Rialma', uf: 'GO' },
			{ name: 'Rianápolis', name_order: 'Rianapolis', uf: 'GO' },
			{ name: 'Rio Quente', name_order: 'Rio Quente', uf: 'GO' },
			{ name: 'Rio Verde', name_order: 'Rio Verde', uf: 'GO' },
			{ name: 'Rubiataba', name_order: 'Rubiataba', uf: 'GO' },
			{ name: 'Sanclerlândia', name_order: 'Sanclerlandia', uf: 'GO' },
			{ name: 'Santa Bárbara de Goiás', name_order: 'Santa Barbara de Goias', uf: 'GO' },
			{ name: 'Santa Cruz de Goiás', name_order: 'Santa Cruz de Goias', uf: 'GO' },
			{ name: 'Santa fé de Goiás', name_order: 'Santa fe de Goias', uf: 'GO' },
			{ name: 'Santa Helena de Goiás', name_order: 'Santa Helena de Goias', uf: 'GO' },
			{ name: 'Santa Isabel', name_order: 'Santa Isabel', uf: 'GO' },
			{ name: 'Santa Rita do Araguaia', name_order: 'Santa Rita do Araguaia', uf: 'GO' },
			{ name: 'Santa Rita do Novo Destino', name_order: 'Santa Rita do Novo Destino', uf: 'GO' },
			{ name: 'Santa Rosa de Goiás', name_order: 'Santa Rosa de Goias', uf: 'GO' },
			{ name: 'Santa Tereza de Goiás', name_order: 'Santa Tereza de Goias', uf: 'GO' },
			{ name: 'Santa Terezinha de Goiás', name_order: 'Santa Terezinha de Goias', uf: 'GO' },
			{ name: 'Santo Antônio da Barra', name_order: 'Santo Antonio da Barra', uf: 'GO' },
			{ name: 'Santo Antônio de Goiás', name_order: 'Santo Antonio de Goias', uf: 'GO' },
			{ name: 'Santo Antônio do Descoberto', name_order: 'Santo Antonio do Descoberto', uf: 'GO' },
			{ name: 'São Domingos', name_order: 'Sao Domingos', uf: 'GO' },
			{ name: 'São Francisco de Goiás', name_order: 'Sao Francisco de Goias', uf: 'GO' },
			{ name: 'São João D´aliança', name_order: 'Sao Joao Dalianca', uf: 'GO' },
			{ name: 'São João da Paraúna', name_order: 'Sao Joao da Parauna', uf: 'GO' },
			{ name: 'São Luís de Montes Belos', name_order: 'Sao Luis de Montes Belos', uf: 'GO' },
			{ name: 'São Luíz do Norte', name_order: 'Sao Luiz do Norte', uf: 'GO' },
			{ name: 'São Miguel do Araguaia', name_order: 'Sao Miguel do Araguaia', uf: 'GO' },
			{ name: 'São Miguel do Passa Quatro', name_order: 'Sao Miguel do Passa Quatro', uf: 'GO' },
			{ name: 'São Patrício', name_order: 'Sao Patricio', uf: 'GO' },
			{ name: 'São Simão', name_order: 'Sao Simao', uf: 'GO' },
			{ name: 'Senador Canedo', name_order: 'Senador Canedo', uf: 'GO' },
			{ name: 'Serranópolis', name_order: 'Serranopolis', uf: 'GO' },
			{ name: 'Silvânia', name_order: 'Silvania', uf: 'GO' },
			{ name: 'Simolândia', name_order: 'Simolandia', uf: 'GO' },
			{ name: 'Sítio D´abadia', name_order: 'Sitio Dabadia', uf: 'GO' },
			{ name: 'Taquaral de Goiás', name_order: 'Taquaral de Goias', uf: 'GO' },
			{ name: 'Teresina de Goiás', name_order: 'Teresina de Goias', uf: 'GO' },
			{ name: 'Terezópolis de Goiás', name_order: 'Terezopolis de Goias', uf: 'GO' },
			{ name: 'Três Ranchos', name_order: 'Tres Ranchos', uf: 'GO' },
			{ name: 'Trindade', name_order: 'Trindade', uf: 'GO' },
			{ name: 'Trombas', name_order: 'Trombas', uf: 'GO' },
			{ name: 'Turvânia', name_order: 'Turvania', uf: 'GO' },
			{ name: 'Turvelândia', name_order: 'Turvelandia', uf: 'GO' },
			{ name: 'Uirapuru', name_order: 'Uirapuru', uf: 'GO' },
			{ name: 'Uruaçu', name_order: 'Uruacu', uf: 'GO' },
			{ name: 'Uruana', name_order: 'Uruana', uf: 'GO' },
			{ name: 'Urutaí', name_order: 'Urutai', uf: 'GO' },
			{ name: 'Valparaíso de Goiás', name_order: 'Valparaiso de Goias', uf: 'GO' },
			{ name: 'Varjão', name_order: 'Varjao', uf: 'GO' },
			{ name: 'Vianópolis', name_order: 'Vianopolis', uf: 'GO' },
			{ name: 'Vicentinópolis', name_order: 'Vicentinopolis', uf: 'GO' },
			{ name: 'Vila Boa', name_order: 'Vila Boa', uf: 'GO' },
			{ name: 'Vila Propício', name_order: 'Vila Propicio', uf: 'GO' },
	]);
};
