exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Quatiguá', name_order: 'Quatigua', uf: 'PR' },
			{ name: 'Quatro Barras', name_order: 'Quatro Barras', uf: 'PR' },
			{ name: 'Quatro Pontes', name_order: 'Quatro Pontes', uf: 'PR' },
			{ name: 'Quedas do Iguaçu', name_order: 'Quedas do Iguacu', uf: 'PR' },
			{ name: 'Querência do Norte', name_order: 'Querencia do Norte', uf: 'PR' },
			{ name: 'Quinta do Sol', name_order: 'Quinta do Sol', uf: 'PR' },
			{ name: 'Quitandinha', name_order: 'Quitandinha', uf: 'PR' },
			{ name: 'Ramilândia', name_order: 'Ramilandia', uf: 'PR' },
			{ name: 'Rancho Alegre', name_order: 'Rancho Alegre', uf: 'PR' },
			{ name: 'Rancho Alegre D´oeste', name_order: 'Rancho Alegre Doeste', uf: 'PR' },
			{ name: 'Realeza', name_order: 'Realeza', uf: 'PR' },
			{ name: 'Rebouças', name_order: 'Reboucas', uf: 'PR' },
			{ name: 'Renascença', name_order: 'Renascenca', uf: 'PR' },
			{ name: 'Reserva', name_order: 'Reserva', uf: 'PR' },
			{ name: 'Reserva do Iguaçu', name_order: 'Reserva do Iguacu', uf: 'PR' },
			{ name: 'Ribeirão Claro', name_order: 'Ribeirao Claro', uf: 'PR' },
			{ name: 'Ribeirão do Pinhal', name_order: 'Ribeirao do Pinhal', uf: 'PR' },
			{ name: 'Rio Azul', name_order: 'Rio Azul', uf: 'PR' },
			{ name: 'Rio Bom', name_order: 'Rio Bom', uf: 'PR' },
			{ name: 'Rio Bonito do Iguaçu', name_order: 'Rio Bonito do Iguacu', uf: 'PR' },
			{ name: 'Rio Branco do Ivaí', name_order: 'Rio Branco do Ivai', uf: 'PR' },
			{ name: 'Rio Branco do Sul', name_order: 'Rio Branco do Sul', uf: 'PR' },
			{ name: 'Rio Negro', name_order: 'Rio Negro', uf: 'PR' },
			{ name: 'Rolândia', name_order: 'Rolandia', uf: 'PR' },
			{ name: 'Roncador', name_order: 'Roncador', uf: 'PR' },
			{ name: 'Rondon', name_order: 'Rondon', uf: 'PR' },
			{ name: 'Rosário do Ivaí', name_order: 'Rosario do Ivai', uf: 'PR' },
			{ name: 'Sabáudia', name_order: 'Sabaudia', uf: 'PR' },
			{ name: 'Salgado Filho', name_order: 'Salgado Filho', uf: 'PR' },
			{ name: 'Salto do Itararé', name_order: 'Salto do Itarare', uf: 'PR' },
			{ name: 'Salto do Lontra', name_order: 'Salto do Lontra', uf: 'PR' },
			{ name: 'Santa Amélia', name_order: 'Santa Amelia', uf: 'PR' },
			{ name: 'Santa Cecília do Pavão', name_order: 'Santa Cecilia do Pavao', uf: 'PR' },
			{ name: 'Santa Cruz de Monte Castelo', name_order: 'Santa Cruz de Monte Castelo', uf: 'PR' },
			{ name: 'Santa fé', name_order: 'Santa fe', uf: 'PR' },
			{ name: 'Santa Helena', name_order: 'Santa Helena', uf: 'PR' },
			{ name: 'Santa Inês', name_order: 'Santa Ines', uf: 'PR' },
			{ name: 'Santa Isabel do Ivaí', name_order: 'Santa Isabel do Ivai', uf: 'PR' },
			{ name: 'Santa Izabel do Oeste', name_order: 'Santa Izabel do Oeste', uf: 'PR' },
			{ name: 'Santa Lúcia', name_order: 'Santa Lucia', uf: 'PR' },
			{ name: 'Santa Maria do Oeste', name_order: 'Santa Maria do Oeste', uf: 'PR' },
			{ name: 'Santa Mariana', name_order: 'Santa Mariana', uf: 'PR' },
			{ name: 'Santa Mônica', name_order: 'Santa Monica', uf: 'PR' },
			{ name: 'Santana do Itararé', name_order: 'Santana do Itarare', uf: 'PR' },
			{ name: 'Santa Tereza do Oeste', name_order: 'Santa Tereza do Oeste', uf: 'PR' },
			{ name: 'Santa Terezinha de Itaipu', name_order: 'Santa Terezinha de Itaipu', uf: 'PR' },
			{ name: 'Santo Antônio da Platina', name_order: 'Santo Antonio da Platina', uf: 'PR' },
			{ name: 'Santo Antônio do Caiuá', name_order: 'Santo Antonio do Caiua', uf: 'PR' },
			{ name: 'Santo Antônio do Paraíso', name_order: 'Santo Antonio do Paraiso', uf: 'PR' },
			{ name: 'Santo Antônio do Sudoeste', name_order: 'Santo Antonio do Sudoeste', uf: 'PR' },
			{ name: 'Santo Inácio', name_order: 'Santo Inacio', uf: 'PR' },
			{ name: 'São Carlos do Ivaí', name_order: 'Sao Carlos do Ivai', uf: 'PR' },
			{ name: 'São Jerônimo da Serra', name_order: 'Sao Jeronimo da Serra', uf: 'PR' },
			{ name: 'São João', name_order: 'Sao Joao', uf: 'PR' },
			{ name: 'São João do Caiuá', name_order: 'Sao Joao do Caiua', uf: 'PR' },
			{ name: 'São João do Ivaí', name_order: 'Sao Joao do Ivai', uf: 'PR' },
			{ name: 'São João do Triunfo', name_order: 'Sao Joao do Triunfo', uf: 'PR' },
			{ name: 'São Jorge D´oeste', name_order: 'Sao Jorge Doeste', uf: 'PR' },
			{ name: 'São Jorge do Ivaí', name_order: 'Sao Jorge do Ivai', uf: 'PR' },
			{ name: 'São Jorge do Patrocínio', name_order: 'Sao Jorge do Patrocinio', uf: 'PR' },
			{ name: 'São José da Boa Vista', name_order: 'Sao Jose da Boa Vista', uf: 'PR' },
			{ name: 'São José Das Palmeiras', name_order: 'Sao Jose Das Palmeiras', uf: 'PR' },
			{ name: 'São José Dos Pinhais', name_order: 'Sao Jose Dos Pinhais', uf: 'PR' },
			{ name: 'São Manoel do Paraná', name_order: 'Sao Manoel do Parana', uf: 'PR' },
			{ name: 'São Mateus do Sul', name_order: 'Sao Mateus do Sul', uf: 'PR' },
			{ name: 'São Miguel do Iguaçu', name_order: 'Sao Miguel do Iguacu', uf: 'PR' },
			{ name: 'São Pedro do Iguaçu', name_order: 'Sao Pedro do Iguacu', uf: 'PR' },
			{ name: 'São Pedro do Ivaí', name_order: 'Sao Pedro do Ivai', uf: 'PR' },
			{ name: 'São Pedro do Paraná', name_order: 'Sao Pedro do Parana', uf: 'PR' },
			{ name: 'São Sebastião da Amoreira', name_order: 'Sao Sebastiao da Amoreira', uf: 'PR' },
			{ name: 'São Tomé', name_order: 'Sao Tome', uf: 'PR' },
			{ name: 'Sapopema', name_order: 'Sapopema', uf: 'PR' },
			{ name: 'Sarandi', name_order: 'Sarandi', uf: 'PR' },
			{ name: 'Saudade do Iguaçu', name_order: 'Saudade do Iguacu', uf: 'PR' },
			{ name: 'Sengés', name_order: 'Senges', uf: 'PR' },
			{ name: 'Serranópolis do Iguaçu', name_order: 'Serranopolis do Iguacu', uf: 'PR' },
			{ name: 'Sertaneja', name_order: 'Sertaneja', uf: 'PR' },
			{ name: 'Sertanópolis', name_order: 'Sertanopolis', uf: 'PR' },
			{ name: 'Siqueira Campos', name_order: 'Siqueira Campos', uf: 'PR' },
			{ name: 'Sulina', name_order: 'Sulina', uf: 'PR' },
			{ name: 'Tamarana', name_order: 'Tamarana', uf: 'PR' },
			{ name: 'Tamboara', name_order: 'Tamboara', uf: 'PR' },
			{ name: 'Tapejara', name_order: 'Tapejara', uf: 'PR' },
			{ name: 'Tapira', name_order: 'Tapira', uf: 'PR' },
			{ name: 'Teixeira Soares', name_order: 'Teixeira Soares', uf: 'PR' },
			{ name: 'Telêmaco Borba', name_order: 'Telemaco Borba', uf: 'PR' },
			{ name: 'Terra Boa', name_order: 'Terra Boa', uf: 'PR' },
			{ name: 'Terra Rica', name_order: 'Terra Rica', uf: 'PR' },
			{ name: 'Terra Roxa', name_order: 'Terra Roxa', uf: 'PR' },
			{ name: 'Tibagi', name_order: 'Tibagi', uf: 'PR' },
			{ name: 'Tijucas do Sul', name_order: 'Tijucas do Sul', uf: 'PR' },
			{ name: 'Toledo', name_order: 'Toledo', uf: 'PR' },
			{ name: 'Tomazina', name_order: 'Tomazina', uf: 'PR' },
			{ name: 'Três Barras do Paraná', name_order: 'Tres Barras do Parana', uf: 'PR' },
			{ name: 'Tunas do Paraná', name_order: 'Tunas do Parana', uf: 'PR' },
			{ name: 'Tuneiras do Oeste', name_order: 'Tuneiras do Oeste', uf: 'PR' },
			{ name: 'Tupãssi', name_order: 'Tupassi', uf: 'PR' },
			{ name: 'Turvo', name_order: 'Turvo', uf: 'PR' },
			{ name: 'Ubiratã', name_order: 'Ubirata', uf: 'PR' },
			{ name: 'Umuarama', name_order: 'Umuarama', uf: 'PR' },
			{ name: 'União da Vitória', name_order: 'Uniao da Vitoria', uf: 'PR' },
			{ name: 'Uniflor', name_order: 'Uniflor', uf: 'PR' },
			{ name: 'Uraí', name_order: 'Urai', uf: 'PR' },
			{ name: 'Wenceslau Braz', name_order: 'Wenceslau Braz', uf: 'PR' },
			{ name: 'Ventania', name_order: 'Ventania', uf: 'PR' },
			{ name: 'Vera Cruz do Oeste', name_order: 'Vera Cruz do Oeste', uf: 'PR' },
			{ name: 'Verê', name_order: 'Vere', uf: 'PR' },
			{ name: 'Vila Alta', name_order: 'Vila Alta', uf: 'PR' },
			{ name: 'Doutor Ulysses', name_order: 'Doutor Ulysses', uf: 'PR' },
			{ name: 'Virmond', name_order: 'Virmond', uf: 'PR' },
			{ name: 'Vitorino', name_order: 'Vitorino', uf: 'PR' },
			{ name: 'Xambrê', name_order: 'Xambre', uf: 'PR' },
	]);
};
