exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abreu e Lima', name_order: 'Abreu e Lima', uf: 'PE' },
			{ name: 'Afogados da Ingazeira', name_order: 'Afogados da Ingazeira', uf: 'PE' },
			{ name: 'Afrânio', name_order: 'Afranio', uf: 'PE' },
			{ name: 'Agrestina', name_order: 'Agrestina', uf: 'PE' },
			{ name: 'Água Preta', name_order: 'Agua Preta', uf: 'PE' },
			{ name: 'Águas Belas', name_order: 'Aguas Belas', uf: 'PE' },
			{ name: 'Alagoinha', name_order: 'Alagoinha', uf: 'PE' },
			{ name: 'Aliança', name_order: 'Alianca', uf: 'PE' },
			{ name: 'Altinho', name_order: 'Altinho', uf: 'PE' },
			{ name: 'Amaraji', name_order: 'Amaraji', uf: 'PE' },
			{ name: 'Angelim', name_order: 'Angelim', uf: 'PE' },
			{ name: 'Araçoiaba', name_order: 'Aracoiaba', uf: 'PE' },
			{ name: 'Araripina', name_order: 'Araripina', uf: 'PE' },
			{ name: 'Arcoverde', name_order: 'Arcoverde', uf: 'PE' },
			{ name: 'Barra de Guabiraba', name_order: 'Barra de Guabiraba', uf: 'PE' },
			{ name: 'Barreiros', name_order: 'Barreiros', uf: 'PE' },
			{ name: 'Belém de Maria', name_order: 'Belem de Maria', uf: 'PE' },
			{ name: 'Belém de São Francisco', name_order: 'Belem de Sao Francisco', uf: 'PE' },
			{ name: 'Belo Jardim', name_order: 'Belo Jardim', uf: 'PE' },
			{ name: 'Betânia', name_order: 'Betania', uf: 'PE' },
			{ name: 'Bezerros', name_order: 'Bezerros', uf: 'PE' },
			{ name: 'Bodocó', name_order: 'Bodoco', uf: 'PE' },
			{ name: 'Bom Conselho', name_order: 'Bom Conselho', uf: 'PE' },
			{ name: 'Bom Jardim', name_order: 'Bom Jardim', uf: 'PE' },
			{ name: 'Bonito', name_order: 'Bonito', uf: 'PE' },
			{ name: 'Brejão', name_order: 'Brejao', uf: 'PE' },
			{ name: 'Brejinho', name_order: 'Brejinho', uf: 'PE' },
			{ name: 'Brejo da Madre de Deus', name_order: 'Brejo da Madre de Deus', uf: 'PE' },
			{ name: 'Buenos Aires', name_order: 'Buenos Aires', uf: 'PE' },
			{ name: 'Buíque', name_order: 'Buique', uf: 'PE' },
			{ name: 'Cabo de Santo Agostinho', name_order: 'Cabo de Santo Agostinho', uf: 'PE' },
			{ name: 'Cabrobó', name_order: 'Cabrobo', uf: 'PE' },
			{ name: 'Cachoeirinha', name_order: 'Cachoeirinha', uf: 'PE' },
			{ name: 'Caetés', name_order: 'Caetes', uf: 'PE' },
	]);
};
