exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Santana do Seridó', name_order: 'Santana do Serido', uf: 'RN' },
			{ name: 'Santo Antônio', name_order: 'Santo Antonio', uf: 'RN' },
			{ name: 'São Bento do Norte', name_order: 'Sao Bento do Norte', uf: 'RN' },
			{ name: 'São Bento do Trairí', name_order: 'Sao Bento do Trairi', uf: 'RN' },
			{ name: 'São Fernando', name_order: 'Sao Fernando', uf: 'RN' },
			{ name: 'São Francisco do Oeste', name_order: 'Sao Francisco do Oeste', uf: 'RN' },
			{ name: 'São Gonçalo do Amarante', name_order: 'Sao Goncalo do Amarante', uf: 'RN' },
			{ name: 'São João do Sabugi', name_order: 'Sao Joao do Sabugi', uf: 'RN' },
			{ name: 'São José de Mipibu', name_order: 'Sao Jose de Mipibu', uf: 'RN' },
			{ name: 'São José do Campestre', name_order: 'Sao Jose do Campestre', uf: 'RN' },
			{ name: 'São José do Seridó', name_order: 'Sao Jose do Serido', uf: 'RN' },
			{ name: 'São Miguel', name_order: 'Sao Miguel', uf: 'RN' },
			{ name: 'São Miguel do Gostoso', name_order: 'Sao Miguel do Gostoso', uf: 'RN' },
			{ name: 'São Paulo do Potengi', name_order: 'Sao Paulo do Potengi', uf: 'RN' },
			{ name: 'São Pedro', name_order: 'Sao Pedro', uf: 'RN' },
			{ name: 'São Rafael', name_order: 'Sao Rafael', uf: 'RN' },
			{ name: 'São Tomé', name_order: 'Sao Tome', uf: 'RN' },
			{ name: 'São Vicente', name_order: 'Sao Vicente', uf: 'RN' },
			{ name: 'Senador Elói de Souza', name_order: 'Senador Eloi de Souza', uf: 'RN' },
			{ name: 'Senador Georgino Avelino', name_order: 'Senador Georgino Avelino', uf: 'RN' },
			{ name: 'Serra de São Bento', name_order: 'Serra de Sao Bento', uf: 'RN' },
			{ name: 'Serra do Mel', name_order: 'Serra do Mel', uf: 'RN' },
			{ name: 'Serra Negra do Norte', name_order: 'Serra Negra do Norte', uf: 'RN' },
			{ name: 'Serrinha', name_order: 'Serrinha', uf: 'RN' },
			{ name: 'Serrinha Dos Pintos', name_order: 'Serrinha Dos Pintos', uf: 'RN' },
			{ name: 'Severiano Melo', name_order: 'Severiano Melo', uf: 'RN' },
			{ name: 'Sítio Novo', name_order: 'Sitio Novo', uf: 'RN' },
			{ name: 'Taboleiro Grande', name_order: 'Taboleiro Grande', uf: 'RN' },
			{ name: 'Taipu', name_order: 'Taipu', uf: 'RN' },
			{ name: 'Tangará', name_order: 'Tangara', uf: 'RN' },
			{ name: 'Tenente Ananias', name_order: 'Tenente Ananias', uf: 'RN' },
			{ name: 'Tenente Laurentino Cruz', name_order: 'Tenente Laurentino Cruz', uf: 'RN' },
			{ name: 'Tibau do Sul', name_order: 'Tibau do Sul', uf: 'RN' },
			{ name: 'Timbaúba Dos Batistas', name_order: 'Timbauba Dos Batistas', uf: 'RN' },
			{ name: 'Touros', name_order: 'Touros', uf: 'RN' },
			{ name: 'Triunfo Potiguar', name_order: 'Triunfo Potiguar', uf: 'RN' },
			{ name: 'Umarizal', name_order: 'Umarizal', uf: 'RN' },
			{ name: 'Upanema', name_order: 'Upanema', uf: 'RN' },
			{ name: 'Várzea', name_order: 'Varzea', uf: 'RN' },
			{ name: 'Venha-ver', name_order: 'Venhaver', uf: 'RN' },
			{ name: 'Vera Cruz', name_order: 'Vera Cruz', uf: 'RN' },
			{ name: 'Viçosa', name_order: 'Vicosa', uf: 'RN' },
			{ name: 'Vila Flor', name_order: 'Vila Flor', uf: 'RN' },
	]);
};
