exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Aceguá', name_order: 'Acegua', uf: 'RS' },
			{ name: 'Água Santa', name_order: 'Agua Santa', uf: 'RS' },
			{ name: 'Agudo', name_order: 'Agudo', uf: 'RS' },
			{ name: 'Ajuricaba', name_order: 'Ajuricaba', uf: 'RS' },
			{ name: 'Alecrim', name_order: 'Alecrim', uf: 'RS' },
			{ name: 'Alegrete', name_order: 'Alegrete', uf: 'RS' },
			{ name: 'Alegria', name_order: 'Alegria', uf: 'RS' },
			{ name: 'Almirante Tamandaré do Sul', name_order: 'Almirante Tamandare do Sul', uf: 'RS' },
			{ name: 'Alpestre', name_order: 'Alpestre', uf: 'RS' },
			{ name: 'Alto Alegre', name_order: 'Alto Alegre', uf: 'RS' },
			{ name: 'Alto Feliz', name_order: 'Alto Feliz', uf: 'RS' },
			{ name: 'Alvorada', name_order: 'Alvorada', uf: 'RS' },
			{ name: 'Amaral Ferrador', name_order: 'Amaral Ferrador', uf: 'RS' },
			{ name: 'Ametista do Sul', name_order: 'Ametista do Sul', uf: 'RS' },
			{ name: 'André da Rocha', name_order: 'Andre da Rocha', uf: 'RS' },
			{ name: 'Anta Gorda', name_order: 'Anta Gorda', uf: 'RS' },
			{ name: 'Antônio Prado', name_order: 'Antonio Prado', uf: 'RS' },
			{ name: 'Arambaré', name_order: 'Arambare', uf: 'RS' },
			{ name: 'Araricá', name_order: 'Ararica', uf: 'RS' },
			{ name: 'Aratiba', name_order: 'Aratiba', uf: 'RS' },
			{ name: 'Arroio do Meio', name_order: 'Arroio do Meio', uf: 'RS' },
			{ name: 'Arroio do Sal', name_order: 'Arroio do Sal', uf: 'RS' },
			{ name: 'Arroio do Padre', name_order: 'Arroio do Padre', uf: 'RS' },
			{ name: 'Arroio Dos Ratos', name_order: 'Arroio Dos Ratos', uf: 'RS' },
			{ name: 'Arroio do Tigre', name_order: 'Arroio do Tigre', uf: 'RS' },
			{ name: 'Arroio Grande', name_order: 'Arroio Grande', uf: 'RS' },
			{ name: 'Arvorezinha', name_order: 'Arvorezinha', uf: 'RS' },
			{ name: 'Augusto Pestana', name_order: 'Augusto Pestana', uf: 'RS' },
			{ name: 'Áurea', name_order: 'Aurea', uf: 'RS' },
			{ name: 'Bagé', name_order: 'Bage', uf: 'RS' },
			{ name: 'Balneário Pinhal', name_order: 'Balneario Pinhal', uf: 'RS' },
			{ name: 'Barão', name_order: 'Barao', uf: 'RS' },
			{ name: 'Barão de Cotegipe', name_order: 'Barao de Cotegipe', uf: 'RS' },
			{ name: 'Barão do Triunfo', name_order: 'Barao do Triunfo', uf: 'RS' },
			{ name: 'Barracão', name_order: 'Barracao', uf: 'RS' },
			{ name: 'Barra do Guarita', name_order: 'Barra do Guarita', uf: 'RS' },
			{ name: 'Barra do Quaraí', name_order: 'Barra do Quarai', uf: 'RS' },
			{ name: 'Barra do Ribeiro', name_order: 'Barra do Ribeiro', uf: 'RS' },
			{ name: 'Barra do Rio Azul', name_order: 'Barra do Rio Azul', uf: 'RS' },
			{ name: 'Barra Funda', name_order: 'Barra Funda', uf: 'RS' },
			{ name: 'Barros Cassal', name_order: 'Barros Cassal', uf: 'RS' },
			{ name: 'Benjamin Constant do Sul', name_order: 'Benjamin Constant do Sul', uf: 'RS' },
			{ name: 'Bento Gonçalves', name_order: 'Bento Goncalves', uf: 'RS' },
			{ name: 'Boa Vista Das Missões', name_order: 'Boa Vista Das Missoes', uf: 'RS' },
			{ name: 'Boa Vista do Buricá', name_order: 'Boa Vista do Burica', uf: 'RS' },
			{ name: 'Boa Vista do Cadeado', name_order: 'Boa Vista do Cadeado', uf: 'RS' },
			{ name: 'Boa Vista do Incra', name_order: 'Boa Vista do Incra', uf: 'RS' },
			{ name: 'Boa Vista do Sul', name_order: 'Boa Vista do Sul', uf: 'RS' },
			{ name: 'Bom Jesus', name_order: 'Bom Jesus', uf: 'RS' },
			{ name: 'Bom Princípio', name_order: 'Bom Principio', uf: 'RS' },
			{ name: 'Bom Progresso', name_order: 'Bom Progresso', uf: 'RS' },
			{ name: 'Bom Retiro do Sul', name_order: 'Bom Retiro do Sul', uf: 'RS' },
			{ name: 'Boqueirão do Leão', name_order: 'Boqueirao do Leao', uf: 'RS' },
			{ name: 'Bossoroca', name_order: 'Bossoroca', uf: 'RS' },
			{ name: 'Bozano', name_order: 'Bozano', uf: 'RS' },
			{ name: 'Braga', name_order: 'Braga', uf: 'RS' },
			{ name: 'Brochier', name_order: 'Brochier', uf: 'RS' },
			{ name: 'Butiá', name_order: 'Butia', uf: 'RS' },
			{ name: 'Caçapava do Sul', name_order: 'Cacapava do Sul', uf: 'RS' },
			{ name: 'Cacequi', name_order: 'Cacequi', uf: 'RS' },
			{ name: 'Cachoeira do Sul', name_order: 'Cachoeira do Sul', uf: 'RS' },
			{ name: 'Cachoeirinha', name_order: 'Cachoeirinha', uf: 'RS' },
			{ name: 'Cacique Doble', name_order: 'Cacique Doble', uf: 'RS' },
			{ name: 'Caibaté', name_order: 'Caibate', uf: 'RS' },
			{ name: 'Caiçara', name_order: 'Caicara', uf: 'RS' },
			{ name: 'Camaquã', name_order: 'Camaqua', uf: 'RS' },
			{ name: 'Camargo', name_order: 'Camargo', uf: 'RS' },
			{ name: 'Cambará do Sul', name_order: 'Cambara do Sul', uf: 'RS' },
			{ name: 'Campestre da Serra', name_order: 'Campestre da Serra', uf: 'RS' },
			{ name: 'Campina Das Missões', name_order: 'Campina Das Missoes', uf: 'RS' },
			{ name: 'Campinas do Sul', name_order: 'Campinas do Sul', uf: 'RS' },
			{ name: 'Campo Bom', name_order: 'Campo Bom', uf: 'RS' },
			{ name: 'Campo Novo', name_order: 'Campo Novo', uf: 'RS' },
			{ name: 'Campos Borges', name_order: 'Campos Borges', uf: 'RS' },
			{ name: 'Candelária', name_order: 'Candelaria', uf: 'RS' },
			{ name: 'Cândido Godói', name_order: 'Candido Godoi', uf: 'RS' },
			{ name: 'Candiota', name_order: 'Candiota', uf: 'RS' },
			{ name: 'Canela', name_order: 'Canela', uf: 'RS' },
			{ name: 'Canguçu', name_order: 'Cangucu', uf: 'RS' },
			{ name: 'Canoas', name_order: 'Canoas', uf: 'RS' },
			{ name: 'Canudos do Vale', name_order: 'Canudos do Vale', uf: 'RS' },
			{ name: 'Capão Bonito do Sul', name_order: 'Capao Bonito do Sul', uf: 'RS' },
			{ name: 'Capão da Canoa', name_order: 'Capao da Canoa', uf: 'RS' },
			{ name: 'Capão do Cipó', name_order: 'Capao do Cipo', uf: 'RS' },
			{ name: 'Capão do Leão', name_order: 'Capao do Leao', uf: 'RS' },
			{ name: 'Capivari do Sul', name_order: 'Capivari do Sul', uf: 'RS' },
			{ name: 'Capela de Santana', name_order: 'Capela de Santana', uf: 'RS' },
			{ name: 'Capitão', name_order: 'Capitao', uf: 'RS' },
			{ name: 'Carazinho', name_order: 'Carazinho', uf: 'RS' },
			{ name: 'Caraá', name_order: 'Caraa', uf: 'RS' },
			{ name: 'Carlos Barbosa', name_order: 'Carlos Barbosa', uf: 'RS' },
			{ name: 'Carlos Gomes', name_order: 'Carlos Gomes', uf: 'RS' },
			{ name: 'Casca', name_order: 'Casca', uf: 'RS' },
			{ name: 'Caseiros', name_order: 'Caseiros', uf: 'RS' },
			{ name: 'Catuípe', name_order: 'Catuipe', uf: 'RS' },
			{ name: 'Caxias do Sul', name_order: 'Caxias do Sul', uf: 'RS' },
			{ name: 'Centenário', name_order: 'Centenario', uf: 'RS' },
			{ name: 'Cerrito', name_order: 'Cerrito', uf: 'RS' },
			{ name: 'Cerro Branco', name_order: 'Cerro Branco', uf: 'RS' },
			{ name: 'Cerro Grande', name_order: 'Cerro Grande', uf: 'RS' },
			{ name: 'Cerro Grande do Sul', name_order: 'Cerro Grande do Sul', uf: 'RS' },
			{ name: 'Cerro Largo', name_order: 'Cerro Largo', uf: 'RS' },
			{ name: 'Chapada', name_order: 'Chapada', uf: 'RS' },
			{ name: 'Charqueadas', name_order: 'Charqueadas', uf: 'RS' },
			{ name: 'Charrua', name_order: 'Charrua', uf: 'RS' },
			{ name: 'Chiapetta', name_order: 'Chiapetta', uf: 'RS' },
			{ name: 'Chuí', name_order: 'Chui', uf: 'RS' },
			{ name: 'Chuvisca', name_order: 'Chuvisca', uf: 'RS' },
			{ name: 'Cidreira', name_order: 'Cidreira', uf: 'RS' },
			{ name: 'Ciríaco', name_order: 'Ciriaco', uf: 'RS' },
			{ name: 'Colinas', name_order: 'Colinas', uf: 'RS' },
			{ name: 'Colorado', name_order: 'Colorado', uf: 'RS' },
			{ name: 'Condor', name_order: 'Condor', uf: 'RS' },
			{ name: 'Constantina', name_order: 'Constantina', uf: 'RS' },
			{ name: 'Coqueiro Baixo', name_order: 'Coqueiro Baixo', uf: 'RS' },
			{ name: 'Coqueiros do Sul', name_order: 'Coqueiros do Sul', uf: 'RS' },
			{ name: 'Coronel Barros', name_order: 'Coronel Barros', uf: 'RS' },
			{ name: 'Coronel Bicaco', name_order: 'Coronel Bicaco', uf: 'RS' },
			{ name: 'Coronel Pilar', name_order: 'Coronel Pilar', uf: 'RS' },
			{ name: 'Cotiporã', name_order: 'Cotipora', uf: 'RS' },
			{ name: 'Coxilha', name_order: 'Coxilha', uf: 'RS' },
			{ name: 'Crissiumal', name_order: 'Crissiumal', uf: 'RS' },
			{ name: 'Cristal', name_order: 'Cristal', uf: 'RS' },
			{ name: 'Cristal do Sul', name_order: 'Cristal do Sul', uf: 'RS' },
			{ name: 'Cruz Alta', name_order: 'Cruz Alta', uf: 'RS' },
			{ name: 'Cruzaltense', name_order: 'Cruzaltense', uf: 'RS' },
			{ name: 'Cruzeiro do Sul', name_order: 'Cruzeiro do Sul', uf: 'RS' },
			{ name: 'David Canabarro', name_order: 'David Canabarro', uf: 'RS' },
			{ name: 'Derrubadas', name_order: 'Derrubadas', uf: 'RS' },
			{ name: 'Dezesseis de Novembro', name_order: 'Dezesseis de Novembro', uf: 'RS' },
			{ name: 'Dilermando de Aguiar', name_order: 'Dilermando de Aguiar', uf: 'RS' },
			{ name: 'Dois Irmãos', name_order: 'Dois Irmaos', uf: 'RS' },
			{ name: 'Dois Irmãos Das Missões', name_order: 'Dois Irmaos Das Missoes', uf: 'RS' },
			{ name: 'Dois Lajeados', name_order: 'Dois Lajeados', uf: 'RS' },
			{ name: 'Dom Feliciano', name_order: 'Dom Feliciano', uf: 'RS' },
			{ name: 'Dom Pedro de Alcântara', name_order: 'Dom Pedro de Alcantara', uf: 'RS' },
			{ name: 'Dom Pedrito', name_order: 'Dom Pedrito', uf: 'RS' },
			{ name: 'Dona Francisca', name_order: 'Dona Francisca', uf: 'RS' },
			{ name: 'Doutor Maurício Cardoso', name_order: 'Doutor Mauricio Cardoso', uf: 'RS' },
			{ name: 'Doutor Ricardo', name_order: 'Doutor Ricardo', uf: 'RS' },
			{ name: 'Eldorado do Sul', name_order: 'Eldorado do Sul', uf: 'RS' },
			{ name: 'Encantado', name_order: 'Encantado', uf: 'RS' },
			{ name: 'Encruzilhada do Sul', name_order: 'Encruzilhada do Sul', uf: 'RS' },
			{ name: 'Engenho Velho', name_order: 'Engenho Velho', uf: 'RS' },
			{ name: 'Entre-ijuís', name_order: 'Entreijuis', uf: 'RS' },
			{ name: 'Entre Rios do Sul', name_order: 'Entre Rios do Sul', uf: 'RS' },
			{ name: 'Erebango', name_order: 'Erebango', uf: 'RS' },
			{ name: 'Erechim', name_order: 'Erechim', uf: 'RS' },
			{ name: 'Ernestina', name_order: 'Ernestina', uf: 'RS' },
			{ name: 'Herval', name_order: 'Herval', uf: 'RS' },
			{ name: 'Erval Grande', name_order: 'Erval Grande', uf: 'RS' },
			{ name: 'Erval Seco', name_order: 'Erval Seco', uf: 'RS' },
			{ name: 'Esmeralda', name_order: 'Esmeralda', uf: 'RS' },
			{ name: 'Esperança do Sul', name_order: 'Esperanca do Sul', uf: 'RS' },
			{ name: 'Espumoso', name_order: 'Espumoso', uf: 'RS' },
			{ name: 'Estação', name_order: 'Estacao', uf: 'RS' },
			{ name: 'Estância Velha', name_order: 'Estancia Velha', uf: 'RS' },
			{ name: 'Esteio', name_order: 'Esteio', uf: 'RS' },
			{ name: 'Estrela', name_order: 'Estrela', uf: 'RS' },
			{ name: 'Estrela Velha', name_order: 'Estrela Velha', uf: 'RS' },
			{ name: 'Eugênio de Castro', name_order: 'Eugenio de Castro', uf: 'RS' },
			{ name: 'Fagundes Varela', name_order: 'Fagundes Varela', uf: 'RS' },
			{ name: 'Farroupilha', name_order: 'Farroupilha', uf: 'RS' },
			{ name: 'Faxinal do Soturno', name_order: 'Faxinal do Soturno', uf: 'RS' },
			{ name: 'Faxinalzinho', name_order: 'Faxinalzinho', uf: 'RS' },
			{ name: 'Fazenda Vilanova', name_order: 'Fazenda Vilanova', uf: 'RS' },
			{ name: 'Feliz', name_order: 'Feliz', uf: 'RS' },
			{ name: 'Flores da Cunha', name_order: 'Flores da Cunha', uf: 'RS' },
			{ name: 'Floriano Peixoto', name_order: 'Floriano Peixoto', uf: 'RS' },
			{ name: 'Fontoura Xavier', name_order: 'Fontoura Xavier', uf: 'RS' },
			{ name: 'Formigueiro', name_order: 'Formigueiro', uf: 'RS' },
			{ name: 'Forquetinha', name_order: 'Forquetinha', uf: 'RS' },
			{ name: 'Fortaleza Dos Valos', name_order: 'Fortaleza Dos Valos', uf: 'RS' },
			{ name: 'Frederico Westphalen', name_order: 'Frederico Westphalen', uf: 'RS' },
			{ name: 'Garibaldi', name_order: 'Garibaldi', uf: 'RS' },
			{ name: 'Garruchos', name_order: 'Garruchos', uf: 'RS' },
			{ name: 'Gaurama', name_order: 'Gaurama', uf: 'RS' },
			{ name: 'General Câmara', name_order: 'General Camara', uf: 'RS' },
			{ name: 'Gentil', name_order: 'Gentil', uf: 'RS' },
			{ name: 'Getúlio Vargas', name_order: 'Getulio Vargas', uf: 'RS' },
			{ name: 'Giruá', name_order: 'Girua', uf: 'RS' },
			{ name: 'Glorinha', name_order: 'Glorinha', uf: 'RS' },
			{ name: 'Gramado', name_order: 'Gramado', uf: 'RS' },
			{ name: 'Gramado Dos Loureiros', name_order: 'Gramado Dos Loureiros', uf: 'RS' },
			{ name: 'Gramado Xavier', name_order: 'Gramado Xavier', uf: 'RS' },
			{ name: 'Gravataí', name_order: 'Gravatai', uf: 'RS' },
			{ name: 'Guabiju', name_order: 'Guabiju', uf: 'RS' },
			{ name: 'Guaíba', name_order: 'Guaiba', uf: 'RS' },
			{ name: 'Guaporé', name_order: 'Guapore', uf: 'RS' },
			{ name: 'Guarani Das Missões', name_order: 'Guarani Das Missoes', uf: 'RS' },
			{ name: 'Harmonia', name_order: 'Harmonia', uf: 'RS' },
			{ name: 'Herveiras', name_order: 'Herveiras', uf: 'RS' },
			{ name: 'Horizontina', name_order: 'Horizontina', uf: 'RS' },
	]);
};
