exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Água Clara', name_order: 'Agua Clara', uf: 'MS' },
			{ name: 'Alcinópolis', name_order: 'Alcinopolis', uf: 'MS' },
			{ name: 'Amambaí', name_order: 'Amambai', uf: 'MS' },
			{ name: 'Anastácio', name_order: 'Anastacio', uf: 'MS' },
			{ name: 'Anaurilândia', name_order: 'Anaurilandia', uf: 'MS' },
			{ name: 'Angélica', name_order: 'Angelica', uf: 'MS' },
			{ name: 'Antônio João', name_order: 'Antonio Joao', uf: 'MS' },
			{ name: 'Aparecida do Taboado', name_order: 'Aparecida do Taboado', uf: 'MS' },
			{ name: 'Aquidauana', name_order: 'Aquidauana', uf: 'MS' },
			{ name: 'Aral Moreira', name_order: 'Aral Moreira', uf: 'MS' },
			{ name: 'Bandeirantes', name_order: 'Bandeirantes', uf: 'MS' },
			{ name: 'Bataguassu', name_order: 'Bataguassu', uf: 'MS' },
			{ name: 'Batayporã', name_order: 'Bataypora', uf: 'MS' },
			{ name: 'Bela Vista', name_order: 'Bela Vista', uf: 'MS' },
			{ name: 'Bodoquena', name_order: 'Bodoquena', uf: 'MS' },
			{ name: 'Bonito', name_order: 'Bonito', uf: 'MS' },
			{ name: 'Brasilândia', name_order: 'Brasilandia', uf: 'MS' },
			{ name: 'Caarapó', name_order: 'Caarapo', uf: 'MS' },
			{ name: 'Camapuã', name_order: 'Camapua', uf: 'MS' },
			{ name: 'Campo Grande', name_order: 'Campo Grande', uf: 'MS' },
			{ name: 'Caracol', name_order: 'Caracol', uf: 'MS' },
			{ name: 'Cassilândia', name_order: 'Cassilandia', uf: 'MS' },
			{ name: 'Chapadão do Sul', name_order: 'Chapadao do Sul', uf: 'MS' },
			{ name: 'Corguinho', name_order: 'Corguinho', uf: 'MS' },
			{ name: 'Coronel Sapucaia', name_order: 'Coronel Sapucaia', uf: 'MS' },
			{ name: 'Corumbá', name_order: 'Corumba', uf: 'MS' },
			{ name: 'Costa Rica', name_order: 'Costa Rica', uf: 'MS' },
			{ name: 'Coxim', name_order: 'Coxim', uf: 'MS' },
			{ name: 'Deodápolis', name_order: 'Deodapolis', uf: 'MS' },
			{ name: 'Dois Irmãos do Buriti', name_order: 'Dois Irmaos do Buriti', uf: 'MS' },
			{ name: 'Douradina', name_order: 'Douradina', uf: 'MS' },
			{ name: 'Dourados', name_order: 'Dourados', uf: 'MS' },
			{ name: 'Eldorado', name_order: 'Eldorado', uf: 'MS' },
			{ name: 'Fátima do Sul', name_order: 'Fatima do Sul', uf: 'MS' },
			{ name: 'Figueirão', name_order: 'Figueirao', uf: 'MS' },
			{ name: 'Glória de Dourados', name_order: 'Gloria de Dourados', uf: 'MS' },
			{ name: 'Guia Lopes da Laguna', name_order: 'Guia Lopes da Laguna', uf: 'MS' },
			{ name: 'Iguatemi', name_order: 'Iguatemi', uf: 'MS' },
			{ name: 'Inocência', name_order: 'Inocencia', uf: 'MS' },
			{ name: 'Itaporã', name_order: 'Itapora', uf: 'MS' },
			{ name: 'Itaquiraí', name_order: 'Itaquirai', uf: 'MS' },
			{ name: 'Ivinhema', name_order: 'Ivinhema', uf: 'MS' },
			{ name: 'Japorã', name_order: 'Japora', uf: 'MS' },
			{ name: 'Jaraguari', name_order: 'Jaraguari', uf: 'MS' },
			{ name: 'Jardim', name_order: 'Jardim', uf: 'MS' },
			{ name: 'Jateí', name_order: 'Jatei', uf: 'MS' },
			{ name: 'Juti', name_order: 'Juti', uf: 'MS' },
			{ name: 'Ladário', name_order: 'Ladario', uf: 'MS' },
			{ name: 'Laguna Carapã', name_order: 'Laguna Carapa', uf: 'MS' },
			{ name: 'Maracaju', name_order: 'Maracaju', uf: 'MS' },
			{ name: 'Miranda', name_order: 'Miranda', uf: 'MS' },
			{ name: 'Mundo Novo', name_order: 'Mundo Novo', uf: 'MS' },
			{ name: 'Naviraí', name_order: 'Navirai', uf: 'MS' },
			{ name: 'Nioaque', name_order: 'Nioaque', uf: 'MS' },
			{ name: 'Nova Alvorada do Sul', name_order: 'Nova Alvorada do Sul', uf: 'MS' },
			{ name: 'Nova Andradina', name_order: 'Nova Andradina', uf: 'MS' },
			{ name: 'Novo Horizonte do Sul', name_order: 'Novo Horizonte do Sul', uf: 'MS' },
			{ name: 'Paraíso das Águas', name_order: 'Paraiso das Aguas', uf: 'MS' },
			{ name: 'Paranaíba', name_order: 'Paranaiba', uf: 'MS' },
			{ name: 'Paranhos', name_order: 'Paranhos', uf: 'MS' },
			{ name: 'Pedro Gomes', name_order: 'Pedro Gomes', uf: 'MS' },
			{ name: 'Ponta Porã', name_order: 'Ponta Pora', uf: 'MS' },
			{ name: 'Porto Murtinho', name_order: 'Porto Murtinho', uf: 'MS' },
			{ name: 'Ribas do Rio Pardo', name_order: 'Ribas do Rio Pardo', uf: 'MS' },
			{ name: 'Rio Brilhante', name_order: 'Rio Brilhante', uf: 'MS' },
			{ name: 'Rio Negro', name_order: 'Rio Negro', uf: 'MS' },
			{ name: 'Rio Verde de Mato Grosso', name_order: 'Rio Verde de Mato Grosso', uf: 'MS' },
			{ name: 'Rochedo', name_order: 'Rochedo', uf: 'MS' },
			{ name: 'Santa Rita do Pardo', name_order: 'Santa Rita do Pardo', uf: 'MS' },
			{ name: 'São Gabriel do Oeste', name_order: 'Sao Gabriel do Oeste', uf: 'MS' },
			{ name: 'Sete Quedas', name_order: 'Sete Quedas', uf: 'MS' },
			{ name: 'Selvíria', name_order: 'Selviria', uf: 'MS' },
			{ name: 'Sidrolândia', name_order: 'Sidrolandia', uf: 'MS' },
			{ name: 'Sonora', name_order: 'Sonora', uf: 'MS' },
			{ name: 'Tacuru', name_order: 'Tacuru', uf: 'MS' },
			{ name: 'Taquarussu', name_order: 'Taquarussu', uf: 'MS' },
			{ name: 'Terenos', name_order: 'Terenos', uf: 'MS' },
			{ name: 'Três Lagoas', name_order: 'Tres Lagoas', uf: 'MS' },
			{ name: 'Vicentina', name_order: 'Vicentina', uf: 'MS' },
	]);
};
