exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Meridiano', name_order: 'Meridiano', uf: 'SP' },
			{ name: 'Mesópolis', name_order: 'Mesopolis', uf: 'SP' },
			{ name: 'Miguelópolis', name_order: 'Miguelopolis', uf: 'SP' },
			{ name: 'Mineiros do Tietê', name_order: 'Mineiros do Tiete', uf: 'SP' },
			{ name: 'Miracatu', name_order: 'Miracatu', uf: 'SP' },
			{ name: 'Mira Estrela', name_order: 'Mira Estrela', uf: 'SP' },
			{ name: 'Mirandópolis', name_order: 'Mirandopolis', uf: 'SP' },
			{ name: 'Mirante do Paranapanema', name_order: 'Mirante do Paranapanema', uf: 'SP' },
			{ name: 'Mirassol', name_order: 'Mirassol', uf: 'SP' },
			{ name: 'Mirassolândia', name_order: 'Mirassolandia', uf: 'SP' },
			{ name: 'Mococa', name_order: 'Mococa', uf: 'SP' },
			{ name: 'Moji Das Cruzes', name_order: 'Moji Das Cruzes', uf: 'SP' },
			{ name: 'Mogi Guaçu', name_order: 'Mogi Guacu', uf: 'SP' },
			{ name: 'Moji-mirim', name_order: 'Mojimirim', uf: 'SP' },
			{ name: 'Mombuca', name_order: 'Mombuca', uf: 'SP' },
			{ name: 'Monções', name_order: 'Moncoes', uf: 'SP' },
			{ name: 'Mongaguá', name_order: 'Mongagua', uf: 'SP' },
			{ name: 'Monte Alegre do Sul', name_order: 'Monte Alegre do Sul', uf: 'SP' },
			{ name: 'Monte Alto', name_order: 'Monte Alto', uf: 'SP' },
			{ name: 'Monte Aprazível', name_order: 'Monte Aprazivel', uf: 'SP' },
			{ name: 'Monte Azul Paulista', name_order: 'Monte Azul Paulista', uf: 'SP' },
			{ name: 'Monte Castelo', name_order: 'Monte Castelo', uf: 'SP' },
			{ name: 'Monteiro Lobato', name_order: 'Monteiro Lobato', uf: 'SP' },
			{ name: 'Monte Mor', name_order: 'Monte Mor', uf: 'SP' },
			{ name: 'Morro Agudo', name_order: 'Morro Agudo', uf: 'SP' },
			{ name: 'Morungaba', name_order: 'Morungaba', uf: 'SP' },
			{ name: 'Motuca', name_order: 'Motuca', uf: 'SP' },
			{ name: 'Murutinga do Sul', name_order: 'Murutinga do Sul', uf: 'SP' },
			{ name: 'Nantes', name_order: 'Nantes', uf: 'SP' },
			{ name: 'Narandiba', name_order: 'Narandiba', uf: 'SP' },
			{ name: 'Natividade da Serra', name_order: 'Natividade da Serra', uf: 'SP' },
			{ name: 'Nazaré Paulista', name_order: 'Nazare Paulista', uf: 'SP' },
			{ name: 'Neves Paulista', name_order: 'Neves Paulista', uf: 'SP' },
			{ name: 'Nhandeara', name_order: 'Nhandeara', uf: 'SP' },
			{ name: 'Nipoã', name_order: 'Nipoa', uf: 'SP' },
			{ name: 'Nova Aliança', name_order: 'Nova Alianca', uf: 'SP' },
			{ name: 'Nova Campina', name_order: 'Nova Campina', uf: 'SP' },
			{ name: 'Nova Canaã Paulista', name_order: 'Nova Canaa Paulista', uf: 'SP' },
			{ name: 'Nova Castilho', name_order: 'Nova Castilho', uf: 'SP' },
			{ name: 'Nova Europa', name_order: 'Nova Europa', uf: 'SP' },
			{ name: 'Nova Granada', name_order: 'Nova Granada', uf: 'SP' },
			{ name: 'Nova Guataporanga', name_order: 'Nova Guataporanga', uf: 'SP' },
			{ name: 'Nova Independência', name_order: 'Nova Independencia', uf: 'SP' },
			{ name: 'Novais', name_order: 'Novais', uf: 'SP' },
			{ name: 'Nova Luzitânia', name_order: 'Nova Luzitania', uf: 'SP' },
			{ name: 'Nova Odessa', name_order: 'Nova Odessa', uf: 'SP' },
			{ name: 'Novo Horizonte', name_order: 'Novo Horizonte', uf: 'SP' },
			{ name: 'Nuporanga', name_order: 'Nuporanga', uf: 'SP' },
			{ name: 'Ocauçu', name_order: 'Ocaucu', uf: 'SP' },
			{ name: 'Óleo', name_order: 'Oleo', uf: 'SP' },
			{ name: 'Olímpia', name_order: 'Olimpia', uf: 'SP' },
			{ name: 'Onda Verde', name_order: 'Onda Verde', uf: 'SP' },
			{ name: 'Oriente', name_order: 'Oriente', uf: 'SP' },
			{ name: 'Orindiúva', name_order: 'Orindiuva', uf: 'SP' },
			{ name: 'Orlândia', name_order: 'Orlandia', uf: 'SP' },
			{ name: 'Osasco', name_order: 'Osasco', uf: 'SP' },
			{ name: 'Oscar Bressane', name_order: 'Oscar Bressane', uf: 'SP' },
			{ name: 'Osvaldo Cruz', name_order: 'Osvaldo Cruz', uf: 'SP' },
			{ name: 'Ourinhos', name_order: 'Ourinhos', uf: 'SP' },
			{ name: 'Ouroeste', name_order: 'Ouroeste', uf: 'SP' },
			{ name: 'Ouro Verde', name_order: 'Ouro Verde', uf: 'SP' },
			{ name: 'Pacaembu', name_order: 'Pacaembu', uf: 'SP' },
			{ name: 'Palestina', name_order: 'Palestina', uf: 'SP' },
			{ name: 'Palmares Paulista', name_order: 'Palmares Paulista', uf: 'SP' },
			{ name: 'Palmeira D´oeste', name_order: 'Palmeira Doeste', uf: 'SP' },
			{ name: 'Palmital', name_order: 'Palmital', uf: 'SP' },
			{ name: 'Panorama', name_order: 'Panorama', uf: 'SP' },
			{ name: 'Paraguaçu Paulista', name_order: 'Paraguacu Paulista', uf: 'SP' },
			{ name: 'Paraibuna', name_order: 'Paraibuna', uf: 'SP' },
			{ name: 'Paraíso', name_order: 'Paraiso', uf: 'SP' },
			{ name: 'Paranapanema', name_order: 'Paranapanema', uf: 'SP' },
			{ name: 'Paranapuã', name_order: 'Paranapua', uf: 'SP' },
			{ name: 'Parapuã', name_order: 'Parapua', uf: 'SP' },
			{ name: 'Pardinho', name_order: 'Pardinho', uf: 'SP' },
			{ name: 'Pariquera-açu', name_order: 'Pariqueraacu', uf: 'SP' },
			{ name: 'Parisi', name_order: 'Parisi', uf: 'SP' },
			{ name: 'Patrocínio Paulista', name_order: 'Patrocinio Paulista', uf: 'SP' },
			{ name: 'Paulicéia', name_order: 'Pauliceia', uf: 'SP' },
			{ name: 'Paulínia', name_order: 'Paulinia', uf: 'SP' },
			{ name: 'Paulistânia', name_order: 'Paulistania', uf: 'SP' },
			{ name: 'Paulo de Faria', name_order: 'Paulo de Faria', uf: 'SP' },
			{ name: 'Pederneiras', name_order: 'Pederneiras', uf: 'SP' },
			{ name: 'Pedra Bela', name_order: 'Pedra Bela', uf: 'SP' },
			{ name: 'Pedranópolis', name_order: 'Pedranopolis', uf: 'SP' },
			{ name: 'Pedregulho', name_order: 'Pedregulho', uf: 'SP' },
			{ name: 'Pedreira', name_order: 'Pedreira', uf: 'SP' },
			{ name: 'Pedrinhas Paulista', name_order: 'Pedrinhas Paulista', uf: 'SP' },
			{ name: 'Pedro de Toledo', name_order: 'Pedro de Toledo', uf: 'SP' },
			{ name: 'Penápolis', name_order: 'Penapolis', uf: 'SP' },
			{ name: 'Pereira Barreto', name_order: 'Pereira Barreto', uf: 'SP' },
			{ name: 'Pereiras', name_order: 'Pereiras', uf: 'SP' },
			{ name: 'Peruíbe', name_order: 'Peruibe', uf: 'SP' },
			{ name: 'Piacatu', name_order: 'Piacatu', uf: 'SP' },
			{ name: 'Piedade', name_order: 'Piedade', uf: 'SP' },
			{ name: 'Pilar do Sul', name_order: 'Pilar do Sul', uf: 'SP' },
			{ name: 'Pindamonhangaba', name_order: 'Pindamonhangaba', uf: 'SP' },
			{ name: 'Pindorama', name_order: 'Pindorama', uf: 'SP' },
			{ name: 'Pinhalzinho', name_order: 'Pinhalzinho', uf: 'SP' },
			{ name: 'Piquerobi', name_order: 'Piquerobi', uf: 'SP' },
			{ name: 'Piquete', name_order: 'Piquete', uf: 'SP' },
			{ name: 'Piracaia', name_order: 'Piracaia', uf: 'SP' },
			{ name: 'Piracicaba', name_order: 'Piracicaba', uf: 'SP' },
			{ name: 'Piraju', name_order: 'Piraju', uf: 'SP' },
			{ name: 'Pirajuí', name_order: 'Pirajui', uf: 'SP' },
			{ name: 'Pirangi', name_order: 'Pirangi', uf: 'SP' },
			{ name: 'Pirapora do Bom Jesus', name_order: 'Pirapora do Bom Jesus', uf: 'SP' },
			{ name: 'Pirapozinho', name_order: 'Pirapozinho', uf: 'SP' },
			{ name: 'Pirassununga', name_order: 'Pirassununga', uf: 'SP' },
			{ name: 'Piratininga', name_order: 'Piratininga', uf: 'SP' },
			{ name: 'Pitangueiras', name_order: 'Pitangueiras', uf: 'SP' },
			{ name: 'Planalto', name_order: 'Planalto', uf: 'SP' },
			{ name: 'Platina', name_order: 'Platina', uf: 'SP' },
			{ name: 'Poá', name_order: 'Poa', uf: 'SP' },
			{ name: 'Poloni', name_order: 'Poloni', uf: 'SP' },
			{ name: 'Pompéia', name_order: 'Pompeia', uf: 'SP' },
			{ name: 'Pongaí', name_order: 'Pongai', uf: 'SP' },
			{ name: 'Pontal', name_order: 'Pontal', uf: 'SP' },
			{ name: 'Pontalinda', name_order: 'Pontalinda', uf: 'SP' },
			{ name: 'Pontes Gestal', name_order: 'Pontes Gestal', uf: 'SP' },
			{ name: 'Populina', name_order: 'Populina', uf: 'SP' },
			{ name: 'Porangaba', name_order: 'Porangaba', uf: 'SP' },
			{ name: 'Porto Feliz', name_order: 'Porto Feliz', uf: 'SP' },
			{ name: 'Porto Ferreira', name_order: 'Porto Ferreira', uf: 'SP' },
			{ name: 'Potim', name_order: 'Potim', uf: 'SP' },
			{ name: 'Potirendaba', name_order: 'Potirendaba', uf: 'SP' },
			{ name: 'Pracinha', name_order: 'Pracinha', uf: 'SP' },
			{ name: 'Pradópolis', name_order: 'Pradopolis', uf: 'SP' },
			{ name: 'Praia Grande', name_order: 'Praia Grande', uf: 'SP' },
			{ name: 'Pratânia', name_order: 'Pratania', uf: 'SP' },
			{ name: 'Presidente Alves', name_order: 'Presidente Alves', uf: 'SP' },
			{ name: 'Presidente Bernardes', name_order: 'Presidente Bernardes', uf: 'SP' },
			{ name: 'Presidente Epitácio', name_order: 'Presidente Epitacio', uf: 'SP' },
			{ name: 'Presidente Prudente', name_order: 'Presidente Prudente', uf: 'SP' },
			{ name: 'Presidente Venceslau', name_order: 'Presidente Venceslau', uf: 'SP' },
			{ name: 'Promissão', name_order: 'Promissao', uf: 'SP' },
			{ name: 'Quadra', name_order: 'Quadra', uf: 'SP' },
			{ name: 'Quatá', name_order: 'Quata', uf: 'SP' },
			{ name: 'Queiroz', name_order: 'Queiroz', uf: 'SP' },
			{ name: 'Queluz', name_order: 'Queluz', uf: 'SP' },
			{ name: 'Quintana', name_order: 'Quintana', uf: 'SP' },
			{ name: 'Rafard', name_order: 'Rafard', uf: 'SP' },
			{ name: 'Rancharia', name_order: 'Rancharia', uf: 'SP' },
			{ name: 'Redenção da Serra', name_order: 'Redencao da Serra', uf: 'SP' },
			{ name: 'Regente Feijó', name_order: 'Regente Feijo', uf: 'SP' },
			{ name: 'Reginópolis', name_order: 'Reginopolis', uf: 'SP' },
			{ name: 'Registro', name_order: 'Registro', uf: 'SP' },
			{ name: 'Restinga', name_order: 'Restinga', uf: 'SP' },
			{ name: 'Ribeira', name_order: 'Ribeira', uf: 'SP' },
			{ name: 'Ribeirão Bonito', name_order: 'Ribeirao Bonito', uf: 'SP' },
			{ name: 'Ribeirão Branco', name_order: 'Ribeirao Branco', uf: 'SP' },
			{ name: 'Ribeirão Corrente', name_order: 'Ribeirao Corrente', uf: 'SP' },
			{ name: 'Ribeirão do Sul', name_order: 'Ribeirao do Sul', uf: 'SP' },
			{ name: 'Ribeirão Dos Índios', name_order: 'Ribeirao Dos Indios', uf: 'SP' },
			{ name: 'Ribeirão Grande', name_order: 'Ribeirao Grande', uf: 'SP' },
			{ name: 'Ribeirão Pires', name_order: 'Ribeirao Pires', uf: 'SP' },
			{ name: 'Ribeirão Preto', name_order: 'Ribeirao Preto', uf: 'SP' },
			{ name: 'Riversul', name_order: 'Riversul', uf: 'SP' },
			{ name: 'Rifaina', name_order: 'Rifaina', uf: 'SP' },
			{ name: 'Rincão', name_order: 'Rincao', uf: 'SP' },
			{ name: 'Rinópolis', name_order: 'Rinopolis', uf: 'SP' },
			{ name: 'Rio Claro', name_order: 'Rio Claro', uf: 'SP' },
			{ name: 'Rio Das Pedras', name_order: 'Rio Das Pedras', uf: 'SP' },
			{ name: 'Rio Grande da Serra', name_order: 'Rio Grande da Serra', uf: 'SP' },
			{ name: 'Riolândia', name_order: 'Riolandia', uf: 'SP' },
			{ name: 'Rosana', name_order: 'Rosana', uf: 'SP' },
			{ name: 'Roseira', name_order: 'Roseira', uf: 'SP' },
			{ name: 'Rubiácea', name_order: 'Rubiacea', uf: 'SP' },
			{ name: 'Rubinéia', name_order: 'Rubineia', uf: 'SP' },
			{ name: 'Sabino', name_order: 'Sabino', uf: 'SP' },
			{ name: 'Sagres', name_order: 'Sagres', uf: 'SP' },
			{ name: 'Sales', name_order: 'Sales', uf: 'SP' },
			{ name: 'Sales Oliveira', name_order: 'Sales Oliveira', uf: 'SP' },
			{ name: 'Salesópolis', name_order: 'Salesopolis', uf: 'SP' },
			{ name: 'Salmourão', name_order: 'Salmourao', uf: 'SP' },
			{ name: 'Saltinho', name_order: 'Saltinho', uf: 'SP' },
			{ name: 'Salto', name_order: 'Salto', uf: 'SP' },
			{ name: 'Salto de Pirapora', name_order: 'Salto de Pirapora', uf: 'SP' },
			{ name: 'Salto Grande', name_order: 'Salto Grande', uf: 'SP' },
			{ name: 'Sandovalina', name_order: 'Sandovalina', uf: 'SP' },
			{ name: 'Santa Adélia', name_order: 'Santa Adelia', uf: 'SP' },
			{ name: 'Santa Albertina', name_order: 'Santa Albertina', uf: 'SP' },
			{ name: 'Santa Bárbara D´oeste', name_order: 'Santa Barbara Doeste', uf: 'SP' },
			{ name: 'Santa Branca', name_order: 'Santa Branca', uf: 'SP' },
			{ name: 'Santa Clara D´oeste', name_order: 'Santa Clara Doeste', uf: 'SP' },
			{ name: 'Santa Cruz da Conceição', name_order: 'Santa Cruz da Conceicao', uf: 'SP' },
			{ name: 'Santa Cruz da Esperança', name_order: 'Santa Cruz da Esperanca', uf: 'SP' },
			{ name: 'Santa Cruz Das Palmeiras', name_order: 'Santa Cruz Das Palmeiras', uf: 'SP' },
			{ name: 'Santa Cruz do Rio Pardo', name_order: 'Santa Cruz do Rio Pardo', uf: 'SP' },
			{ name: 'Santa Ernestina', name_order: 'Santa Ernestina', uf: 'SP' },
			{ name: 'Santa fé do Sul', name_order: 'Santa fe do Sul', uf: 'SP' },
			{ name: 'Santa Gertrudes', name_order: 'Santa Gertrudes', uf: 'SP' },
			{ name: 'Santa Isabel', name_order: 'Santa Isabel', uf: 'SP' },
			{ name: 'Santa Lúcia', name_order: 'Santa Lucia', uf: 'SP' },
			{ name: 'Santa Maria da Serra', name_order: 'Santa Maria da Serra', uf: 'SP' },
			{ name: 'Santa Mercedes', name_order: 'Santa Mercedes', uf: 'SP' },
			{ name: 'Santana da Ponte Pensa', name_order: 'Santana da Ponte Pensa', uf: 'SP' },
			{ name: 'Santana de Parnaíba', name_order: 'Santana de Parnaiba', uf: 'SP' },
			{ name: 'Santa Rita D´oeste', name_order: 'Santa Rita Doeste', uf: 'SP' },
			{ name: 'Santa Rita do Passa Quatro', name_order: 'Santa Rita do Passa Quatro', uf: 'SP' },
			{ name: 'Santa Rosa de Viterbo', name_order: 'Santa Rosa de Viterbo', uf: 'SP' },
			{ name: 'Santa Salete', name_order: 'Santa Salete', uf: 'SP' },
			{ name: 'Santo Anastácio', name_order: 'Santo Anastacio', uf: 'SP' },
			{ name: 'Santo André', name_order: 'Santo Andre', uf: 'SP' },
			{ name: 'Santo Antônio da Alegria', name_order: 'Santo Antonio da Alegria', uf: 'SP' },
			{ name: 'Santo Antônio de Posse', name_order: 'Santo Antonio de Posse', uf: 'SP' },
			{ name: 'Santo Antônio do Aracanguá', name_order: 'Santo Antonio do Aracangua', uf: 'SP' },
			{ name: 'Santo Antônio do Jardim', name_order: 'Santo Antonio do Jardim', uf: 'SP' },
			{ name: 'Santo Antônio do Pinhal', name_order: 'Santo Antonio do Pinhal', uf: 'SP' },
			{ name: 'Santo Expedito', name_order: 'Santo Expedito', uf: 'SP' },
			{ name: 'Santópolis do Aguapeí', name_order: 'Santopolis do Aguapei', uf: 'SP' },
			{ name: 'Santos', name_order: 'Santos', uf: 'SP' },
			{ name: 'São Bento do Sapucaí', name_order: 'Sao Bento do Sapucai', uf: 'SP' },
			{ name: 'São Bernardo do Campo', name_order: 'Sao Bernardo do Campo', uf: 'SP' },
			{ name: 'São Caetano do Sul', name_order: 'Sao Caetano do Sul', uf: 'SP' },
			{ name: 'São Carlos', name_order: 'Sao Carlos', uf: 'SP' },
			{ name: 'São Francisco', name_order: 'Sao Francisco', uf: 'SP' },
			{ name: 'São João da Boa Vista', name_order: 'Sao Joao da Boa Vista', uf: 'SP' },
			{ name: 'São João Das Duas Pontes', name_order: 'Sao Joao Das Duas Pontes', uf: 'SP' },
			{ name: 'São João de Iracema', name_order: 'Sao Joao de Iracema', uf: 'SP' },
			{ name: 'São João do Pau D´alho', name_order: 'Sao Joao do Pau Dalho', uf: 'SP' },
			{ name: 'São Joaquim da Barra', name_order: 'Sao Joaquim da Barra', uf: 'SP' },
			{ name: 'São José da Bela Vista', name_order: 'Sao Jose da Bela Vista', uf: 'SP' },
			{ name: 'São José do Barreiro', name_order: 'Sao Jose do Barreiro', uf: 'SP' },
			{ name: 'São José do Rio Pardo', name_order: 'Sao Jose do Rio Pardo', uf: 'SP' },
			{ name: 'São José do Rio Preto', name_order: 'Sao Jose do Rio Preto', uf: 'SP' },
			{ name: 'São José Dos Campos', name_order: 'Sao Jose Dos Campos', uf: 'SP' },
			{ name: 'São Lourenço da Serra', name_order: 'Sao Lourenco da Serra', uf: 'SP' },
			{ name: 'São Luís do Paraitinga', name_order: 'Sao Luis do Paraitinga', uf: 'SP' },
			{ name: 'São Manuel', name_order: 'Sao Manuel', uf: 'SP' },
			{ name: 'São Miguel Arcanjo', name_order: 'Sao Miguel Arcanjo', uf: 'SP' },
			{ name: 'São Paulo', name_order: 'Sao Paulo', uf: 'SP' },
			{ name: 'São Pedro', name_order: 'Sao Pedro', uf: 'SP' },
			{ name: 'São Pedro do Turvo', name_order: 'Sao Pedro do Turvo', uf: 'SP' },
			{ name: 'São Roque', name_order: 'Sao Roque', uf: 'SP' },
			{ name: 'São Sebastião', name_order: 'Sao Sebastiao', uf: 'SP' },
			{ name: 'São Sebastião da Grama', name_order: 'Sao Sebastiao da Grama', uf: 'SP' },
			{ name: 'São Simão', name_order: 'Sao Simao', uf: 'SP' },
			{ name: 'São Vicente', name_order: 'Sao Vicente', uf: 'SP' },
			{ name: 'Sarapuí', name_order: 'Sarapui', uf: 'SP' },
			{ name: 'Sarutaiá', name_order: 'Sarutaia', uf: 'SP' },
			{ name: 'Sebastianópolis do Sul', name_order: 'Sebastianopolis do Sul', uf: 'SP' },
			{ name: 'Serra Azul', name_order: 'Serra Azul', uf: 'SP' },
			{ name: 'Serrana', name_order: 'Serrana', uf: 'SP' },
			{ name: 'Serra Negra', name_order: 'Serra Negra', uf: 'SP' },
			{ name: 'Sertãozinho', name_order: 'Sertaozinho', uf: 'SP' },
			{ name: 'Sete Barras', name_order: 'Sete Barras', uf: 'SP' },
			{ name: 'Severínia', name_order: 'Severinia', uf: 'SP' },
			{ name: 'Silveiras', name_order: 'Silveiras', uf: 'SP' },
			{ name: 'Socorro', name_order: 'Socorro', uf: 'SP' },
			{ name: 'Sorocaba', name_order: 'Sorocaba', uf: 'SP' },
			{ name: 'Sud Mennucci', name_order: 'Sud Mennucci', uf: 'SP' },
			{ name: 'Sumaré', name_order: 'Sumare', uf: 'SP' },
			{ name: 'Suzano', name_order: 'Suzano', uf: 'SP' },
			{ name: 'Suzanápolis', name_order: 'Suzanapolis', uf: 'SP' },
			{ name: 'Tabapuã', name_order: 'Tabapua', uf: 'SP' },
			{ name: 'Tabatinga', name_order: 'Tabatinga', uf: 'SP' },
			{ name: 'Taboão da Serra', name_order: 'Taboao da Serra', uf: 'SP' },
			{ name: 'Taciba', name_order: 'Taciba', uf: 'SP' },
			{ name: 'Taguaí', name_order: 'Taguai', uf: 'SP' },
			{ name: 'Taiaçu', name_order: 'Taiacu', uf: 'SP' },
			{ name: 'Taiúva', name_order: 'Taiuva', uf: 'SP' },
			{ name: 'Tambaú', name_order: 'Tambau', uf: 'SP' },
			{ name: 'Tanabi', name_order: 'Tanabi', uf: 'SP' },
			{ name: 'Tapiraí', name_order: 'Tapirai', uf: 'SP' },
			{ name: 'Tapiratiba', name_order: 'Tapiratiba', uf: 'SP' },
			{ name: 'Taquaral', name_order: 'Taquaral', uf: 'SP' },
			{ name: 'Taquaritinga', name_order: 'Taquaritinga', uf: 'SP' },
			{ name: 'Taquarituba', name_order: 'Taquarituba', uf: 'SP' },
			{ name: 'Taquarivaí', name_order: 'Taquarivai', uf: 'SP' },
			{ name: 'Tarabai', name_order: 'Tarabai', uf: 'SP' },
			{ name: 'Tarumã', name_order: 'Taruma', uf: 'SP' },
			{ name: 'Tatuí', name_order: 'Tatui', uf: 'SP' },
			{ name: 'Taubaté', name_order: 'Taubate', uf: 'SP' },
			{ name: 'Tejupá', name_order: 'Tejupa', uf: 'SP' },
			{ name: 'Teodoro Sampaio', name_order: 'Teodoro Sampaio', uf: 'SP' },
			{ name: 'Terra Roxa', name_order: 'Terra Roxa', uf: 'SP' },
			{ name: 'Tietê', name_order: 'Tiete', uf: 'SP' },
			{ name: 'Timburi', name_order: 'Timburi', uf: 'SP' },
			{ name: 'Torre de Pedra', name_order: 'Torre de Pedra', uf: 'SP' },
			{ name: 'Torrinha', name_order: 'Torrinha', uf: 'SP' },
			{ name: 'Trabiju', name_order: 'Trabiju', uf: 'SP' },
			{ name: 'Tremembé', name_order: 'Tremembe', uf: 'SP' },
			{ name: 'Três Fronteiras', name_order: 'Tres Fronteiras', uf: 'SP' },
			{ name: 'Tuiuti', name_order: 'Tuiuti', uf: 'SP' },
			{ name: 'Tupã', name_order: 'Tupa', uf: 'SP' },
			{ name: 'Tupi Paulista', name_order: 'Tupi Paulista', uf: 'SP' },
			{ name: 'Turiúba', name_order: 'Turiuba', uf: 'SP' },
			{ name: 'Turmalina', name_order: 'Turmalina', uf: 'SP' },
			{ name: 'Ubarana', name_order: 'Ubarana', uf: 'SP' },
			{ name: 'Ubatuba', name_order: 'Ubatuba', uf: 'SP' },
			{ name: 'Ubirajara', name_order: 'Ubirajara', uf: 'SP' },
			{ name: 'Uchoa', name_order: 'Uchoa', uf: 'SP' },
			{ name: 'União Paulista', name_order: 'Uniao Paulista', uf: 'SP' },
			{ name: 'Urânia', name_order: 'Urania', uf: 'SP' },
			{ name: 'Uru', name_order: 'Uru', uf: 'SP' },
			{ name: 'Urupês', name_order: 'Urupes', uf: 'SP' },
			{ name: 'Valentim Gentil', name_order: 'Valentim Gentil', uf: 'SP' },
			{ name: 'Valinhos', name_order: 'Valinhos', uf: 'SP' },
			{ name: 'Valparaíso', name_order: 'Valparaiso', uf: 'SP' },
			{ name: 'Vargem', name_order: 'Vargem', uf: 'SP' },
	]);
};
