exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Nilo Peçanha', name_order: 'Nilo Pecanha', uf: 'BA' },
			{ name: 'Nordestina', name_order: 'Nordestina', uf: 'BA' },
			{ name: 'Nova Canaã', name_order: 'Nova Canaa', uf: 'BA' },
			{ name: 'Nova Fátima', name_order: 'Nova Fatima', uf: 'BA' },
			{ name: 'Nova Ibiá', name_order: 'Nova Ibia', uf: 'BA' },
			{ name: 'Nova Itarana', name_order: 'Nova Itarana', uf: 'BA' },
			{ name: 'Nova Redenção', name_order: 'Nova Redencao', uf: 'BA' },
			{ name: 'Nova Soure', name_order: 'Nova Soure', uf: 'BA' },
			{ name: 'Nova Viçosa', name_order: 'Nova Vicosa', uf: 'BA' },
			{ name: 'Novo Horizonte', name_order: 'Novo Horizonte', uf: 'BA' },
			{ name: 'Novo Triunfo', name_order: 'Novo Triunfo', uf: 'BA' },
			{ name: 'Olindina', name_order: 'Olindina', uf: 'BA' },
			{ name: 'Oliveira Dos Brejinhos', name_order: 'Oliveira Dos Brejinhos', uf: 'BA' },
			{ name: 'Ouriçangas', name_order: 'Ouricangas', uf: 'BA' },
			{ name: 'Ourolândia', name_order: 'Ourolandia', uf: 'BA' },
			{ name: 'Palmas de Monte Alto', name_order: 'Palmas de Monte Alto', uf: 'BA' },
			{ name: 'Palmeiras', name_order: 'Palmeiras', uf: 'BA' },
			{ name: 'Paramirim', name_order: 'Paramirim', uf: 'BA' },
			{ name: 'Paratinga', name_order: 'Paratinga', uf: 'BA' },
			{ name: 'Paripiranga', name_order: 'Paripiranga', uf: 'BA' },
			{ name: 'Pau Brasil', name_order: 'Pau Brasil', uf: 'BA' },
			{ name: 'Paulo Afonso', name_order: 'Paulo Afonso', uf: 'BA' },
			{ name: 'pé de Serra', name_order: 'pe de Serra', uf: 'BA' },
			{ name: 'Pedrão', name_order: 'Pedrao', uf: 'BA' },
			{ name: 'Pedro Alexandre', name_order: 'Pedro Alexandre', uf: 'BA' },
			{ name: 'Piatã', name_order: 'Piata', uf: 'BA' },
			{ name: 'Pilão Arcado', name_order: 'Pilao Arcado', uf: 'BA' },
			{ name: 'Pindaí', name_order: 'Pindai', uf: 'BA' },
			{ name: 'Pindobaçu', name_order: 'Pindobacu', uf: 'BA' },
			{ name: 'Pintadas', name_order: 'Pintadas', uf: 'BA' },
			{ name: 'Piraí do Norte', name_order: 'Pirai do Norte', uf: 'BA' },
			{ name: 'Piripá', name_order: 'Piripa', uf: 'BA' },
			{ name: 'Piritiba', name_order: 'Piritiba', uf: 'BA' },
			{ name: 'Planaltino', name_order: 'Planaltino', uf: 'BA' },
			{ name: 'Planalto', name_order: 'Planalto', uf: 'BA' },
			{ name: 'Poções', name_order: 'Pocoes', uf: 'BA' },
			{ name: 'Pojuca', name_order: 'Pojuca', uf: 'BA' },
			{ name: 'Ponto Novo', name_order: 'Ponto Novo', uf: 'BA' },
			{ name: 'Porto Seguro', name_order: 'Porto Seguro', uf: 'BA' },
			{ name: 'Potiraguá', name_order: 'Potiragua', uf: 'BA' },
			{ name: 'Prado', name_order: 'Prado', uf: 'BA' },
			{ name: 'Presidente Dutra', name_order: 'Presidente Dutra', uf: 'BA' },
			{ name: 'Presidente Jânio Quadros', name_order: 'Presidente Janio Quadros', uf: 'BA' },
			{ name: 'Presidente Tancredo Neves', name_order: 'Presidente Tancredo Neves', uf: 'BA' },
			{ name: 'Queimadas', name_order: 'Queimadas', uf: 'BA' },
			{ name: 'Quijingue', name_order: 'Quijingue', uf: 'BA' },
			{ name: 'Quixabeira', name_order: 'Quixabeira', uf: 'BA' },
			{ name: 'Rafael Jambeiro', name_order: 'Rafael Jambeiro', uf: 'BA' },
			{ name: 'Remanso', name_order: 'Remanso', uf: 'BA' },
			{ name: 'Retirolândia', name_order: 'Retirolandia', uf: 'BA' },
			{ name: 'Riachão Das Neves', name_order: 'Riachao Das Neves', uf: 'BA' },
			{ name: 'Riachão do Jacuípe', name_order: 'Riachao do Jacuipe', uf: 'BA' },
			{ name: 'Riacho de Santana', name_order: 'Riacho de Santana', uf: 'BA' },
			{ name: 'Ribeira do Amparo', name_order: 'Ribeira do Amparo', uf: 'BA' },
			{ name: 'Ribeira do Pombal', name_order: 'Ribeira do Pombal', uf: 'BA' },
			{ name: 'Ribeirão do Largo', name_order: 'Ribeirao do Largo', uf: 'BA' },
			{ name: 'Rio de Contas', name_order: 'Rio de Contas', uf: 'BA' },
			{ name: 'Rio do Antônio', name_order: 'Rio do Antonio', uf: 'BA' },
			{ name: 'Rio do Pires', name_order: 'Rio do Pires', uf: 'BA' },
			{ name: 'Rio Real', name_order: 'Rio Real', uf: 'BA' },
			{ name: 'Rodelas', name_order: 'Rodelas', uf: 'BA' },
			{ name: 'Ruy Barbosa', name_order: 'Ruy Barbosa', uf: 'BA' },
			{ name: 'Salinas da Margarida', name_order: 'Salinas da Margarida', uf: 'BA' },
			{ name: 'Salvador', name_order: 'Salvador', uf: 'BA' },
			{ name: 'Santa Bárbara', name_order: 'Santa Barbara', uf: 'BA' },
			{ name: 'Santa Brígida', name_order: 'Santa Brigida', uf: 'BA' },
			{ name: 'Santa Cruz Cabrália', name_order: 'Santa Cruz Cabralia', uf: 'BA' },
			{ name: 'Santa Cruz da Vitória', name_order: 'Santa Cruz da Vitoria', uf: 'BA' },
			{ name: 'Santa Inês', name_order: 'Santa Ines', uf: 'BA' },
			{ name: 'Santaluz', name_order: 'Santaluz', uf: 'BA' },
			{ name: 'Santa Luzia', name_order: 'Santa Luzia', uf: 'BA' },
			{ name: 'Santa Maria da Vitória', name_order: 'Santa Maria da Vitoria', uf: 'BA' },
			{ name: 'Santana', name_order: 'Santana', uf: 'BA' },
			{ name: 'Santanópolis', name_order: 'Santanopolis', uf: 'BA' },
			{ name: 'Santa Rita de Cássia', name_order: 'Santa Rita de Cassia', uf: 'BA' },
			{ name: 'Santa Teresinha', name_order: 'Santa Teresinha', uf: 'BA' },
			{ name: 'Santo Amaro', name_order: 'Santo Amaro', uf: 'BA' },
			{ name: 'Santo Antônio de Jesus', name_order: 'Santo Antonio de Jesus', uf: 'BA' },
			{ name: 'Santo Estêvão', name_order: 'Santo Estevao', uf: 'BA' },
			{ name: 'São Desidério', name_order: 'Sao Desiderio', uf: 'BA' },
			{ name: 'São Domingos', name_order: 'Sao Domingos', uf: 'BA' },
			{ name: 'São Félix', name_order: 'Sao Felix', uf: 'BA' },
			{ name: 'São Félix do Coribe', name_order: 'Sao Felix do Coribe', uf: 'BA' },
			{ name: 'São Felipe', name_order: 'Sao Felipe', uf: 'BA' },
			{ name: 'São Francisco do Conde', name_order: 'Sao Francisco do Conde', uf: 'BA' },
			{ name: 'São Gabriel', name_order: 'Sao Gabriel', uf: 'BA' },
			{ name: 'São Gonçalo Dos Campos', name_order: 'Sao Goncalo Dos Campos', uf: 'BA' },
			{ name: 'São José da Vitória', name_order: 'Sao Jose da Vitoria', uf: 'BA' },
			{ name: 'São José do Jacuípe', name_order: 'Sao Jose do Jacuipe', uf: 'BA' },
			{ name: 'São Miguel Das Matas', name_order: 'Sao Miguel Das Matas', uf: 'BA' },
			{ name: 'São Sebastião do Passé', name_order: 'Sao Sebastiao do Passe', uf: 'BA' },
			{ name: 'Sapeaçu', name_order: 'Sapeacu', uf: 'BA' },
			{ name: 'Sátiro Dias', name_order: 'Satiro Dias', uf: 'BA' },
			{ name: 'Saubara', name_order: 'Saubara', uf: 'BA' },
			{ name: 'Saúde', name_order: 'Saude', uf: 'BA' },
			{ name: 'Seabra', name_order: 'Seabra', uf: 'BA' },
			{ name: 'Sebastião Laranjeiras', name_order: 'Sebastiao Laranjeiras', uf: 'BA' },
			{ name: 'Senhor do Bonfim', name_order: 'Senhor do Bonfim', uf: 'BA' },
			{ name: 'Serra do Ramalho', name_order: 'Serra do Ramalho', uf: 'BA' },
			{ name: 'Sento sé', name_order: 'Sento se', uf: 'BA' },
			{ name: 'Serra Dourada', name_order: 'Serra Dourada', uf: 'BA' },
			{ name: 'Serra Preta', name_order: 'Serra Preta', uf: 'BA' },
			{ name: 'Serrinha', name_order: 'Serrinha', uf: 'BA' },
			{ name: 'Serrolândia', name_order: 'Serrolandia', uf: 'BA' },
			{ name: 'Simões Filho', name_order: 'Simoes Filho', uf: 'BA' },
			{ name: 'Sítio do Mato', name_order: 'Sitio do Mato', uf: 'BA' },
			{ name: 'Sítio do Quinto', name_order: 'Sitio do Quinto', uf: 'BA' },
			{ name: 'Sobradinho', name_order: 'Sobradinho', uf: 'BA' },
			{ name: 'Souto Soares', name_order: 'Souto Soares', uf: 'BA' },
			{ name: 'Tabocas do Brejo Velho', name_order: 'Tabocas do Brejo Velho', uf: 'BA' },
			{ name: 'Tanhaçu', name_order: 'Tanhacu', uf: 'BA' },
			{ name: 'Tanque Novo', name_order: 'Tanque Novo', uf: 'BA' },
			{ name: 'Tanquinho', name_order: 'Tanquinho', uf: 'BA' },
			{ name: 'Taperoá', name_order: 'Taperoa', uf: 'BA' },
			{ name: 'Tapiramutá', name_order: 'Tapiramuta', uf: 'BA' },
			{ name: 'Teixeira de Freitas', name_order: 'Teixeira de Freitas', uf: 'BA' },
			{ name: 'Teodoro Sampaio', name_order: 'Teodoro Sampaio', uf: 'BA' },
			{ name: 'Teofilândia', name_order: 'Teofilandia', uf: 'BA' },
			{ name: 'Teolândia', name_order: 'Teolandia', uf: 'BA' },
			{ name: 'Terra Nova', name_order: 'Terra Nova', uf: 'BA' },
			{ name: 'Tremedal', name_order: 'Tremedal', uf: 'BA' },
			{ name: 'Tucano', name_order: 'Tucano', uf: 'BA' },
			{ name: 'Uauá', name_order: 'Uaua', uf: 'BA' },
			{ name: 'Ubaíra', name_order: 'Ubaira', uf: 'BA' },
			{ name: 'Ubaitaba', name_order: 'Ubaitaba', uf: 'BA' },
			{ name: 'Ubatã', name_order: 'Ubata', uf: 'BA' },
			{ name: 'Uibaí', name_order: 'Uibai', uf: 'BA' },
			{ name: 'Umburanas', name_order: 'Umburanas', uf: 'BA' },
			{ name: 'Una', name_order: 'Una', uf: 'BA' },
			{ name: 'Urandi', name_order: 'Urandi', uf: 'BA' },
			{ name: 'Uruçuca', name_order: 'Urucuca', uf: 'BA' },
			{ name: 'Utinga', name_order: 'Utinga', uf: 'BA' },
			{ name: 'Valença', name_order: 'Valenca', uf: 'BA' },
			{ name: 'Valente', name_order: 'Valente', uf: 'BA' },
			{ name: 'Várzea da Roça', name_order: 'Varzea da Roca', uf: 'BA' },
			{ name: 'Várzea do Poço', name_order: 'Varzea do Poco', uf: 'BA' },
			{ name: 'Várzea Nova', name_order: 'Varzea Nova', uf: 'BA' },
			{ name: 'Varzedo', name_order: 'Varzedo', uf: 'BA' },
			{ name: 'Vera Cruz', name_order: 'Vera Cruz', uf: 'BA' },
			{ name: 'Vereda', name_order: 'Vereda', uf: 'BA' },
			{ name: 'Vitória da Conquista', name_order: 'Vitoria da Conquista', uf: 'BA' },
			{ name: 'Wagner', name_order: 'Wagner', uf: 'BA' },
			{ name: 'Wanderley', name_order: 'Wanderley', uf: 'BA' },
			{ name: 'Wenceslau Guimarães', name_order: 'Wenceslau Guimaraes', uf: 'BA' },
			{ name: 'Xique-xique', name_order: 'Xiquexique', uf: 'BA' },
	]);
};
