exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Hulha Negra', name_order: 'Hulha Negra', uf: 'RS' },
			{ name: 'Humaitá', name_order: 'Humaita', uf: 'RS' },
			{ name: 'Ibarama', name_order: 'Ibarama', uf: 'RS' },
			{ name: 'Ibiaçá', name_order: 'Ibiaca', uf: 'RS' },
			{ name: 'Ibiraiaras', name_order: 'Ibiraiaras', uf: 'RS' },
			{ name: 'Ibirapuitã', name_order: 'Ibirapuita', uf: 'RS' },
			{ name: 'Ibirubá', name_order: 'Ibiruba', uf: 'RS' },
			{ name: 'Igrejinha', name_order: 'Igrejinha', uf: 'RS' },
			{ name: 'Ijuí', name_order: 'Ijui', uf: 'RS' },
			{ name: 'Ilópolis', name_order: 'Ilopolis', uf: 'RS' },
			{ name: 'Imbé', name_order: 'Imbe', uf: 'RS' },
			{ name: 'Imigrante', name_order: 'Imigrante', uf: 'RS' },
			{ name: 'Independência', name_order: 'Independencia', uf: 'RS' },
			{ name: 'Inhacorá', name_order: 'Inhacora', uf: 'RS' },
			{ name: 'Ipê', name_order: 'Ipe', uf: 'RS' },
			{ name: 'Ipiranga do Sul', name_order: 'Ipiranga do Sul', uf: 'RS' },
			{ name: 'Iraí', name_order: 'Irai', uf: 'RS' },
			{ name: 'Itaara', name_order: 'Itaara', uf: 'RS' },
			{ name: 'Itacurubi', name_order: 'Itacurubi', uf: 'RS' },
			{ name: 'Itapuca', name_order: 'Itapuca', uf: 'RS' },
			{ name: 'Itaqui', name_order: 'Itaqui', uf: 'RS' },
			{ name: 'Itati', name_order: 'Itati', uf: 'RS' },
			{ name: 'Itatiba do Sul', name_order: 'Itatiba do Sul', uf: 'RS' },
			{ name: 'Ivorá', name_order: 'Ivora', uf: 'RS' },
			{ name: 'Ivoti', name_order: 'Ivoti', uf: 'RS' },
			{ name: 'Jaboticaba', name_order: 'Jaboticaba', uf: 'RS' },
			{ name: 'Jacuizinho', name_order: 'Jacuizinho', uf: 'RS' },
			{ name: 'Jacutinga', name_order: 'Jacutinga', uf: 'RS' },
			{ name: 'Jaguarão', name_order: 'Jaguarao', uf: 'RS' },
			{ name: 'Jaguari', name_order: 'Jaguari', uf: 'RS' },
			{ name: 'Jaquirana', name_order: 'Jaquirana', uf: 'RS' },
			{ name: 'Jari', name_order: 'Jari', uf: 'RS' },
			{ name: 'Jóia', name_order: 'Joia', uf: 'RS' },
			{ name: 'Júlio de Castilhos', name_order: 'Julio de Castilhos', uf: 'RS' },
			{ name: 'Lagoa Bonita do Sul', name_order: 'Lagoa Bonita do Sul', uf: 'RS' },
			{ name: 'Lagoão', name_order: 'Lagoao', uf: 'RS' },
			{ name: 'Lagoa Dos Três Cantos', name_order: 'Lagoa Dos Tres Cantos', uf: 'RS' },
			{ name: 'Lagoa Vermelha', name_order: 'Lagoa Vermelha', uf: 'RS' },
			{ name: 'Lajeado', name_order: 'Lajeado', uf: 'RS' },
			{ name: 'Lajeado do Bugre', name_order: 'Lajeado do Bugre', uf: 'RS' },
			{ name: 'Lavras do Sul', name_order: 'Lavras do Sul', uf: 'RS' },
			{ name: 'Liberato Salzano', name_order: 'Liberato Salzano', uf: 'RS' },
			{ name: 'Lindolfo Collor', name_order: 'Lindolfo Collor', uf: 'RS' },
			{ name: 'Linha Nova', name_order: 'Linha Nova', uf: 'RS' },
			{ name: 'Machadinho', name_order: 'Machadinho', uf: 'RS' },
			{ name: 'Maçambara', name_order: 'Macambara', uf: 'RS' },
			{ name: 'Mampituba', name_order: 'Mampituba', uf: 'RS' },
			{ name: 'Manoel Viana', name_order: 'Manoel Viana', uf: 'RS' },
			{ name: 'Maquiné', name_order: 'Maquine', uf: 'RS' },
			{ name: 'Maratá', name_order: 'Marata', uf: 'RS' },
			{ name: 'Marau', name_order: 'Marau', uf: 'RS' },
			{ name: 'Marcelino Ramos', name_order: 'Marcelino Ramos', uf: 'RS' },
			{ name: 'Mariana Pimentel', name_order: 'Mariana Pimentel', uf: 'RS' },
			{ name: 'Mariano Moro', name_order: 'Mariano Moro', uf: 'RS' },
			{ name: 'Marques de Souza', name_order: 'Marques de Souza', uf: 'RS' },
			{ name: 'Mata', name_order: 'Mata', uf: 'RS' },
			{ name: 'Mato Castelhano', name_order: 'Mato Castelhano', uf: 'RS' },
			{ name: 'Mato Leitão', name_order: 'Mato Leitao', uf: 'RS' },
			{ name: 'Mato Queimado', name_order: 'Mato Queimado', uf: 'RS' },
			{ name: 'Maximiliano de Almeida', name_order: 'Maximiliano de Almeida', uf: 'RS' },
			{ name: 'Minas do Leão', name_order: 'Minas do Leao', uf: 'RS' },
			{ name: 'Miraguaí', name_order: 'Miraguai', uf: 'RS' },
			{ name: 'Montauri', name_order: 'Montauri', uf: 'RS' },
			{ name: 'Monte Alegre Dos Campos', name_order: 'Monte Alegre Dos Campos', uf: 'RS' },
			{ name: 'Monte Belo do Sul', name_order: 'Monte Belo do Sul', uf: 'RS' },
			{ name: 'Montenegro', name_order: 'Montenegro', uf: 'RS' },
			{ name: 'Mormaço', name_order: 'Mormaco', uf: 'RS' },
			{ name: 'Morrinhos do Sul', name_order: 'Morrinhos do Sul', uf: 'RS' },
			{ name: 'Morro Redondo', name_order: 'Morro Redondo', uf: 'RS' },
			{ name: 'Morro Reuter', name_order: 'Morro Reuter', uf: 'RS' },
			{ name: 'Mostardas', name_order: 'Mostardas', uf: 'RS' },
			{ name: 'Muçum', name_order: 'Mucum', uf: 'RS' },
			{ name: 'Muitos Capões', name_order: 'Muitos Capoes', uf: 'RS' },
			{ name: 'Muliterno', name_order: 'Muliterno', uf: 'RS' },
			{ name: 'Não-me-toque', name_order: 'Naometoque', uf: 'RS' },
			{ name: 'Nicolau Vergueiro', name_order: 'Nicolau Vergueiro', uf: 'RS' },
			{ name: 'Nonoai', name_order: 'Nonoai', uf: 'RS' },
			{ name: 'Nova Alvorada', name_order: 'Nova Alvorada', uf: 'RS' },
			{ name: 'Nova Araçá', name_order: 'Nova Araca', uf: 'RS' },
			{ name: 'Nova Bassano', name_order: 'Nova Bassano', uf: 'RS' },
			{ name: 'Nova Boa Vista', name_order: 'Nova Boa Vista', uf: 'RS' },
			{ name: 'Nova Bréscia', name_order: 'Nova Brescia', uf: 'RS' },
			{ name: 'Nova Candelária', name_order: 'Nova Candelaria', uf: 'RS' },
			{ name: 'Nova Esperança do Sul', name_order: 'Nova Esperanca do Sul', uf: 'RS' },
			{ name: 'Nova Hartz', name_order: 'Nova Hartz', uf: 'RS' },
			{ name: 'Nova Pádua', name_order: 'Nova Padua', uf: 'RS' },
			{ name: 'Nova Palma', name_order: 'Nova Palma', uf: 'RS' },
			{ name: 'Nova Petrópolis', name_order: 'Nova Petropolis', uf: 'RS' },
			{ name: 'Nova Prata', name_order: 'Nova Prata', uf: 'RS' },
			{ name: 'Nova Ramada', name_order: 'Nova Ramada', uf: 'RS' },
			{ name: 'Nova Roma do Sul', name_order: 'Nova Roma do Sul', uf: 'RS' },
			{ name: 'Nova Santa Rita', name_order: 'Nova Santa Rita', uf: 'RS' },
			{ name: 'Novo Cabrais', name_order: 'Novo Cabrais', uf: 'RS' },
			{ name: 'Novo Hamburgo', name_order: 'Novo Hamburgo', uf: 'RS' },
			{ name: 'Novo Machado', name_order: 'Novo Machado', uf: 'RS' },
			{ name: 'Novo Tiradentes', name_order: 'Novo Tiradentes', uf: 'RS' },
			{ name: 'Novo Xingu', name_order: 'Novo Xingu', uf: 'RS' },
			{ name: 'Novo Barreiro', name_order: 'Novo Barreiro', uf: 'RS' },
			{ name: 'Osório', name_order: 'Osorio', uf: 'RS' },
			{ name: 'Paim Filho', name_order: 'Paim Filho', uf: 'RS' },
			{ name: 'Palmares do Sul', name_order: 'Palmares do Sul', uf: 'RS' },
			{ name: 'Palmeira Das Missões', name_order: 'Palmeira Das Missoes', uf: 'RS' },
			{ name: 'Palmitinho', name_order: 'Palmitinho', uf: 'RS' },
			{ name: 'Panambi', name_order: 'Panambi', uf: 'RS' },
			{ name: 'Pantano Grande', name_order: 'Pantano Grande', uf: 'RS' },
			{ name: 'Paraí', name_order: 'Parai', uf: 'RS' },
			{ name: 'Paraíso do Sul', name_order: 'Paraiso do Sul', uf: 'RS' },
			{ name: 'Pareci Novo', name_order: 'Pareci Novo', uf: 'RS' },
			{ name: 'Parobé', name_order: 'Parobe', uf: 'RS' },
			{ name: 'Passa Sete', name_order: 'Passa Sete', uf: 'RS' },
			{ name: 'Passo do Sobrado', name_order: 'Passo do Sobrado', uf: 'RS' },
			{ name: 'Passo Fundo', name_order: 'Passo Fundo', uf: 'RS' },
			{ name: 'Paulo Bento', name_order: 'Paulo Bento', uf: 'RS' },
			{ name: 'Paverama', name_order: 'Paverama', uf: 'RS' },
			{ name: 'Pedras Altas', name_order: 'Pedras Altas', uf: 'RS' },
			{ name: 'Pedro Osório', name_order: 'Pedro Osorio', uf: 'RS' },
			{ name: 'Pejuçara', name_order: 'Pejucara', uf: 'RS' },
			{ name: 'Pelotas', name_order: 'Pelotas', uf: 'RS' },
			{ name: 'Picada Café', name_order: 'Picada Cafe', uf: 'RS' },
			{ name: 'Pinhal', name_order: 'Pinhal', uf: 'RS' },
			{ name: 'Pinhal da Serra', name_order: 'Pinhal da Serra', uf: 'RS' },
			{ name: 'Pinhal Grande', name_order: 'Pinhal Grande', uf: 'RS' },
			{ name: 'Pinheirinho do Vale', name_order: 'Pinheirinho do Vale', uf: 'RS' },
			{ name: 'Pinheiro Machado', name_order: 'Pinheiro Machado', uf: 'RS' },
			{ name: 'Pinto Bandeira', name_order: 'Pinto Bandeira', uf: 'RS' },
			{ name: 'Pirapó', name_order: 'Pirapo', uf: 'RS' },
			{ name: 'Piratini', name_order: 'Piratini', uf: 'RS' },
			{ name: 'Planalto', name_order: 'Planalto', uf: 'RS' },
			{ name: 'Poço Das Antas', name_order: 'Poco Das Antas', uf: 'RS' },
			{ name: 'Pontão', name_order: 'Pontao', uf: 'RS' },
			{ name: 'Ponte Preta', name_order: 'Ponte Preta', uf: 'RS' },
			{ name: 'Portão', name_order: 'Portao', uf: 'RS' },
			{ name: 'Porto Alegre', name_order: 'Porto Alegre', uf: 'RS' },
			{ name: 'Porto Lucena', name_order: 'Porto Lucena', uf: 'RS' },
			{ name: 'Porto Mauá', name_order: 'Porto Maua', uf: 'RS' },
			{ name: 'Porto Vera Cruz', name_order: 'Porto Vera Cruz', uf: 'RS' },
			{ name: 'Porto Xavier', name_order: 'Porto Xavier', uf: 'RS' },
			{ name: 'Pouso Novo', name_order: 'Pouso Novo', uf: 'RS' },
			{ name: 'Presidente Lucena', name_order: 'Presidente Lucena', uf: 'RS' },
			{ name: 'Progresso', name_order: 'Progresso', uf: 'RS' },
			{ name: 'Protásio Alves', name_order: 'Protasio Alves', uf: 'RS' },
			{ name: 'Putinga', name_order: 'Putinga', uf: 'RS' },
			{ name: 'Quaraí', name_order: 'Quarai', uf: 'RS' },
			{ name: 'Quatro Irmãos', name_order: 'Quatro Irmaos', uf: 'RS' },
			{ name: 'Quevedos', name_order: 'Quevedos', uf: 'RS' },
			{ name: 'Quinze de Novembro', name_order: 'Quinze de Novembro', uf: 'RS' },
			{ name: 'Redentora', name_order: 'Redentora', uf: 'RS' },
			{ name: 'Relvado', name_order: 'Relvado', uf: 'RS' },
			{ name: 'Restinga Seca', name_order: 'Restinga Seca', uf: 'RS' },
			{ name: 'Rio Dos Índios', name_order: 'Rio Dos Indios', uf: 'RS' },
			{ name: 'Rio Grande', name_order: 'Rio Grande', uf: 'RS' },
			{ name: 'Rio Pardo', name_order: 'Rio Pardo', uf: 'RS' },
			{ name: 'Riozinho', name_order: 'Riozinho', uf: 'RS' },
			{ name: 'Roca Sales', name_order: 'Roca Sales', uf: 'RS' },
			{ name: 'Rodeio Bonito', name_order: 'Rodeio Bonito', uf: 'RS' },
			{ name: 'Rolador', name_order: 'Rolador', uf: 'RS' },
			{ name: 'Rolante', name_order: 'Rolante', uf: 'RS' },
			{ name: 'Ronda Alta', name_order: 'Ronda Alta', uf: 'RS' },
			{ name: 'Rondinha', name_order: 'Rondinha', uf: 'RS' },
			{ name: 'Roque Gonzales', name_order: 'Roque Gonzales', uf: 'RS' },
			{ name: 'Rosário do Sul', name_order: 'Rosario do Sul', uf: 'RS' },
			{ name: 'Sagrada Família', name_order: 'Sagrada Familia', uf: 'RS' },
			{ name: 'Saldanha Marinho', name_order: 'Saldanha Marinho', uf: 'RS' },
			{ name: 'Salto do Jacuí', name_order: 'Salto do Jacui', uf: 'RS' },
			{ name: 'Salvador Das Missões', name_order: 'Salvador Das Missoes', uf: 'RS' },
			{ name: 'Salvador do Sul', name_order: 'Salvador do Sul', uf: 'RS' },
			{ name: 'Sananduva', name_order: 'Sananduva', uf: 'RS' },
			{ name: 'Santa Bárbara do Sul', name_order: 'Santa Barbara do Sul', uf: 'RS' },
			{ name: 'Santa Cecília do Sul', name_order: 'Santa Cecilia do Sul', uf: 'RS' },
			{ name: 'Santa Clara do Sul', name_order: 'Santa Clara do Sul', uf: 'RS' },
			{ name: 'Santa Cruz do Sul', name_order: 'Santa Cruz do Sul', uf: 'RS' },
			{ name: 'Santa Maria', name_order: 'Santa Maria', uf: 'RS' },
			{ name: 'Santa Maria do Herval', name_order: 'Santa Maria do Herval', uf: 'RS' },
			{ name: 'Santa Margarida do Sul', name_order: 'Santa Margarida do Sul', uf: 'RS' },
			{ name: 'Santana da Boa Vista', name_order: 'Santana da Boa Vista', uf: 'RS' },
			{ name: 'Santana do Livramento', name_order: 'Santana do Livramento', uf: 'RS' },
			{ name: 'Santa Rosa', name_order: 'Santa Rosa', uf: 'RS' },
			{ name: 'Santa Tereza', name_order: 'Santa Tereza', uf: 'RS' },
			{ name: 'Santa Vitória do Palmar', name_order: 'Santa Vitoria do Palmar', uf: 'RS' },
			{ name: 'Santiago', name_order: 'Santiago', uf: 'RS' },
			{ name: 'Santo Ângelo', name_order: 'Santo Angelo', uf: 'RS' },
			{ name: 'Santo Antônio do Palma', name_order: 'Santo Antonio do Palma', uf: 'RS' },
			{ name: 'Santo Antônio da Patrulha', name_order: 'Santo Antonio da Patrulha', uf: 'RS' },
			{ name: 'Santo Antônio Das Missões', name_order: 'Santo Antonio Das Missoes', uf: 'RS' },
			{ name: 'Santo Antônio do Planalto', name_order: 'Santo Antonio do Planalto', uf: 'RS' },
			{ name: 'Santo Augusto', name_order: 'Santo Augusto', uf: 'RS' },
			{ name: 'Santo Cristo', name_order: 'Santo Cristo', uf: 'RS' },
			{ name: 'Santo Expedito do Sul', name_order: 'Santo Expedito do Sul', uf: 'RS' },
			{ name: 'São Borja', name_order: 'Sao Borja', uf: 'RS' },
			{ name: 'São Domingos do Sul', name_order: 'Sao Domingos do Sul', uf: 'RS' },
			{ name: 'São Francisco de Assis', name_order: 'Sao Francisco de Assis', uf: 'RS' },
			{ name: 'São Francisco de Paula', name_order: 'Sao Francisco de Paula', uf: 'RS' },
			{ name: 'São Gabriel', name_order: 'Sao Gabriel', uf: 'RS' },
			{ name: 'São Jerônimo', name_order: 'Sao Jeronimo', uf: 'RS' },
			{ name: 'São João da Urtiga', name_order: 'Sao Joao da Urtiga', uf: 'RS' },
			{ name: 'São João do Polêsine', name_order: 'Sao Joao do Polesine', uf: 'RS' },
			{ name: 'São Jorge', name_order: 'Sao Jorge', uf: 'RS' },
			{ name: 'São José Das Missões', name_order: 'Sao Jose Das Missoes', uf: 'RS' },
			{ name: 'São José do Herval', name_order: 'Sao Jose do Herval', uf: 'RS' },
			{ name: 'São José do Hortêncio', name_order: 'Sao Jose do Hortencio', uf: 'RS' },
			{ name: 'São José do Inhacorá', name_order: 'Sao Jose do Inhacora', uf: 'RS' },
			{ name: 'São José do Norte', name_order: 'Sao Jose do Norte', uf: 'RS' },
			{ name: 'São José do Ouro', name_order: 'Sao Jose do Ouro', uf: 'RS' },
			{ name: 'São Jos�� do Sul', name_order: 'Sao Jos do Sul', uf: 'RS' },
			{ name: 'São José Dos Ausentes', name_order: 'Sao Jose Dos Ausentes', uf: 'RS' },
			{ name: 'São Leopoldo', name_order: 'Sao Leopoldo', uf: 'RS' },
			{ name: 'São Lourenço do Sul', name_order: 'Sao Lourenco do Sul', uf: 'RS' },
			{ name: 'São Luiz Gonzaga', name_order: 'Sao Luiz Gonzaga', uf: 'RS' },
			{ name: 'São Marcos', name_order: 'Sao Marcos', uf: 'RS' },
			{ name: 'São Martinho', name_order: 'Sao Martinho', uf: 'RS' },
			{ name: 'São Martinho da Serra', name_order: 'Sao Martinho da Serra', uf: 'RS' },
			{ name: 'São Miguel Das Missões', name_order: 'Sao Miguel Das Missoes', uf: 'RS' },
			{ name: 'São Nicolau', name_order: 'Sao Nicolau', uf: 'RS' },
			{ name: 'São Paulo Das Missões', name_order: 'Sao Paulo Das Missoes', uf: 'RS' },
			{ name: 'São Pedro da Serra', name_order: 'Sao Pedro da Serra', uf: 'RS' },
			{ name: 'São Pedro Das Missões', name_order: 'Sao Pedro Das Missoes', uf: 'RS' },
			{ name: 'São Pedro do Butiá', name_order: 'Sao Pedro do Butia', uf: 'RS' },
			{ name: 'São Pedro do Sul', name_order: 'Sao Pedro do Sul', uf: 'RS' },
			{ name: 'São Sebastião do Caí', name_order: 'Sao Sebastiao do Cai', uf: 'RS' },
			{ name: 'São Sepé', name_order: 'Sao Sepe', uf: 'RS' },
			{ name: 'São Valentim', name_order: 'Sao Valentim', uf: 'RS' },
			{ name: 'São Valentim do Sul', name_order: 'Sao Valentim do Sul', uf: 'RS' },
			{ name: 'São Valério do Sul', name_order: 'Sao Valerio do Sul', uf: 'RS' },
			{ name: 'São Vendelino', name_order: 'Sao Vendelino', uf: 'RS' },
			{ name: 'São Vicente do Sul', name_order: 'Sao Vicente do Sul', uf: 'RS' },
			{ name: 'Sapiranga', name_order: 'Sapiranga', uf: 'RS' },
			{ name: 'Sapucaia do Sul', name_order: 'Sapucaia do Sul', uf: 'RS' },
			{ name: 'Sarandi', name_order: 'Sarandi', uf: 'RS' },
			{ name: 'Seberi', name_order: 'Seberi', uf: 'RS' },
			{ name: 'Sede Nova', name_order: 'Sede Nova', uf: 'RS' },
			{ name: 'Segredo', name_order: 'Segredo', uf: 'RS' },
			{ name: 'Selbach', name_order: 'Selbach', uf: 'RS' },
			{ name: 'Senador Salgado Filho', name_order: 'Senador Salgado Filho', uf: 'RS' },
			{ name: 'Sentinela do Sul', name_order: 'Sentinela do Sul', uf: 'RS' },
			{ name: 'Serafina Corrêa', name_order: 'Serafina Correa', uf: 'RS' },
			{ name: 'Sério', name_order: 'Serio', uf: 'RS' },
			{ name: 'Sertão', name_order: 'Sertao', uf: 'RS' },
			{ name: 'Sertão Santana', name_order: 'Sertao Santana', uf: 'RS' },
			{ name: 'Sete de Setembro', name_order: 'Sete de Setembro', uf: 'RS' },
			{ name: 'Severiano de Almeida', name_order: 'Severiano de Almeida', uf: 'RS' },
			{ name: 'Silveira Martins', name_order: 'Silveira Martins', uf: 'RS' },
			{ name: 'Sinimbu', name_order: 'Sinimbu', uf: 'RS' },
			{ name: 'Sobradinho', name_order: 'Sobradinho', uf: 'RS' },
			{ name: 'Soledade', name_order: 'Soledade', uf: 'RS' },
			{ name: 'Tabaí', name_order: 'Tabai', uf: 'RS' },
			{ name: 'Tapejara', name_order: 'Tapejara', uf: 'RS' },
			{ name: 'Tapera', name_order: 'Tapera', uf: 'RS' },
			{ name: 'Tapes', name_order: 'Tapes', uf: 'RS' },
			{ name: 'Taquara', name_order: 'Taquara', uf: 'RS' },
			{ name: 'Taquari', name_order: 'Taquari', uf: 'RS' },
			{ name: 'Taquaruçu do Sul', name_order: 'Taquarucu do Sul', uf: 'RS' },
			{ name: 'Tavares', name_order: 'Tavares', uf: 'RS' },
			{ name: 'Tenente Portela', name_order: 'Tenente Portela', uf: 'RS' },
			{ name: 'Terra de Areia', name_order: 'Terra de Areia', uf: 'RS' },
			{ name: 'Teutônia', name_order: 'Teutonia', uf: 'RS' },
			{ name: 'Tio Hugo', name_order: 'Tio Hugo', uf: 'RS' },
			{ name: 'Tiradentes do Sul', name_order: 'Tiradentes do Sul', uf: 'RS' },
			{ name: 'Toropi', name_order: 'Toropi', uf: 'RS' },
			{ name: 'Torres', name_order: 'Torres', uf: 'RS' },
			{ name: 'Tramandaí', name_order: 'Tramandai', uf: 'RS' },
			{ name: 'Travesseiro', name_order: 'Travesseiro', uf: 'RS' },
			{ name: 'Três Arroios', name_order: 'Tres Arroios', uf: 'RS' },
			{ name: 'Três Cachoeiras', name_order: 'Tres Cachoeiras', uf: 'RS' },
			{ name: 'Três Coroas', name_order: 'Tres Coroas', uf: 'RS' },
			{ name: 'Três de Maio', name_order: 'Tres de Maio', uf: 'RS' },
			{ name: 'Três Forquilhas', name_order: 'Tres Forquilhas', uf: 'RS' },
			{ name: 'Três Palmeiras', name_order: 'Tres Palmeiras', uf: 'RS' },
			{ name: 'Três Passos', name_order: 'Tres Passos', uf: 'RS' },
			{ name: 'Trindade do Sul', name_order: 'Trindade do Sul', uf: 'RS' },
			{ name: 'Triunfo', name_order: 'Triunfo', uf: 'RS' },
			{ name: 'Tucunduva', name_order: 'Tucunduva', uf: 'RS' },
			{ name: 'Tunas', name_order: 'Tunas', uf: 'RS' },
			{ name: 'Tupanci do Sul', name_order: 'Tupanci do Sul', uf: 'RS' },
			{ name: 'Tupanciretã', name_order: 'Tupancireta', uf: 'RS' },
			{ name: 'Tupandi', name_order: 'Tupandi', uf: 'RS' },
			{ name: 'Tuparendi', name_order: 'Tuparendi', uf: 'RS' },
			{ name: 'Turuçu', name_order: 'Turucu', uf: 'RS' },
			{ name: 'Ubiretama', name_order: 'Ubiretama', uf: 'RS' },
			{ name: 'União da Serra', name_order: 'Uniao da Serra', uf: 'RS' },
			{ name: 'Unistalda', name_order: 'Unistalda', uf: 'RS' },
			{ name: 'Uruguaiana', name_order: 'Uruguaiana', uf: 'RS' },
			{ name: 'Vacaria', name_order: 'Vacaria', uf: 'RS' },
			{ name: 'Vale Verde', name_order: 'Vale Verde', uf: 'RS' },
			{ name: 'Vale do Sol', name_order: 'Vale do Sol', uf: 'RS' },
			{ name: 'Vale Real', name_order: 'Vale Real', uf: 'RS' },
			{ name: 'Vanini', name_order: 'Vanini', uf: 'RS' },
			{ name: 'Venâncio Aires', name_order: 'Venancio Aires', uf: 'RS' },
			{ name: 'Vera Cruz', name_order: 'Vera Cruz', uf: 'RS' },
			{ name: 'Veranópolis', name_order: 'Veranopolis', uf: 'RS' },
			{ name: 'Vespasiano Correa', name_order: 'Vespasiano Correa', uf: 'RS' },
			{ name: 'Viadutos', name_order: 'Viadutos', uf: 'RS' },
			{ name: 'Viamão', name_order: 'Viamao', uf: 'RS' },
			{ name: 'Vicente Dutra', name_order: 'Vicente Dutra', uf: 'RS' },
			{ name: 'Victor Graeff', name_order: 'Victor Graeff', uf: 'RS' },
			{ name: 'Vila Flores', name_order: 'Vila Flores', uf: 'RS' },
			{ name: 'Vila Lângaro', name_order: 'Vila Langaro', uf: 'RS' },
			{ name: 'Vila Maria', name_order: 'Vila Maria', uf: 'RS' },
			{ name: 'Vila Nova do Sul', name_order: 'Vila Nova do Sul', uf: 'RS' },
			{ name: 'Vista Alegre', name_order: 'Vista Alegre', uf: 'RS' },
			{ name: 'Vista Alegre do Prata', name_order: 'Vista Alegre do Prata', uf: 'RS' },
	]);
};
