exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Calçado', name_order: 'Calcado', uf: 'PE' },
			{ name: 'Calumbi', name_order: 'Calumbi', uf: 'PE' },
			{ name: 'Camaragibe', name_order: 'Camaragibe', uf: 'PE' },
			{ name: 'Camocim de São Félix', name_order: 'Camocim de Sao Felix', uf: 'PE' },
			{ name: 'Camutanga', name_order: 'Camutanga', uf: 'PE' },
			{ name: 'Canhotinho', name_order: 'Canhotinho', uf: 'PE' },
			{ name: 'Capoeiras', name_order: 'Capoeiras', uf: 'PE' },
			{ name: 'Carnaíba', name_order: 'Carnaiba', uf: 'PE' },
			{ name: 'Carnaubeira da Penha', name_order: 'Carnaubeira da Penha', uf: 'PE' },
			{ name: 'Carpina', name_order: 'Carpina', uf: 'PE' },
			{ name: 'Caruaru', name_order: 'Caruaru', uf: 'PE' },
			{ name: 'Casinhas', name_order: 'Casinhas', uf: 'PE' },
			{ name: 'Catende', name_order: 'Catende', uf: 'PE' },
			{ name: 'Cedro', name_order: 'Cedro', uf: 'PE' },
			{ name: 'Chã de Alegria', name_order: 'Cha de Alegria', uf: 'PE' },
			{ name: 'Chã Grande', name_order: 'Cha Grande', uf: 'PE' },
			{ name: 'Condado', name_order: 'Condado', uf: 'PE' },
			{ name: 'Correntes', name_order: 'Correntes', uf: 'PE' },
			{ name: 'Cortês', name_order: 'Cortes', uf: 'PE' },
			{ name: 'Cumaru', name_order: 'Cumaru', uf: 'PE' },
			{ name: 'Cupira', name_order: 'Cupira', uf: 'PE' },
			{ name: 'Custódia', name_order: 'Custodia', uf: 'PE' },
			{ name: 'Dormentes', name_order: 'Dormentes', uf: 'PE' },
			{ name: 'Escada', name_order: 'Escada', uf: 'PE' },
			{ name: 'Exu', name_order: 'Exu', uf: 'PE' },
			{ name: 'Feira Nova', name_order: 'Feira Nova', uf: 'PE' },
			{ name: 'Fernando de Noronha', name_order: 'Fernando de Noronha', uf: 'PE' },
			{ name: 'Ferreiros', name_order: 'Ferreiros', uf: 'PE' },
			{ name: 'Flores', name_order: 'Flores', uf: 'PE' },
			{ name: 'Floresta', name_order: 'Floresta', uf: 'PE' },
			{ name: 'Frei Miguelinho', name_order: 'Frei Miguelinho', uf: 'PE' },
			{ name: 'Gameleira', name_order: 'Gameleira', uf: 'PE' },
			{ name: 'Garanhuns', name_order: 'Garanhuns', uf: 'PE' },
			{ name: 'Glória do Goitá', name_order: 'Gloria do Goita', uf: 'PE' },
			{ name: 'Goiana', name_order: 'Goiana', uf: 'PE' },
			{ name: 'Granito', name_order: 'Granito', uf: 'PE' },
			{ name: 'Gravatá', name_order: 'Gravata', uf: 'PE' },
			{ name: 'Iati', name_order: 'Iati', uf: 'PE' },
			{ name: 'Ibimirim', name_order: 'Ibimirim', uf: 'PE' },
			{ name: 'Ibirajuba', name_order: 'Ibirajuba', uf: 'PE' },
			{ name: 'Igarassu', name_order: 'Igarassu', uf: 'PE' },
			{ name: 'Iguaraci', name_order: 'Iguaraci', uf: 'PE' },
			{ name: 'Inajá', name_order: 'Inaja', uf: 'PE' },
			{ name: 'Ingazeira', name_order: 'Ingazeira', uf: 'PE' },
			{ name: 'Ipojuca', name_order: 'Ipojuca', uf: 'PE' },
			{ name: 'Ipubi', name_order: 'Ipubi', uf: 'PE' },
			{ name: 'Itacuruba', name_order: 'Itacuruba', uf: 'PE' },
			{ name: 'Itaíba', name_order: 'Itaiba', uf: 'PE' },
			{ name: 'Ilha de Itamaracá', name_order: 'Ilha de Itamaraca', uf: 'PE' },
			{ name: 'Itambé', name_order: 'Itambe', uf: 'PE' },
			{ name: 'Itapetim', name_order: 'Itapetim', uf: 'PE' },
			{ name: 'Itapissuma', name_order: 'Itapissuma', uf: 'PE' },
			{ name: 'Itaquitinga', name_order: 'Itaquitinga', uf: 'PE' },
			{ name: 'Jaboatão Dos Guararapes', name_order: 'Jaboatao Dos Guararapes', uf: 'PE' },
			{ name: 'Jaqueira', name_order: 'Jaqueira', uf: 'PE' },
			{ name: 'Jataúba', name_order: 'Jatauba', uf: 'PE' },
			{ name: 'Jatobá', name_order: 'Jatoba', uf: 'PE' },
			{ name: 'João Alfredo', name_order: 'Joao Alfredo', uf: 'PE' },
			{ name: 'Joaquim Nabuco', name_order: 'Joaquim Nabuco', uf: 'PE' },
			{ name: 'Jucati', name_order: 'Jucati', uf: 'PE' },
			{ name: 'Jupi', name_order: 'Jupi', uf: 'PE' },
			{ name: 'Jurema', name_order: 'Jurema', uf: 'PE' },
			{ name: 'Lagoa do Carro', name_order: 'Lagoa do Carro', uf: 'PE' },
			{ name: 'Lagoa do Itaenga', name_order: 'Lagoa do Itaenga', uf: 'PE' },
			{ name: 'Lagoa do Ouro', name_order: 'Lagoa do Ouro', uf: 'PE' },
			{ name: 'Lagoa Dos Gatos', name_order: 'Lagoa Dos Gatos', uf: 'PE' },
			{ name: 'Lagoa Grande', name_order: 'Lagoa Grande', uf: 'PE' },
			{ name: 'Lajedo', name_order: 'Lajedo', uf: 'PE' },
			{ name: 'Limoeiro', name_order: 'Limoeiro', uf: 'PE' },
			{ name: 'Macaparana', name_order: 'Macaparana', uf: 'PE' },
			{ name: 'Machados', name_order: 'Machados', uf: 'PE' },
			{ name: 'Manari', name_order: 'Manari', uf: 'PE' },
			{ name: 'Maraial', name_order: 'Maraial', uf: 'PE' },
			{ name: 'Mirandiba', name_order: 'Mirandiba', uf: 'PE' },
			{ name: 'Moreno', name_order: 'Moreno', uf: 'PE' },
			{ name: 'Nazaré da Mata', name_order: 'Nazare da Mata', uf: 'PE' },
			{ name: 'Olinda', name_order: 'Olinda', uf: 'PE' },
			{ name: 'Orobó', name_order: 'Orobo', uf: 'PE' },
			{ name: 'Orocó', name_order: 'Oroco', uf: 'PE' },
			{ name: 'Ouricuri', name_order: 'Ouricuri', uf: 'PE' },
			{ name: 'Palmares', name_order: 'Palmares', uf: 'PE' },
			{ name: 'Palmeirina', name_order: 'Palmeirina', uf: 'PE' },
			{ name: 'Panelas', name_order: 'Panelas', uf: 'PE' },
			{ name: 'Paranatama', name_order: 'Paranatama', uf: 'PE' },
			{ name: 'Parnamirim', name_order: 'Parnamirim', uf: 'PE' },
			{ name: 'Passira', name_order: 'Passira', uf: 'PE' },
			{ name: 'Paudalho', name_order: 'Paudalho', uf: 'PE' },
			{ name: 'Paulista', name_order: 'Paulista', uf: 'PE' },
			{ name: 'Pedra', name_order: 'Pedra', uf: 'PE' },
			{ name: 'Pesqueira', name_order: 'Pesqueira', uf: 'PE' },
			{ name: 'Petrolândia', name_order: 'Petrolandia', uf: 'PE' },
			{ name: 'Petrolina', name_order: 'Petrolina', uf: 'PE' },
			{ name: 'Poção', name_order: 'Pocao', uf: 'PE' },
			{ name: 'Pombos', name_order: 'Pombos', uf: 'PE' },
			{ name: 'Primavera', name_order: 'Primavera', uf: 'PE' },
			{ name: 'Quipapá', name_order: 'Quipapa', uf: 'PE' },
			{ name: 'Quixaba', name_order: 'Quixaba', uf: 'PE' },
			{ name: 'Recife', name_order: 'Recife', uf: 'PE' },
			{ name: 'Riacho Das Almas', name_order: 'Riacho Das Almas', uf: 'PE' },
			{ name: 'Ribeirão', name_order: 'Ribeirao', uf: 'PE' },
			{ name: 'Rio Formoso', name_order: 'Rio Formoso', uf: 'PE' },
			{ name: 'Sairé', name_order: 'Saire', uf: 'PE' },
			{ name: 'Salgadinho', name_order: 'Salgadinho', uf: 'PE' },
			{ name: 'Salgueiro', name_order: 'Salgueiro', uf: 'PE' },
			{ name: 'Saloá', name_order: 'Saloa', uf: 'PE' },
			{ name: 'Sanharó', name_order: 'Sanharo', uf: 'PE' },
			{ name: 'Santa Cruz', name_order: 'Santa Cruz', uf: 'PE' },
			{ name: 'Santa Cruz da Baixa Verde', name_order: 'Santa Cruz da Baixa Verde', uf: 'PE' },
			{ name: 'Santa Cruz do Capibaribe', name_order: 'Santa Cruz do Capibaribe', uf: 'PE' },
			{ name: 'Santa Filomena', name_order: 'Santa Filomena', uf: 'PE' },
			{ name: 'Santa Maria da Boa Vista', name_order: 'Santa Maria da Boa Vista', uf: 'PE' },
			{ name: 'Santa Maria do Cambucá', name_order: 'Santa Maria do Cambuca', uf: 'PE' },
			{ name: 'Santa Terezinha', name_order: 'Santa Terezinha', uf: 'PE' },
			{ name: 'São Benedito do Sul', name_order: 'Sao Benedito do Sul', uf: 'PE' },
			{ name: 'São Bento do Una', name_order: 'Sao Bento do Una', uf: 'PE' },
			{ name: 'São Caitano', name_order: 'Sao Caitano', uf: 'PE' },
			{ name: 'São João', name_order: 'Sao Joao', uf: 'PE' },
			{ name: 'São Joaquim do Monte', name_order: 'Sao Joaquim do Monte', uf: 'PE' },
			{ name: 'São José da Coroa Grande', name_order: 'Sao Jose da Coroa Grande', uf: 'PE' },
			{ name: 'São José do Belmonte', name_order: 'Sao Jose do Belmonte', uf: 'PE' },
			{ name: 'São José do Egito', name_order: 'Sao Jose do Egito', uf: 'PE' },
			{ name: 'São Lourenço da Mata', name_order: 'Sao Lourenco da Mata', uf: 'PE' },
			{ name: 'São Vicente Ferrer', name_order: 'Sao Vicente Ferrer', uf: 'PE' },
			{ name: 'Serra Talhada', name_order: 'Serra Talhada', uf: 'PE' },
			{ name: 'Serrita', name_order: 'Serrita', uf: 'PE' },
			{ name: 'Sertânia', name_order: 'Sertania', uf: 'PE' },
			{ name: 'Sirinhaém', name_order: 'Sirinhaem', uf: 'PE' },
			{ name: 'Moreilândia', name_order: 'Moreilandia', uf: 'PE' },
			{ name: 'Solidão', name_order: 'Solidao', uf: 'PE' },
			{ name: 'Surubim', name_order: 'Surubim', uf: 'PE' },
			{ name: 'Tabira', name_order: 'Tabira', uf: 'PE' },
			{ name: 'Tacaimbó', name_order: 'Tacaimbo', uf: 'PE' },
			{ name: 'Tacaratu', name_order: 'Tacaratu', uf: 'PE' },
			{ name: 'Tamandaré', name_order: 'Tamandare', uf: 'PE' },
			{ name: 'Taquaritinga do Norte', name_order: 'Taquaritinga do Norte', uf: 'PE' },
			{ name: 'Terezinha', name_order: 'Terezinha', uf: 'PE' },
			{ name: 'Terra Nova', name_order: 'Terra Nova', uf: 'PE' },
			{ name: 'Timbaúba', name_order: 'Timbauba', uf: 'PE' },
			{ name: 'Toritama', name_order: 'Toritama', uf: 'PE' },
			{ name: 'Tracunhaém', name_order: 'Tracunhaem', uf: 'PE' },
			{ name: 'Trindade', name_order: 'Trindade', uf: 'PE' },
			{ name: 'Triunfo', name_order: 'Triunfo', uf: 'PE' },
			{ name: 'Tupanatinga', name_order: 'Tupanatinga', uf: 'PE' },
			{ name: 'Tuparetama', name_order: 'Tuparetama', uf: 'PE' },
			{ name: 'Venturosa', name_order: 'Venturosa', uf: 'PE' },
			{ name: 'Verdejante', name_order: 'Verdejante', uf: 'PE' },
			{ name: 'Vertente do Lério', name_order: 'Vertente do Lerio', uf: 'PE' },
			{ name: 'Vertentes', name_order: 'Vertentes', uf: 'PE' },
			{ name: 'Vicência', name_order: 'Vicencia', uf: 'PE' },
			{ name: 'Vitória de Santo Antão', name_order: 'Vitoria de Santo Antao', uf: 'PE' },
			{ name: 'Xexéu', name_order: 'Xexeu', uf: 'PE' },
	]);
};
