exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Acauã', name_order: 'Acaua', uf: 'PI' },
			{ name: 'Agricolândia', name_order: 'Agricolandia', uf: 'PI' },
			{ name: 'Água Branca', name_order: 'Agua Branca', uf: 'PI' },
			{ name: 'Alagoinha do Piauí', name_order: 'Alagoinha do Piaui', uf: 'PI' },
			{ name: 'Alegrete do Piauí', name_order: 'Alegrete do Piaui', uf: 'PI' },
			{ name: 'Alto Longá', name_order: 'Alto Longa', uf: 'PI' },
			{ name: 'Altos', name_order: 'Altos', uf: 'PI' },
			{ name: 'Alvorada do Gurguéia', name_order: 'Alvorada do Gurgueia', uf: 'PI' },
			{ name: 'Amarante', name_order: 'Amarante', uf: 'PI' },
			{ name: 'Angical do Piauí', name_order: 'Angical do Piaui', uf: 'PI' },
			{ name: 'Anísio de Abreu', name_order: 'Anisio de Abreu', uf: 'PI' },
			{ name: 'Antônio Almeida', name_order: 'Antonio Almeida', uf: 'PI' },
			{ name: 'Aroazes', name_order: 'Aroazes', uf: 'PI' },
			{ name: 'Aroeiras do Itaim', name_order: 'Aroeiras do Itaim', uf: 'PI' },
			{ name: 'Arraial', name_order: 'Arraial', uf: 'PI' },
			{ name: 'Assunção do Piauí', name_order: 'Assuncao do Piaui', uf: 'PI' },
			{ name: 'Avelino Lopes', name_order: 'Avelino Lopes', uf: 'PI' },
			{ name: 'Baixa Grande do Ribeiro', name_order: 'Baixa Grande do Ribeiro', uf: 'PI' },
			{ name: 'Barra D´alcântara', name_order: 'Barra Dalcantara', uf: 'PI' },
			{ name: 'Barras', name_order: 'Barras', uf: 'PI' },
			{ name: 'Barreiras do Piauí', name_order: 'Barreiras do Piaui', uf: 'PI' },
			{ name: 'Barro Duro', name_order: 'Barro Duro', uf: 'PI' },
			{ name: 'Batalha', name_order: 'Batalha', uf: 'PI' },
			{ name: 'Bela Vista do Piauí', name_order: 'Bela Vista do Piaui', uf: 'PI' },
			{ name: 'Belém do Piauí', name_order: 'Belem do Piaui', uf: 'PI' },
			{ name: 'Beneditinos', name_order: 'Beneditinos', uf: 'PI' },
			{ name: 'Bertolínia', name_order: 'Bertolinia', uf: 'PI' },
			{ name: 'Betânia do Piauí', name_order: 'Betania do Piaui', uf: 'PI' },
			{ name: 'Boa Hora', name_order: 'Boa Hora', uf: 'PI' },
			{ name: 'Bocaina', name_order: 'Bocaina', uf: 'PI' },
			{ name: 'Bom Jesus', name_order: 'Bom Jesus', uf: 'PI' },
			{ name: 'Bom Princípio do Piauí', name_order: 'Bom Principio do Piaui', uf: 'PI' },
			{ name: 'Bonfim do Piauí', name_order: 'Bonfim do Piaui', uf: 'PI' },
			{ name: 'Boqueirão do Piauí', name_order: 'Boqueirao do Piaui', uf: 'PI' },
			{ name: 'Brasileira', name_order: 'Brasileira', uf: 'PI' },
			{ name: 'Brejo do Piauí', name_order: 'Brejo do Piaui', uf: 'PI' },
			{ name: 'Buriti Dos Lopes', name_order: 'Buriti Dos Lopes', uf: 'PI' },
			{ name: 'Buriti Dos Montes', name_order: 'Buriti Dos Montes', uf: 'PI' },
			{ name: 'Cabeceiras do Piauí', name_order: 'Cabeceiras do Piaui', uf: 'PI' },
			{ name: 'Cajazeiras do Piauí', name_order: 'Cajazeiras do Piaui', uf: 'PI' },
			{ name: 'Cajueiro da Praia', name_order: 'Cajueiro da Praia', uf: 'PI' },
			{ name: 'Caldeirão Grande do Piauí', name_order: 'Caldeirao Grande do Piaui', uf: 'PI' },
			{ name: 'Campinas do Piauí', name_order: 'Campinas do Piaui', uf: 'PI' },
			{ name: 'Campo Alegre do Fidalgo', name_order: 'Campo Alegre do Fidalgo', uf: 'PI' },
			{ name: 'Campo Grande do Piauí', name_order: 'Campo Grande do Piaui', uf: 'PI' },
			{ name: 'Campo Largo do Piauí', name_order: 'Campo Largo do Piaui', uf: 'PI' },
			{ name: 'Campo Maior', name_order: 'Campo Maior', uf: 'PI' },
			{ name: 'Canavieira', name_order: 'Canavieira', uf: 'PI' },
			{ name: 'Canto do Buriti', name_order: 'Canto do Buriti', uf: 'PI' },
			{ name: 'Capitão de Campos', name_order: 'Capitao de Campos', uf: 'PI' },
			{ name: 'Capitão Gervásio Oliveira', name_order: 'Capitao Gervasio Oliveira', uf: 'PI' },
			{ name: 'Caracol', name_order: 'Caracol', uf: 'PI' },
			{ name: 'Caraúbas do Piauí', name_order: 'Caraubas do Piaui', uf: 'PI' },
			{ name: 'Caridade do Piauí', name_order: 'Caridade do Piaui', uf: 'PI' },
			{ name: 'Castelo do Piauí', name_order: 'Castelo do Piaui', uf: 'PI' },
			{ name: 'Caxingó', name_order: 'Caxingo', uf: 'PI' },
			{ name: 'Cocal', name_order: 'Cocal', uf: 'PI' },
			{ name: 'Cocal de Telha', name_order: 'Cocal de Telha', uf: 'PI' },
			{ name: 'Cocal Dos Alves', name_order: 'Cocal Dos Alves', uf: 'PI' },
			{ name: 'Coivaras', name_order: 'Coivaras', uf: 'PI' },
			{ name: 'Colônia do Gurguéia', name_order: 'Colonia do Gurgueia', uf: 'PI' },
			{ name: 'Colônia do Piauí', name_order: 'Colonia do Piaui', uf: 'PI' },
			{ name: 'Conceição do Canindé', name_order: 'Conceicao do Caninde', uf: 'PI' },
			{ name: 'Coronel José Dias', name_order: 'Coronel Jose Dias', uf: 'PI' },
			{ name: 'Corrente', name_order: 'Corrente', uf: 'PI' },
			{ name: 'Cristalândia do Piauí', name_order: 'Cristalandia do Piaui', uf: 'PI' },
			{ name: 'Cristino Castro', name_order: 'Cristino Castro', uf: 'PI' },
			{ name: 'Curimatá', name_order: 'Curimata', uf: 'PI' },
			{ name: 'Currais', name_order: 'Currais', uf: 'PI' },
			{ name: 'Curralinhos', name_order: 'Curralinhos', uf: 'PI' },
			{ name: 'Curral Novo do Piauí', name_order: 'Curral Novo do Piaui', uf: 'PI' },
			{ name: 'Demerval Lobão', name_order: 'Demerval Lobao', uf: 'PI' },
			{ name: 'Dirceu Arcoverde', name_order: 'Dirceu Arcoverde', uf: 'PI' },
			{ name: 'Dom Expedito Lopes', name_order: 'Dom Expedito Lopes', uf: 'PI' },
			{ name: 'Domingos Mourão', name_order: 'Domingos Mourao', uf: 'PI' },
			{ name: 'Dom Inocêncio', name_order: 'Dom Inocencio', uf: 'PI' },
			{ name: 'Elesbão Veloso', name_order: 'Elesbao Veloso', uf: 'PI' },
			{ name: 'Eliseu Martins', name_order: 'Eliseu Martins', uf: 'PI' },
			{ name: 'Esperantina', name_order: 'Esperantina', uf: 'PI' },
			{ name: 'Fartura do Piauí', name_order: 'Fartura do Piaui', uf: 'PI' },
			{ name: 'Flores do Piauí', name_order: 'Flores do Piaui', uf: 'PI' },
			{ name: 'Floresta do Piauí', name_order: 'Floresta do Piaui', uf: 'PI' },
			{ name: 'Floriano', name_order: 'Floriano', uf: 'PI' },
			{ name: 'Francinópolis', name_order: 'Francinopolis', uf: 'PI' },
			{ name: 'Francisco Ayres', name_order: 'Francisco Ayres', uf: 'PI' },
			{ name: 'Francisco Macedo', name_order: 'Francisco Macedo', uf: 'PI' },
			{ name: 'Francisco Santos', name_order: 'Francisco Santos', uf: 'PI' },
			{ name: 'Fronteiras', name_order: 'Fronteiras', uf: 'PI' },
			{ name: 'Geminiano', name_order: 'Geminiano', uf: 'PI' },
			{ name: 'Gilbués', name_order: 'Gilbues', uf: 'PI' },
			{ name: 'Guadalupe', name_order: 'Guadalupe', uf: 'PI' },
			{ name: 'Guaribas', name_order: 'Guaribas', uf: 'PI' },
			{ name: 'Hugo Napoleão', name_order: 'Hugo Napoleao', uf: 'PI' },
			{ name: 'Ilha Grande', name_order: 'Ilha Grande', uf: 'PI' },
			{ name: 'Inhuma', name_order: 'Inhuma', uf: 'PI' },
			{ name: 'Ipiranga do Piauí', name_order: 'Ipiranga do Piaui', uf: 'PI' },
			{ name: 'Isaías Coelho', name_order: 'Isaias Coelho', uf: 'PI' },
			{ name: 'Itainópolis', name_order: 'Itainopolis', uf: 'PI' },
			{ name: 'Itaueira', name_order: 'Itaueira', uf: 'PI' },
			{ name: 'Jacobina do Piauí', name_order: 'Jacobina do Piaui', uf: 'PI' },
			{ name: 'Jaicós', name_order: 'Jaicos', uf: 'PI' },
			{ name: 'Jardim do Mulato', name_order: 'Jardim do Mulato', uf: 'PI' },
			{ name: 'Jatobá do Piauí', name_order: 'Jatoba do Piaui', uf: 'PI' },
			{ name: 'Jerumenha', name_order: 'Jerumenha', uf: 'PI' },
			{ name: 'João Costa', name_order: 'Joao Costa', uf: 'PI' },
			{ name: 'Joaquim Pires', name_order: 'Joaquim Pires', uf: 'PI' },
			{ name: 'Joca Marques', name_order: 'Joca Marques', uf: 'PI' },
			{ name: 'José de Freitas', name_order: 'Jose de Freitas', uf: 'PI' },
			{ name: 'Juazeiro do Piauí', name_order: 'Juazeiro do Piaui', uf: 'PI' },
			{ name: 'Júlio Borges', name_order: 'Julio Borges', uf: 'PI' },
			{ name: 'Jurema', name_order: 'Jurema', uf: 'PI' },
			{ name: 'Lagoinha do Piauí', name_order: 'Lagoinha do Piaui', uf: 'PI' },
			{ name: 'Lagoa Alegre', name_order: 'Lagoa Alegre', uf: 'PI' },
			{ name: 'Lagoa do Barro do Piauí', name_order: 'Lagoa do Barro do Piaui', uf: 'PI' },
			{ name: 'Lagoa de São Francisco', name_order: 'Lagoa de Sao Francisco', uf: 'PI' },
			{ name: 'Lagoa do Piauí', name_order: 'Lagoa do Piaui', uf: 'PI' },
			{ name: 'Lagoa do Sítio', name_order: 'Lagoa do Sitio', uf: 'PI' },
			{ name: 'Landri Sales', name_order: 'Landri Sales', uf: 'PI' },
			{ name: 'Luís Correia', name_order: 'Luis Correia', uf: 'PI' },
			{ name: 'Luzilândia', name_order: 'Luzilandia', uf: 'PI' },
			{ name: 'Madeiro', name_order: 'Madeiro', uf: 'PI' },
			{ name: 'Manoel Emídio', name_order: 'Manoel Emidio', uf: 'PI' },
			{ name: 'Marcolândia', name_order: 'Marcolandia', uf: 'PI' },
			{ name: 'Marcos Parente', name_order: 'Marcos Parente', uf: 'PI' },
			{ name: 'Massapê do Piauí', name_order: 'Massape do Piaui', uf: 'PI' },
			{ name: 'Matias Olímpio', name_order: 'Matias Olimpio', uf: 'PI' },
			{ name: 'Miguel Alves', name_order: 'Miguel Alves', uf: 'PI' },
			{ name: 'Miguel Leão', name_order: 'Miguel Leao', uf: 'PI' },
			{ name: 'Milton Brandão', name_order: 'Milton Brandao', uf: 'PI' },
			{ name: 'Monsenhor Gil', name_order: 'Monsenhor Gil', uf: 'PI' },
			{ name: 'Monsenhor Hipólito', name_order: 'Monsenhor Hipolito', uf: 'PI' },
			{ name: 'Monte Alegre do Piauí', name_order: 'Monte Alegre do Piaui', uf: 'PI' },
			{ name: 'Morro Cabeça no Tempo', name_order: 'Morro Cabeca no Tempo', uf: 'PI' },
			{ name: 'Morro do Chapéu do Piauí', name_order: 'Morro do Chapeu do Piaui', uf: 'PI' },
			{ name: 'Murici Dos Portelas', name_order: 'Murici Dos Portelas', uf: 'PI' },
			{ name: 'Nazaré do Piauí', name_order: 'Nazare do Piaui', uf: 'PI' },
			{ name: 'Nazária', name_order: 'Nazaria', uf: 'PI' },
			{ name: 'Nossa Senhora de Nazaré', name_order: 'Nossa Senhora de Nazare', uf: 'PI' },
			{ name: 'Nossa Senhora Dos Remédios', name_order: 'Nossa Senhora Dos Remedios', uf: 'PI' },
			{ name: 'Novo Oriente do Piauí', name_order: 'Novo Oriente do Piaui', uf: 'PI' },
			{ name: 'Novo Santo Antônio', name_order: 'Novo Santo Antonio', uf: 'PI' },
			{ name: 'Oeiras', name_order: 'Oeiras', uf: 'PI' },
			{ name: 'Olho D´água do Piauí', name_order: 'Olho Dagua do Piaui', uf: 'PI' },
			{ name: 'Padre Marcos', name_order: 'Padre Marcos', uf: 'PI' },
			{ name: 'Paes Landim', name_order: 'Paes Landim', uf: 'PI' },
			{ name: 'Pajeú do Piauí', name_order: 'Pajeu do Piaui', uf: 'PI' },
			{ name: 'Palmeira do Piauí', name_order: 'Palmeira do Piaui', uf: 'PI' },
			{ name: 'Palmeirais', name_order: 'Palmeirais', uf: 'PI' },
			{ name: 'Paquetá', name_order: 'Paqueta', uf: 'PI' },
			{ name: 'Parnaguá', name_order: 'Parnagua', uf: 'PI' },
			{ name: 'Parnaíba', name_order: 'Parnaiba', uf: 'PI' },
			{ name: 'Passagem Franca do Piauí', name_order: 'Passagem Franca do Piaui', uf: 'PI' },
			{ name: 'Patos do Piauí', name_order: 'Patos do Piaui', uf: 'PI' },
			{ name: 'Pau D´arco do Piauí', name_order: 'Pau Darco do Piaui', uf: 'PI' },
			{ name: 'Paulistana', name_order: 'Paulistana', uf: 'PI' },
			{ name: 'Pavussu', name_order: 'Pavussu', uf: 'PI' },
			{ name: 'Pedro ii', name_order: 'Pedro ii', uf: 'PI' },
			{ name: 'Pedro Laurentino', name_order: 'Pedro Laurentino', uf: 'PI' },
			{ name: 'Nova Santa Rita', name_order: 'Nova Santa Rita', uf: 'PI' },
			{ name: 'Picos', name_order: 'Picos', uf: 'PI' },
			{ name: 'Pimenteiras', name_order: 'Pimenteiras', uf: 'PI' },
			{ name: 'Pio ix', name_order: 'Pio ix', uf: 'PI' },
			{ name: 'Piracuruca', name_order: 'Piracuruca', uf: 'PI' },
			{ name: 'Piripiri', name_order: 'Piripiri', uf: 'PI' },
			{ name: 'Porto', name_order: 'Porto', uf: 'PI' },
			{ name: 'Porto Alegre do Piauí', name_order: 'Porto Alegre do Piaui', uf: 'PI' },
			{ name: 'Prata do Piauí', name_order: 'Prata do Piaui', uf: 'PI' },
			{ name: 'Queimada Nova', name_order: 'Queimada Nova', uf: 'PI' },
			{ name: 'Redenção do Gurguéia', name_order: 'Redencao do Gurgueia', uf: 'PI' },
			{ name: 'Regeneração', name_order: 'Regeneracao', uf: 'PI' },
			{ name: 'Riacho Frio', name_order: 'Riacho Frio', uf: 'PI' },
			{ name: 'Ribeira do Piauí', name_order: 'Ribeira do Piaui', uf: 'PI' },
			{ name: 'Ribeiro Gonçalves', name_order: 'Ribeiro Goncalves', uf: 'PI' },
			{ name: 'Rio Grande do Piauí', name_order: 'Rio Grande do Piaui', uf: 'PI' },
			{ name: 'Santa Cruz do Piauí', name_order: 'Santa Cruz do Piaui', uf: 'PI' },
			{ name: 'Santa Cruz Dos Milagres', name_order: 'Santa Cruz Dos Milagres', uf: 'PI' },
			{ name: 'Santa Filomena', name_order: 'Santa Filomena', uf: 'PI' },
			{ name: 'Santa Luz', name_order: 'Santa Luz', uf: 'PI' },
			{ name: 'Santana do Piauí', name_order: 'Santana do Piaui', uf: 'PI' },
			{ name: 'Santa Rosa do Piauí', name_order: 'Santa Rosa do Piaui', uf: 'PI' },
			{ name: 'Santo Antônio de Lisboa', name_order: 'Santo Antonio de Lisboa', uf: 'PI' },
			{ name: 'Santo Antônio Dos Milagres', name_order: 'Santo Antonio Dos Milagres', uf: 'PI' },
			{ name: 'Santo Inácio do Piauí', name_order: 'Santo Inacio do Piaui', uf: 'PI' },
			{ name: 'São Braz do Piauí', name_order: 'Sao Braz do Piaui', uf: 'PI' },
			{ name: 'São Félix do Piauí', name_order: 'Sao Felix do Piaui', uf: 'PI' },
			{ name: 'São Francisco de Assis do Piauí', name_order: 'Sao Francisco de Assis do Piaui', uf: 'PI' },
			{ name: 'São Francisco do Piauí', name_order: 'Sao Francisco do Piaui', uf: 'PI' },
			{ name: 'São Gonçalo do Gurguéia', name_order: 'Sao Goncalo do Gurgueia', uf: 'PI' },
			{ name: 'São Gonçalo do Piauí', name_order: 'Sao Goncalo do Piaui', uf: 'PI' },
			{ name: 'São João da Canabrava', name_order: 'Sao Joao da Canabrava', uf: 'PI' },
			{ name: 'São João da Fronteira', name_order: 'Sao Joao da Fronteira', uf: 'PI' },
			{ name: 'São João da Serra', name_order: 'Sao Joao da Serra', uf: 'PI' },
			{ name: 'São João da Varjota', name_order: 'Sao Joao da Varjota', uf: 'PI' },
			{ name: 'São João do Arraial', name_order: 'Sao Joao do Arraial', uf: 'PI' },
			{ name: 'São João do Piauí', name_order: 'Sao Joao do Piaui', uf: 'PI' },
			{ name: 'São José do Divino', name_order: 'Sao Jose do Divino', uf: 'PI' },
			{ name: 'São José do Peixe', name_order: 'Sao Jose do Peixe', uf: 'PI' },
			{ name: 'São José do Piauí', name_order: 'Sao Jose do Piaui', uf: 'PI' },
			{ name: 'São Julião', name_order: 'Sao Juliao', uf: 'PI' },
			{ name: 'São Lourenço do Piauí', name_order: 'Sao Lourenco do Piaui', uf: 'PI' },
			{ name: 'São Luis do Piauí', name_order: 'Sao Luis do Piaui', uf: 'PI' },
			{ name: 'São Miguel da Baixa Grande', name_order: 'Sao Miguel da Baixa Grande', uf: 'PI' },
			{ name: 'São Miguel do Fidalgo', name_order: 'Sao Miguel do Fidalgo', uf: 'PI' },
			{ name: 'São Miguel do Tapuio', name_order: 'Sao Miguel do Tapuio', uf: 'PI' },
			{ name: 'São Pedro do Piauí', name_order: 'Sao Pedro do Piaui', uf: 'PI' },
			{ name: 'São Raimundo Nonato', name_order: 'Sao Raimundo Nonato', uf: 'PI' },
			{ name: 'Sebastião Barros', name_order: 'Sebastiao Barros', uf: 'PI' },
			{ name: 'Sebastião Leal', name_order: 'Sebastiao Leal', uf: 'PI' },
			{ name: 'Sigefredo Pacheco', name_order: 'Sigefredo Pacheco', uf: 'PI' },
			{ name: 'Simões', name_order: 'Simoes', uf: 'PI' },
			{ name: 'Simplício Mendes', name_order: 'Simplicio Mendes', uf: 'PI' },
			{ name: 'Socorro do Piauí', name_order: 'Socorro do Piaui', uf: 'PI' },
			{ name: 'Sussuapara', name_order: 'Sussuapara', uf: 'PI' },
			{ name: 'Tamboril do Piauí', name_order: 'Tamboril do Piaui', uf: 'PI' },
			{ name: 'Tanque do Piauí', name_order: 'Tanque do Piaui', uf: 'PI' },
			{ name: 'Teresina', name_order: 'Teresina', uf: 'PI' },
			{ name: 'União', name_order: 'Uniao', uf: 'PI' },
			{ name: 'Uruçuí', name_order: 'Urucui', uf: 'PI' },
			{ name: 'Valença do Piauí', name_order: 'Valenca do Piaui', uf: 'PI' },
			{ name: 'Várzea Branca', name_order: 'Varzea Branca', uf: 'PI' },
			{ name: 'Várzea Grande', name_order: 'Varzea Grande', uf: 'PI' },
			{ name: 'Vera Mendes', name_order: 'Vera Mendes', uf: 'PI' },
			{ name: 'Vila Nova do Piauí', name_order: 'Vila Nova do Piaui', uf: 'PI' },
			{ name: 'Wall Ferraz', name_order: 'Wall Ferraz', uf: 'PI' },
	]);
};
