exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'São Sebastião da Vargem Alegre', name_order: 'Sao Sebastiao da Vargem Alegre', uf: 'MG' },
			{ name: 'São Sebastião do Anta', name_order: 'Sao Sebastiao do Anta', uf: 'MG' },
			{ name: 'São Sebastião do Maranhão', name_order: 'Sao Sebastiao do Maranhao', uf: 'MG' },
			{ name: 'São Sebastião do Oeste', name_order: 'Sao Sebastiao do Oeste', uf: 'MG' },
			{ name: 'São Sebastião do Paraíso', name_order: 'Sao Sebastiao do Paraiso', uf: 'MG' },
			{ name: 'São Sebastião do Rio Preto', name_order: 'Sao Sebastiao do Rio Preto', uf: 'MG' },
			{ name: 'São Sebastião do Rio Verde', name_order: 'Sao Sebastiao do Rio Verde', uf: 'MG' },
			{ name: 'São Tiago', name_order: 'Sao Tiago', uf: 'MG' },
			{ name: 'São Tomás de Aquino', name_order: 'Sao Tomas de Aquino', uf: 'MG' },
			{ name: 'São Thomé Das Letras', name_order: 'Sao Thome Das Letras', uf: 'MG' },
			{ name: 'São Vicente de Minas', name_order: 'Sao Vicente de Minas', uf: 'MG' },
			{ name: 'Sapucaí-mirim', name_order: 'Sapucaimirim', uf: 'MG' },
			{ name: 'Sardoá', name_order: 'Sardoa', uf: 'MG' },
			{ name: 'Sarzedo', name_order: 'Sarzedo', uf: 'MG' },
			{ name: 'Setubinha', name_order: 'Setubinha', uf: 'MG' },
			{ name: 'Sem-peixe', name_order: 'Sempeixe', uf: 'MG' },
			{ name: 'Senador Amaral', name_order: 'Senador Amaral', uf: 'MG' },
			{ name: 'Senador Cortes', name_order: 'Senador Cortes', uf: 'MG' },
			{ name: 'Senador Firmino', name_order: 'Senador Firmino', uf: 'MG' },
			{ name: 'Senador José Bento', name_order: 'Senador Jose Bento', uf: 'MG' },
			{ name: 'Senador Modestino Gonçalves', name_order: 'Senador Modestino Goncalves', uf: 'MG' },
			{ name: 'Senhora de Oliveira', name_order: 'Senhora de Oliveira', uf: 'MG' },
			{ name: 'Senhora do Porto', name_order: 'Senhora do Porto', uf: 'MG' },
			{ name: 'Senhora Dos Remédios', name_order: 'Senhora Dos Remedios', uf: 'MG' },
			{ name: 'Sericita', name_order: 'Sericita', uf: 'MG' },
			{ name: 'Seritinga', name_order: 'Seritinga', uf: 'MG' },
			{ name: 'Serra Azul de Minas', name_order: 'Serra Azul de Minas', uf: 'MG' },
			{ name: 'Serra da Saudade', name_order: 'Serra da Saudade', uf: 'MG' },
			{ name: 'Serra Dos Aimorés', name_order: 'Serra Dos Aimores', uf: 'MG' },
			{ name: 'Serra do Salitre', name_order: 'Serra do Salitre', uf: 'MG' },
			{ name: 'Serrania', name_order: 'Serrania', uf: 'MG' },
			{ name: 'Serranópolis de Minas', name_order: 'Serranopolis de Minas', uf: 'MG' },
			{ name: 'Serranos', name_order: 'Serranos', uf: 'MG' },
			{ name: 'Serro', name_order: 'Serro', uf: 'MG' },
			{ name: 'Sete Lagoas', name_order: 'Sete Lagoas', uf: 'MG' },
			{ name: 'Silveirânia', name_order: 'Silveirania', uf: 'MG' },
			{ name: 'Silvianópolis', name_order: 'Silvianopolis', uf: 'MG' },
			{ name: 'Simão Pereira', name_order: 'Simao Pereira', uf: 'MG' },
			{ name: 'Simonésia', name_order: 'Simonesia', uf: 'MG' },
			{ name: 'Sobrália', name_order: 'Sobralia', uf: 'MG' },
			{ name: 'Soledade de Minas', name_order: 'Soledade de Minas', uf: 'MG' },
			{ name: 'Tabuleiro', name_order: 'Tabuleiro', uf: 'MG' },
			{ name: 'Taiobeiras', name_order: 'Taiobeiras', uf: 'MG' },
			{ name: 'Taparuba', name_order: 'Taparuba', uf: 'MG' },
			{ name: 'Tapira', name_order: 'Tapira', uf: 'MG' },
			{ name: 'Tapiraí', name_order: 'Tapirai', uf: 'MG' },
			{ name: 'Taquaraçu de Minas', name_order: 'Taquaracu de Minas', uf: 'MG' },
			{ name: 'Tarumirim', name_order: 'Tarumirim', uf: 'MG' },
			{ name: 'Teixeiras', name_order: 'Teixeiras', uf: 'MG' },
			{ name: 'Teófilo Otoni', name_order: 'Teofilo Otoni', uf: 'MG' },
			{ name: 'Timóteo', name_order: 'Timoteo', uf: 'MG' },
			{ name: 'Tiradentes', name_order: 'Tiradentes', uf: 'MG' },
			{ name: 'Tiros', name_order: 'Tiros', uf: 'MG' },
			{ name: 'Tocantins', name_order: 'Tocantins', uf: 'MG' },
			{ name: 'Tocos do Moji', name_order: 'Tocos do Moji', uf: 'MG' },
			{ name: 'Toledo', name_order: 'Toledo', uf: 'MG' },
			{ name: 'Tombos', name_order: 'Tombos', uf: 'MG' },
			{ name: 'Três Corações', name_order: 'Tres Coracoes', uf: 'MG' },
			{ name: 'Três Marias', name_order: 'Tres Marias', uf: 'MG' },
			{ name: 'Três Pontas', name_order: 'Tres Pontas', uf: 'MG' },
			{ name: 'Tumiritinga', name_order: 'Tumiritinga', uf: 'MG' },
			{ name: 'Tupaciguara', name_order: 'Tupaciguara', uf: 'MG' },
			{ name: 'Turmalina', name_order: 'Turmalina', uf: 'MG' },
			{ name: 'Turvolândia', name_order: 'Turvolandia', uf: 'MG' },
			{ name: 'Ubá', name_order: 'Uba', uf: 'MG' },
			{ name: 'Ubaí', name_order: 'Ubai', uf: 'MG' },
			{ name: 'Ubaporanga', name_order: 'Ubaporanga', uf: 'MG' },
			{ name: 'Uberaba', name_order: 'Uberaba', uf: 'MG' },
			{ name: 'Uberlândia', name_order: 'Uberlandia', uf: 'MG' },
			{ name: 'Umburatiba', name_order: 'Umburatiba', uf: 'MG' },
			{ name: 'Unaí', name_order: 'Unai', uf: 'MG' },
			{ name: 'União de Minas', name_order: 'Uniao de Minas', uf: 'MG' },
			{ name: 'Uruana de Minas', name_order: 'Uruana de Minas', uf: 'MG' },
			{ name: 'Urucânia', name_order: 'Urucania', uf: 'MG' },
			{ name: 'Urucuia', name_order: 'Urucuia', uf: 'MG' },
			{ name: 'Vargem Alegre', name_order: 'Vargem Alegre', uf: 'MG' },
			{ name: 'Vargem Bonita', name_order: 'Vargem Bonita', uf: 'MG' },
			{ name: 'Vargem Grande do Rio Pardo', name_order: 'Vargem Grande do Rio Pardo', uf: 'MG' },
			{ name: 'Varginha', name_order: 'Varginha', uf: 'MG' },
			{ name: 'Varjão de Minas', name_order: 'Varjao de Minas', uf: 'MG' },
			{ name: 'Várzea da Palma', name_order: 'Varzea da Palma', uf: 'MG' },
			{ name: 'Varzelândia', name_order: 'Varzelandia', uf: 'MG' },
			{ name: 'Vazante', name_order: 'Vazante', uf: 'MG' },
			{ name: 'Verdelândia', name_order: 'Verdelandia', uf: 'MG' },
			{ name: 'Veredinha', name_order: 'Veredinha', uf: 'MG' },
			{ name: 'Veríssimo', name_order: 'Verissimo', uf: 'MG' },
			{ name: 'Vermelho Novo', name_order: 'Vermelho Novo', uf: 'MG' },
			{ name: 'Vespasiano', name_order: 'Vespasiano', uf: 'MG' },
			{ name: 'Viçosa', name_order: 'Vicosa', uf: 'MG' },
			{ name: 'Vieiras', name_order: 'Vieiras', uf: 'MG' },
			{ name: 'Mathias Lobato', name_order: 'Mathias Lobato', uf: 'MG' },
			{ name: 'Virgem da Lapa', name_order: 'Virgem da Lapa', uf: 'MG' },
			{ name: 'Virgínia', name_order: 'Virginia', uf: 'MG' },
			{ name: 'Virginópolis', name_order: 'Virginopolis', uf: 'MG' },
			{ name: 'Virgolândia', name_order: 'Virgolandia', uf: 'MG' },
			{ name: 'Visconde do Rio Branco', name_order: 'Visconde do Rio Branco', uf: 'MG' },
			{ name: 'Volta Grande', name_order: 'Volta Grande', uf: 'MG' },
			{ name: 'Wenceslau Braz', name_order: 'Wenceslau Braz', uf: 'MG' },
	]);
};
