exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Carmo do Rio Claro', name_order: 'Carmo do Rio Claro', uf: 'MG' },
			{ name: 'Carmópolis de Minas', name_order: 'Carmopolis de Minas', uf: 'MG' },
			{ name: 'Carneirinho', name_order: 'Carneirinho', uf: 'MG' },
			{ name: 'Carrancas', name_order: 'Carrancas', uf: 'MG' },
			{ name: 'Carvalhópolis', name_order: 'Carvalhopolis', uf: 'MG' },
			{ name: 'Carvalhos', name_order: 'Carvalhos', uf: 'MG' },
			{ name: 'Casa Grande', name_order: 'Casa Grande', uf: 'MG' },
			{ name: 'Cascalho Rico', name_order: 'Cascalho Rico', uf: 'MG' },
			{ name: 'Cássia', name_order: 'Cassia', uf: 'MG' },
			{ name: 'Conceição da Barra de Minas', name_order: 'Conceicao da Barra de Minas', uf: 'MG' },
			{ name: 'Cataguases', name_order: 'Cataguases', uf: 'MG' },
			{ name: 'Catas Altas', name_order: 'Catas Altas', uf: 'MG' },
			{ name: 'Catas Altas da Noruega', name_order: 'Catas Altas da Noruega', uf: 'MG' },
			{ name: 'Catuji', name_order: 'Catuji', uf: 'MG' },
			{ name: 'Catuti', name_order: 'Catuti', uf: 'MG' },
			{ name: 'Caxambu', name_order: 'Caxambu', uf: 'MG' },
			{ name: 'Cedro do Abaeté', name_order: 'Cedro do Abaete', uf: 'MG' },
			{ name: 'Central de Minas', name_order: 'Central de Minas', uf: 'MG' },
			{ name: 'Centralina', name_order: 'Centralina', uf: 'MG' },
			{ name: 'Chácara', name_order: 'Chacara', uf: 'MG' },
			{ name: 'Chalé', name_order: 'Chale', uf: 'MG' },
			{ name: 'Chapada do Norte', name_order: 'Chapada do Norte', uf: 'MG' },
			{ name: 'Chapada Gaúcha', name_order: 'Chapada Gaucha', uf: 'MG' },
			{ name: 'Chiador', name_order: 'Chiador', uf: 'MG' },
			{ name: 'Cipotânea', name_order: 'Cipotanea', uf: 'MG' },
			{ name: 'Claraval', name_order: 'Claraval', uf: 'MG' },
			{ name: 'Claro Dos Poções', name_order: 'Claro Dos Pocoes', uf: 'MG' },
			{ name: 'Cláudio', name_order: 'Claudio', uf: 'MG' },
			{ name: 'Coimbra', name_order: 'Coimbra', uf: 'MG' },
			{ name: 'Coluna', name_order: 'Coluna', uf: 'MG' },
			{ name: 'Comendador Gomes', name_order: 'Comendador Gomes', uf: 'MG' },
			{ name: 'Comercinho', name_order: 'Comercinho', uf: 'MG' },
			{ name: 'Conceição da Aparecida', name_order: 'Conceicao da Aparecida', uf: 'MG' },
			{ name: 'Conceição Das Pedras', name_order: 'Conceicao Das Pedras', uf: 'MG' },
			{ name: 'Conceição Das Alagoas', name_order: 'Conceicao Das Alagoas', uf: 'MG' },
			{ name: 'Conceição de Ipanema', name_order: 'Conceicao de Ipanema', uf: 'MG' },
			{ name: 'Conceição do Mato Dentro', name_order: 'Conceicao do Mato Dentro', uf: 'MG' },
			{ name: 'Conceição do Pará', name_order: 'Conceicao do Para', uf: 'MG' },
			{ name: 'Conceição do Rio Verde', name_order: 'Conceicao do Rio Verde', uf: 'MG' },
			{ name: 'Conceição Dos Ouros', name_order: 'Conceicao Dos Ouros', uf: 'MG' },
			{ name: 'Cônego Marinho', name_order: 'Conego Marinho', uf: 'MG' },
			{ name: 'Confins', name_order: 'Confins', uf: 'MG' },
			{ name: 'Congonhal', name_order: 'Congonhal', uf: 'MG' },
			{ name: 'Congonhas', name_order: 'Congonhas', uf: 'MG' },
			{ name: 'Congonhas do Norte', name_order: 'Congonhas do Norte', uf: 'MG' },
			{ name: 'Conquista', name_order: 'Conquista', uf: 'MG' },
			{ name: 'Conselheiro Lafaiete', name_order: 'Conselheiro Lafaiete', uf: 'MG' },
			{ name: 'Conselheiro Pena', name_order: 'Conselheiro Pena', uf: 'MG' },
			{ name: 'Consolação', name_order: 'Consolacao', uf: 'MG' },
			{ name: 'Contagem', name_order: 'Contagem', uf: 'MG' },
			{ name: 'Coqueiral', name_order: 'Coqueiral', uf: 'MG' },
			{ name: 'Coração de Jesus', name_order: 'Coracao de Jesus', uf: 'MG' },
			{ name: 'Cordisburgo', name_order: 'Cordisburgo', uf: 'MG' },
			{ name: 'Cordislândia', name_order: 'Cordislandia', uf: 'MG' },
			{ name: 'Corinto', name_order: 'Corinto', uf: 'MG' },
			{ name: 'Coroaci', name_order: 'Coroaci', uf: 'MG' },
			{ name: 'Coromandel', name_order: 'Coromandel', uf: 'MG' },
			{ name: 'Coronel Fabriciano', name_order: 'Coronel Fabriciano', uf: 'MG' },
			{ name: 'Coronel Murta', name_order: 'Coronel Murta', uf: 'MG' },
			{ name: 'Coronel Pacheco', name_order: 'Coronel Pacheco', uf: 'MG' },
			{ name: 'Coronel Xavier Chaves', name_order: 'Coronel Xavier Chaves', uf: 'MG' },
			{ name: 'Córrego Danta', name_order: 'Corrego Danta', uf: 'MG' },
			{ name: 'Córrego do Bom Jesus', name_order: 'Corrego do Bom Jesus', uf: 'MG' },
			{ name: 'Córrego Fundo', name_order: 'Corrego Fundo', uf: 'MG' },
			{ name: 'Córrego Novo', name_order: 'Corrego Novo', uf: 'MG' },
			{ name: 'Couto de Magalhães de Minas', name_order: 'Couto de Magalhaes de Minas', uf: 'MG' },
			{ name: 'Crisólita', name_order: 'Crisolita', uf: 'MG' },
			{ name: 'Cristais', name_order: 'Cristais', uf: 'MG' },
			{ name: 'Cristália', name_order: 'Cristalia', uf: 'MG' },
			{ name: 'Cristiano Otoni', name_order: 'Cristiano Otoni', uf: 'MG' },
			{ name: 'Cristina', name_order: 'Cristina', uf: 'MG' },
			{ name: 'Crucilândia', name_order: 'Crucilandia', uf: 'MG' },
			{ name: 'Cruzeiro da Fortaleza', name_order: 'Cruzeiro da Fortaleza', uf: 'MG' },
			{ name: 'Cruzília', name_order: 'Cruzilia', uf: 'MG' },
			{ name: 'Cuparaque', name_order: 'Cuparaque', uf: 'MG' },
			{ name: 'Curral de Dentro', name_order: 'Curral de Dentro', uf: 'MG' },
			{ name: 'Curvelo', name_order: 'Curvelo', uf: 'MG' },
			{ name: 'Datas', name_order: 'Datas', uf: 'MG' },
			{ name: 'Delfim Moreira', name_order: 'Delfim Moreira', uf: 'MG' },
			{ name: 'Delfinópolis', name_order: 'Delfinopolis', uf: 'MG' },
			{ name: 'Delta', name_order: 'Delta', uf: 'MG' },
			{ name: 'Descoberto', name_order: 'Descoberto', uf: 'MG' },
			{ name: 'Desterro de Entre Rios', name_order: 'Desterro de Entre Rios', uf: 'MG' },
			{ name: 'Desterro do Melo', name_order: 'Desterro do Melo', uf: 'MG' },
			{ name: 'Diamantina', name_order: 'Diamantina', uf: 'MG' },
			{ name: 'Diogo de Vasconcelos', name_order: 'Diogo de Vasconcelos', uf: 'MG' },
			{ name: 'Dionísio', name_order: 'Dionisio', uf: 'MG' },
			{ name: 'Divinésia', name_order: 'Divinesia', uf: 'MG' },
			{ name: 'Divino', name_order: 'Divino', uf: 'MG' },
			{ name: 'Divino Das Laranjeiras', name_order: 'Divino Das Laranjeiras', uf: 'MG' },
			{ name: 'Divinolândia de Minas', name_order: 'Divinolandia de Minas', uf: 'MG' },
			{ name: 'Divinópolis', name_order: 'Divinopolis', uf: 'MG' },
			{ name: 'Divisa Alegre', name_order: 'Divisa Alegre', uf: 'MG' },
			{ name: 'Divisa Nova', name_order: 'Divisa Nova', uf: 'MG' },
			{ name: 'Divisópolis', name_order: 'Divisopolis', uf: 'MG' },
			{ name: 'Dom Bosco', name_order: 'Dom Bosco', uf: 'MG' },
			{ name: 'Dom Cavati', name_order: 'Dom Cavati', uf: 'MG' },
			{ name: 'Dom Joaquim', name_order: 'Dom Joaquim', uf: 'MG' },
			{ name: 'Dom Silvério', name_order: 'Dom Silverio', uf: 'MG' },
			{ name: 'Dom Viçoso', name_order: 'Dom Vicoso', uf: 'MG' },
			{ name: 'Dona Eusébia', name_order: 'Dona Eusebia', uf: 'MG' },
			{ name: 'Dores de Campos', name_order: 'Dores de Campos', uf: 'MG' },
			{ name: 'Dores de Guanhães', name_order: 'Dores de Guanhaes', uf: 'MG' },
			{ name: 'Dores do Indaiá', name_order: 'Dores do Indaia', uf: 'MG' },
			{ name: 'Dores do Turvo', name_order: 'Dores do Turvo', uf: 'MG' },
			{ name: 'Doresópolis', name_order: 'Doresopolis', uf: 'MG' },
			{ name: 'Douradoquara', name_order: 'Douradoquara', uf: 'MG' },
			{ name: 'Durandé', name_order: 'Durande', uf: 'MG' },
			{ name: 'Elói Mendes', name_order: 'Eloi Mendes', uf: 'MG' },
			{ name: 'Engenheiro Caldas', name_order: 'Engenheiro Caldas', uf: 'MG' },
			{ name: 'Engenheiro Navarro', name_order: 'Engenheiro Navarro', uf: 'MG' },
			{ name: 'Entre Folhas', name_order: 'Entre Folhas', uf: 'MG' },
			{ name: 'Entre Rios de Minas', name_order: 'Entre Rios de Minas', uf: 'MG' },
			{ name: 'Ervália', name_order: 'Ervalia', uf: 'MG' },
			{ name: 'Esmeraldas', name_order: 'Esmeraldas', uf: 'MG' },
			{ name: 'Espera Feliz', name_order: 'Espera Feliz', uf: 'MG' },
			{ name: 'Espinosa', name_order: 'Espinosa', uf: 'MG' },
			{ name: 'Espírito Santo do Dourado', name_order: 'Espirito Santo do Dourado', uf: 'MG' },
			{ name: 'Estiva', name_order: 'Estiva', uf: 'MG' },
			{ name: 'Estrela Dalva', name_order: 'Estrela Dalva', uf: 'MG' },
			{ name: 'Estrela do Indaiá', name_order: 'Estrela do Indaia', uf: 'MG' },
			{ name: 'Estrela do Sul', name_order: 'Estrela do Sul', uf: 'MG' },
			{ name: 'Eugenópolis', name_order: 'Eugenopolis', uf: 'MG' },
			{ name: 'Ewbank da Câmara', name_order: 'Ewbank da Camara', uf: 'MG' },
			{ name: 'Extrema', name_order: 'Extrema', uf: 'MG' },
			{ name: 'Fama', name_order: 'Fama', uf: 'MG' },
			{ name: 'Faria Lemos', name_order: 'Faria Lemos', uf: 'MG' },
			{ name: 'Felício Dos Santos', name_order: 'Felicio Dos Santos', uf: 'MG' },
			{ name: 'São Gonçalo do Rio Preto', name_order: 'Sao Goncalo do Rio Preto', uf: 'MG' },
			{ name: 'Felisburgo', name_order: 'Felisburgo', uf: 'MG' },
			{ name: 'Felixlândia', name_order: 'Felixlandia', uf: 'MG' },
			{ name: 'Fernandes Tourinho', name_order: 'Fernandes Tourinho', uf: 'MG' },
			{ name: 'Ferros', name_order: 'Ferros', uf: 'MG' },
			{ name: 'Fervedouro', name_order: 'Fervedouro', uf: 'MG' },
			{ name: 'Florestal', name_order: 'Florestal', uf: 'MG' },
			{ name: 'Formiga', name_order: 'Formiga', uf: 'MG' },
			{ name: 'Formoso', name_order: 'Formoso', uf: 'MG' },
			{ name: 'Fortaleza de Minas', name_order: 'Fortaleza de Minas', uf: 'MG' },
			{ name: 'Fortuna de Minas', name_order: 'Fortuna de Minas', uf: 'MG' },
			{ name: 'Francisco Badaró', name_order: 'Francisco Badaro', uf: 'MG' },
			{ name: 'Francisco Dumont', name_order: 'Francisco Dumont', uf: 'MG' },
			{ name: 'Francisco sá', name_order: 'Francisco sa', uf: 'MG' },
			{ name: 'Franciscópolis', name_order: 'Franciscopolis', uf: 'MG' },
			{ name: 'Frei Gaspar', name_order: 'Frei Gaspar', uf: 'MG' },
			{ name: 'Frei Inocêncio', name_order: 'Frei Inocencio', uf: 'MG' },
			{ name: 'Frei Lagonegro', name_order: 'Frei Lagonegro', uf: 'MG' },
			{ name: 'Fronteira', name_order: 'Fronteira', uf: 'MG' },
			{ name: 'Fronteira Dos Vales', name_order: 'Fronteira Dos Vales', uf: 'MG' },
			{ name: 'Fruta de Leite', name_order: 'Fruta de Leite', uf: 'MG' },
			{ name: 'Frutal', name_order: 'Frutal', uf: 'MG' },
			{ name: 'Funilândia', name_order: 'Funilandia', uf: 'MG' },
			{ name: 'Galiléia', name_order: 'Galileia', uf: 'MG' },
			{ name: 'Gameleiras', name_order: 'Gameleiras', uf: 'MG' },
			{ name: 'Glaucilândia', name_order: 'Glaucilandia', uf: 'MG' },
			{ name: 'Goiabeira', name_order: 'Goiabeira', uf: 'MG' },
			{ name: 'Goianá', name_order: 'Goiana', uf: 'MG' },
			{ name: 'Gonçalves', name_order: 'Goncalves', uf: 'MG' },
			{ name: 'Gonzaga', name_order: 'Gonzaga', uf: 'MG' },
			{ name: 'Gouveia', name_order: 'Gouveia', uf: 'MG' },
			{ name: 'Governador Valadares', name_order: 'Governador Valadares', uf: 'MG' },
			{ name: 'Grão Mogol', name_order: 'Grao Mogol', uf: 'MG' },
			{ name: 'Grupiara', name_order: 'Grupiara', uf: 'MG' },
			{ name: 'Guanhães', name_order: 'Guanhaes', uf: 'MG' },
			{ name: 'Guapé', name_order: 'Guape', uf: 'MG' },
			{ name: 'Guaraciaba', name_order: 'Guaraciaba', uf: 'MG' },
			{ name: 'Guaraciama', name_order: 'Guaraciama', uf: 'MG' },
			{ name: 'Guaranésia', name_order: 'Guaranesia', uf: 'MG' },
			{ name: 'Guarani', name_order: 'Guarani', uf: 'MG' },
			{ name: 'Guarará', name_order: 'Guarara', uf: 'MG' },
			{ name: 'Guarda-mor', name_order: 'Guardamor', uf: 'MG' },
			{ name: 'Guaxupé', name_order: 'Guaxupe', uf: 'MG' },
			{ name: 'Guidoval', name_order: 'Guidoval', uf: 'MG' },
			{ name: 'Guimarânia', name_order: 'Guimarania', uf: 'MG' },
			{ name: 'Guiricema', name_order: 'Guiricema', uf: 'MG' },
			{ name: 'Gurinhatã', name_order: 'Gurinhata', uf: 'MG' },
			{ name: 'Heliodora', name_order: 'Heliodora', uf: 'MG' },
			{ name: 'Iapu', name_order: 'Iapu', uf: 'MG' },
			{ name: 'Ibertioga', name_order: 'Ibertioga', uf: 'MG' },
			{ name: 'Ibiá', name_order: 'Ibia', uf: 'MG' },
			{ name: 'Ibiaí', name_order: 'Ibiai', uf: 'MG' },
			{ name: 'Ibiracatu', name_order: 'Ibiracatu', uf: 'MG' },
			{ name: 'Ibiraci', name_order: 'Ibiraci', uf: 'MG' },
			{ name: 'Ibirité', name_order: 'Ibirite', uf: 'MG' },
			{ name: 'Ibitiúra de Minas', name_order: 'Ibitiura de Minas', uf: 'MG' },
			{ name: 'Ibituruna', name_order: 'Ibituruna', uf: 'MG' },
			{ name: 'Icaraí de Minas', name_order: 'Icarai de Minas', uf: 'MG' },
			{ name: 'Igarapé', name_order: 'Igarape', uf: 'MG' },
			{ name: 'Igaratinga', name_order: 'Igaratinga', uf: 'MG' },
			{ name: 'Iguatama', name_order: 'Iguatama', uf: 'MG' },
			{ name: 'Ijaci', name_order: 'Ijaci', uf: 'MG' },
			{ name: 'Ilicínea', name_order: 'Ilicinea', uf: 'MG' },
			{ name: 'Imbé de Minas', name_order: 'Imbe de Minas', uf: 'MG' },
			{ name: 'Inconfidentes', name_order: 'Inconfidentes', uf: 'MG' },
			{ name: 'Indaiabira', name_order: 'Indaiabira', uf: 'MG' },
			{ name: 'Indianópolis', name_order: 'Indianopolis', uf: 'MG' },
			{ name: 'Ingaí', name_order: 'Ingai', uf: 'MG' },
			{ name: 'Inhapim', name_order: 'Inhapim', uf: 'MG' },
			{ name: 'Inhaúma', name_order: 'Inhauma', uf: 'MG' },
			{ name: 'Inimutaba', name_order: 'Inimutaba', uf: 'MG' },
			{ name: 'Ipaba', name_order: 'Ipaba', uf: 'MG' },
			{ name: 'Ipanema', name_order: 'Ipanema', uf: 'MG' },
			{ name: 'Ipatinga', name_order: 'Ipatinga', uf: 'MG' },
			{ name: 'Ipiaçu', name_order: 'Ipiacu', uf: 'MG' },
			{ name: 'Ipuiúna', name_order: 'Ipuiuna', uf: 'MG' },
			{ name: 'Iraí de Minas', name_order: 'Irai de Minas', uf: 'MG' },
			{ name: 'Itabira', name_order: 'Itabira', uf: 'MG' },
			{ name: 'Itabirinha', name_order: 'Itabirinha', uf: 'MG' },
			{ name: 'Itabirito', name_order: 'Itabirito', uf: 'MG' },
			{ name: 'Itacambira', name_order: 'Itacambira', uf: 'MG' },
			{ name: 'Itacarambi', name_order: 'Itacarambi', uf: 'MG' },
			{ name: 'Itaguara', name_order: 'Itaguara', uf: 'MG' },
			{ name: 'Itaipé', name_order: 'Itaipe', uf: 'MG' },
			{ name: 'Itajubá', name_order: 'Itajuba', uf: 'MG' },
			{ name: 'Itamarandiba', name_order: 'Itamarandiba', uf: 'MG' },
			{ name: 'Itamarati de Minas', name_order: 'Itamarati de Minas', uf: 'MG' },
			{ name: 'Itambacuri', name_order: 'Itambacuri', uf: 'MG' },
			{ name: 'Itambé do Mato Dentro', name_order: 'Itambe do Mato Dentro', uf: 'MG' },
			{ name: 'Itamogi', name_order: 'Itamogi', uf: 'MG' },
			{ name: 'Itamonte', name_order: 'Itamonte', uf: 'MG' },
			{ name: 'Itanhandu', name_order: 'Itanhandu', uf: 'MG' },
			{ name: 'Itanhomi', name_order: 'Itanhomi', uf: 'MG' },
			{ name: 'Itaobim', name_order: 'Itaobim', uf: 'MG' },
			{ name: 'Itapagipe', name_order: 'Itapagipe', uf: 'MG' },
			{ name: 'Itapecerica', name_order: 'Itapecerica', uf: 'MG' },
			{ name: 'Itapeva', name_order: 'Itapeva', uf: 'MG' },
			{ name: 'Itatiaiuçu', name_order: 'Itatiaiucu', uf: 'MG' },
			{ name: 'Itaú de Minas', name_order: 'Itau de Minas', uf: 'MG' },
			{ name: 'Itaúna', name_order: 'Itauna', uf: 'MG' },
			{ name: 'Itaverava', name_order: 'Itaverava', uf: 'MG' },
			{ name: 'Itinga', name_order: 'Itinga', uf: 'MG' },
			{ name: 'Itueta', name_order: 'Itueta', uf: 'MG' },
			{ name: 'Ituiutaba', name_order: 'Ituiutaba', uf: 'MG' },
			{ name: 'Itumirim', name_order: 'Itumirim', uf: 'MG' },
			{ name: 'Iturama', name_order: 'Iturama', uf: 'MG' },
			{ name: 'Itutinga', name_order: 'Itutinga', uf: 'MG' },
			{ name: 'Jaboticatubas', name_order: 'Jaboticatubas', uf: 'MG' },
			{ name: 'Jacinto', name_order: 'Jacinto', uf: 'MG' },
			{ name: 'Jacuí', name_order: 'Jacui', uf: 'MG' },
			{ name: 'Jacutinga', name_order: 'Jacutinga', uf: 'MG' },
			{ name: 'Jaguaraçu', name_order: 'Jaguaracu', uf: 'MG' },
			{ name: 'Jaíba', name_order: 'Jaiba', uf: 'MG' },
			{ name: 'Jampruca', name_order: 'Jampruca', uf: 'MG' },
			{ name: 'Janaúba', name_order: 'Janauba', uf: 'MG' },
			{ name: 'Januária', name_order: 'Januaria', uf: 'MG' },
			{ name: 'Japaraíba', name_order: 'Japaraiba', uf: 'MG' },
			{ name: 'Japonvar', name_order: 'Japonvar', uf: 'MG' },
			{ name: 'Jeceaba', name_order: 'Jeceaba', uf: 'MG' },
			{ name: 'Jenipapo de Minas', name_order: 'Jenipapo de Minas', uf: 'MG' },
			{ name: 'Jequeri', name_order: 'Jequeri', uf: 'MG' },
			{ name: 'Jequitaí', name_order: 'Jequitai', uf: 'MG' },
			{ name: 'Jequitibá', name_order: 'Jequitiba', uf: 'MG' },
			{ name: 'Jequitinhonha', name_order: 'Jequitinhonha', uf: 'MG' },
			{ name: 'Jesuânia', name_order: 'Jesuania', uf: 'MG' },
			{ name: 'Joaíma', name_order: 'Joaima', uf: 'MG' },
			{ name: 'Joanésia', name_order: 'Joanesia', uf: 'MG' },
			{ name: 'João Monlevade', name_order: 'Joao Monlevade', uf: 'MG' },
			{ name: 'João Pinheiro', name_order: 'Joao Pinheiro', uf: 'MG' },
			{ name: 'Joaquim Felício', name_order: 'Joaquim Felicio', uf: 'MG' },
			{ name: 'Jordânia', name_order: 'Jordania', uf: 'MG' },
			{ name: 'José Gonçalves de Minas', name_order: 'Jose Goncalves de Minas', uf: 'MG' },
			{ name: 'José Raydan', name_order: 'Jose Raydan', uf: 'MG' },
			{ name: 'Josenópolis', name_order: 'Josenopolis', uf: 'MG' },
			{ name: 'Nova União', name_order: 'Nova Uniao', uf: 'MG' },
			{ name: 'Juatuba', name_order: 'Juatuba', uf: 'MG' },
			{ name: 'Juiz de Fora', name_order: 'Juiz de Fora', uf: 'MG' },
			{ name: 'Juramento', name_order: 'Juramento', uf: 'MG' },
			{ name: 'Juruaia', name_order: 'Juruaia', uf: 'MG' },
			{ name: 'Juvenília', name_order: 'Juvenilia', uf: 'MG' },
			{ name: 'Ladainha', name_order: 'Ladainha', uf: 'MG' },
			{ name: 'Lagamar', name_order: 'Lagamar', uf: 'MG' },
			{ name: 'Lagoa da Prata', name_order: 'Lagoa da Prata', uf: 'MG' },
			{ name: 'Lagoa Dos Patos', name_order: 'Lagoa Dos Patos', uf: 'MG' },
			{ name: 'Lagoa Dourada', name_order: 'Lagoa Dourada', uf: 'MG' },
			{ name: 'Lagoa Formosa', name_order: 'Lagoa Formosa', uf: 'MG' },
			{ name: 'Lagoa Grande', name_order: 'Lagoa Grande', uf: 'MG' },
			{ name: 'Lagoa Santa', name_order: 'Lagoa Santa', uf: 'MG' },
			{ name: 'Lajinha', name_order: 'Lajinha', uf: 'MG' },
			{ name: 'Lambari', name_order: 'Lambari', uf: 'MG' },
			{ name: 'Lamim', name_order: 'Lamim', uf: 'MG' },
			{ name: 'Laranjal', name_order: 'Laranjal', uf: 'MG' },
			{ name: 'Lassance', name_order: 'Lassance', uf: 'MG' },
			{ name: 'Lavras', name_order: 'Lavras', uf: 'MG' },
			{ name: 'Leandro Ferreira', name_order: 'Leandro Ferreira', uf: 'MG' },
			{ name: 'Leme do Prado', name_order: 'Leme do Prado', uf: 'MG' },
			{ name: 'Leopoldina', name_order: 'Leopoldina', uf: 'MG' },
			{ name: 'Liberdade', name_order: 'Liberdade', uf: 'MG' },
			{ name: 'Lima Duarte', name_order: 'Lima Duarte', uf: 'MG' },
			{ name: 'Limeira do Oeste', name_order: 'Limeira do Oeste', uf: 'MG' },
			{ name: 'Lontra', name_order: 'Lontra', uf: 'MG' },
			{ name: 'Luisburgo', name_order: 'Luisburgo', uf: 'MG' },
			{ name: 'Luislândia', name_order: 'Luislandia', uf: 'MG' },
			{ name: 'Luminárias', name_order: 'Luminarias', uf: 'MG' },
			{ name: 'Luz', name_order: 'Luz', uf: 'MG' },
			{ name: 'Machacalis', name_order: 'Machacalis', uf: 'MG' },
			{ name: 'Machado', name_order: 'Machado', uf: 'MG' },
			{ name: 'Madre de Deus de Minas', name_order: 'Madre de Deus de Minas', uf: 'MG' },
			{ name: 'Malacacheta', name_order: 'Malacacheta', uf: 'MG' },
			{ name: 'Mamonas', name_order: 'Mamonas', uf: 'MG' },
			{ name: 'Manga', name_order: 'Manga', uf: 'MG' },
			{ name: 'Manhuaçu', name_order: 'Manhuacu', uf: 'MG' },
	]);
};
