exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Água Branca', name_order: 'Agua Branca', uf: 'AL' },
			{ name: 'Anadia', name_order: 'Anadia', uf: 'AL' },
			{ name: 'Arapiraca', name_order: 'Arapiraca', uf: 'AL' },
			{ name: 'Atalaia', name_order: 'Atalaia', uf: 'AL' },
			{ name: 'Barra de Santo Antônio', name_order: 'Barra de Santo Antonio', uf: 'AL' },
			{ name: 'Barra de São Miguel', name_order: 'Barra de Sao Miguel', uf: 'AL' },
			{ name: 'Batalha', name_order: 'Batalha', uf: 'AL' },
			{ name: 'Belém', name_order: 'Belem', uf: 'AL' },
			{ name: 'Belo Monte', name_order: 'Belo Monte', uf: 'AL' },
			{ name: 'Boca da Mata', name_order: 'Boca da Mata', uf: 'AL' },
			{ name: 'Branquinha', name_order: 'Branquinha', uf: 'AL' },
			{ name: 'Cacimbinhas', name_order: 'Cacimbinhas', uf: 'AL' },
			{ name: 'Cajueiro', name_order: 'Cajueiro', uf: 'AL' },
			{ name: 'Campestre', name_order: 'Campestre', uf: 'AL' },
			{ name: 'Campo Alegre', name_order: 'Campo Alegre', uf: 'AL' },
			{ name: 'Campo Grande', name_order: 'Campo Grande', uf: 'AL' },
			{ name: 'Canapi', name_order: 'Canapi', uf: 'AL' },
			{ name: 'Capela', name_order: 'Capela', uf: 'AL' },
			{ name: 'Carneiros', name_order: 'Carneiros', uf: 'AL' },
			{ name: 'Chã Preta', name_order: 'Cha Preta', uf: 'AL' },
			{ name: 'Coité do Nóia', name_order: 'Coite do Noia', uf: 'AL' },
			{ name: 'Colônia Leopoldina', name_order: 'Colonia Leopoldina', uf: 'AL' },
			{ name: 'Coqueiro Seco', name_order: 'Coqueiro Seco', uf: 'AL' },
			{ name: 'Coruripe', name_order: 'Coruripe', uf: 'AL' },
			{ name: 'Craíbas', name_order: 'Craibas', uf: 'AL' },
			{ name: 'Delmiro Gouveia', name_order: 'Delmiro Gouveia', uf: 'AL' },
			{ name: 'Dois Riachos', name_order: 'Dois Riachos', uf: 'AL' },
			{ name: 'Estrela de Alagoas', name_order: 'Estrela de Alagoas', uf: 'AL' },
			{ name: 'Feira Grande', name_order: 'Feira Grande', uf: 'AL' },
			{ name: 'Feliz Deserto', name_order: 'Feliz Deserto', uf: 'AL' },
			{ name: 'Flexeiras', name_order: 'Flexeiras', uf: 'AL' },
			{ name: 'Girau do Ponciano', name_order: 'Girau do Ponciano', uf: 'AL' },
			{ name: 'Ibateguara', name_order: 'Ibateguara', uf: 'AL' },
			{ name: 'Igaci', name_order: 'Igaci', uf: 'AL' },
			{ name: 'Igreja Nova', name_order: 'Igreja Nova', uf: 'AL' },
			{ name: 'Inhapi', name_order: 'Inhapi', uf: 'AL' },
			{ name: 'Jacaré Dos Homens', name_order: 'Jacare Dos Homens', uf: 'AL' },
			{ name: 'Jacuípe', name_order: 'Jacuipe', uf: 'AL' },
			{ name: 'Japaratinga', name_order: 'Japaratinga', uf: 'AL' },
			{ name: 'Jaramataia', name_order: 'Jaramataia', uf: 'AL' },
			{ name: 'Jequiá da Praia', name_order: 'Jequia da Praia', uf: 'AL' },
			{ name: 'Joaquim Gomes', name_order: 'Joaquim Gomes', uf: 'AL' },
			{ name: 'Jundiá', name_order: 'Jundia', uf: 'AL' },
			{ name: 'Junqueiro', name_order: 'Junqueiro', uf: 'AL' },
			{ name: 'Lagoa da Canoa', name_order: 'Lagoa da Canoa', uf: 'AL' },
			{ name: 'Limoeiro de Anadia', name_order: 'Limoeiro de Anadia', uf: 'AL' },
			{ name: 'Maceió', name_order: 'Maceio', uf: 'AL' },
			{ name: 'Major Isidoro', name_order: 'Major Isidoro', uf: 'AL' },
			{ name: 'Maragogi', name_order: 'Maragogi', uf: 'AL' },
			{ name: 'Maravilha', name_order: 'Maravilha', uf: 'AL' },
			{ name: 'Marechal Deodoro', name_order: 'Marechal Deodoro', uf: 'AL' },
			{ name: 'Maribondo', name_order: 'Maribondo', uf: 'AL' },
			{ name: 'Mar Vermelho', name_order: 'Mar Vermelho', uf: 'AL' },
			{ name: 'Mata Grande', name_order: 'Mata Grande', uf: 'AL' },
			{ name: 'Matriz de Camaragibe', name_order: 'Matriz de Camaragibe', uf: 'AL' },
			{ name: 'Messias', name_order: 'Messias', uf: 'AL' },
			{ name: 'Minador do Negrão', name_order: 'Minador do Negrao', uf: 'AL' },
			{ name: 'Monteirópolis', name_order: 'Monteiropolis', uf: 'AL' },
			{ name: 'Murici', name_order: 'Murici', uf: 'AL' },
			{ name: 'Novo Lino', name_order: 'Novo Lino', uf: 'AL' },
			{ name: 'Olho D´água Das Flores', name_order: 'Olho Dagua Das Flores', uf: 'AL' },
			{ name: 'Olho D´água do Casado', name_order: 'Olho Dagua do Casado', uf: 'AL' },
			{ name: 'Olho D´água Grande', name_order: 'Olho Dagua Grande', uf: 'AL' },
			{ name: 'Olivença', name_order: 'Olivenca', uf: 'AL' },
			{ name: 'Ouro Branco', name_order: 'Ouro Branco', uf: 'AL' },
			{ name: 'Palestina', name_order: 'Palestina', uf: 'AL' },
			{ name: 'Palmeira Dos Índios', name_order: 'Palmeira Dos Indios', uf: 'AL' },
			{ name: 'Pão de Açúcar', name_order: 'Pao de Acucar', uf: 'AL' },
			{ name: 'Pariconha', name_order: 'Pariconha', uf: 'AL' },
			{ name: 'Paripueira', name_order: 'Paripueira', uf: 'AL' },
			{ name: 'Passo de Camaragibe', name_order: 'Passo de Camaragibe', uf: 'AL' },
			{ name: 'Paulo Jacinto', name_order: 'Paulo Jacinto', uf: 'AL' },
			{ name: 'Penedo', name_order: 'Penedo', uf: 'AL' },
			{ name: 'Piaçabuçu', name_order: 'Piacabucu', uf: 'AL' },
			{ name: 'Pilar', name_order: 'Pilar', uf: 'AL' },
			{ name: 'Pindoba', name_order: 'Pindoba', uf: 'AL' },
			{ name: 'Piranhas', name_order: 'Piranhas', uf: 'AL' },
			{ name: 'Poço Das Trincheiras', name_order: 'Poco Das Trincheiras', uf: 'AL' },
			{ name: 'Porto Calvo', name_order: 'Porto Calvo', uf: 'AL' },
			{ name: 'Porto de Pedras', name_order: 'Porto de Pedras', uf: 'AL' },
			{ name: 'Porto Real do Colégio', name_order: 'Porto Real do Colegio', uf: 'AL' },
			{ name: 'Quebrangulo', name_order: 'Quebrangulo', uf: 'AL' },
			{ name: 'Rio Largo', name_order: 'Rio Largo', uf: 'AL' },
			{ name: 'Roteiro', name_order: 'Roteiro', uf: 'AL' },
			{ name: 'Santa Luzia do Norte', name_order: 'Santa Luzia do Norte', uf: 'AL' },
			{ name: 'Santana do Ipanema', name_order: 'Santana do Ipanema', uf: 'AL' },
			{ name: 'Santana do Mundaú', name_order: 'Santana do Mundau', uf: 'AL' },
			{ name: 'São Brás', name_order: 'Sao Bras', uf: 'AL' },
			{ name: 'São José da Laje', name_order: 'Sao Jose da Laje', uf: 'AL' },
			{ name: 'São José da Tapera', name_order: 'Sao Jose da Tapera', uf: 'AL' },
			{ name: 'São Luís do Quitunde', name_order: 'Sao Luis do Quitunde', uf: 'AL' },
			{ name: 'São Miguel Dos Campos', name_order: 'Sao Miguel Dos Campos', uf: 'AL' },
			{ name: 'São Miguel Dos Milagres', name_order: 'Sao Miguel Dos Milagres', uf: 'AL' },
			{ name: 'São Sebastião', name_order: 'Sao Sebastiao', uf: 'AL' },
			{ name: 'Satuba', name_order: 'Satuba', uf: 'AL' },
			{ name: 'Senador Rui Palmeira', name_order: 'Senador Rui Palmeira', uf: 'AL' },
			{ name: 'Tanque D´arca', name_order: 'Tanque Darca', uf: 'AL' },
			{ name: 'Taquarana', name_order: 'Taquarana', uf: 'AL' },
			{ name: 'Teotônio Vilela', name_order: 'Teotonio Vilela', uf: 'AL' },
			{ name: 'Traipu', name_order: 'Traipu', uf: 'AL' },
			{ name: 'União Dos Palmares', name_order: 'Uniao Dos Palmares', uf: 'AL' },
			{ name: 'Viçosa', name_order: 'Vicosa', uf: 'AL' },
	]);
};
