exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Abaíra', name_order: 'Abaira', uf: 'BA' },
			{ name: 'Abaré', name_order: 'Abare', uf: 'BA' },
			{ name: 'Acajutiba', name_order: 'Acajutiba', uf: 'BA' },
			{ name: 'Adustina', name_order: 'Adustina', uf: 'BA' },
			{ name: 'Água Fria', name_order: 'Agua Fria', uf: 'BA' },
			{ name: 'Érico Cardoso', name_order: 'Erico Cardoso', uf: 'BA' },
			{ name: 'Aiquara', name_order: 'Aiquara', uf: 'BA' },
			{ name: 'Alagoinhas', name_order: 'Alagoinhas', uf: 'BA' },
			{ name: 'Alcobaça', name_order: 'Alcobaca', uf: 'BA' },
			{ name: 'Almadina', name_order: 'Almadina', uf: 'BA' },
			{ name: 'Amargosa', name_order: 'Amargosa', uf: 'BA' },
			{ name: 'Amélia Rodrigues', name_order: 'Amelia Rodrigues', uf: 'BA' },
			{ name: 'América Dourada', name_order: 'America Dourada', uf: 'BA' },
			{ name: 'Anagé', name_order: 'Anage', uf: 'BA' },
			{ name: 'Andaraí', name_order: 'Andarai', uf: 'BA' },
			{ name: 'Andorinha', name_order: 'Andorinha', uf: 'BA' },
			{ name: 'Angical', name_order: 'Angical', uf: 'BA' },
			{ name: 'Anguera', name_order: 'Anguera', uf: 'BA' },
			{ name: 'Antas', name_order: 'Antas', uf: 'BA' },
			{ name: 'Antônio Cardoso', name_order: 'Antonio Cardoso', uf: 'BA' },
			{ name: 'Antônio Gonçalves', name_order: 'Antonio Goncalves', uf: 'BA' },
			{ name: 'Aporá', name_order: 'Apora', uf: 'BA' },
			{ name: 'Apuarema', name_order: 'Apuarema', uf: 'BA' },
			{ name: 'Aracatu', name_order: 'Aracatu', uf: 'BA' },
			{ name: 'Araças', name_order: 'Aracas', uf: 'BA' },
			{ name: 'Araci', name_order: 'Araci', uf: 'BA' },
			{ name: 'Aramari', name_order: 'Aramari', uf: 'BA' },
			{ name: 'Arataca', name_order: 'Arataca', uf: 'BA' },
			{ name: 'Aratuípe', name_order: 'Aratuipe', uf: 'BA' },
			{ name: 'Aurelino Leal', name_order: 'Aurelino Leal', uf: 'BA' },
			{ name: 'Baianópolis', name_order: 'Baianopolis', uf: 'BA' },
			{ name: 'Baixa Grande', name_order: 'Baixa Grande', uf: 'BA' },
			{ name: 'Banzaê', name_order: 'Banzae', uf: 'BA' },
			{ name: 'Barra', name_order: 'Barra', uf: 'BA' },
			{ name: 'Barra da Estiva', name_order: 'Barra da Estiva', uf: 'BA' },
			{ name: 'Barra do Choça', name_order: 'Barra do Choca', uf: 'BA' },
			{ name: 'Barra do Mendes', name_order: 'Barra do Mendes', uf: 'BA' },
			{ name: 'Barra do Rocha', name_order: 'Barra do Rocha', uf: 'BA' },
			{ name: 'Barreiras', name_order: 'Barreiras', uf: 'BA' },
			{ name: 'Barro Alto', name_order: 'Barro Alto', uf: 'BA' },
			{ name: 'Barrocas', name_order: 'Barrocas', uf: 'BA' },
			{ name: 'Governador Lomanto Júnior', name_order: 'Governador Lomanto Junior', uf: 'BA' },
			{ name: 'Belmonte', name_order: 'Belmonte', uf: 'BA' },
			{ name: 'Belo Campo', name_order: 'Belo Campo', uf: 'BA' },
			{ name: 'Biritinga', name_order: 'Biritinga', uf: 'BA' },
			{ name: 'Boa Nova', name_order: 'Boa Nova', uf: 'BA' },
			{ name: 'Boa Vista do Tupim', name_order: 'Boa Vista do Tupim', uf: 'BA' },
			{ name: 'Bom Jesus da Lapa', name_order: 'Bom Jesus da Lapa', uf: 'BA' },
			{ name: 'Bom Jesus da Serra', name_order: 'Bom Jesus da Serra', uf: 'BA' },
			{ name: 'Boninal', name_order: 'Boninal', uf: 'BA' },
			{ name: 'Bonito', name_order: 'Bonito', uf: 'BA' },
			{ name: 'Boquira', name_order: 'Boquira', uf: 'BA' },
			{ name: 'Botuporã', name_order: 'Botupora', uf: 'BA' },
			{ name: 'Brejões', name_order: 'Brejoes', uf: 'BA' },
			{ name: 'Brejolândia', name_order: 'Brejolandia', uf: 'BA' },
			{ name: 'Brotas de Macaúbas', name_order: 'Brotas de Macaubas', uf: 'BA' },
			{ name: 'Brumado', name_order: 'Brumado', uf: 'BA' },
			{ name: 'Buerarema', name_order: 'Buerarema', uf: 'BA' },
			{ name: 'Buritirama', name_order: 'Buritirama', uf: 'BA' },
			{ name: 'Caatiba', name_order: 'Caatiba', uf: 'BA' },
			{ name: 'Cabaceiras do Paraguaçu', name_order: 'Cabaceiras do Paraguacu', uf: 'BA' },
			{ name: 'Cachoeira', name_order: 'Cachoeira', uf: 'BA' },
			{ name: 'Caculé', name_order: 'Cacule', uf: 'BA' },
			{ name: 'Caém', name_order: 'Caem', uf: 'BA' },
			{ name: 'Caetanos', name_order: 'Caetanos', uf: 'BA' },
			{ name: 'Caetité', name_order: 'Caetite', uf: 'BA' },
			{ name: 'Cafarnaum', name_order: 'Cafarnaum', uf: 'BA' },
			{ name: 'Cairu', name_order: 'Cairu', uf: 'BA' },
			{ name: 'Caldeirão Grande', name_order: 'Caldeirao Grande', uf: 'BA' },
			{ name: 'Camacan', name_order: 'Camacan', uf: 'BA' },
			{ name: 'Camaçari', name_order: 'Camacari', uf: 'BA' },
			{ name: 'Camamu', name_order: 'Camamu', uf: 'BA' },
			{ name: 'Campo Alegre de Lourdes', name_order: 'Campo Alegre de Lourdes', uf: 'BA' },
			{ name: 'Campo Formoso', name_order: 'Campo Formoso', uf: 'BA' },
			{ name: 'Canápolis', name_order: 'Canapolis', uf: 'BA' },
			{ name: 'Canarana', name_order: 'Canarana', uf: 'BA' },
			{ name: 'Canavieiras', name_order: 'Canavieiras', uf: 'BA' },
			{ name: 'Candeal', name_order: 'Candeal', uf: 'BA' },
			{ name: 'Candeias', name_order: 'Candeias', uf: 'BA' },
			{ name: 'Candiba', name_order: 'Candiba', uf: 'BA' },
			{ name: 'Cândido Sales', name_order: 'Candido Sales', uf: 'BA' },
			{ name: 'Cansanção', name_order: 'Cansancao', uf: 'BA' },
			{ name: 'Canudos', name_order: 'Canudos', uf: 'BA' },
			{ name: 'Capela do Alto Alegre', name_order: 'Capela do Alto Alegre', uf: 'BA' },
			{ name: 'Capim Grosso', name_order: 'Capim Grosso', uf: 'BA' },
			{ name: 'Caraíbas', name_order: 'Caraibas', uf: 'BA' },
			{ name: 'Caravelas', name_order: 'Caravelas', uf: 'BA' },
			{ name: 'Cardeal da Silva', name_order: 'Cardeal da Silva', uf: 'BA' },
			{ name: 'Carinhanha', name_order: 'Carinhanha', uf: 'BA' },
			{ name: 'Casa Nova', name_order: 'Casa Nova', uf: 'BA' },
			{ name: 'Castro Alves', name_order: 'Castro Alves', uf: 'BA' },
			{ name: 'Catolândia', name_order: 'Catolandia', uf: 'BA' },
			{ name: 'Catu', name_order: 'Catu', uf: 'BA' },
			{ name: 'Caturama', name_order: 'Caturama', uf: 'BA' },
			{ name: 'Central', name_order: 'Central', uf: 'BA' },
			{ name: 'Chorrochó', name_order: 'Chorrocho', uf: 'BA' },
			{ name: 'Cícero Dantas', name_order: 'Cicero Dantas', uf: 'BA' },
			{ name: 'Cipó', name_order: 'Cipo', uf: 'BA' },
			{ name: 'Coaraci', name_order: 'Coaraci', uf: 'BA' },
			{ name: 'Cocos', name_order: 'Cocos', uf: 'BA' },
			{ name: 'Conceição da Feira', name_order: 'Conceicao da Feira', uf: 'BA' },
			{ name: 'Conceição do Almeida', name_order: 'Conceicao do Almeida', uf: 'BA' },
			{ name: 'Conceição do Coité', name_order: 'Conceicao do Coite', uf: 'BA' },
			{ name: 'Conceição do Jacuípe', name_order: 'Conceicao do Jacuipe', uf: 'BA' },
			{ name: 'Conde', name_order: 'Conde', uf: 'BA' },
			{ name: 'Condeúba', name_order: 'Condeuba', uf: 'BA' },
			{ name: 'Contendas do Sincorá', name_order: 'Contendas do Sincora', uf: 'BA' },
			{ name: 'Coração de Maria', name_order: 'Coracao de Maria', uf: 'BA' },
			{ name: 'Cordeiros', name_order: 'Cordeiros', uf: 'BA' },
			{ name: 'Coribe', name_order: 'Coribe', uf: 'BA' },
			{ name: 'Coronel João sá', name_order: 'Coronel Joao sa', uf: 'BA' },
			{ name: 'Correntina', name_order: 'Correntina', uf: 'BA' },
			{ name: 'Cotegipe', name_order: 'Cotegipe', uf: 'BA' },
			{ name: 'Cravolândia', name_order: 'Cravolandia', uf: 'BA' },
			{ name: 'Crisópolis', name_order: 'Crisopolis', uf: 'BA' },
			{ name: 'Cristópolis', name_order: 'Cristopolis', uf: 'BA' },
			{ name: 'Cruz Das Almas', name_order: 'Cruz Das Almas', uf: 'BA' },
			{ name: 'Curaçá', name_order: 'Curaca', uf: 'BA' },
			{ name: 'Dário Meira', name_order: 'Dario Meira', uf: 'BA' },
			{ name: 'Dias D´ávila', name_order: 'Dias Davila', uf: 'BA' },
			{ name: 'Dom Basílio', name_order: 'Dom Basilio', uf: 'BA' },
			{ name: 'Dom Macedo Costa', name_order: 'Dom Macedo Costa', uf: 'BA' },
			{ name: 'Elísio Medrado', name_order: 'Elisio Medrado', uf: 'BA' },
			{ name: 'Encruzilhada', name_order: 'Encruzilhada', uf: 'BA' },
			{ name: 'Entre Rios', name_order: 'Entre Rios', uf: 'BA' },
			{ name: 'Esplanada', name_order: 'Esplanada', uf: 'BA' },
			{ name: 'Euclides da Cunha', name_order: 'Euclides da Cunha', uf: 'BA' },
			{ name: 'Eunápolis', name_order: 'Eunapolis', uf: 'BA' },
			{ name: 'Fátima', name_order: 'Fatima', uf: 'BA' },
			{ name: 'Feira da Mata', name_order: 'Feira da Mata', uf: 'BA' },
			{ name: 'Feira de Santana', name_order: 'Feira de Santana', uf: 'BA' },
			{ name: 'Filadélfia', name_order: 'Filadelfia', uf: 'BA' },
			{ name: 'Firmino Alves', name_order: 'Firmino Alves', uf: 'BA' },
			{ name: 'Floresta Azul', name_order: 'Floresta Azul', uf: 'BA' },
			{ name: 'Formosa do Rio Preto', name_order: 'Formosa do Rio Preto', uf: 'BA' },
			{ name: 'Gandu', name_order: 'Gandu', uf: 'BA' },
			{ name: 'Gavião', name_order: 'Gaviao', uf: 'BA' },
			{ name: 'Gentio do Ouro', name_order: 'Gentio do Ouro', uf: 'BA' },
			{ name: 'Glória', name_order: 'Gloria', uf: 'BA' },
			{ name: 'Gongogi', name_order: 'Gongogi', uf: 'BA' },
			{ name: 'Governador Mangabeira', name_order: 'Governador Mangabeira', uf: 'BA' },
			{ name: 'Guajeru', name_order: 'Guajeru', uf: 'BA' },
			{ name: 'Guanambi', name_order: 'Guanambi', uf: 'BA' },
			{ name: 'Guaratinga', name_order: 'Guaratinga', uf: 'BA' },
			{ name: 'Heliópolis', name_order: 'Heliopolis', uf: 'BA' },
			{ name: 'Iaçu', name_order: 'Iacu', uf: 'BA' },
			{ name: 'Ibiassucê', name_order: 'Ibiassuce', uf: 'BA' },
			{ name: 'Ibicaraí', name_order: 'Ibicarai', uf: 'BA' },
			{ name: 'Ibicoara', name_order: 'Ibicoara', uf: 'BA' },
			{ name: 'Ibicuí', name_order: 'Ibicui', uf: 'BA' },
			{ name: 'Ibipeba', name_order: 'Ibipeba', uf: 'BA' },
			{ name: 'Ibipitanga', name_order: 'Ibipitanga', uf: 'BA' },
			{ name: 'Ibiquera', name_order: 'Ibiquera', uf: 'BA' },
			{ name: 'Ibirapitanga', name_order: 'Ibirapitanga', uf: 'BA' },
			{ name: 'Ibirapuã', name_order: 'Ibirapua', uf: 'BA' },
			{ name: 'Ibirataia', name_order: 'Ibirataia', uf: 'BA' },
			{ name: 'Ibitiara', name_order: 'Ibitiara', uf: 'BA' },
			{ name: 'Ibititá', name_order: 'Ibitita', uf: 'BA' },
			{ name: 'Ibotirama', name_order: 'Ibotirama', uf: 'BA' },
			{ name: 'Ichu', name_order: 'Ichu', uf: 'BA' },
			{ name: 'Igaporã', name_order: 'Igapora', uf: 'BA' },
			{ name: 'Igrapiúna', name_order: 'Igrapiuna', uf: 'BA' },
			{ name: 'Iguaí', name_order: 'Iguai', uf: 'BA' },
			{ name: 'Ilhéus', name_order: 'Ilheus', uf: 'BA' },
			{ name: 'Inhambupe', name_order: 'Inhambupe', uf: 'BA' },
			{ name: 'Ipecaetá', name_order: 'Ipecaeta', uf: 'BA' },
			{ name: 'Ipiaú', name_order: 'Ipiau', uf: 'BA' },
			{ name: 'Ipirá', name_order: 'Ipira', uf: 'BA' },
			{ name: 'Ipupiara', name_order: 'Ipupiara', uf: 'BA' },
			{ name: 'Irajuba', name_order: 'Irajuba', uf: 'BA' },
			{ name: 'Iramaia', name_order: 'Iramaia', uf: 'BA' },
			{ name: 'Iraquara', name_order: 'Iraquara', uf: 'BA' },
			{ name: 'Irará', name_order: 'Irara', uf: 'BA' },
			{ name: 'Irecê', name_order: 'Irece', uf: 'BA' },
			{ name: 'Itabela', name_order: 'Itabela', uf: 'BA' },
			{ name: 'Itaberaba', name_order: 'Itaberaba', uf: 'BA' },
			{ name: 'Itabuna', name_order: 'Itabuna', uf: 'BA' },
			{ name: 'Itacaré', name_order: 'Itacare', uf: 'BA' },
			{ name: 'Itaeté', name_order: 'Itaete', uf: 'BA' },
			{ name: 'Itagi', name_order: 'Itagi', uf: 'BA' },
			{ name: 'Itagibá', name_order: 'Itagiba', uf: 'BA' },
			{ name: 'Itagimirim', name_order: 'Itagimirim', uf: 'BA' },
			{ name: 'Itaguaçu da Bahia', name_order: 'Itaguacu da Bahia', uf: 'BA' },
			{ name: 'Itaju do Colônia', name_order: 'Itaju do Colonia', uf: 'BA' },
			{ name: 'Itajuípe', name_order: 'Itajuipe', uf: 'BA' },
			{ name: 'Itamaraju', name_order: 'Itamaraju', uf: 'BA' },
			{ name: 'Itamari', name_order: 'Itamari', uf: 'BA' },
			{ name: 'Itambé', name_order: 'Itambe', uf: 'BA' },
			{ name: 'Itanagra', name_order: 'Itanagra', uf: 'BA' },
			{ name: 'Itanhém', name_order: 'Itanhem', uf: 'BA' },
			{ name: 'Itaparica', name_order: 'Itaparica', uf: 'BA' },
			{ name: 'Itapé', name_order: 'Itape', uf: 'BA' },
			{ name: 'Itapebi', name_order: 'Itapebi', uf: 'BA' },
			{ name: 'Itapetinga', name_order: 'Itapetinga', uf: 'BA' },
			{ name: 'Itapicuru', name_order: 'Itapicuru', uf: 'BA' },
			{ name: 'Itapitanga', name_order: 'Itapitanga', uf: 'BA' },
			{ name: 'Itaquara', name_order: 'Itaquara', uf: 'BA' },
			{ name: 'Itarantim', name_order: 'Itarantim', uf: 'BA' },
			{ name: 'Itatim', name_order: 'Itatim', uf: 'BA' },
			{ name: 'Itiruçu', name_order: 'Itirucu', uf: 'BA' },
			{ name: 'Itiúba', name_order: 'Itiuba', uf: 'BA' },
			{ name: 'Itororó', name_order: 'Itororo', uf: 'BA' },
			{ name: 'Ituaçu', name_order: 'Ituacu', uf: 'BA' },
			{ name: 'Ituberá', name_order: 'Itubera', uf: 'BA' },
			{ name: 'Iuiú', name_order: 'Iuiu', uf: 'BA' },
			{ name: 'Jaborandi', name_order: 'Jaborandi', uf: 'BA' },
			{ name: 'Jacaraci', name_order: 'Jacaraci', uf: 'BA' },
			{ name: 'Jacobina', name_order: 'Jacobina', uf: 'BA' },
			{ name: 'Jaguaquara', name_order: 'Jaguaquara', uf: 'BA' },
			{ name: 'Jaguarari', name_order: 'Jaguarari', uf: 'BA' },
			{ name: 'Jaguaripe', name_order: 'Jaguaripe', uf: 'BA' },
			{ name: 'Jandaíra', name_order: 'Jandaira', uf: 'BA' },
			{ name: 'Jequié', name_order: 'Jequie', uf: 'BA' },
			{ name: 'Jeremoabo', name_order: 'Jeremoabo', uf: 'BA' },
			{ name: 'Jiquiriçá', name_order: 'Jiquirica', uf: 'BA' },
			{ name: 'Jitaúna', name_order: 'Jitauna', uf: 'BA' },
			{ name: 'João Dourado', name_order: 'Joao Dourado', uf: 'BA' },
			{ name: 'Juazeiro', name_order: 'Juazeiro', uf: 'BA' },
			{ name: 'Jucuruçu', name_order: 'Jucurucu', uf: 'BA' },
			{ name: 'Jussara', name_order: 'Jussara', uf: 'BA' },
			{ name: 'Jussari', name_order: 'Jussari', uf: 'BA' },
			{ name: 'Jussiape', name_order: 'Jussiape', uf: 'BA' },
			{ name: 'Lafaiete Coutinho', name_order: 'Lafaiete Coutinho', uf: 'BA' },
			{ name: 'Lagoa Real', name_order: 'Lagoa Real', uf: 'BA' },
			{ name: 'Laje', name_order: 'Laje', uf: 'BA' },
			{ name: 'Lajedão', name_order: 'Lajedao', uf: 'BA' },
			{ name: 'Lajedinho', name_order: 'Lajedinho', uf: 'BA' },
			{ name: 'Lajedo do Tabocal', name_order: 'Lajedo do Tabocal', uf: 'BA' },
			{ name: 'Lamarão', name_order: 'Lamarao', uf: 'BA' },
			{ name: 'Lapão', name_order: 'Lapao', uf: 'BA' },
			{ name: 'Lauro de Freitas', name_order: 'Lauro de Freitas', uf: 'BA' },
			{ name: 'Lençóis', name_order: 'Lencois', uf: 'BA' },
			{ name: 'Licínio de Almeida', name_order: 'Licinio de Almeida', uf: 'BA' },
			{ name: 'Livramento de Nossa Senhora', name_order: 'Livramento de Nossa Senhora', uf: 'BA' },
			{ name: 'Luís Eduardo Magalhães', name_order: 'Luis Eduardo Magalhaes', uf: 'BA' },
			{ name: 'Macajuba', name_order: 'Macajuba', uf: 'BA' },
			{ name: 'Macarani', name_order: 'Macarani', uf: 'BA' },
			{ name: 'Macaúbas', name_order: 'Macaubas', uf: 'BA' },
			{ name: 'Macururé', name_order: 'Macurure', uf: 'BA' },
			{ name: 'Madre de Deus', name_order: 'Madre de Deus', uf: 'BA' },
			{ name: 'Maetinga', name_order: 'Maetinga', uf: 'BA' },
			{ name: 'Maiquinique', name_order: 'Maiquinique', uf: 'BA' },
			{ name: 'Mairi', name_order: 'Mairi', uf: 'BA' },
			{ name: 'Malhada', name_order: 'Malhada', uf: 'BA' },
			{ name: 'Malhada de Pedras', name_order: 'Malhada de Pedras', uf: 'BA' },
			{ name: 'Manoel Vitorino', name_order: 'Manoel Vitorino', uf: 'BA' },
			{ name: 'Mansidão', name_order: 'Mansidao', uf: 'BA' },
			{ name: 'Maracás', name_order: 'Maracas', uf: 'BA' },
			{ name: 'Maragogipe', name_order: 'Maragogipe', uf: 'BA' },
			{ name: 'Maraú', name_order: 'Marau', uf: 'BA' },
			{ name: 'Marcionílio Souza', name_order: 'Marcionilio Souza', uf: 'BA' },
			{ name: 'Mascote', name_order: 'Mascote', uf: 'BA' },
			{ name: 'Mata de São João', name_order: 'Mata de Sao Joao', uf: 'BA' },
			{ name: 'Matina', name_order: 'Matina', uf: 'BA' },
			{ name: 'Medeiros Neto', name_order: 'Medeiros Neto', uf: 'BA' },
			{ name: 'Miguel Calmon', name_order: 'Miguel Calmon', uf: 'BA' },
			{ name: 'Milagres', name_order: 'Milagres', uf: 'BA' },
			{ name: 'Mirangaba', name_order: 'Mirangaba', uf: 'BA' },
			{ name: 'Mirante', name_order: 'Mirante', uf: 'BA' },
			{ name: 'Monte Santo', name_order: 'Monte Santo', uf: 'BA' },
			{ name: 'Morpará', name_order: 'Morpara', uf: 'BA' },
			{ name: 'Morro do Chapéu', name_order: 'Morro do Chapeu', uf: 'BA' },
			{ name: 'Mortugaba', name_order: 'Mortugaba', uf: 'BA' },
			{ name: 'Mucugê', name_order: 'Mucuge', uf: 'BA' },
			{ name: 'Mucuri', name_order: 'Mucuri', uf: 'BA' },
			{ name: 'Mulungu do Morro', name_order: 'Mulungu do Morro', uf: 'BA' },
			{ name: 'Mundo Novo', name_order: 'Mundo Novo', uf: 'BA' },
			{ name: 'Muniz Ferreira', name_order: 'Muniz Ferreira', uf: 'BA' },
			{ name: 'Muquém de São Francisco', name_order: 'Muquem de Sao Francisco', uf: 'BA' },
			{ name: 'Muritiba', name_order: 'Muritiba', uf: 'BA' },
			{ name: 'Mutuípe', name_order: 'Mutuipe', uf: 'BA' },
			{ name: 'Nazaré', name_order: 'Nazare', uf: 'BA' },
	]);
};
