exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Araçoiaba da Serra', name_order: 'Aracoiaba da Serra', uf: 'SP' },
			{ name: 'Aramina', name_order: 'Aramina', uf: 'SP' },
			{ name: 'Arandu', name_order: 'Arandu', uf: 'SP' },
			{ name: 'Arapeí', name_order: 'Arapei', uf: 'SP' },
			{ name: 'Araraquara', name_order: 'Araraquara', uf: 'SP' },
			{ name: 'Araras', name_order: 'Araras', uf: 'SP' },
			{ name: 'Arco-íris', name_order: 'Arcoiris', uf: 'SP' },
			{ name: 'Arealva', name_order: 'Arealva', uf: 'SP' },
			{ name: 'Areias', name_order: 'Areias', uf: 'SP' },
			{ name: 'Areiópolis', name_order: 'Areiopolis', uf: 'SP' },
			{ name: 'Ariranha', name_order: 'Ariranha', uf: 'SP' },
			{ name: 'Artur Nogueira', name_order: 'Artur Nogueira', uf: 'SP' },
			{ name: 'Arujá', name_order: 'Aruja', uf: 'SP' },
			{ name: 'Aspásia', name_order: 'Aspasia', uf: 'SP' },
			{ name: 'Assis', name_order: 'Assis', uf: 'SP' },
			{ name: 'Atibaia', name_order: 'Atibaia', uf: 'SP' },
			{ name: 'Auriflama', name_order: 'Auriflama', uf: 'SP' },
			{ name: 'Avaí', name_order: 'Avai', uf: 'SP' },
			{ name: 'Avanhandava', name_order: 'Avanhandava', uf: 'SP' },
			{ name: 'Avaré', name_order: 'Avare', uf: 'SP' },
			{ name: 'Bady Bassitt', name_order: 'Bady Bassitt', uf: 'SP' },
			{ name: 'Balbinos', name_order: 'Balbinos', uf: 'SP' },
			{ name: 'Bálsamo', name_order: 'Balsamo', uf: 'SP' },
			{ name: 'Bananal', name_order: 'Bananal', uf: 'SP' },
			{ name: 'Barão de Antonina', name_order: 'Barao de Antonina', uf: 'SP' },
			{ name: 'Barbosa', name_order: 'Barbosa', uf: 'SP' },
			{ name: 'Bariri', name_order: 'Bariri', uf: 'SP' },
			{ name: 'Barra Bonita', name_order: 'Barra Bonita', uf: 'SP' },
			{ name: 'Barra do Chapéu', name_order: 'Barra do Chapeu', uf: 'SP' },
			{ name: 'Barra do Turvo', name_order: 'Barra do Turvo', uf: 'SP' },
			{ name: 'Barretos', name_order: 'Barretos', uf: 'SP' },
			{ name: 'Barrinha', name_order: 'Barrinha', uf: 'SP' },
			{ name: 'Barueri', name_order: 'Barueri', uf: 'SP' },
			{ name: 'Bastos', name_order: 'Bastos', uf: 'SP' },
			{ name: 'Batatais', name_order: 'Batatais', uf: 'SP' },
			{ name: 'Bauru', name_order: 'Bauru', uf: 'SP' },
			{ name: 'Bebedouro', name_order: 'Bebedouro', uf: 'SP' },
			{ name: 'Bento de Abreu', name_order: 'Bento de Abreu', uf: 'SP' },
			{ name: 'Bernardino de Campos', name_order: 'Bernardino de Campos', uf: 'SP' },
			{ name: 'Bertioga', name_order: 'Bertioga', uf: 'SP' },
			{ name: 'Bilac', name_order: 'Bilac', uf: 'SP' },
			{ name: 'Birigui', name_order: 'Birigui', uf: 'SP' },
			{ name: 'Biritiba-mirim', name_order: 'Biritibamirim', uf: 'SP' },
			{ name: 'Boa Esperança do Sul', name_order: 'Boa Esperanca do Sul', uf: 'SP' },
			{ name: 'Bocaina', name_order: 'Bocaina', uf: 'SP' },
			{ name: 'Bofete', name_order: 'Bofete', uf: 'SP' },
			{ name: 'Boituva', name_order: 'Boituva', uf: 'SP' },
			{ name: 'Bom Jesus Dos Perdões', name_order: 'Bom Jesus Dos Perdoes', uf: 'SP' },
			{ name: 'Bom Sucesso de Itararé', name_order: 'Bom Sucesso de Itarare', uf: 'SP' },
			{ name: 'Borá', name_order: 'Bora', uf: 'SP' },
			{ name: 'Boracéia', name_order: 'Boraceia', uf: 'SP' },
			{ name: 'Borborema', name_order: 'Borborema', uf: 'SP' },
			{ name: 'Borebi', name_order: 'Borebi', uf: 'SP' },
			{ name: 'Botucatu', name_order: 'Botucatu', uf: 'SP' },
			{ name: 'Bragança Paulista', name_order: 'Braganca Paulista', uf: 'SP' },
			{ name: 'Braúna', name_order: 'Brauna', uf: 'SP' },
			{ name: 'Brejo Alegre', name_order: 'Brejo Alegre', uf: 'SP' },
			{ name: 'Brodowski', name_order: 'Brodowski', uf: 'SP' },
			{ name: 'Brotas', name_order: 'Brotas', uf: 'SP' },
			{ name: 'Buri', name_order: 'Buri', uf: 'SP' },
			{ name: 'Buritama', name_order: 'Buritama', uf: 'SP' },
			{ name: 'Buritizal', name_order: 'Buritizal', uf: 'SP' },
			{ name: 'Cabrália Paulista', name_order: 'Cabralia Paulista', uf: 'SP' },
			{ name: 'Cabreúva', name_order: 'Cabreuva', uf: 'SP' },
			{ name: 'Caçapava', name_order: 'Cacapava', uf: 'SP' },
			{ name: 'Cachoeira Paulista', name_order: 'Cachoeira Paulista', uf: 'SP' },
			{ name: 'Caconde', name_order: 'Caconde', uf: 'SP' },
			{ name: 'Cafelândia', name_order: 'Cafelandia', uf: 'SP' },
			{ name: 'Caiabu', name_order: 'Caiabu', uf: 'SP' },
			{ name: 'Caieiras', name_order: 'Caieiras', uf: 'SP' },
			{ name: 'Caiuá', name_order: 'Caiua', uf: 'SP' },
			{ name: 'Cajamar', name_order: 'Cajamar', uf: 'SP' },
			{ name: 'Cajati', name_order: 'Cajati', uf: 'SP' },
			{ name: 'Cajobi', name_order: 'Cajobi', uf: 'SP' },
			{ name: 'Cajuru', name_order: 'Cajuru', uf: 'SP' },
			{ name: 'Campina do Monte Alegre', name_order: 'Campina do Monte Alegre', uf: 'SP' },
			{ name: 'Campinas', name_order: 'Campinas', uf: 'SP' },
			{ name: 'Campo Limpo Paulista', name_order: 'Campo Limpo Paulista', uf: 'SP' },
			{ name: 'Campos do Jordão', name_order: 'Campos do Jordao', uf: 'SP' },
			{ name: 'Campos Novos Paulista', name_order: 'Campos Novos Paulista', uf: 'SP' },
			{ name: 'Cananéia', name_order: 'Cananeia', uf: 'SP' },
			{ name: 'Canas', name_order: 'Canas', uf: 'SP' },
			{ name: 'Cândido Mota', name_order: 'Candido Mota', uf: 'SP' },
			{ name: 'Cândido Rodrigues', name_order: 'Candido Rodrigues', uf: 'SP' },
			{ name: 'Canitar', name_order: 'Canitar', uf: 'SP' },
			{ name: 'Capão Bonito', name_order: 'Capao Bonito', uf: 'SP' },
			{ name: 'Capela do Alto', name_order: 'Capela do Alto', uf: 'SP' },
			{ name: 'Capivari', name_order: 'Capivari', uf: 'SP' },
			{ name: 'Caraguatatuba', name_order: 'Caraguatatuba', uf: 'SP' },
			{ name: 'Carapicuíba', name_order: 'Carapicuiba', uf: 'SP' },
			{ name: 'Cardoso', name_order: 'Cardoso', uf: 'SP' },
			{ name: 'Casa Branca', name_order: 'Casa Branca', uf: 'SP' },
			{ name: 'Cássia Dos Coqueiros', name_order: 'Cassia Dos Coqueiros', uf: 'SP' },
			{ name: 'Castilho', name_order: 'Castilho', uf: 'SP' },
			{ name: 'Catanduva', name_order: 'Catanduva', uf: 'SP' },
			{ name: 'Catiguá', name_order: 'Catigua', uf: 'SP' },
			{ name: 'Cedral', name_order: 'Cedral', uf: 'SP' },
			{ name: 'Cerqueira César', name_order: 'Cerqueira Cesar', uf: 'SP' },
			{ name: 'Cerquilho', name_order: 'Cerquilho', uf: 'SP' },
			{ name: 'Cesário Lange', name_order: 'Cesario Lange', uf: 'SP' },
			{ name: 'Charqueada', name_order: 'Charqueada', uf: 'SP' },
			{ name: 'Clementina', name_order: 'Clementina', uf: 'SP' },
			{ name: 'Colina', name_order: 'Colina', uf: 'SP' },
			{ name: 'Colômbia', name_order: 'Colombia', uf: 'SP' },
			{ name: 'Conchal', name_order: 'Conchal', uf: 'SP' },
			{ name: 'Conchas', name_order: 'Conchas', uf: 'SP' },
			{ name: 'Cordeirópolis', name_order: 'Cordeiropolis', uf: 'SP' },
			{ name: 'Coroados', name_order: 'Coroados', uf: 'SP' },
			{ name: 'Coronel Macedo', name_order: 'Coronel Macedo', uf: 'SP' },
			{ name: 'Corumbataí', name_order: 'Corumbatai', uf: 'SP' },
			{ name: 'Cosmópolis', name_order: 'Cosmopolis', uf: 'SP' },
			{ name: 'Cosmorama', name_order: 'Cosmorama', uf: 'SP' },
			{ name: 'Cotia', name_order: 'Cotia', uf: 'SP' },
			{ name: 'Cravinhos', name_order: 'Cravinhos', uf: 'SP' },
			{ name: 'Cristais Paulista', name_order: 'Cristais Paulista', uf: 'SP' },
			{ name: 'Cruzália', name_order: 'Cruzalia', uf: 'SP' },
			{ name: 'Cruzeiro', name_order: 'Cruzeiro', uf: 'SP' },
			{ name: 'Cubatão', name_order: 'Cubatao', uf: 'SP' },
			{ name: 'Cunha', name_order: 'Cunha', uf: 'SP' },
			{ name: 'Descalvado', name_order: 'Descalvado', uf: 'SP' },
			{ name: 'Diadema', name_order: 'Diadema', uf: 'SP' },
			{ name: 'Dirce Reis', name_order: 'Dirce Reis', uf: 'SP' },
			{ name: 'Divinolândia', name_order: 'Divinolandia', uf: 'SP' },
			{ name: 'Dobrada', name_order: 'Dobrada', uf: 'SP' },
			{ name: 'Dois Córregos', name_order: 'Dois Corregos', uf: 'SP' },
			{ name: 'Dolcinópolis', name_order: 'Dolcinopolis', uf: 'SP' },
			{ name: 'Dourado', name_order: 'Dourado', uf: 'SP' },
			{ name: 'Dracena', name_order: 'Dracena', uf: 'SP' },
			{ name: 'Duartina', name_order: 'Duartina', uf: 'SP' },
			{ name: 'Dumont', name_order: 'Dumont', uf: 'SP' },
			{ name: 'Echaporã', name_order: 'Echapora', uf: 'SP' },
			{ name: 'Eldorado', name_order: 'Eldorado', uf: 'SP' },
			{ name: 'Elias Fausto', name_order: 'Elias Fausto', uf: 'SP' },
			{ name: 'Elisiário', name_order: 'Elisiario', uf: 'SP' },
			{ name: 'Embaúba', name_order: 'Embauba', uf: 'SP' },
			{ name: 'Embu', name_order: 'Embu', uf: 'SP' },
			{ name: 'Embu-guaçu', name_order: 'Embuguacu', uf: 'SP' },
			{ name: 'Emilianópolis', name_order: 'Emilianopolis', uf: 'SP' },
			{ name: 'Engenheiro Coelho', name_order: 'Engenheiro Coelho', uf: 'SP' },
			{ name: 'Espírito Santo do Pinhal', name_order: 'Espirito Santo do Pinhal', uf: 'SP' },
			{ name: 'Espírito Santo do Turvo', name_order: 'Espirito Santo do Turvo', uf: 'SP' },
			{ name: 'Estrela D´oeste', name_order: 'Estrela Doeste', uf: 'SP' },
			{ name: 'Estrela do Norte', name_order: 'Estrela do Norte', uf: 'SP' },
			{ name: 'Euclides da Cunha Paulista', name_order: 'Euclides da Cunha Paulista', uf: 'SP' },
			{ name: 'Fartura', name_order: 'Fartura', uf: 'SP' },
			{ name: 'Fernandópolis', name_order: 'Fernandopolis', uf: 'SP' },
			{ name: 'Fernando Prestes', name_order: 'Fernando Prestes', uf: 'SP' },
			{ name: 'Fernão', name_order: 'Fernao', uf: 'SP' },
			{ name: 'Ferraz de Vasconcelos', name_order: 'Ferraz de Vasconcelos', uf: 'SP' },
			{ name: 'Flora Rica', name_order: 'Flora Rica', uf: 'SP' },
			{ name: 'Floreal', name_order: 'Floreal', uf: 'SP' },
			{ name: 'Flórida Paulista', name_order: 'Florida Paulista', uf: 'SP' },
			{ name: 'Florínia', name_order: 'Florinia', uf: 'SP' },
			{ name: 'Franca', name_order: 'Franca', uf: 'SP' },
			{ name: 'Francisco Morato', name_order: 'Francisco Morato', uf: 'SP' },
			{ name: 'Franco da Rocha', name_order: 'Franco da Rocha', uf: 'SP' },
			{ name: 'Gabriel Monteiro', name_order: 'Gabriel Monteiro', uf: 'SP' },
			{ name: 'Gália', name_order: 'Galia', uf: 'SP' },
			{ name: 'Garça', name_order: 'Garca', uf: 'SP' },
			{ name: 'Gastão Vidigal', name_order: 'Gastao Vidigal', uf: 'SP' },
			{ name: 'Gavião Peixoto', name_order: 'Gaviao Peixoto', uf: 'SP' },
			{ name: 'General Salgado', name_order: 'General Salgado', uf: 'SP' },
			{ name: 'Getulina', name_order: 'Getulina', uf: 'SP' },
			{ name: 'Glicério', name_order: 'Glicerio', uf: 'SP' },
			{ name: 'Guaiçara', name_order: 'Guaicara', uf: 'SP' },
			{ name: 'Guaimbê', name_order: 'Guaimbe', uf: 'SP' },
			{ name: 'Guaíra', name_order: 'Guaira', uf: 'SP' },
			{ name: 'Guapiaçu', name_order: 'Guapiacu', uf: 'SP' },
			{ name: 'Guapiara', name_order: 'Guapiara', uf: 'SP' },
			{ name: 'Guará', name_order: 'Guara', uf: 'SP' },
			{ name: 'Guaraçaí', name_order: 'Guaracai', uf: 'SP' },
			{ name: 'Guaraci', name_order: 'Guaraci', uf: 'SP' },
			{ name: 'Guarani D´oeste', name_order: 'Guarani Doeste', uf: 'SP' },
			{ name: 'Guarantã', name_order: 'Guaranta', uf: 'SP' },
			{ name: 'Guararapes', name_order: 'Guararapes', uf: 'SP' },
			{ name: 'Guararema', name_order: 'Guararema', uf: 'SP' },
			{ name: 'Guaratinguetá', name_order: 'Guaratingueta', uf: 'SP' },
			{ name: 'Guareí', name_order: 'Guarei', uf: 'SP' },
			{ name: 'Guariba', name_order: 'Guariba', uf: 'SP' },
			{ name: 'Guarujá', name_order: 'Guaruja', uf: 'SP' },
			{ name: 'Guarulhos', name_order: 'Guarulhos', uf: 'SP' },
			{ name: 'Guatapará', name_order: 'Guatapara', uf: 'SP' },
			{ name: 'Guzolândia', name_order: 'Guzolandia', uf: 'SP' },
			{ name: 'Herculândia', name_order: 'Herculandia', uf: 'SP' },
			{ name: 'Holambra', name_order: 'Holambra', uf: 'SP' },
			{ name: 'Hortolândia', name_order: 'Hortolandia', uf: 'SP' },
			{ name: 'Iacanga', name_order: 'Iacanga', uf: 'SP' },
			{ name: 'Iacri', name_order: 'Iacri', uf: 'SP' },
			{ name: 'Iaras', name_order: 'Iaras', uf: 'SP' },
			{ name: 'Ibaté', name_order: 'Ibate', uf: 'SP' },
			{ name: 'Ibirá', name_order: 'Ibira', uf: 'SP' },
			{ name: 'Ibirarema', name_order: 'Ibirarema', uf: 'SP' },
			{ name: 'Ibitinga', name_order: 'Ibitinga', uf: 'SP' },
			{ name: 'Ibiúna', name_order: 'Ibiuna', uf: 'SP' },
			{ name: 'Icém', name_order: 'Icem', uf: 'SP' },
			{ name: 'Iepê', name_order: 'Iepe', uf: 'SP' },
			{ name: 'Igaraçu do Tietê', name_order: 'Igaracu do Tiete', uf: 'SP' },
			{ name: 'Igarapava', name_order: 'Igarapava', uf: 'SP' },
			{ name: 'Igaratá', name_order: 'Igarata', uf: 'SP' },
			{ name: 'Iguape', name_order: 'Iguape', uf: 'SP' },
			{ name: 'Ilhabela', name_order: 'Ilhabela', uf: 'SP' },
			{ name: 'Ilha Comprida', name_order: 'Ilha Comprida', uf: 'SP' },
			{ name: 'Ilha Solteira', name_order: 'Ilha Solteira', uf: 'SP' },
			{ name: 'Indaiatuba', name_order: 'Indaiatuba', uf: 'SP' },
			{ name: 'Indiana', name_order: 'Indiana', uf: 'SP' },
			{ name: 'Indiaporã', name_order: 'Indiapora', uf: 'SP' },
			{ name: 'Inúbia Paulista', name_order: 'Inubia Paulista', uf: 'SP' },
			{ name: 'Ipaussu', name_order: 'Ipaussu', uf: 'SP' },
			{ name: 'Iperó', name_order: 'Ipero', uf: 'SP' },
			{ name: 'Ipeúna', name_order: 'Ipeuna', uf: 'SP' },
			{ name: 'Ipiguá', name_order: 'Ipigua', uf: 'SP' },
			{ name: 'Iporanga', name_order: 'Iporanga', uf: 'SP' },
			{ name: 'Ipuã', name_order: 'Ipua', uf: 'SP' },
			{ name: 'Iracemápolis', name_order: 'Iracemapolis', uf: 'SP' },
			{ name: 'Irapuã', name_order: 'Irapua', uf: 'SP' },
			{ name: 'Irapuru', name_order: 'Irapuru', uf: 'SP' },
			{ name: 'Itaberá', name_order: 'Itabera', uf: 'SP' },
			{ name: 'Itaí', name_order: 'Itai', uf: 'SP' },
			{ name: 'Itajobi', name_order: 'Itajobi', uf: 'SP' },
			{ name: 'Itaju', name_order: 'Itaju', uf: 'SP' },
			{ name: 'Itanhaém', name_order: 'Itanhaem', uf: 'SP' },
			{ name: 'Itaóca', name_order: 'Itaoca', uf: 'SP' },
			{ name: 'Itapecerica da Serra', name_order: 'Itapecerica da Serra', uf: 'SP' },
			{ name: 'Itapetininga', name_order: 'Itapetininga', uf: 'SP' },
			{ name: 'Itapeva', name_order: 'Itapeva', uf: 'SP' },
			{ name: 'Itapevi', name_order: 'Itapevi', uf: 'SP' },
			{ name: 'Itapira', name_order: 'Itapira', uf: 'SP' },
			{ name: 'Itapirapuã Paulista', name_order: 'Itapirapua Paulista', uf: 'SP' },
			{ name: 'Itápolis', name_order: 'Itapolis', uf: 'SP' },
			{ name: 'Itaporanga', name_order: 'Itaporanga', uf: 'SP' },
			{ name: 'Itapuí', name_order: 'Itapui', uf: 'SP' },
			{ name: 'Itapura', name_order: 'Itapura', uf: 'SP' },
			{ name: 'Itaquaquecetuba', name_order: 'Itaquaquecetuba', uf: 'SP' },
			{ name: 'Itararé', name_order: 'Itarare', uf: 'SP' },
			{ name: 'Itariri', name_order: 'Itariri', uf: 'SP' },
			{ name: 'Itatiba', name_order: 'Itatiba', uf: 'SP' },
			{ name: 'Itatinga', name_order: 'Itatinga', uf: 'SP' },
			{ name: 'Itirapina', name_order: 'Itirapina', uf: 'SP' },
			{ name: 'Itirapuã', name_order: 'Itirapua', uf: 'SP' },
			{ name: 'Itobi', name_order: 'Itobi', uf: 'SP' },
			{ name: 'Itu', name_order: 'Itu', uf: 'SP' },
			{ name: 'Itupeva', name_order: 'Itupeva', uf: 'SP' },
			{ name: 'Ituverava', name_order: 'Ituverava', uf: 'SP' },
			{ name: 'Jaborandi', name_order: 'Jaborandi', uf: 'SP' },
			{ name: 'Jaboticabal', name_order: 'Jaboticabal', uf: 'SP' },
			{ name: 'Jacareí', name_order: 'Jacarei', uf: 'SP' },
			{ name: 'Jaci', name_order: 'Jaci', uf: 'SP' },
			{ name: 'Jacupiranga', name_order: 'Jacupiranga', uf: 'SP' },
			{ name: 'Jaguariúna', name_order: 'Jaguariuna', uf: 'SP' },
			{ name: 'Jales', name_order: 'Jales', uf: 'SP' },
			{ name: 'Jambeiro', name_order: 'Jambeiro', uf: 'SP' },
			{ name: 'Jandira', name_order: 'Jandira', uf: 'SP' },
			{ name: 'Jardinópolis', name_order: 'Jardinopolis', uf: 'SP' },
			{ name: 'Jarinu', name_order: 'Jarinu', uf: 'SP' },
			{ name: 'Jaú', name_order: 'Jau', uf: 'SP' },
			{ name: 'Jeriquara', name_order: 'Jeriquara', uf: 'SP' },
			{ name: 'Joanópolis', name_order: 'Joanopolis', uf: 'SP' },
			{ name: 'João Ramalho', name_order: 'Joao Ramalho', uf: 'SP' },
			{ name: 'José Bonifácio', name_order: 'Jose Bonifacio', uf: 'SP' },
			{ name: 'Júlio Mesquita', name_order: 'Julio Mesquita', uf: 'SP' },
			{ name: 'Jumirim', name_order: 'Jumirim', uf: 'SP' },
			{ name: 'Jundiaí', name_order: 'Jundiai', uf: 'SP' },
			{ name: 'Junqueirópolis', name_order: 'Junqueiropolis', uf: 'SP' },
			{ name: 'Juquiá', name_order: 'Juquia', uf: 'SP' },
			{ name: 'Juquitiba', name_order: 'Juquitiba', uf: 'SP' },
			{ name: 'Lagoinha', name_order: 'Lagoinha', uf: 'SP' },
			{ name: 'Laranjal Paulista', name_order: 'Laranjal Paulista', uf: 'SP' },
			{ name: 'Lavínia', name_order: 'Lavinia', uf: 'SP' },
			{ name: 'Lavrinhas', name_order: 'Lavrinhas', uf: 'SP' },
			{ name: 'Leme', name_order: 'Leme', uf: 'SP' },
			{ name: 'Lençóis Paulista', name_order: 'Lencois Paulista', uf: 'SP' },
			{ name: 'Limeira', name_order: 'Limeira', uf: 'SP' },
			{ name: 'Lindóia', name_order: 'Lindoia', uf: 'SP' },
			{ name: 'Lins', name_order: 'Lins', uf: 'SP' },
			{ name: 'Lorena', name_order: 'Lorena', uf: 'SP' },
			{ name: 'Lourdes', name_order: 'Lourdes', uf: 'SP' },
			{ name: 'Louveira', name_order: 'Louveira', uf: 'SP' },
			{ name: 'Lucélia', name_order: 'Lucelia', uf: 'SP' },
			{ name: 'Lucianópolis', name_order: 'Lucianopolis', uf: 'SP' },
			{ name: 'Luís Antônio', name_order: 'Luis Antonio', uf: 'SP' },
			{ name: 'Luiziânia', name_order: 'Luiziania', uf: 'SP' },
			{ name: 'Lupércio', name_order: 'Lupercio', uf: 'SP' },
			{ name: 'Lutécia', name_order: 'Lutecia', uf: 'SP' },
			{ name: 'Macatuba', name_order: 'Macatuba', uf: 'SP' },
			{ name: 'Macaubal', name_order: 'Macaubal', uf: 'SP' },
			{ name: 'Macedônia', name_order: 'Macedonia', uf: 'SP' },
			{ name: 'Magda', name_order: 'Magda', uf: 'SP' },
			{ name: 'Mairinque', name_order: 'Mairinque', uf: 'SP' },
			{ name: 'Mairiporã', name_order: 'Mairipora', uf: 'SP' },
			{ name: 'Manduri', name_order: 'Manduri', uf: 'SP' },
			{ name: 'Marabá Paulista', name_order: 'Maraba Paulista', uf: 'SP' },
			{ name: 'Maracaí', name_order: 'Maracai', uf: 'SP' },
			{ name: 'Marapoama', name_order: 'Marapoama', uf: 'SP' },
			{ name: 'Mariápolis', name_order: 'Mariapolis', uf: 'SP' },
			{ name: 'Marília', name_order: 'Marilia', uf: 'SP' },
			{ name: 'Marinópolis', name_order: 'Marinopolis', uf: 'SP' },
			{ name: 'Martinópolis', name_order: 'Martinopolis', uf: 'SP' },
			{ name: 'Matão', name_order: 'Matao', uf: 'SP' },
			{ name: 'Mauá', name_order: 'Maua', uf: 'SP' },
			{ name: 'Mendonça', name_order: 'Mendonca', uf: 'SP' },
	]);
};
