exports.seed = function(knex) {
	return knex("cities").insert([
{ name: 'Acorizal', name_order: 'Acorizal', uf: 'MT' },
			{ name: 'Água Boa', name_order: 'Agua Boa', uf: 'MT' },
			{ name: 'Alta Floresta', name_order: 'Alta Floresta', uf: 'MT' },
			{ name: 'Alto Araguaia', name_order: 'Alto Araguaia', uf: 'MT' },
			{ name: 'Alto Boa Vista', name_order: 'Alto Boa Vista', uf: 'MT' },
			{ name: 'Alto Garças', name_order: 'Alto Garcas', uf: 'MT' },
			{ name: 'Alto Paraguai', name_order: 'Alto Paraguai', uf: 'MT' },
			{ name: 'Alto Taquari', name_order: 'Alto Taquari', uf: 'MT' },
			{ name: 'Apiacás', name_order: 'Apiacas', uf: 'MT' },
			{ name: 'Araguaiana', name_order: 'Araguaiana', uf: 'MT' },
			{ name: 'Araguainha', name_order: 'Araguainha', uf: 'MT' },
			{ name: 'Araputanga', name_order: 'Araputanga', uf: 'MT' },
			{ name: 'Arenápolis', name_order: 'Arenapolis', uf: 'MT' },
			{ name: 'Aripuanã', name_order: 'Aripuana', uf: 'MT' },
			{ name: 'Barão de Melgaço', name_order: 'Barao de Melgaco', uf: 'MT' },
			{ name: 'Barra do Bugres', name_order: 'Barra do Bugres', uf: 'MT' },
			{ name: 'Barra do Garças', name_order: 'Barra do Garcas', uf: 'MT' },
			{ name: 'Bom Jesus do Araguaia', name_order: 'Bom Jesus do Araguaia', uf: 'MT' },
			{ name: 'Brasnorte', name_order: 'Brasnorte', uf: 'MT' },
			{ name: 'Cáceres', name_order: 'Caceres', uf: 'MT' },
			{ name: 'Campinápolis', name_order: 'Campinapolis', uf: 'MT' },
			{ name: 'Campo Novo do Parecis', name_order: 'Campo Novo do Parecis', uf: 'MT' },
			{ name: 'Campo Verde', name_order: 'Campo Verde', uf: 'MT' },
			{ name: 'Campos de Júlio', name_order: 'Campos de Julio', uf: 'MT' },
			{ name: 'Canabrava do Norte', name_order: 'Canabrava do Norte', uf: 'MT' },
			{ name: 'Canarana', name_order: 'Canarana', uf: 'MT' },
			{ name: 'Carlinda', name_order: 'Carlinda', uf: 'MT' },
			{ name: 'Castanheira', name_order: 'Castanheira', uf: 'MT' },
			{ name: 'Chapada Dos Guimarães', name_order: 'Chapada Dos Guimaraes', uf: 'MT' },
			{ name: 'Cláudia', name_order: 'Claudia', uf: 'MT' },
			{ name: 'Cocalinho', name_order: 'Cocalinho', uf: 'MT' },
			{ name: 'Colíder', name_order: 'Colider', uf: 'MT' },
			{ name: 'Colniza', name_order: 'Colniza', uf: 'MT' },
			{ name: 'Comodoro', name_order: 'Comodoro', uf: 'MT' },
			{ name: 'Confresa', name_order: 'Confresa', uf: 'MT' },
			{ name: 'Conquista D´oeste', name_order: 'Conquista Doeste', uf: 'MT' },
			{ name: 'Cotriguaçu', name_order: 'Cotriguacu', uf: 'MT' },
			{ name: 'Cuiabá', name_order: 'Cuiaba', uf: 'MT' },
			{ name: 'Curvelândia', name_order: 'Curvelandia', uf: 'MT' },
			{ name: 'Denise', name_order: 'Denise', uf: 'MT' },
			{ name: 'Diamantino', name_order: 'Diamantino', uf: 'MT' },
			{ name: 'Dom Aquino', name_order: 'Dom Aquino', uf: 'MT' },
			{ name: 'Feliz Natal', name_order: 'Feliz Natal', uf: 'MT' },
			{ name: 'Figueirópolis D´oeste', name_order: 'Figueiropolis Doeste', uf: 'MT' },
			{ name: 'Gaúcha do Norte', name_order: 'Gaucha do Norte', uf: 'MT' },
			{ name: 'General Carneiro', name_order: 'General Carneiro', uf: 'MT' },
			{ name: 'Glória D´oeste', name_order: 'Gloria Doeste', uf: 'MT' },
			{ name: 'Guarantã do Norte', name_order: 'Guaranta do Norte', uf: 'MT' },
			{ name: 'Guiratinga', name_order: 'Guiratinga', uf: 'MT' },
			{ name: 'Indiavaí', name_order: 'Indiavai', uf: 'MT' },
			{ name: 'Ipiranga do Norte', name_order: 'Ipiranga do Norte', uf: 'MT' },
			{ name: 'Itanhangá', name_order: 'Itanhanga', uf: 'MT' },
			{ name: 'Itaúba', name_order: 'Itauba', uf: 'MT' },
			{ name: 'Itiquira', name_order: 'Itiquira', uf: 'MT' },
			{ name: 'Jaciara', name_order: 'Jaciara', uf: 'MT' },
			{ name: 'Jangada', name_order: 'Jangada', uf: 'MT' },
			{ name: 'Jauru', name_order: 'Jauru', uf: 'MT' },
			{ name: 'Juara', name_order: 'Juara', uf: 'MT' },
			{ name: 'Juína', name_order: 'Juina', uf: 'MT' },
			{ name: 'Juruena', name_order: 'Juruena', uf: 'MT' },
			{ name: 'Juscimeira', name_order: 'Juscimeira', uf: 'MT' },
			{ name: 'Lambari D´oeste', name_order: 'Lambari Doeste', uf: 'MT' },
			{ name: 'Lucas do Rio Verde', name_order: 'Lucas do Rio Verde', uf: 'MT' },
			{ name: 'Luciára', name_order: 'Luciara', uf: 'MT' },
			{ name: 'Vila Bela da Santíssima Trindade', name_order: 'Vila Bela da Santissima Trindade', uf: 'MT' },
			{ name: 'Marcelândia', name_order: 'Marcelandia', uf: 'MT' },
			{ name: 'Matupá', name_order: 'Matupa', uf: 'MT' },
			{ name: 'Mirassol D´oeste', name_order: 'Mirassol Doeste', uf: 'MT' },
			{ name: 'Nobres', name_order: 'Nobres', uf: 'MT' },
			{ name: 'Nortelândia', name_order: 'Nortelandia', uf: 'MT' },
			{ name: 'Nossa Senhora do Livramento', name_order: 'Nossa Senhora do Livramento', uf: 'MT' },
			{ name: 'Nova Bandeirantes', name_order: 'Nova Bandeirantes', uf: 'MT' },
			{ name: 'Nova Nazaré', name_order: 'Nova Nazare', uf: 'MT' },
			{ name: 'Nova Lacerda', name_order: 'Nova Lacerda', uf: 'MT' },
			{ name: 'Nova Santa Helena', name_order: 'Nova Santa Helena', uf: 'MT' },
			{ name: 'Nova Brasilândia', name_order: 'Nova Brasilandia', uf: 'MT' },
			{ name: 'Nova Canaã do Norte', name_order: 'Nova Canaa do Norte', uf: 'MT' },
			{ name: 'Nova Mutum', name_order: 'Nova Mutum', uf: 'MT' },
			{ name: 'Nova Olímpia', name_order: 'Nova Olimpia', uf: 'MT' },
			{ name: 'Nova Ubiratã', name_order: 'Nova Ubirata', uf: 'MT' },
			{ name: 'Nova Xavantina', name_order: 'Nova Xavantina', uf: 'MT' },
			{ name: 'Novo Mundo', name_order: 'Novo Mundo', uf: 'MT' },
			{ name: 'Novo Horizonte do Norte', name_order: 'Novo Horizonte do Norte', uf: 'MT' },
			{ name: 'Novo São Joaquim', name_order: 'Novo Sao Joaquim', uf: 'MT' },
			{ name: 'Paranaíta', name_order: 'Paranaita', uf: 'MT' },
			{ name: 'Paranatinga', name_order: 'Paranatinga', uf: 'MT' },
			{ name: 'Novo Santo Antônio', name_order: 'Novo Santo Antonio', uf: 'MT' },
			{ name: 'Pedra Preta', name_order: 'Pedra Preta', uf: 'MT' },
			{ name: 'Peixoto de Azevedo', name_order: 'Peixoto de Azevedo', uf: 'MT' },
			{ name: 'Planalto da Serra', name_order: 'Planalto da Serra', uf: 'MT' },
			{ name: 'Poconé', name_order: 'Pocone', uf: 'MT' },
			{ name: 'Pontal do Araguaia', name_order: 'Pontal do Araguaia', uf: 'MT' },
			{ name: 'Ponte Branca', name_order: 'Ponte Branca', uf: 'MT' },
			{ name: 'Pontes e Lacerda', name_order: 'Pontes e Lacerda', uf: 'MT' },
			{ name: 'Porto Alegre do Norte', name_order: 'Porto Alegre do Norte', uf: 'MT' },
			{ name: 'Porto Dos Gaúchos', name_order: 'Porto Dos Gauchos', uf: 'MT' },
			{ name: 'Porto Esperidião', name_order: 'Porto Esperidiao', uf: 'MT' },
			{ name: 'Porto Estrela', name_order: 'Porto Estrela', uf: 'MT' },
			{ name: 'Poxoréo', name_order: 'Poxoreo', uf: 'MT' },
			{ name: 'Primavera do Leste', name_order: 'Primavera do Leste', uf: 'MT' },
			{ name: 'Querência', name_order: 'Querencia', uf: 'MT' },
			{ name: 'São José Dos Quatro Marcos', name_order: 'Sao Jose Dos Quatro Marcos', uf: 'MT' },
			{ name: 'Reserva do Cabaçal', name_order: 'Reserva do Cabacal', uf: 'MT' },
			{ name: 'Ribeirão Cascalheira', name_order: 'Ribeirao Cascalheira', uf: 'MT' },
			{ name: 'Ribeirãozinho', name_order: 'Ribeiraozinho', uf: 'MT' },
			{ name: 'Rio Branco', name_order: 'Rio Branco', uf: 'MT' },
			{ name: 'Santa Carmem', name_order: 'Santa Carmem', uf: 'MT' },
			{ name: 'Santo Afonso', name_order: 'Santo Afonso', uf: 'MT' },
			{ name: 'São José do Povo', name_order: 'Sao Jose do Povo', uf: 'MT' },
			{ name: 'São José do Rio Claro', name_order: 'Sao Jose do Rio Claro', uf: 'MT' },
			{ name: 'São José do Xingu', name_order: 'Sao Jose do Xingu', uf: 'MT' },
			{ name: 'São Pedro da Cipa', name_order: 'Sao Pedro da Cipa', uf: 'MT' },
			{ name: 'Rondolândia', name_order: 'Rondolandia', uf: 'MT' },
			{ name: 'Rondonópolis', name_order: 'Rondonopolis', uf: 'MT' },
			{ name: 'Rosário Oeste', name_order: 'Rosario Oeste', uf: 'MT' },
			{ name: 'Santa Cruz do Xingu', name_order: 'Santa Cruz do Xingu', uf: 'MT' },
			{ name: 'Salto do Céu', name_order: 'Salto do Ceu', uf: 'MT' },
			{ name: 'Santa Rita do Trivelato', name_order: 'Santa Rita do Trivelato', uf: 'MT' },
			{ name: 'Santa Terezinha', name_order: 'Santa Terezinha', uf: 'MT' },
			{ name: 'Santo Antônio do Leste', name_order: 'Santo Antonio do Leste', uf: 'MT' },
			{ name: 'Santo Antônio do Leverger', name_order: 'Santo Antonio do Leverger', uf: 'MT' },
			{ name: 'São Félix do Araguaia', name_order: 'Sao Felix do Araguaia', uf: 'MT' },
			{ name: 'Sapezal', name_order: 'Sapezal', uf: 'MT' },
			{ name: 'Serra Nova Dourada', name_order: 'Serra Nova Dourada', uf: 'MT' },
			{ name: 'Sinop', name_order: 'Sinop', uf: 'MT' },
			{ name: 'Sorriso', name_order: 'Sorriso', uf: 'MT' },
			{ name: 'Tabaporã', name_order: 'Tabapora', uf: 'MT' },
			{ name: 'Tangará da Serra', name_order: 'Tangara da Serra', uf: 'MT' },
			{ name: 'Tapurah', name_order: 'Tapurah', uf: 'MT' },
			{ name: 'Terra Nova do Norte', name_order: 'Terra Nova do Norte', uf: 'MT' },
			{ name: 'Tesouro', name_order: 'Tesouro', uf: 'MT' },
			{ name: 'Torixoréu', name_order: 'Torixoreu', uf: 'MT' },
			{ name: 'União do Sul', name_order: 'Uniao do Sul', uf: 'MT' },
			{ name: 'Vale de São Domingos', name_order: 'Vale de Sao Domingos', uf: 'MT' },
			{ name: 'Várzea Grande', name_order: 'Varzea Grande', uf: 'MT' },
			{ name: 'Vera', name_order: 'Vera', uf: 'MT' },
			{ name: 'Vila Rica', name_order: 'Vila Rica', uf: 'MT' },
			{ name: 'Nova Guarita', name_order: 'Nova Guarita', uf: 'MT' },
			{ name: 'Nova Marilândia', name_order: 'Nova Marilandia', uf: 'MT' },
			{ name: 'Nova Maringá', name_order: 'Nova Maringa', uf: 'MT' },
			{ name: 'Nova Monte Verde', name_order: 'Nova Monte Verde', uf: 'MT' },
	]);
};
